// ============================================
// INFRASTRUCTURE ACADEMY - HINDI TRANSLATIONS
// इन्फ्रास्ट्रक्चर अकादमी - हिंदी अनुवाद
// ============================================
// This file is loaded by i18n.js as a translation overlay.
// English HTML content is NEVER modified. This provides HI text swaps.

window.IA_LANG_HI = {

    // ============================================
    // SHARED NAVIGATION & HEADER
    // ============================================
    "nav.home": "होम",
    "nav.precis": "कार्यकारी सारांश",
    "nav.framework": "ढांचा",
    "nav.resources": "संसाधन",
    "nav.documents": "दस्तावेज़",
    "nav.author": "लेखक",
    "nav.ep1": "EP.1: परिप्रेक्ष्य",
    "nav.ep2": "EP.2: प्लेबुक",
    "nav.ep3": "EP.3: खेल",
    "nav.supplements": "पूरक",
    "header.title": "इन्फ्रास्ट्रक्चर अकादमी",
    "header.subtitle": "एक इन्फ्रास्ट्रक्चर ओडिसी: पुस्तक I — कैलोरी से चेतना तक",

    // ============================================
    // FOOTER
    // ============================================
    "footer.copyright": "&copy; 2026 इन्फ्रास्ट्रक्चर अकादमी। सर्वाधिकार सुरक्षित। ज्ञान को शाश्वत रूप से संरक्षित करना।",
    "footer.ep1": "एपिसोड 1: पार्थिव नींव",
    "footer.ep2": "एपिसोड 2: ग्रे एरिना",
    "footer.ep3": "एपिसोड 3: ब्रह्मांडीय पैमाना",

    // ============================================
    // SITE.HTML (HOME PAGE)
    // ============================================
    "home.title": "एक इन्फ्रास्ट्रक्चर ओडिसी",
    "home.subtitle": "एक सिविल इंजीनियर के लिए परिप्रेक्ष्य और प्लेबुक — एपिसोड I: कैलोरी से चेतना तक",
    "home.author": "द्वारा Ir. Nigel T. Dearden",
    "home.hero.caption": "कैलोरी से चेतना तक: एक इन्फ्रास्ट्रक्चर ओडिसी — सभ्यता का रिले",
    "home.cover.front": "आगे और पीछे के कवर — एपिसोड I: पार्थिव नींव",
    "home.cover.interior": "इंटीरियर स्प्रेड — अध्याय 1: अग्नि का रिले (भाग I और II)",
    "home.cover.portrait": "सभ्यता का रिले — पेड़ से टोरस तक 12 अध्याय",

    // Framework section
    "home.framework.title": "पूरा ढांचा",
    "home.framework.subtitle": "एक सिविल इंजीनियर के लेंस के माध्यम से इन्फ्रास्ट्रक्चर शिक्षा के लिए एक एकीकृत प्रणाली सोच",
    "home.framework.motto": "इन्फ्रास्ट्रक्चर शिक्षा: सिस्टम सोच, रटना नहीं।",
    "home.framework.journey": "यात्रा ही काम है।",
    "home.framework.modes.caption": "तीन मोड — पश्चिमी, पूर्वी और आउटराइडर 12,000 वर्षों में",
    "home.framework.relays.caption": "12 सभ्यता रिले — अग्नि से चेतना तक",
    "home.framework.silk.caption": "सिल्क रोड विरोधाभास — आउटराइडर्स ने व्यापार मार्गों को नियंत्रित किया, फिर भी कोई बुनियादी ढांचा नहीं बनाया",

    // Volumes section
    "home.vol1.title": "खंड I: परिप्रेक्ष्य",
    "home.vol1.subtitle": "इतिहास और संदर्भ — कहानी",
    "home.vol1.desc": "कथा नींव: 12,000 वर्षों के मानव अवसंरचना विकास में 12 सभ्यता रिले। आग में महारत हासिल करने से लेकर चेतना के टोरस तक।",
    "home.vol1.btn": "परिप्रेक्ष्य पढ़ें",
    "home.vol2.title": "खंड II: प्लेबुक",
    "home.vol2.subtitle": "रणनीतिक ढांचा — विस्तार",
    "home.vol2.desc": "व्यावहारिक ढांचा: पश्चिमी/पूर्वी/आउटराइडर तुलनात्मक दृष्टिकोण, 4C विश्लेषण, और सभ्यता के डीएनए के रूप में बुनियादी ढांचे को समझने के लिए रणनीतिक मॉडल।",
    "home.vol2.btn": "प्लेबुक पढ़ें",
    "home.supplements.title": "खंड II: 4 पूरक",
    "home.s1.title": "S1: पहचानें",
    "home.s1.desc": "मूल अवधारणाएँ — तीन मोड, तत्व घड़ी, सड़क बनाम जहाज समयरेखा",
    "home.s2.title": "S2: समझें",
    "home.s2.desc": "प्रौद्योगिकी प्रसार — एक बुनियादी ढांचे के रूप में कलम, लेखन प्रणाली",
    "home.s3.title": "S3: प्रबंधन और नियंत्रण",
    "home.s3.desc": "कार्यान्वयन — प्रत्येक रिले के लिए प्रबंधन चार्ट",
    "home.s4.title": "S4: थीसिस और विजन",
    "home.s4.desc": "प्रतिपक्ष — प्रत्येक रिले के लिए पश्चिमी, आउटराइडर और पूर्वी तुलना",
    "home.supplements.btn": "पूरक देखें",

    // Challenge section
    "home.challenge.title": "हम जिस चुनौती को संबोधित करते हैं",
    "home.challenge.subtitle": "इन्फ्रास्ट्रक्चर शिक्षा खंडित, सारगर्भित और वास्तविक दुनिया के प्रभाव से अलग है।",
    "home.challenge.stat1.num": "70%",
    "home.challenge.stat1.desc": "पाठ्यक्रमों में अंतःविषय एकीकरण का अभाव है",
    "home.challenge.stat2.num": "65%",
    "home.challenge.stat2.desc": "छात्र वास्तविक दुनिया के अनुप्रयोगों के लिए तैयार नहीं महसूस करते हैं",
    "home.challenge.stat3.num": "45%",
    "home.challenge.stat3.desc": "सिस्टम-स्तरीय सोच के लिए सीमित जोखिम की रिपोर्ट करें",
    "home.challenge.stat4.num": "80%",
    "home.challenge.stat4.desc": "नियोक्ता परियोजना की तैयारी में कौशल अंतर देखते हैं",
    "home.challenge.stat5.num": "30%",
    "home.challenge.stat5.desc": "परियोजनाएं सामुदायिक या पर्यावरणीय प्रभाव मेट्रिक्स को एकीकृत करती हैं",
    "home.challenge.stat6.num": "90%",
    "home.challenge.stat6.desc": "व्यावहारिक ज्ञान अंतराल के कारण बुनियादी ढांचा परियोजनाओं में देरी हुई",
    "home.challenge.urgent": "तत्काल आवश्यकता: भविष्य के लिए तैयार बुनियादी ढांचा पेशेवरों के लिए अंतर को पाटना",

    // Trilogy section
    "home.trilogy.title": "त्रयी विजन",
    "home.ep1.title": "एपिसोड I",
    "home.ep1.subtitle": "पार्थिव नींव",
    "home.ep1.desc": "कैलोरी से चेतना तक — अग्नि से टोरस तक 12 रिले",
    "home.ep1.btn": "पहले से ही उपलब्ध",
    "home.ep2.title": "एपिसोड II",
    "home.ep2.subtitle": "रियलिटी इंजन — ग्रे एरिना",
    "home.ep2.desc": "साइबरनेटिक्स, एआई और इंटेलिजेंट सिस्टम",
    "home.ep2.btn": "जल्द आ रहा है",
    "home.ep3.title": "एपिसोड III",
    "home.ep3.subtitle": "प्रबंधन और नवीनीकरण — ब्रह्मांडीय مقياس",
    "home.ep3.desc": "ग्रह, सौर और गांगेय प्रबंधन",
    "home.ep3.btn": "जल्द आ रहा है",

    // Media section
    "home.media.title": "मीडिया",
    "home.media.trailer": "स्नैपशॉट ट्रेलर",
    "home.media.calories": "कैलोरी से चेतना तक",
    "home.media.engine": "रियलिटी इंजन — गाइडेड लर्निंग प्लेटफॉर्म",
    "home.media.river": "रिवर प्लेन मूवी",

    // Knowledge Web section
    "home.kw.title": "ज्ञान वेब: एक बुनियादी ढांचे के रूप में शब्द",
    "home.kw.subtitle": "लेखांकन टोकन से डिजिटल युग तक लेखन का एक व्यापक इतिहास। अंतिम अवसंरचना रिले के रूप में कलम।",

    // Game CTA section
    "home.game.title": "खंड III: खेल",
    "home.game.desc": "जो आपने सीखा है उसे लागू करने के लिए तैयार हैं? रियलिटी इंजन में प्रवेश करें — इमर्सिव लर्निंग प्लेटफॉर्म जहां आप इन्फ्रास्ट्रक्चर इंजीनियर बनते हैं।",
    "home.game.cta.title": "खेल में प्रवेश करें",
    "home.game.cta.sub": "खंड III: रियलिटी इंजन — गाइडेड लर्निंग प्लेटफॉर्म",
    "home.game.note": "सिमुलेशन और अभ्यास: एक गतिशील वातावरण में अवधारणाओं को लागू करें",

    // About Archive section
    "home.archive.title": "इस पुरालेख के बारे में",
    "home.archive.p1": "इन्फ्रास्ट्रक्चर अकादमी एक डिजिटल पुरालेख है जो 'एन इन्फ्रास्ट्रक्चर ओडिसी' की पूरी ज्ञान संपत्ति को संरक्षित करता है — 12,000 वर्षों के मानव अवसंरचना विकास पर एक सभ्यतागत मास्टरक्लास। यह साइट दुनिया भर के विद्वानों, इंजीनियरों और शिक्षार्थियों के लिए ज्ञान के स्थायी संरक्षण को सुनिश्चित करती है।",
    "home.archive.p2": "सभी सामग्री, विज़ुअलाइज़ेशन और फ्रेमवर्क आसान नेविगेशन और खोज के लिए यहां एकीकृत हैं। यह कैलोरी से चेतना तक मानवता के उदय का एक स्थायी रिकॉर्ड है, जिसे कलम द्वारा डिजिटल अनंत काल में अंकित किया गया है।",

    // ============================================
    // EXECUTIVE PRÉCIS
    // ============================================
    "precis.title": "कार्यकारी सारांश",
    "precis.subtitle": "एक इन्फ्रास्ट्रक्चर ओडिसी — एक रणनीतिक अवलोकन",

    // ============================================
    // FRAMEWORK PAGE
    // ============================================
    "framework.title": "पूरा ढांचा",
    "framework.subtitle": "एक एकीकृत प्रणाली सोच पद्धति",
    "framework.modes.title": "तीन सभ्यता मोड",
    "framework.modes.west": "पश्चिमी मोड",
    "framework.modes.west.desc": "असंतत / बिल्ड — सिकंदर महान का मूलरूप",
    "framework.modes.east": "पूर्वी मोड",
    "framework.modes.east.desc": "सतत / बिल्ड — किन शी हुआंग का मूलरूप",
    "framework.modes.outrider": "आउटराइडर मोड",
    "framework.modes.outrider.desc": "अर्ध-सतत / अस्थायी कार्य — चंगेज खान का मूलरूप",
    "framework.relays.title": "12 सभ्यता रिले",
    "framework.4cs.title": "4C विश्लेषण ढांचा",
    "framework.4cs.context": "प्रसंग",
    "framework.4cs.challenge": "चुनौती",
    "framework.4cs.consequence": "परिणाम",
    "framework.4cs.continuum": "सातत्य",

    // ============================================
    // RELAY NAMES (used across all volumes)
    // ============================================
    "relay.1.name": "रिले 1: अग्नि",
    "relay.1.subtitle": "मौलिक चिंगारी — ऊर्जा महारत की शुरुआत",
    "relay.2.name": "रिले 2: पेड़",
    "relay.2.subtitle": "जीवित वास्तुकला — प्रकृति इंजीनियरिंग के रूप में",
    "relay.3.name": "रिले 3: नदी",
    "relay.3.subtitle": "हाइड्रोलिक सभ्यता — तरल अवसंरचना",
    "relay.4.name": "रिले 4: घोड़ा",
    "relay.4.subtitle": "गतिशीलता क्रांति — गति और साम्राज्य",
    "relay.5.name": "रिले 5: सड़क",
    "relay.5.subtitle": "जुड़े हुए नेटवर्क — साम्राज्य की धमनियां",
    "relay.6.name": "रिले 6: जहाज",
    "relay.6.subtitle": "महासागर राजमार्ग — वैश्विक व्यापार नेटवर्क",
    "relay.7.name": "रिले 7: रेल",
    "relay.7.subtitle": "स्टील की रीढ़ — औद्योगिक कनेक्टिविटी",
    "relay.8.name": "रिले 8: करघा",
    "relay.8.subtitle": "बुने हुए वेब — सूचना अवसंरचना",
    "relay.9.name": "रिले 9: इंजन",
    "relay.9.subtitle": "शक्ति क्रांति — एक मशीनीकृत दुनिया",
    "relay.10.name": "रिले 10: AAA ट्रायड",
    "relay.10.subtitle": "विमानन, परमाणु, स्वचालन — आधुनिक त्रिमूर्ति",
    "relay.11.name": "रिले 11: मानव नोड",
    "relay.11.subtitle": "नेटवर्कयुक्त मानव — डिजिटल कनेक्टिविटी",
    "relay.12.name": "रिले 12: चेतना",
    "relay.12.subtitle": "टोरस — अंतिम अवसंरचना",
    "relay.prologue": "प्रस्तावना",
    "relay.epilogue": "उपसंहार",

    // ============================================
    // VOLUME INDEX PAGES
    // ============================================
    "vol1.index.title": "खंड I: परिप्रेक्ष्य",
    "vol1.index.subtitle": "इतिहास और संदर्भ — कहानी",
    "vol1.index.desc": "12 सभ्यता रिले के माध्यम से 12,000 वर्षों के बुनियादी ढांचे के विकास का अन्वेषण करें। प्रत्येक रिले मानव क्षमता में एक मौलिक छलांग का प्रतिनिधित्व करता है।",
    "vol2.index.title": "खंड II: प्लेबुक",
    "vol2.index.subtitle": "रणनीतिक ढांचा — विस्तार",
    "vol2.index.desc": "प्रत्येक रिले के लिए व्यावहारिक ढांचा, तुलनात्मक विश्लेषण और रणनीतिक मॉडल। पश्चिमी, पूर्वी और आउटराइडर दृष्टिकोणों की गहन तुलना।",
    "vol3.index.title": "खंड III: खेल",
    "vol3.index.subtitle": "सिमुलेशन और अभ्यास — अनुप्रयोग",
    "vol3.index.desc": "रियलिटी इंजन गाइडेड लर्निंग प्लेटफॉर्म। एक गतिशील सिमुलेशन वातावरण में अवधारणाओं को लागू करें।",

    // ============================================
    // RESOURCES PAGE
    // ============================================
    "resources.title": "संसाधन",
    "resources.subtitle": "संदर्भ, डेटा स्रोत और आगे पढ़ने के लिए",

    // ============================================
    // ABOUT AUTHOR PAGE
    // ============================================
    "author.title": "लेखक के बारे में",
    "author.name": "Ir. Nigel T. Dearden",
    "author.credentials": "चार्टर्ड इंजीनियर (CEng), इंस्टीट्यूशन ऑफ सिविल इंजीनियर्स के सदस्य (MICE), हांगकांग इंस्टीट्यूशन ऑफ इंजीनियर्स के सदस्य (MHKIE)",
    "author.bio": "Ir. Nigel T Dearden (鄧禮祖) एक चार्टर्ड सिविल एवं स्ट्रक्चरल इंजीनियर तथा चार्टर्ड जल एवं पर्यावरण प्रबंधक हैं, जिनके पास हांगकांग बुनियादी ढांचे में 33+ वर्षों का अनुभव है। 4 Elements Consulting Ltd के संस्थापक (2006, www.4ecl.com)। BEng (Hon's), CEng, C.WEM, RPE (CSB), MICE, MHKIE, MCIWEM।",

    // ============================================
    // LIBRARY / DOCUMENTS PAGE
    // ============================================
    "library.title": "दस्तावेज़ पुस्तकालय",
    "library.subtitle": "पूरी ज्ञान संपत्ति का पुरालेख",

    // ============================================
    // SUPPLEMENTS PAGE
    // ============================================
    "supplements.title": "पूरक",
    "supplements.subtitle": "खंड II के लिए गहन विस्तार",
    "supplements.s1": "पूरक 1: पहचानें",
    "supplements.s2": "पूरक 2: समझें",
    "supplements.s3": "पूरक 3: प्रबंधन और नियंत्रण",
    "supplements.s4": "पूरक 4: थीसिस और विजन",

    // ============================================
    // COMMON UI ELEMENTS
    // ============================================
    "ui.read.more": "और पढ़ें",
    "ui.back": "वापस",
    "ui.loading": "लोड हो रहा है...",
    "ui.error": "सामग्री लोड करते समय त्रुटि। कृपया पुनः प्रयास करें।",
    "ui.available": "पहले से ही उपलब्ध",
    "ui.coming.soon": "जल्द आ रहा है",
    "ui.view": "देखें",
    "ui.download": "डाउनलोड करें",
    "ui.prev": "पिछला",
    "ui.next": "अगला",

    // ============================================
    // TABLE OF CONTENTS
    // ============================================
    "toc.title": "विषय-सूची",
    "toc.volume1": "खंड I: परिप्रेक्ष्य — इतिहास और संदर्भ",
    "toc.volume2": "खंड II: प्लेबुक — रणनीतिक ढांचा",
    "toc.volume3": "खंड III: खेल — सिमुलेशन और अभ्यास",
    "toc.prologue": "प्रस्तावना",
    "toc.epilogue": "उपसंहार",
    "toc.chapter": "अध्याय",
    "toc.chapter.suffix": "",

    // ============================================
    // ARCHIVE PAGES
    // ============================================
    "archive.title": "पुरालेख",
    "archive.subtitle": "पूरी ज्ञान संपत्ति का संरक्षण",
    "archive.documents": "दस्तावेज़",
    "archive.images": "छवियाँ",
    "archive.references": "संदर्भ",
    "archive.relays": "रिले",
    "archive.supplements": "पूरक",

    // Home page extras
    "home.archive.architects": "भाग्य के निर्माता और महान एकीकृतकर्ता: सिकंदर महान, चंगेज खान, किन शी हुआंग",

    // Additional nav items
    "nav.supplements": "पूरक",

    // Volume subtitles
    "header.subtitle.v2": "एक इन्फ्रास्ट्रक्चर ओडिसी: पुस्तक II — एक प्रैक्टिकल प्लेबुक",
    "header.subtitle.v3": "एक इन्फ्रास्ट्रक्चर ओडिसी: पुस्तक III — रियलिटी इंजन",

    // ============================================
    // RELAY CONTENT TRANSLATIONS (Auto-generated)
    // ============================================
    "section.4c_analysis": "4C विश्लेषण",
    "section.active_webs": "सक्रिय वेब",
    "section.back_to_index": "अनुक्रमणिका पर वापस जाएं",
    "section.challenge": "चुनौती",
    "section.communication_web": "संचार वेब",
    "section.comparative_analysis": "तुलनात्मक विश्लेषण",
    "section.consciousness_web": "चेतना वेब",
    "section.consequence": "परिणाम",
    "section.context": "प्रसंग",
    "section.continuity": "निरंतरता",
    "section.continuum": "सातत्य",
    "section.cosmic_clock": "ब्रह्मांडीय घड़ी",
    "section.counterparts": "प्रतिपक्ष",
    "section.documents": "दस्तावेज़",
    "section.east": "पूर्व",
    "section.education": "शिक्षा",
    "section.energy_web": "ऊर्जा वेब",
    "section.epilogue": "उपसंहार",
    "section.four_cs": "चार सी",
    "section.four_pillars": "चार स्तंभ",
    "section.gallery": "गैलरी",
    "section.historical_significance": "ऐतिहासिक महत्व",
    "section.home": "होम",
    "section.infrastructure_elements": "अवसंरचना तत्व",
    "section.introduction": "परिचय",
    "section.knowledge_web": "ज्ञान वेब",
    "section.logistics_web": "लॉजिस्टिक्स वेब",
    "section.management_charts": "प्रबंधन चार्ट",
    "section.next_relay": "अगला रिले",
    "section.observation": "अवलोकन",
    "section.outrider": "आउटराइडर",
    "section.overview": "अवलोकन",
    "section.planetary_clock": "ग्रहीय घड़ी",
    "section.previous_relay": "पिछला रिले",
    "section.prologue": "प्रस्तावना",
    "section.references": "संदर्भ",
    "section.summary": "सारांश",
    "section.supplements": "पूरक",
    "section.table_of_contents": "विषय-सूची",
    "section.thesis": "थीसिस",
    "section.timeline": "समय-सीमा",
    "section.transport_web": "परिवहन वेब",
    "section.west": "पश्चिम",
    "v1.r1.about_this_relay": "इस रिले के बारे में",
    "v1.r1.active_webs": "सक्रिय वेब",
    "v1.r1.back_to_v1_index": "खंड 1 अनुक्रमणिका पर वापस जाएं",
    "v1.r1.epilogue": "उपसंहार",
    "v1.r1.historical_significance": "ऐतिहासिक महत्व",
    "v1.r1.home": "होम",
    "v1.r1.infrastructure_elements": "अवसंरचना तत्व",
    "v1.r1.introduction": "परिचय",
    "v1.r1.next_relay": "अगला रिले →",
    "v1.r1.prologue": "प्रस्तावना",
    "v1.r1.subtitle": "मौलिक चिंगारी — ऊर्जा महारत की शुरुआत",
    "v1.r1.summary": "सारांश",
    "v1.r1.title": "रिले 1: अग्नि",
    "v1.r10.about_this_relay": "इस रिले के बारे में",
    "v1.r10.active_webs": "सक्रिय वेब",
    "v1.r10.back_to_v1_index": "खंड 1 अनुक्रमणिका पर वापस जाएं",
    "v1.r10.epilogue": "उपसंहार",
    "v1.r10.historical_significance": "ऐतिहासिक महत्व",
    "v1.r10.home": "होम",
    "v1.r10.infrastructure_elements": "अवसंरचना तत्व",
    "v1.r10.introduction": "परिचय",
    "v1.r10.next_relay": "अगला रिले →",
    "v1.r10.previous_relay": "← पिछला रिले",
    "v1.r10.prologue": "प्रस्तावना",
    "v1.r10.subtitle": "विमानन, परमाणु, स्वचालन — आधुनिक त्रिमूर्ति",
    "v1.r10.summary": "सारांश",
    "v1.r10.title": "रिले 10: AAA ट्रायड",
    "v1.r11.about_this_relay": "इस रिले के बारे में",
    "v1.r11.active_webs": "सक्रिय वेब",
    "v1.r11.back_to_v1_index": "खंड 1 अनुक्रमणिका पर वापस जाएं",
    "v1.r11.epilogue": "उपसंहार",
    "v1.r11.historical_significance": "ऐतिहासिक महत्व",
    "v1.r11.home": "होम",
    "v1.r11.infrastructure_elements": "अवसंरचना तत्व",
    "v1.r11.introduction": "परिचय",
    "v1.r11.next_relay": "अगला रिले →",
    "v1.r11.previous_relay": "← पिछला रिले",
    "v1.r11.prologue": "प्रस्तावना",
    "v1.r11.subtitle": "नेटवर्कयुक्त मानव — डिजिटल कनेक्टिविटी",
    "v1.r11.summary": "सारांश",
    "v1.r11.title": "रिले 11: मानव नोड",
    "v1.r12.about_this_relay": "इस रिले के बारे में",
    "v1.r12.active_webs": "सक्रिय वेब",
    "v1.r12.back_to_v1_index": "खंड 1 अनुक्रमणिका पर वापस जाएं",
    "v1.r12.epilogue": "उपसंहार",
    "v1.r12.historical_significance": "ऐतिहासिक महत्व",
    "v1.r12.home": "होम",
    "v1.r12.infrastructure_elements": "अवसंरचना तत्व",
    "v1.r12.introduction": "परिचय",
    "v1.r12.previous_relay": "← पिछला रिले",
    "v1.r12.prologue": "प्रस्तावना",
    "v1.r12.subtitle": "टोरस — अंतिम अवसंरचना",
    "v1.r12.summary": "सारांश",
    "v1.r12.title": "रिले 12: चेतना",
    "v1.r2.about_this_relay": "इस रिले के बारे में",
    "v1.r2.active_webs": "सक्रिय वेब",
    "v1.r2.back_to_v1_index": "खंड 1 अनुक्रमणिका पर वापस जाएं",
    "v1.r2.epilogue": "उपसंहार",
    "v1.r2.historical_significance": "ऐतिहासिक महत्व",
    "v1.r2.home": "होम",
    "v1.r2.infrastructure_elements": "अवसंरचना तत्व",
    "v1.r2.introduction": "परिचय",
    "v1.r2.next_relay": "अगला रिले →",
    "v1.r2.previous_relay": "← पिछला रिले",
    "v1.r2.prologue": "प्रस्तावना",
    "v1.r2.subtitle": "जीवित वास्तुकला — प्रकृति इंजीनियरिंग के रूप में",
    "v1.r2.summary": "सारांश",
    "v1.r2.title": "रिले 2: पेड़",
    "v1.r3.about_this_relay": "इस रिले के बारे में",
    "v1.r3.active_webs": "सक्रिय वेब",
    "v1.r3.back_to_v1_index": "खंड 1 अनुक्रमणिका पर वापस जाएं",
    "v1.r3.epilogue": "उपसंहार",
    "v1.r3.historical_significance": "ऐतिहासिक महत्व",
    "v1.r3.home": "होम",
    "v1.r3.infrastructure_elements": "अवसंरचना तत्व",
    "v1.r3.introduction": "परिचय",
    "v1.r3.next_relay": "अगला रिले →",
    "v1.r3.previous_relay": "← पिछला रिले",
    "v1.r3.prologue": "प्रस्तावना",
    "v1.r3.subtitle": "हाइड्रोलिक सभ्यता — तरल अवसंरचना",
    "v1.r3.summary": "सारांश",
    "v1.r3.title": "रिले 3: नदी",
    "v1.r4.about_this_relay": "इस रिले के बारे में",
    "v1.r4.active_webs": "सक्रिय वेब",
    "v1.r4.back_to_v1_index": "खंड 1 अनुक्रमणिका पर वापस जाएं",
    "v1.r4.epilogue": "उपसंहार",
    "v1.r4.historical_significance": "ऐतिहासिक महत्व",
    "v1.r4.home": "होम",
    "v1.r4.infrastructure_elements": "अवसंरचना तत्व",
    "v1.r4.introduction": "परिचय",
    "v1.r4.next_relay": "अगला रिले →",
    "v1.r4.previous_relay": "← पिछला रिले",
    "v1.r4.prologue": "प्रस्तावना",
    "v1.r4.subtitle": "गतिशीलता क्रांति — गति और साम्राज्य",
    "v1.r4.summary": "सारांश",
    "v1.r4.title": "रिले 4: घोड़ा",
    "v1.r5.about_this_relay": "इस रिले के बारे में",
    "v1.r5.active_webs": "सक्रिय वेब",
    "v1.r5.back_to_v1_index": "खंड 1 अनुक्रमणिका पर वापस जाएं",
    "v1.r5.epilogue": "उपसंहार",
    "v1.r5.historical_significance": "ऐतिहासिक महत्व",
    "v1.r5.home": "होम",
    "v1.r5.infrastructure_elements": "अवसंरचना तत्व",
    "v1.r5.introduction": "परिचय",
    "v1.r5.next_relay": "अगला रिले →",
    "v1.r5.previous_relay": "← पिछला रिले",
    "v1.r5.prologue": "प्रस्तावना",
    "v1.r5.subtitle": "जुड़े हुए नेटवर्क — साम्राज्य की धमनियां",
    "v1.r5.summary": "सारांश",
    "v1.r5.title": "रिले 5: सड़क",
    "v1.r6.about_this_relay": "इस रिले के बारे में",
    "v1.r6.active_webs": "सक्रिय वेब",
    "v1.r6.back_to_v1_index": "खंड 1 अनुक्रमणिका पर वापस जाएं",
    "v1.r6.epilogue": "उपसंहार",
    "v1.r6.historical_significance": "ऐतिहासिक महत्व",
    "v1.r6.home": "होम",
    "v1.r6.infrastructure_elements": "अवसंरचना तत्व",
    "v1.r6.introduction": "परिचय",
    "v1.r6.next_relay": "अगला रिले →",
    "v1.r6.previous_relay": "← पिछला रिले",
    "v1.r6.prologue": "प्रस्तावना",
    "v1.r6.subtitle": "महासागर राजमार्ग — वैश्विक व्यापार नेटवर्क",
    "v1.r6.summary": "सारांश",
    "v1.r6.title": "रिले 6: जहाज",
    "v1.r7.about_this_relay": "इस रिले के बारे में",
    "v1.r7.active_webs": "सक्रिय वेब",
    "v1.r7.back_to_v1_index": "खंड 1 अनुक्रमणिका पर वापस जाएं",
    "v1.r7.epilogue": "उपसंहार",
    "v1.r7.historical_significance": "ऐतिहासिक महत्व",
    "v1.r7.home": "होम",
    "v1.r7.infrastructure_elements": "अवसंरचना तत्व",
    "v1.r7.introduction": "परिचय",
    "v1.r7.next_relay": "अगला रिले →",
    "v1.r7.previous_relay": "← पिछला रिले",
    "v1.r7.prologue": "प्रस्तावना",
    "v1.r7.subtitle": "स्टील की रीढ़ — औद्योगिक कनेक्टिविटी",
    "v1.r7.summary": "सारांश",
    "v1.r7.title": "रिले 7: रेल",
    "v1.r8.about_this_relay": "इस रिले के बारे में",
    "v1.r8.active_webs": "सक्रिय वेब",
    "v1.r8.back_to_v1_index": "खंड 1 अनुक्रमणिका पर वापस जाएं",
    "v1.r8.epilogue": "उपसंहार",
    "v1.r8.historical_significance": "ऐतिहासिक महत्व",
    "v1.r8.home": "होम",
    "v1.r8.infrastructure_elements": "अवसंरचना तत्व",
    "v1.r8.introduction": "परिचय",
    "v1.r8.next_relay": "अगला रिले →",
    "v1.r8.previous_relay": "← पिछला रिले",
    "v1.r8.prologue": "प्रस्तावना",
    "v1.r8.subtitle": "बुने हुए वेब — सूचना अवसंरचना",
    "v1.r8.summary": "सारांश",
    "v1.r8.title": "रिले 8: करघा",
    "v1.r9.about_this_relay": "इस रिले के बारे में",
    "v1.r9.active_webs": "सक्रिय वेब",
    "v1.r9.back_to_v1_index": "खंड 1 अनुक्रमणिका पर वापस जाएं",
    "v1.r9.epilogue": "उपसंहार",
    "v1.r9.historical_significance": "ऐतिहासिक महत्व",
    "v1.r9.home": "होम",
    "v1.r9.infrastructure_elements": "अवसंरचना तत्व",
    "v1.r9.introduction": "परिचय",
    "v1.r9.next_relay": "अगला रिले →",
    "v1.r9.previous_relay": "← पिछला रिले",
    "v1.r9.prologue": "प्रस्तावना",
    "v1.r9.subtitle": "शक्ति क्रांति — एक मशीनीकृत दुनिया",
    "v1.r9.summary": "सारांश",
    "v1.r9.title": "रिले 9: इंजन",
    "v2.r1.4c_analysis": "4C विश्लेषण",
    "v2.r1.active_webs": "सक्रिय वेब",
    "v2.r1.comparative_analysis": "तुलनात्मक विश्लेषण",
    "v2.r1.counterparts_title": "प्रतिपक्ष: अग्नि",
    "v2.r1.four_pillars": "चार स्तंभ",
    "v2.r1.historical_significance": "ऐतिहासिक महत्व",
    "v2.r1.next_relay": "अगला रिले →",
    "v2.r1.subtitle": "मौलिक चिंगारी — ऊर्जा महारत की शुरुआत",
    "v2.r1.title": "रिले 1: अग्नि",
    "v2.r10.active_webs": "सक्रिय वेब",
    "v2.r10.counterparts_title": "प्रतिपक्ष: AAA ट्रायड",
    "v2.r10.four_pillars": "चार स्तंभ",
    "v2.r10.historical_significance": "ऐतिहासिक महत्व",
    "v2.r10.next_relay": "अगला रिले →",
    "v2.r10.previous_relay": "← पिछला रिले",
    "v2.r10.subtitle": "विमानन, परमाणु, स्वचालन — आधुनिक त्रिमूर्ति",
    "v2.r10.title": "रिले 10: AAA ट्रायड",
    "v2.r11.active_webs": "सक्रिय वेब",
    "v2.r11.counterparts_title": "प्रतिपक्ष: मानव नोड",
    "v2.r11.four_pillars": "चार स्तंभ",
    "v2.r11.historical_significance": "ऐतिहासिक महत्व",
    "v2.r11.next_relay": "अगला रिले →",
    "v2.r11.previous_relay": "← पिछला रिले",
    "v2.r11.subtitle": "नेटवर्कयुक्त मानव — डिजिटल कनेक्टिविटी",
    "v2.r11.title": "रिले 11: मानव नोड",
    "v2.r12.active_webs": "सक्रिय वेब",
    "v2.r12.counterparts_title": "प्रतिपक्ष: चेतना",
    "v2.r12.four_pillars": "चार स्तंभ",
    "v2.r12.historical_significance": "ऐतिहासिक महत्व",
    "v2.r12.next_relay": "अगला रिले →",
    "v2.r12.previous_relay": "← पिछला रिले",
    "v2.r12.subtitle": "टोरस — अंतिम अवसंरचना",
    "v2.r12.title": "रिले 12: चेतना",

    // ============================================
    // PAGE-SPECIFIC TRANSLATIONS
    // ============================================
    "precis.relay.epilogue": "उपसंहार",
    "precis.relay.prologue": "प्रस्तावना",
    "precis.relay.relay_10_aaa": "रिले 10: AAA ट्रायड",
    "precis.relay.relay_11_humans": "रिले 11: मानव नोड",
    "precis.relay.relay_12_torus": "रिले 12: टोरस",
    "precis.relay.relay_10_autoair": "रिले 10: ऑटो/एयर",
    "precis.relay.relay_11_orbit": "रिले 11: ऑर्बिट",
    "precis.relay.relay_12_programmable": "रिले 12: प्रोग्रामेबल",
    "precis.relay.torus": "टोरस",
    "precis.relay.relay_1_fire": "रिले 1: अग्नि",
    "precis.relay.relay_2_tree": "रिले 2: पेड़",
    "precis.relay.relay_3_river": "रिले 3: नदी",
    "precis.relay.relay_4_horse": "रिले 4: घोड़ा",
    "precis.relay.relay_5_road": "रिले 5: सड़क",
    "precis.relay.relay_6_ship": "रिले 6: जहाज",
    "precis.relay.relay_7_rail": "रिले 7: रेल",
    "precis.relay.relay_8_loom": "रिले 8: करघा",
    "precis.relay.relay_9_engine": "रिले 9: इंजन",
    // ============================================
    // NAVIGATION — NEW PAGES
    // ============================================
    "nav.clock": "मोबिलाइजेशन क्लॉक",
    "nav.pioneers": "पायनियर प्रोग्राम",
    // ============================================
    // MOBILISATION CLOCK PAGE
    // ============================================
    "clock.title": "IAAI ग्लोबल मोबिलाइजेशन क्लॉक",
    "clock.subtitle": "बुनियादी ढांचे की साक्षरता की दौड़ में मानवता — चुनौती",
    "clock.hero.pop": "विश्व जनसंख्या",
    "clock.hero.pop.sub": "संयुक्त राष्ट्र द्वारा लाइव अनुमान",
    "clock.hero.target": "लक्ष्य: 1 अरब शिक्षार्थी",
    "clock.hero.target.sub": "मानवता का 12.1% — टिपिंग पॉइंट",
    "clock.hero.mobilised": "वर्तमान में जुटा हुआ",
    "clock.bar.start": "0 — लॉन्च",
    "clock.bar.mid": "पायनियर → एंबेसडर → स्कॉलर",
    "clock.bar.end": "1,000,000,000 — मिशन पूरा हुआ",
    "clock.contributors.title": "योगदानकर्ता वर्ग",
    "clock.contributors.players": "खिलाड़ी (खेल)",
    "clock.contributors.pioneers": "पायनियर (परीक्षक)",
    "clock.contributors.ambassadors": "एंबेसडर (भाषा प्रमुख)",
    "clock.contributors.scholars": "स्कॉलर (अकादमिक सत्यापनकर्ता)",
    "clock.contributors.advisors": "सलाहकार (रणनीति)",
    "clock.contributors.patrons": "संरक्षक (संस्थान)",
    "clock.contributors.backers": "समर्थक (वित्त पोषण)",
    "clock.contributors.founders": "संस्थापक टीम",
    "clock.platform.title": "प्लेटफार्म मेट्रिक्स",
    "clock.platform.languages_active": "सक्रिय भाषाएँ",
    "clock.platform.languages_planned": "नियोजित भाषाएँ",
    "clock.platform.relays": "निर्मित रिले",
    "clock.platform.pages": "वेबसाइट पेज",
    "clock.platform.game_pages": "गेम पेज",
    "clock.platform.inventions": "सूचीबद्ध आविष्कार",
    "clock.platform.words": "लिखित शब्द",
    "clock.platform.tests": "उत्तीर्ण परीक्षण",
    "clock.milestones.title": "मील के पत्थर",
    "clock.milestones.github": "GitHub ओपन सोर्स",
    "clock.milestones.first_pioneer": "पायनियर्स की पहली लहर",
    "clock.milestones.seed": "सीड राउंड ($500K)",
    "clock.milestones.vr": "वीआर कैंपस (मेटा)",
    "clock.regions.title": "8 भाषा ब्लॉक — वैश्विक दौड़",
    "clock.regions.coverage": "संयुक्त कवरेज: ~85% वैश्विक गेमिंग बाजार · ~80% एडटेक खर्च",
    "clock.regions.goal": "लक्ष्य: 2027 तक सभी 8 भाषाएँ",
    "clock.notyet.title": "अभी तक शामिल नहीं — चुनौती",
    "clock.notyet.universities": "वैश्विक विश्वविद्यालय",
    "clock.notyet.eng_students": "इंजीनियरिंग छात्र",
    "clock.notyet.ce_firms": "सिविल इंजीनियरिंग फर्म (शीर्ष 100)",
    "clock.notyet.govts": "राष्ट्रीय सरकारें",
    "clock.notyet.un_bodies": "संयुक्त राष्ट्र निकाय",
    "clock.notyet.people": "जो लोग बुनियादी ढांचे को नहीं समझते हैं",
    "clock.notyet.cta": "उपरोक्त प्रत्येक संख्या एक चुनौती है। प्रत्येक शून्य एक निमंत्रण है।",
    "clock.challenge.title": "संरक्षक चुनौती बोर्ड",
    "clock.challenge.note": "चुनौती दी गई = खिलाड़ियों द्वारा नामांकित · अभी तक नहीं = नामांकन की प्रतीक्षा में",
    "clock.partners.title": "पार्टनर चैलेंज बोर्ड",
    "clock.scaling.title": "स्केलिंग मॉडल",
    "clock.scaling.phase1": "चरण 1: संस्थापक",
    "clock.scaling.phase2": "चरण 2: पायनियर (प्रति ब्लॉक 2-3)",
    "clock.scaling.phase3": "चरण 3: एंबेसडर (प्रति ब्लॉक 10)",
    "clock.scaling.phase4": "चरण 4: GitHub ओपन सोर्स",
    "clock.scaling.phase5": "चरण 5: विश्वविद्यालय द्वारा अपनाना",
    "clock.scaling.phase6": "चरण 6: जैविक विकास",
    "clock.intelligence.title": "IAAI इंटेलिजेंस नेटवर्क (INTs)",
    "clock.intelligence.humint": "HUMINT — मानव खुफिया (पायनियर + एंबेसडर)",
    "clock.intelligence.osint": "OSINT — ओपन-सोर्स इंटेलिजेंस (GitHub + सार्वजनिक डेटा)",
    "clock.intelligence.sigint": "SIGINT — सिग्नल इंटेलिजेंस (DAVID AI विश्लेषण)",
    "clock.intelligence.geoint": "GEOINT — जियोस्पेशियल इंटेलिजेंस (8-भाषा क्षेत्र मानचित्रण)",
    "clock.intelligence.comint": "COMINT — संचार खुफिया (अनुवाद नेटवर्क)",
    "clock.intelligence.masint": "MASINT — मापन खुफिया (लर्निंग एनालिटिक्स)",
    "clock.intelligence.elint": "ELINT — इलेक्ट्रॉनिक इंटेलिजेंस (प्लेटफॉर्म वितरण)",
    "clock.cta": "दौड़ में शामिल हों — एक पायनियर बनें",
    "clock.cta.sub": "एक अरब शिक्षार्थियों की यात्रा एक पायनियर से शुरू होती है।",
    // ============================================
    // PIONEERS PAGE
    // ============================================
    "pioneers.title": "पायनियर प्रोग्राम",
    "pioneers.subtitle": "योगदानकर्ताओं की पहली लहर जो हर महाद्वीप पर बुनियादी ढांचे की साक्षरता का परीक्षण, अनुवाद, सत्यापन और प्रसार करेगी। मुफ्त बीटा एक्सेस। संस्थापक दीवार पर अपना स्थान अर्जित करें।",
    "pioneers.tier1.title": "पायनियर",
    "pioneers.tier1.desc": "पहले परीक्षक। खेल खेलें, बग की रिपोर्ट करें, सामग्री को सत्यापित करें। प्रति भाषा ब्लॉक 2-3। खुफिया नेटवर्क के स्काउट्स।",
    "pioneers.tier1.req": "आवश्यकताएँ: जिज्ञासा, कोई भी भाषा, परीक्षण करने की इच्छा",
    "pioneers.tier2.title": "एंबेसडर",
    "pioneers.tier2.desc": "भाषा प्रमुख। देशी उपयोग के लिए एआई अनुवादों की समीक्षा और सुधार करें। एक श्रेय प्राप्त योगदानकर्ता बनें। प्रति भाषा ब्लॉक 10।",
    "pioneers.tier2.req": "आवश्यकताएँ: देशी प्रवाह + पायनियर अनुभव",
    "pioneers.tier3.title": "स्कॉलर",
    "pioneers.tier3.desc": "अकादमिक सत्यापनकर्ता। इंजीनियर, प्रोफेसर, शोधकर्ता जो तकनीकी सटीकता को सत्यापित करते हैं और सामग्री को पाठ्यक्रम में मैप करते हैं।",
    "pioneers.tier3.req": "आवश्यकताएँ: अकादमिक साख + डोमेन विशेषज्ञता",
    "pioneers.tier4.title": "सलाहकार",
    "pioneers.tier4.desc": "रणनीतिक मार्गदर्शन। उद्योग के नेता, नीति निर्माता और संस्थागत कनेक्टर जो दरवाजे खोलते हैं और दिशा को आकार देते हैं।",
    "pioneers.tier4.req": "आवश्यकताएँ: केवल निमंत्रण या नामांकन द्वारा",
    "pioneers.form.title": "एक पायनियर बनने के लिए आवेदन करें",
    "pioneers.form.subtitle": "मुफ्त बीटा एक्सेस। कोई शुल्क नहीं। कोई दायित्व नहीं। बस जिज्ञासा और प्रतिबद्धता।",
    "pioneers.form.name": "पूरा नाम",
    "pioneers.form.email": "ईमेल पता",
    "pioneers.form.country": "देश",
    "pioneers.form.language": "प्राथमिक भाषा",
    "pioneers.form.expertise": "विशेषज्ञता का क्षेत्र",
    "pioneers.form.other_langs": "अन्य भाषाएँ",
    "pioneers.form.motivation": "आप क्यों शामिल होना चाहते हैं? (वैकल्पिक)",
    "pioneers.charter.title": "IAAI चार्टर",
    "pioneers.charter.text": "हमारा मानना है कि बुनियादी ढांचा सभ्यता का ऑपरेटिंग सिस्टम है। जैसे एक नदी ग्रह-स्तरीय परिवर्तन को प्रभावित करने के लिए धीरे-धीरे लेकिन लगातार भूमि को तराशती है, हम खुले ज्ञान, सत्यापित योगदान, सांस्कृतिक सम्मान और इस समझ के लिए प्रतिबद्ध हैं कि हम दुनिया का निर्माण कैसे करते हैं, यह एक बेहतर दुनिया बनाने का पहला कदम है।",
    "pioneers.charter.agree": "मैंने IAAI चार्टर पढ़ लिया है और मैं इससे सहमत हूं। मैं ईमानदारी से योगदान, सांस्कृतिक सम्मान और भाषाओं और सीमाओं के पार ज्ञान के खुले बंटवारे के लिए प्रतिबद्ध हूं। मैं समझता हूं कि यह एक स्वयंसेवी कार्यक्रम है और मेरे योगदान को CC BY-NC-SA 4.0 के तहत श्रेय दिया जाएगा।",
    "pioneers.form.submit": "आवेदन जमा करें — दौड़ में शामिल हों",
    // ============================================
    // HOME PAGE — NEW SECTIONS
    // ============================================
    "home.ppp.clock.title": "मोबिलाइजेशन क्लॉक देखें",
    "home.ppp.clock.sub": "बुनियादी ढांचे की साक्षरता की दौड़ में मानवता को वास्तविक समय में ट्रैक करें। चुनौती शुरू हो गई है।",

    // ============================================
    // NAV ROW 2 — CAMPAIGN / COMMUNITY
    // ============================================
    "nav.taxonomy": "वर्गीकरण",
    "nav.outriders": "आउटराइडर्स",
    "nav.institutions": "संस्थान",
    "nav.charter": "चार्टर",

    // ============================================
    // TAXONOMY PAGE
    // ============================================
    "tax.title": "IAAI वर्गीकरण",
    "tax.subtitle": "एक 6+1 स्तरीय संरचना — जैसे जैविक वर्गीकरण राज्य से प्रजाति तक जाता है, IAAI का योगदानकर्ता पदानुक्रम संस्थापक से लेकर समर्थक तक होता है, प्रत्येक परत व्यापक और अधिक विशिष्ट होती है।",
    "tax.founder": "संस्थापक",
    "tax.founder.desc": "वास्तुकार। 1 की गिनती। जिसने पूरी प्रणाली को डिजाइन किया।",
    "tax.advisors": "सलाहकार",
    "tax.advisors.desc": "रणनीतिक मार्गदर्शन। उद्योग के नेता और संस्थागत कनेक्टर।",
    "tax.scholars": "स्कॉलर",
    "tax.scholars.desc": "अकादमिक सत्यापनकर्ता। प्रोफेसर, इंजीनियर, शोधकर्ता।",
    "tax.ambassadors": "एंबेसडर",
    "tax.ambassadors.desc": "भाषा प्रमुख। प्रति भाषा ब्लॉक 10।",
    "tax.pioneers": "पायनियर",
    "tax.pioneers.desc": "पहले परीक्षक। प्रति भाषा ब्लॉक 2-3।",
    "tax.players": "खिलाड़ी",
    "tax.players.desc": "खेल प्रतिभागी। लक्ष्य: 1 अरब शिक्षार्थी।",
    "tax.backers": "समर्थक",
    "tax.backers.desc": "वित्त पोषण और संस्थागत समर्थन। संरक्षक और भागीदार।",
    "tax.biology": "जीव विज्ञान सादृश्य",
    "tax.iaai": "IAAI रैंक",
    "tax.count": "गिनती",
    "tax.role": "भूमिका",
    "tax.outriders.note": "आउटराइडर्स (ऐतिहासिक आत्मा गाइड) 6+1 पदानुक्रम में नहीं गिने जाते हैं — वे सभी मोड, सभी रिले, सभी 12,000 वर्षों तक साथ-साथ चलते हैं।",

    // ============================================
    // OUTRIDERS PAGE
    // ============================================
    "or.title": "आउटराइडर्स",
    "or.subtitle": "ऐतिहासिक आत्मा गाइड जो हर रैंक के साथ-साथ चलते हैं — 6+1 पदानुक्रम में नहीं गिने जाते हैं, ये ज्ञान भागीदार सभी मोड, सभी रिले, सभी 12,000 वर्षों तक फैले हुए हैं। वे खेल में आवाजें हैं, दीवारों पर उद्धरण हैं, आग को टोरस से जोड़ने वाला ज्ञान हैं।",
    "or.quote": "\'''एक प्रबुद्ध राजकुमार और एक बुद्धिमान जनरल जो आगे बढ़ते हैं और पुरुषों पर विजय प्राप्त करते हैं, और जो उपलब्धियां हासिल करते हैं, वे आम लोगों से आगे निकल जाते हैं, वे पूर्वज्ञान हैं।\''' — सुन त्ज़ु, अध्याय XIII",
    "or.stat.total": "कुल आउटराइडर्स",
    "or.stat.eras": "ऐतिहासिक युग",
    "or.stat.relays": "कवर किए गए रिले",
    "or.stat.civilisations": "प्रतिनिधित्व की गई सभ्यताएँ",
    "or.era1.title": "प्राचीन विश्व",
    "or.era2.title": "शास्त्रीय विश्व",
    "or.era3.title": "मध्य युग और पुनर्जागरण",
    "or.era4.title": "औद्योगिक क्रांति",
    "or.era5.title": "आधुनिक युग",
    "or.era6.title": "डिजिटल और भविष्य",
    "or.conn.title": "आउटराइडर्स मिशन की सेवा कैसे करते हैं",
    "or.conn.game.title": "खेल में",
    "or.conn.game.desc": "आउटराइडर्स प्रत्येक रिले में एनपीसी मेंटर्स, उद्धरण स्रोत और ऐतिहासिक संदर्भ प्रदाताओं के रूप में दिखाई देते हैं। खिलाड़ी 12 अध्यायों के माध्यम से आगे बढ़ते हुए उनसे मिलेंगे।",
    "or.conn.book.title": "किताब में",
    "or.conn.book.desc": "प्रत्येक अध्याय एक आउटराइडर के उद्धरण के साथ खुलता और बंद होता है। उनके नवाचार केस स्टडी हैं। उनकी विफलताएं चेतावनी हैं। वे थीसिस के लिए प्रमाण आधार हैं।",
    "or.conn.movement.title": "आंदोलन में",
    "or.conn.movement.desc": "आउटराइडर्स नैतिक अधिकार प्रदान करते हैं। जब IAAI यूनेस्को या एमआईटी को चुनौती देता है, तो यह 12,000 वर्षों के बुनियादी ढांचे के ज्ञान के कंधों पर खड़ा होता है, जिसका प्रतीक ये आंकड़े हैं।",

    // ============================================
    // INSTITUTIONS PAGE
    // ============================================
    "inst.title": "संस्थान",
    "inst.subtitle": "खुफिया नक्शा — हर संस्थान, विश्वविद्यालय, संयुक्त राष्ट्र निकाय, पेशेवर समाज, गैर सरकारी संगठन, प्रौद्योगिकी प्रदाता और पूंजी निकाय जिसे लामबंद, चुनौती या भागीदारी की जा सकती है। वैश्विक प्राथमिकताओं के साथ संरेखण दिखाने के लिए संयुक्त राष्ट्र एसडीजी द्वारा आयोजित।",
    "inst.sdg.title": "एसडीजी द्वारा वर्गीकृत",
    "inst.status.challenged": "चुनौती दी गई",
    "inst.status.engaged": "व्यस्त",
    "inst.status.notyet": "अभी तक संपर्क नहीं किया गया",
    "inst.status.potential": "संभावित",
    "inst.coming": "जल्द आ रहा है — पूरा संस्थागत डेटाबेस निर्माणाधीन है",

    // ============================================
    // CIVILISATION CLOCK PAGE
    // ============================================
    "nav.civclock": "सभ्यता घड़ी",
    "civ.title": "तत्व घड़ी",
    "civ.subtitle": "तीन नेस्टेड 24-घंटे की घड़ियां — बिग बैंग से लेकर मानव क्षण तक। 13.5 अरब साल का ब्रह्मांडीय इतिहास, 4.5 अरब साल का ग्रहीय विकास, 12,000 साल की सभ्यता — प्रत्येक को एक ही दिन में मैप किया गया है। आधी रात करीब है।",
    "civ.epigraph": "\'''तत्व घड़ी आधी रात की ओर टिक-टिक कर रही है। हम इन अंतिम सेकंड में जो करते हैं वह सहस्राब्दियों तक गूंजेगा।\'''",
    "civ.nesting.title": "तीन घड़ियां, एक कहानी",
    "civ.nesting.desc": "प्रत्येक घड़ी पिछले के भीतर नेस्टेड है। पूरी ग्रहीय घड़ी ब्रह्मांडीय घड़ी के अंतिम तीसरे हिस्से पर ही कब्जा करती है। पूरी सभ्यता घड़ी ग्रहीय घड़ी के अंतिम क्षण पर ही कब्जा करती है। हम आधी रात से ठीक पहले के क्षणों में जी रहे हैं।",
    "civ.cosmic.title": "ब्रह्मांडीय घड़ी",
    "civ.cosmic.subtitle": "13.5 अरब वर्ष = 24 घंटे",
    "civ.planetary.title": "ग्रहीय घड़ी",
    "civ.planetary.subtitle": "4.5 अरब वर्ष = 24 घंटे",
    "civ.civilisation.title": "सभ्यता घड़ी",
    "civ.civilisation.subtitle": "12,000 वर्ष = 24 घंटे",
    "civ.relay.title": "सभ्यता घड़ी पर 12 रिले",
    "civ.cta.title": "आधी रात करीब है",
    "civ.cta.desc": "कलम हमारे हाथ में है। बुनियादी ढांचा मौजूद है। क्षण अब है। सवाल यह नहीं है कि यह अभिसरण होगा या नहीं — यह पहले से ही हो रहा है। सवाल यह है: हम इसका जवाब कैसे देंगे?",
    // Volume index pages
    "v1.index.title": "खंड I: परिप्रेक्ष्य",
    "v1.index.about_title": "इस खंड के बारे में",
    "v1.index.relays_title": "बारह रिले",
    
    "v2.index.title": "खंड II: प्लेबुक",
    "v2.index.subtitle": "प्लेबुक — प्रैक्टिकल फ्रेमवर्क और विस्तारित विश्लेषण",
    "v2.index.relays_caption": "बारह सभ्यता रिले — अग्नि से चेतना तक",
    "v2.index.about_title": "इस खंड के बारे में",
    "v2.index.about_text": "खंड II: प्लेबुक चार-स्तंभ ढांचे (अवलोकन → शिक्षा → अनुप्रयोग → थीसिस) को बारह सभ्यता रिले में से प्रत्येक पर लागू करता है। यह खंड यह समझने के लिए व्यावहारिक मार्गदर्शन प्रदान करता है कि बुनियादी ढांचा प्रणाली कैसे काम करती है, उनका विश्लेषण कैसे किया जाए, और उन्हें समकालीन चुनौतियों पर कैसे लागू किया जाए।",
    "v2.index.framework_title": "चार-स्तंभ ढांचा",
    "v2.index.obs": "अवलोकन",
    "v2.index.obs_text": "हम इस रिले के बारे में क्या देखते हैं? इसकी विशेषताएं, घटक और पैटर्न क्या हैं?",
    "v2.index.edu": "शिक्षा",
    "v2.index.edu_text": "हम इस रिले से क्या सीख सकते हैं? यह हमें बुनियादी ढांचे के बारे में कौन से सिद्धांत और सबक सिखाता है?",
    "v2.index.app": "अनुप्रयोग",
    "v2.index.app_text": "हम इन सबकों को कैसे लागू कर सकते हैं? इस रिले से कौन से व्यावहारिक ढांचे और उपकरण निकलते हैं?",
    "v2.index.thesis": "थीसिस",
    "v2.index.thesis_text": "समग्र थीसिस क्या है? इस रिले द्वारा प्रकट की गई मौलिक अंतर्दृष्टि क्या है?",
    
    "v3.index.title": "खंड III: खेल",
    "v3.index.experience_title": "रिले अनुभव",
    
    "lib.title": "दस्तावेज़ पुस्तकालय",
    "lib.supp_title": "पूरक दस्तावेज़",
    "home.charter.charter.h": "चार्टर",
    "home.charter.charter.p": "हम मानते हैं कि बुनियादी ढांचा सभ्यता का ऑपरेटिंग सिस्टम है। जैसे नदी धीरे-धीरे और लगातार भूमि को तराशकर ग्रहीय परिवर्तन लाती है, हम खुले ज्ञान, सत्यापित योगदान, सांस्कृतिक सम्मान और इस विश्वास के प्रति प्रतिबद्ध हैं कि हमने दुनिया कैसे बनाई यह समझना इसे बेहतर बनाने का पहला कदम है।",
    "home.charter.mission.h": "मिशन",
    "home.charter.mission.p": "दुनिया का पहला खुला, बहुभाषी, AI-निर्देशित बुनियादी ढांचा शिक्षा मंच प्रदान करना — 8 भाषाओं के माध्यम से 1 अरब शिक्षार्थियों तक पहुंचना, हर महाद्वीप के मानव योगदानकर्ताओं द्वारा सत्यापित।",
    "home.charter.title": "मिशन, विज़न और चार्टर",
    "home.charter.vision.h": "विज़न",
    "home.charter.vision.p": "एक ऐसी दुनिया जहां हर व्यक्ति सभ्यता को बनाए रखने वाले बुनियादी ढांचे को समझता है — और आगे क्या बनाना है इसका ज्ञान रखता है।",
    "home.pop.answer": "IAAI इस संख्या को बदलने के लिए मौजूद है।",
    "home.pop.question": "लोग इस ग्रह के बुनियादी ढांचे को साझा करते हैं। कितने इसे समझते हैं?",
    "home.pop.source": "स्रोत: संयुक्त राष्ट्र विश्व जनसंख्या अनुमान (वास्तविक समय प्रक्षेपण)",
    "home.ppp.cta.sub": "मुफ्त बीटा एक्सेस — परीक्षण करें, अनुवाद करें, मान्य करें, और संस्थापक दीवार पर अपना स्थान अर्जित करें। ओडिसी में शामिल हों।",
    "home.ppp.cta.title": "पायनियर बनें",
    "home.ppp.partners.h": "भागीदार",
    "home.ppp.partners.p": "विश्वविद्यालय, प्रौद्योगिकी मंच और बुनियादी ढांचा कंपनियां। MIT OCW, खान अकादमी, Meta/VR, Manus/AI, AECOM, Arup, Bechtel। प्रौद्योगिकी, सामग्री सत्यापन और बाजार पहुंच।",
    "home.ppp.partners.status": "स्थिति: चुनौती के लिए खुला — खिलाड़ियों द्वारा नामांकित",
    "home.ppp.patrons.h": "संरक्षक",
    "home.ppp.patrons.p": "ऐसे संस्थान जिनका मिशन सार्वभौमिक बुनियादी ढांचा शिक्षा से मेल खाता है। UNESCO, नेशनल जियोग्राफिक, NASA, रॉयल सोसाइटी, डिस्कवरी, स्मिथसोनियन, NOAA, विश्व बैंक, ADB, चीनी विज्ञान अकादमी।",
    "home.ppp.patrons.status": "स्थिति: चुनौती के लिए खुला — खिलाड़ियों द्वारा नामांकित",
    "home.ppp.players.h": "खिलाड़ी",
    "home.ppp.players.p": "हर देश से पायनियर, एंबेसडर, स्कॉलर और एडवाइजर। वास्तविक लोग जो परीक्षण, अनुवाद, मान्यता, योगदान और प्रचार करते हैं। लोकतंत्र की शक्ति।",
    "home.ppp.players.status": "स्थिति: पायनियर भर्ती — मुफ्त बीटा एक्सेस",
    "home.ppp.reach.active": "सक्रिय",
    "home.ppp.reach.active2": "सक्रिय",
    "home.ppp.reach.active3": "सक्रिय",
    "home.ppp.reach.active4": "सक्रिय",
    "home.ppp.reach.active5": "सक्रिय",
    "home.ppp.reach.active6": "सक्रिय",
    "home.ppp.reach.active7": "सक्रिय",
    "home.ppp.reach.active8": "सक्रिय",
    "home.ppp.reach.ar": "अरबी",
    "home.ppp.reach.cn": "चीनी",
    "home.ppp.reach.coverage": "8 भाषाएं वैश्विक गेमिंग बाजार का ~85%, EdTech खर्च का ~80%, और शीर्ष बुनियादी ढांचा निवेश गलियारों को कवर करती हैं।",
    "home.ppp.reach.en": "अंग्रेज़ी",
    "home.ppp.reach.es": "स्पेनिश",
    "home.ppp.reach.h": "वैश्विक भाषा पहुंच",
    "home.ppp.reach.hi": "हिन्दी",
    "home.ppp.reach.ja": "जापानी",
    "home.ppp.reach.ko": "कोरियाई",
    "home.ppp.reach.vi": "वियतनामी",
    "home.ppp.subtitle": "कैलोरी से चेतना तक — व्यक्तिगत स्तर पर कार्रवाई का आह्वान जिसे रोका या नियंत्रित नहीं किया जा सकता। यह बस सीखता रहता है।",
    "home.ppp.title": "संरक्षक, भागीदार और खिलाड़ी",
    "nav.founders": "संस्थापक दीवार",
    // ============================================
    // MISSING KEYS - ADDED BY TRANSLATION GENERATOR
    // ============================================
    "home.guide.btn": "गाइड पढ़ें",
    "home.guide.title": "खंड 2: मार्गदर्शिका",
    "masters.subtitle": "ऐतिहासिक आध्यात्मिक मार्गदर्शक जो हर स्तर के साथ चलते हैं — 6+1 पदानुक्रम में नहीं गिने जाते, ये बौद्धिक साथी सभी मोड, सभी रिले, सभी 12,000 वर्षों में फैले हैं। वे खेल में आवाज़ें हैं, दीवारों पर उद्धरण हैं, आग को टोरस से जोड़ने वाली बुद्धि हैं।",
    "masters.title": "गुरु",
    "nav.glossary": "शब्दावली",
    "nav.masters": "गुरु",
    "nav.olympiad": "ओलंपियाड",
    "nav.starthere": "यहाँ शुरू करें",
    "precis.relay.relay_10_orbit": "रिले 11: कक्षा",
    "precis.relay.relay_11_human_nodes": "रिले 12: मानव नोड",
    "precis.relay.relay_1_tree": "रिले 2: वृक्ष",
    "precis.relay.relay_2_river": "रिले 3: नदी",
    "precis.relay.relay_3_horse": "रिले 4: घोड़ा",
    "precis.relay.relay_4_roads": "रिले 5: सड़कें",
    "precis.relay.relay_5_ships": "रिले 6: जहाज",
    "precis.relay.relay_6_loom": "रिले 7: करघा",
    "precis.relay.relay_8_engine": "रिले 9: इंजन",
    "precis.relay.relay_9_aaa": "रिले 10: AAA त्रय",
    "tax.cta": "वृक्ष में अपना स्थान खोजें",
    "tax.cta.sub": "हर प्रजाति एक जीव से शुरू होती है। हर आंदोलन एक अग्रणी से शुरू होता है।",
    "tax.footer.cc": "CC BY-NC-SA 4.0",
    "tax.parallel.institutions.desc": "Organisations that can be challenged, engaged, or partnered with. Universities, UN bodies, professional societies, government agencies, NGOs, and corporations. They sit outside the contributor hierarchy but are the targets of the intelligence network and the Challenge Board.",
    "tax.parallel.institutions.title": "&#x1F3DB; Institutions &mdash; The Challenge Map",
    "tax.parallel.institutions.who": "UNESCO &bull; World Bank &bull; ASCE &bull; ICE &bull; MIT &bull; Khan Academy &bull; Meta &bull; National Geographic",
    "tax.parallel.outriders.desc": "Historical and philosophical figures who ride alongside every tier as intellectual companions. Not counted in the 6+1 &mdash; they exist across all levels, all modes, all time periods. They are the voices in the game, the quotes on the walls, the wisdom that connects 12,000 years of infrastructure.",
    "tax.parallel.outriders.title": "&#x1F3C7; Outriders &mdash; Spirit Guides",
    "tax.parallel.outriders.who": "Laozi &bull; Sun Tzu &bull; Confucius &bull; Vitruvius &bull; Leonardo da Vinci &bull; Isambard Kingdom Brunel &bull; Nikola Tesla &bull; Ada Lovelace",
    "tax.parallel.title": "समानांतर पथ (पदानुक्रम के बाहर)",
    "tax.plus1.desc": "जीव विज्ञान में, प्रजाति सबसे विशिष्ट वर्गीकरण है — व्यक्तिगत जीव स्वयं। IAAI में, +1 एक अरब शिक्षार्थी हैं",
    "tax.plus1.subtitle": "मानवता का 12.1% — अवसंरचना साक्षरता का टिपिंग पॉइंट",
    "tax.plus1.target": "लक्ष्य: 1,000,000,000",
    "tax.plus1.title": "+1 — प्रजाति",
    "tax.quote": "\"जिस तरह सभी जीवन एक साझा पूर्वज साझा करते हैं, सभी अवसंरचना एक साझा उद्देश्य साझा करती है — सभ्यता की सेवा करना।\"",
    "tax.rank.class": "वर्ग",
    "tax.rank.domain": "डोमेन",
    "tax.rank.family": "कुल",
    "tax.rank.genus": "वंश",
    "tax.rank.kingdom": "जगत",
    "tax.rank.order": "गण",
    "tax.rank.phylum": "संघ",
    "tax.table.biology": "जीव विज्ञान",
    "tax.table.count": "संख्या",
    "tax.table.iaai": "IAAI",
    "tax.table.suntzu": "बुद्धिमत्ता (INT)",
    "tax.tier1.analogy": "Biology: Domain (Eukarya) &bull; Military: Commander-in-Chief &bull; Architecture: Master Builder",
    "tax.tier1.desc": "The singular origin point. Conceived the 12-relay framework, wrote the trilogy, designed the game, and built the platform. Like Domain in biology &mdash; the broadest, most fundamental classification from which everything else branches.",
    "tax.tier1.name": "संस्थापक",
    "tax.tier1.title": "वास्तुकार",
    "tax.tier1.who": "Ir. Nigel T. Dearden &mdash; CEng MICE MHKIE",
    "tax.tier2.analogy": "Biology: Kingdom (Animalia) &bull; Military: General Staff &bull; Sun Tzu: The Five Essentials",
    "tax.tier2.desc": "The inner circle. Industry leaders, capital strategists, and institutional connectors who shape direction, open doors, and bridge the gap between vision and execution. By invitation or nomination only.",
    "tax.tier2.name": "सलाहकार",
    "tax.tier2.title": "रणनीतिक परिषद",
    "tax.tier2.who": "Michael Wu (COO) &bull; Henry Leong (CFO) &bull; Frank Sheu (CTO) &bull; Stephen Markscheid (Strategic Advisor)",
    "tax.tier3.analogy": "Biology: Phylum (Chordata) &bull; Military: Intelligence Corps &bull; Academia: Peer Review Board",
    "tax.tier3.desc": "Engineers, professors, and researchers who verify technical accuracy, map content to university curricula, and provide the academic credibility that transforms a game into an educational standard. The peer-review layer.",
    "tax.tier3.name": "विद्वान",
    "tax.tier3.title": "शैक्षणिक सत्यापनकर्ता",
    "tax.tier3.who": "Target: Engineering faculties, infrastructure researchers, curriculum designers",
    "tax.tier4.analogy": "Biology: Class (Mammalia) &bull; Military: Field Officers &bull; Diplomacy: Cultural Attach&eacute;s",
    "tax.tier4.desc": "Native-fluency contributors who review and correct AI translations against real usage. 10 per language block across 8 languages. They ensure infrastructure literacy speaks authentically in every tongue. Credited contributors with their names on the work.",
    "tax.tier4.name": "राजदूत",
    "tax.tier4.title": "भाषा नेता",
    "tax.tier4.who": "Target: 10 per block &times; 8 blocks = 80 Ambassadors worldwide",
    "tax.tier5.analogy": "Biology: Order (Primates) &bull; Military: HUMINT (Human Intelligence) &bull; Scouts &amp; Reconnaissance",
    "tax.tier5.desc": "The first wave. 2&ndash;3 per language block who play the game, report bugs, validate content, and provide the ground-truth feedback that shapes the platform before public release. The HUMINT assets of the intelligence network — human intelligence on the ground.",
    "tax.tier5.name": "अग्रणी",
    "tax.tier5.title": "बीटा परीक्षक और स्काउट",
    "tax.tier5.who": "Currently recruiting &mdash; 3 active across EN and CN blocks",
    "tax.tier6.analogy": "Biology: Family (Hominidae) &bull; Military: The Rank and File &bull; Gaming: The Player Base",
    "tax.tier6.desc": "Everyone who plays The Reality Engine. From casual explorers to completionists who master all 12 relays across all 4 modes. They generate the data, the engagement, and the democratic nominations that power the Challenge Board. The lifeblood of the platform.",
    "tax.tier6.name": "खिलाड़ी",
    "tax.tier6.title": "गेम समुदाय",
    "tax.tier6.who": "Target: 1M players by Year 2 &bull; Currently: 21 (beta)",
    "tax.tier7.analogy": "Biology: Genus (Homo) &bull; Military: ELINT (Electronic Intelligence) &bull; Logistics &amp; Supply",
    "tax.tier7.desc": "Those who fund the mission &mdash; from individual Kickstarter backers to institutional patrons (UNESCO, National Geographic, universities). They don't play or translate; they enable. Challenged by Players, engaged by Advisors. The ELINT channel of the intelligence network — converting institutional signals into engagement.",
    "tax.tier7.name": "समर्थक",
    "tax.tier7.title": "वित्तीय और संस्थागत समर्थक",
    "tax.tier7.who": "Target: $500K seed &bull; Challenged: UNESCO, NatGeo, NASA, Royal Society, MIT OCW, Khan Academy",
    "v1.r01.continuity": "निरंतरता",
    "v1.r01.energy_web": "ऊर्जा जाल",
    "v1.r01.infrastructure": "अवसंरचना",
    "v1.r01.knowledge_web": "ज्ञान जाल",
    "v1.r01.threats": "खतरे",
    "v1.r01.unification": "एकीकरण",
    "v1.r02.continuity": "निरंतरता",
    "v1.r02.energy_web": "ऊर्जा जाल",
    "v1.r02.infrastructure": "अवसंरचना",
    "v1.r02.knowledge_web": "ज्ञान जाल",
    "v1.r02.threats": "खतरे",
    "v1.r02.unification": "एकीकरण",
    "v1.r03.continuity": "निरंतरता",
    "v1.r03.energy_web": "ऊर्जा जाल",
    "v1.r03.infrastructure": "अवसंरचना",
    "v1.r03.knowledge_web": "ज्ञान जाल",
    "v1.r03.threats": "खतरे",
    "v1.r03.unification": "एकीकरण",
    "v1.r04.continuity": "निरंतरता",
    "v1.r04.energy_web": "ऊर्जा जाल",
    "v1.r04.infrastructure": "अवसंरचना",
    "v1.r04.threats": "खतरे",
    "v1.r04.unification": "एकीकरण",
    "v1.r05.consciousness_web": "चेतना जाल",
    "v1.r05.continuity": "निरंतरता",
    "v1.r05.infrastructure": "अवसंरचना",
    "v1.r05.knowledge_web": "ज्ञान जाल",
    "v1.r05.threats": "खतरे",
    "v1.r05.unification": "एकीकरण",
    "v1.r06.consciousness_web": "चेतना जाल",
    "v1.r06.continuity": "निरंतरता",
    "v1.r06.infrastructure": "अवसंरचना",
    "v1.r06.knowledge_web": "ज्ञान जाल",
    "v1.r06.threats": "खतरे",
    "v1.r06.unification": "एकीकरण",
    "v1.r07.continuity": "निरंतरता",
    "v1.r07.energy_web": "ऊर्जा जाल",
    "v1.r07.infrastructure": "अवसंरचना",
    "v1.r07.knowledge_web": "ज्ञान जाल",
    "v1.r07.threats": "खतरे",
    "v1.r07.unification": "एकीकरण",
    "v1.r08.consciousness_web": "चेतना जाल",
    "v1.r08.continuity": "निरंतरता",
    "v1.r08.energy_web": "ऊर्जा जाल",
    "v1.r08.infrastructure": "अवसंरचना",
    "v1.r08.knowledge_web": "ज्ञान जाल",
    "v1.r08.threats": "खतरे",
    "v1.r08.unification": "एकीकरण",
    "v1.r09.continuity": "निरंतरता",
    "v1.r09.energy_web": "ऊर्जा जाल",
    "v1.r09.infrastructure": "अवसंरचना",
    "v1.r09.knowledge_web": "ज्ञान जाल",
    "v1.r09.threats": "खतरे",
    "v1.r09.unification": "एकीकरण",
    "v1.r10.consciousness_web": "चेतना जाल",
    "v1.r10.continuity": "निरंतरता",
    "v1.r10.energy_web": "ऊर्जा जाल",
    "v1.r10.infrastructure": "अवसंरचना",
    "v1.r10.knowledge_web": "ज्ञान जाल",
    "v1.r10.threats": "खतरे",
    "v1.r10.unification": "एकीकरण",
    "v1.r11.consciousness_web": "चेतना जाल",
    "v1.r11.continuity": "निरंतरता",
    "v1.r11.infrastructure": "अवसंरचना",
    "v1.r11.knowledge_web": "ज्ञान जाल",
    "v1.r11.threats": "खतरे",
    "v1.r11.unification": "एकीकरण",
    "v1.r12.consciousness_web": "चेतना जाल",
    "v1.r12.continuity": "निरंतरता",
    "v1.r12.infrastructure": "अवसंरचना",
    "v1.r12.knowledge_web": "ज्ञान जाल",
    "v1.r12.threats": "खतरे",
    "v1.r12.unification": "एकीकरण",
    // ============================================
    // RELAY PAGE TRANSLATIONS (HINDI)
    // ============================================
    "v1.r01.active_webs": "सक्रिय जाल",
    "v1.r01.counterparts_title": "प्रतिरूप: अग्नि",
    "v1.r01.four_pillars": "चार स्तंभ",
    "v1.r01.historical_significance": "ऐतिहासिक महत्व",
    "v1.r01.subtitle": "प्रज्वलन — संगीतकार | ऊर्जा: आदिम विकिरण | प्राकृतिक / ऊर्जा जाल",
    "v1.r01.title": "रिले 1: अग्नि",
    "v1.r02.active_webs": "सक्रिय जाल",
    "v1.r02.counterparts_title": "प्रतिरूप: वृक्ष",
    "v1.r02.four_pillars": "चार स्तंभ",
    "v1.r02.historical_significance": "ऐतिहासिक महत्व",
    "v1.r02.subtitle": "बसावट — पुनर्जनक | ऊर्जा: स्थिर संग्रहित | प्राकृतिक / ऊर्जा जाल",
    "v1.r02.title": "रिले 2: वृक्ष",
    "v1.r03.active_webs": "सक्रिय जाल",
    "v1.r03.counterparts_title": "प्रतिरूप: नदी",
    "v1.r03.four_pillars": "चार स्तंभ",
    "v1.r03.historical_significance": "ऐतिहासिक महत्व",
    "v1.r03.subtitle": "विनिमय — प्रवाह गुरु | ऊर्जा: संभावित अदोहित | प्राकृतिक / ऊर्जा जाल",
    "v1.r03.title": "रिले 3: नदी",
    "v1.r04.active_webs": "सक्रिय जाल",
    "v1.r04.counterparts_title": "प्रतिरूप: घोड़ा",
    "v1.r04.four_pillars": "चार स्तंभ",
    "v1.r04.historical_significance": "ऐतिहासिक महत्व",
    "v1.r04.subtitle": "साम्राज्य — मुक्तिदाता | ऊर्जा: लचीली गतिशील | प्राकृतिक / ऊर्जा जाल",
    "v1.r04.title": "रिले 4: घोड़ा",
    "v1.r05.active_webs": "सक्रिय जाल",
    "v1.r05.counterparts_title": "प्रतिरूप: सड़कें",
    "v1.r05.four_pillars": "चार स्तंभ",
    "v1.r05.historical_significance": "ऐतिहासिक महत्व",
    "v1.r05.subtitle": "पतन — कथाकार | ऊर्जा: संभावित सुप्त | यंत्र / ज्ञान जाल",
    "v1.r05.title": "रिले 5: सड़कें",
    "v1.r06.active_webs": "सक्रिय जाल",
    "v1.r06.counterparts_title": "प्रतिरूप: जहाज",
    "v1.r06.four_pillars": "चार स्तंभ",
    "v1.r06.historical_significance": "ऐतिहासिक महत्व",
    "v1.r06.subtitle": "पुनर्खोज — संयोजक | ऊर्जा: वेगीय गतिज | यंत्र / ज्ञान जाल",
    "v1.r06.title": "रिले 6: जहाज",
    "v1.r07.active_webs": "सक्रिय जाल",
    "v1.r07.counterparts_title": "प्रतिरूप: रेल",
    "v1.r07.four_pillars": "चार स्तंभ",
    "v1.r07.historical_significance": "ऐतिहासिक महत्व",
    "v1.r07.subtitle": "पुनर्जागरण — बुनकर | ऊर्जा: स्थायी यांत्रिक | यंत्र / ज्ञान जाल",
    "v1.r07.title": "रिले 7: करघा",
    "v1.r08.active_webs": "सक्रिय जाल",
    "v1.r08.counterparts_title": "प्रतिरूप: करघा",
    "v1.r08.four_pillars": "चार स्तंभ",
    "v1.r08.historical_significance": "ऐतिहासिक महत्व",
    "v1.r08.subtitle": "उद्योग — सशक्तकर्ता | ऊर्जा: विस्फोटक ताप | यंत्र / ज्ञान जाल",
    "v1.r08.title": "रिले 8: रेल",
    "v1.r09.active_webs": "सक्रिय जाल",
    "v1.r09.counterparts_title": "प्रतिरूप: इंजन",
    "v1.r09.four_pillars": "चार स्तंभ",
    "v1.r09.historical_significance": "ऐतिहासिक महत्व",
    "v1.r09.subtitle": "आधुनिकता — लोकतंत्रकर्ता | ऊर्जा: गतिशील रासायनिक | सूचना / वाणिज्य",
    "v1.r09.title": "रिले 9: इंजन",
    "v1.r10.active_webs": "सक्रिय जाल",
    "v1.r10.counterparts_title": "प्रतिरूप: AAA त्रय",
    "v1.r10.four_pillars": "चार स्तंभ",
    "v1.r10.historical_significance": "ऐतिहासिक महत्व",
    "v1.r10.subtitle": "ऑटोमोबाइल, विमानन और एयरवेव्स — तिहरी क्रांति | ऊर्जा: पेट्रोलियम",
    "v1.r10.title": "रिले 10: AAA त्रय",
    "v1.r11.active_webs": "सक्रिय जाल",
    "v1.r11.counterparts_title": "प्रतिरूप: मानव नोड",
    "v1.r11.four_pillars": "चार स्तंभ",
    "v1.r11.historical_significance": "ऐतिहासिक महत्व",
    "v1.r11.subtitle": "अंतरिक्ष — वर्णनकर्ता | ऊर्जा: स्थानिक आकर्षक | बुद्धि / चेतना",
    "v1.r11.title": "रिले 11: कक्षा",
    "v1.r12.active_webs": "सक्रिय जाल",
    "v1.r12.counterparts_title": "प्रतिरूप: चेतना",
    "v1.r12.four_pillars": "चार स्तंभ",
    "v1.r12.historical_significance": "ऐतिहासिक महत्व",
    "v1.r12.subtitle": "चेतना — मेस्ट्रो | ऊर्जा: बुद्धिमान ऊर्जा | बुद्धि / चेतना",
    "v1.r12.title": "रिले 12: मानव नोड",
    "oly.title": "इन्फ्रास्ट्रक्चर ओलंपियाड",
    "oly.stat.blocks": "भाषा ब्लॉक",
    "oly.stat.categories": "प्रतियोगिता श्रेणियाँ",
    "oly.stat.universities": "विश्वविद्यालय विश्वभर में",
    "oly.stat.xpcap": "XP कैप (मास्टर वीवर)",
    "oly.stat.people": "पहुँच",
    "oly.stat.gap": "इन्फ्रास्ट्रक्चर अंतर",
    "oly.flywheel.title": "फ्लाईव्हील — ओलंपियाड कैसे बढ़ता है",
    "oly.flywheel.players": "खिलाड़ी प्रतिस्पर्धा करते हैं",
    "oly.flywheel.professionals": "पेशेवर मान्य करते हैं",
    "oly.flywheel.patrons": "प्रायोजक सहायता करते हैं",
    "oly.flywheel.platform": "मंच विस्तार करता है",
    "oly.medal.title": "लाइव मेडल टेबल — सभ्यता प्रबंधन पर राष्ट्र प्रतिस्पर्धा",
    "oly.th.nation": "राष्ट्र",
    "oly.th.blocks": "ब्लॉक",
    "oly.th.pop": "जनसंख्या (M)",
    "oly.th.gamers": "गेमर्स (M)",
    "oly.th.story": "इन्फ्रास्ट्रक्चर कहानी",
    "oly.th.total": "कुल",
    "oly.th.status": "स्थिति",
    "oly.rogue.title": "रोग टीमें — असंबद्ध प्रतिभा पूल",
    "oly.categories.title": "प्रतियोगिता श्रेणियाँ — सभ्यता इन्फ्रास्ट्रक्चर के छह स्तंभ",
    "oly.pipeline.unis": "विश्वविद्यालय विश्वभर में",
    "oly.pipeline.students": "इंजीनियरिंग छात्र",
    "oly.pipeline.firms": "शीर्ष सिविल इंजीनियरिंग कंपनियाँ",
    "oly.pipeline.govts": "राष्ट्रीय सरकारें",
    "oly.sponsor.title": "प्रायोजन स्तर — राष्ट्रीय टीम का समर्थन करें",
    "oly.sponsor.gold": "स्वर्ण प्रायोजक",
    "oly.sponsor.silver": "रजत प्रायोजक",
    "oly.sponsor.bronze": "कांस्य प्रायोजक",
    "oly.sponsor.patron": "संरक्षक",
    "oly.form.register.title": "अपनी विश्वविद्यालय टीम पंजीकृत करें",
    "oly.form.sponsor.title": "प्रायोजन पूछताछ",
    "nav.behind": "थीसिस के पीछे",

    // SDG Alignment Section
    "sdg.title": "सतत विकास लक्ष्य — संरेखण",
    "sdg.subtitle": "IAAI की 12-रिले पाठ्यक्रम संयुक्त राष्ट्र सतत विकास लक्ष्यों से कैसे जुड़ती है",
    "sdg.iconCaption": "IAAI सामग्री सीधे 17 सतत विकास लक्ष्यों में से 11 को संबोधित करती है। प्रत्येक आइकन आधिकारिक संयुक्त राष्ट्र लक्ष्य पृष्ठ से जुड़ा है।",
    "sdg.col.relay": "IAAI रिले",
    "sdg.col.sdgGoals": "SDG लक्ष्य",
    "sdg.col.alignment": "संरेखण तर्क",
    "sdg.col.5p": "5P श्रेणी",
    "sdg.r1.rationale": "सड़क नेटवर्क आर्थिक विकास की संचार प्रणाली है। सड़कों के बिना, न बाजार पहुंच, न आपातकालीन सेवाएं, न आपूर्ति श्रृंखला।",
    "sdg.r2.rationale": "रेल सामूहिक परिवहन और माल ढुलाई की रीढ़ है। सड़क से प्रति टन-किमी कम उत्सर्जन, टिकाऊ शहरीकरण को सक्षम बनाता है।",
    "sdg.r3.rationale": "बंदरगाह राष्ट्रों को वैश्विक व्यापार से जोड़ते हैं। दुनिया के 90% माल समुद्र से चलते हैं।",
    "sdg.r4.rationale": "विमानन बुनियादी ढांचा वैश्विक कनेक्टिविटी, व्यापार, पर्यटन और आपातकालीन प्रतिक्रिया को सक्षम बनाता है।",
    "sdg.r5.rationale": "स्वच्छ जल सबसे मूलभूत बुनियादी ढांचा है। 2.2 अरब लोगों के पास अभी भी सुरक्षित पेयजल नहीं है।",
    "sdg.r6.rationale": "स्वच्छता बीमारी को रोकती है, जल स्रोतों की रक्षा करती है और मानव गरिमा को बनाए रखती है।",
    "sdg.r7.rationale": "ऊर्जा बुनियादी ढांचा निर्धारित करता है कि राष्ट्र स्वच्छ रूप से औद्योगीकरण करते हैं या जीवाश्म ईंधन निर्भरता दोहराते हैं।",
    "sdg.r8.rationale": "दूरसंचार लोगों को शिक्षा, बाजारों और शासन से जोड़ता है। डिजिटल विभाजन बुनियादी ढांचे का विभाजन है।",
    "sdg.r9.rationale": "अपशिष्ट प्रबंधन उपभोग का दर्पण है। चक्रीय अर्थव्यवस्थाओं को संग्रह, छंटाई और पुनर्चक्रण के बुनियादी ढांचे की आवश्यकता है।",
    "sdg.r10.rationale": "स्वास्थ्य बुनियादी ढांचा — अस्पताल, क्लीनिक, आपूर्ति श्रृंखला — निर्धारित करता है कि आबादी महामारी से बचती है या नहीं।",
    "sdg.r11.rationale": "शैक्षिक बुनियादी ढांचा — स्कूल, विश्वविद्यालय, पुस्तकालय — वह तंत्र है जिसके द्वारा सभ्यताएं पीढ़ियों में ज्ञान प्रसारित करती हैं।",
    "sdg.r12.rationale": "डिजिटल बुनियादी ढांचा — डेटा सेंटर, फाइबर, क्लाउड — 21वीं सदी की सड़कें और बंदरगाह हैं।",
    "sdg.5pTitle": "5P — लोग, ग्रह, समृद्धि, शांति, साझेदारी",
    "sdg.5pText": "संयुक्त राष्ट्र 17 SDG को पांच स्तंभों (5P) के माध्यम से तैयार करता है। बुनियादी ढांचा वह तंत्र है जिसके द्वारा सभ्यताएं सभी पांच P को पूरा करती हैं।",
    "sdg.visitUN": "संयुक्त राष्ट्र SDG आधिकारिक वेबसाइट पर जाएं →",
    "sdg.disclaimerTitle": "अस्वीकरण:",
    "sdg.disclaimerText": "इस प्रकाशन की सामग्री संयुक्त राष्ट्र द्वारा अनुमोदित नहीं है और संयुक्त राष्ट्र या इसके अधिकारियों या सदस्य राज्यों के विचारों को प्रतिबिंबित नहीं करती है।",
    "home.dominion.title": "प्रभुत्व का नुकसान — अभिसरण संकट",
    "home.dominion.text": "छठा रीसेट अंतरिक्ष से नहीं आएगा। यह पहले से यहाँ है — निर्णय-निर्माण, डिज़ाइन और शासन के मानव प्रणालियों से मशीन प्रणालियों में स्थानांतरण में। विलुप्ति नहीं। विस्थापन। 12,000 वर्षों से सभ्यता को वहन करने वाला बुनियादी ढांचा अब किसी भी पीढ़ी की अवशोषण क्षमता से तेज़ गति से अभिसरित हो रहा है। यही अभिसरण संकट है। एपिसोड 2 मानव निरंतरता की वास्तुकला का मानचित्रण करता है।",
    "home.fw.ele_planetary": "ELE ग्रहीय घड़ी — पृथ्वी: 4.5 अरब वर्ष। पाँच रीसेट। ELE 6 सभ्यतागत है — 2050। अभी कार्य करें या प्रभुत्व खोएं।",
    "home.fw.continuity_grid": "पूर्ण निरंतरता ग्रिड — यदि मानव इतिहास 1,200 पृष्ठों की पुस्तक होती। 24 पंक्तियाँ = 24 घंटे। ग्रिड ही घड़ी है। पंक्ति 24 = अंतिम घंटा।",
    "home.fw.row24": "पंक्ति 24 विस्तारित — अंतिम घंटा। 12,000 वर्ष (10,000 ईसा पूर्व → 2050 ईस्वी)। 500 पीढ़ियाँ। एकमात्र पंक्ति जहाँ मानवता रिले का उपयोग करती है। सात विद्वान। 246 वर्षों में छह रिले। सभी अभी भी चल रहे हैं।",
    "home.fw.relay_cone": "रिले शंकु — 500 पीढ़ियों की सभ्यता 12 बुनियादी ढांचा रिले में संपीड़ित। पार्श्व दृश्य, ऊपरी दृश्य, और सात विद्वान। पहले छह रिले 11,500 वर्षों में फैले हैं; अंतिम छह 246 वर्षों में संपीड़ित हैं।",
    "home.ascent.title": "चेतना की चढ़ाई",
    "home.ascent.subtitle": "रिले 12 और आगे — 2050 को मध्यरात्रि मानते हुए सभ्यता का शोधप्रबंध",
    "home.ascent.text": "यहीं सभ्यता का मूल निवास करता है। कैलोरी से चेतना तक — एक बुनियादी ढांचा ओडिसी 12,000 वर्षों को 12 रिले, 7 विद्वानों, 5 जालों और 3 महान साम्राज्यों के माध्यम से चित्रित करती है। चेतना की चढ़ाई रिले 12 और उससे आगे है: वह स्थानांतरण बिंदु जहाँ जैविक बुद्धि अपने स्वयं के बुनियादी ढांचे से मिलती है। बौद्धिक वंशावली के पाँच स्तर — होमर से अनुप्रयुक्त पीढ़ी तक — एक ही प्रश्न पर अभिसरित होते हैं: रिले को आगे कौन ले जाएगा? धार्मिक निहितार्थ गहन हैं। प्रभुत्व का नुकसान संकट को रूपरेखा देता है; प्रतिबल: भाग, माप और संतुलन इंजीनियर का कलन प्रदान करता है। 8वाँ विद्वान खुली खोज बना हुआ है — 3,500 वर्षों की मूलभूत ज्ञान श्रृंखला में अगला नोड।",
    "home.ascent.source": "वंशावली 5 स्तर — 8वें विद्वान की ओर 3,500 वर्षीय बौद्धिक रिले — iAAi सत्य ढांचा"
};
