// INFRASTRUCTURE ACADEMY - JA TRANSLATIONS
window.IA_LANG_JA = {
    "archive.documents": "文献",
    "archive.images": "画像",
    "archive.references": "参考文献",
    "archive.relays": "リレー",
    "archive.subtitle": "完全な知識資産の保存",
    "archive.supplements": "補足資料",
    "archive.title": "アーカイブ",
    "author.bio": "Ir. Nigel T Dearden（鄧禮祖）は特許土木構造技術士および特許水環境管理士であり、香港インフラ分野で33年以上の経験を持ちます。4 Elements Consulting Ltd 創設者（2006年設立、www.4ecl.com）。BEng (Hon's), CEng, C.WEM, RPE (CSB), MICE, MHKIE, MCIWEM。",
    "author.credentials": "公認技術者 (CEng)、英国土木学会員 (MICE)、香港技術者学会員 (MHKIE)",
    "author.name": "ナイジェル・T・デアデン技術士 (Ir. Nigel T. Dearden)",
    "author.title": "著者について",
    "civ.civilisation.subtitle": "12,000年 = 24時間",
    "civ.civilisation.title": "文明時計",
    "civ.cosmic.subtitle": "135億年 = 24時間",
    "civ.cosmic.title": "宇宙時計",
    "civ.cta.desc": "ペンは私たちの手の中にあります。インフラは整っています。時は今です。問題は、この収束が起こるかどうかではありません — それはすでに起こっています。問題は、私たちはそれにどう応えるかです。",
    "civ.cta.title": "真夜中は近い",
    "civ.epigraph": "\"元素時計は真夜中に向かって時を刻む。私たちが最後の数秒で行うことは、千年にわたって響き渡るだろう。\"",
    "civ.nesting.desc": "各時計は前の時計に入れ子になっています。惑星時計全体は、宇宙時計の最後の3分の1しか占めていません。文明時計全体は、惑星時計の最後の瞬間です。私たちは真夜中直前の最後の瞬間に生きています。",
    "civ.nesting.title": "3つの時計、1つの物語",
    "civ.planetary.subtitle": "45億年 = 24時間",
    "civ.planetary.title": "惑星時計",
    "civ.relay.title": "文明時計上の12のリレー",
    "civ.subtitle": "3つの入れ子になった24時間時計 — ビッグバンから人類の瞬間まで。135億年の宇宙の歴史、45億年の惑星の進化、12,000年の文明 — それぞれが1日にマッピングされています。真夜中は近いです。",
    "civ.title": "元素時計",
    "clock.bar.end": "1,000,000,000 — ミッション完了",
    "clock.bar.mid": "パイオニア → アンバサダー → スカラー",
    "clock.bar.start": "0 — 開始",
    "clock.challenge.note": "挑戦済み = プレイヤーによる指名・まだ = 指名待ち",
    "clock.challenge.title": "パトロンチャレンジリーダーボード",
    "clock.contributors.advisors": "アドバイザー（戦略）",
    "clock.contributors.ambassadors": "アンバサダー（言語リーダー）",
    "clock.contributors.backers": "バッカー（資金提供）",
    "clock.contributors.founders": "創設チーム",
    "clock.contributors.patrons": "パトロン（機関）",
    "clock.contributors.pioneers": "パイオニア（テスター）",
    "clock.contributors.players": "プレイヤー（ゲーム）",
    "clock.contributors.scholars": "スカラー（学術バリデーター）",
    "clock.contributors.title": "貢献者のカテゴリー",
    "clock.cta": "競争に参加 — パイオニアになる",
    "clock.cta.sub": "10億人の学習者の旅は、一人のパイオニアから始まります。",
    "clock.hero.mobilised": "現在動員済み",
    "clock.hero.pop": "世界人口",
    "clock.hero.pop.sub": "国連によるリアルタイム推定",
    "clock.hero.target": "目標：10億人の学習者",
    "clock.hero.target.sub": "人類の12.1% — 転換点",
    "clock.intelligence.comint": "COMINT — 通信インテリジェンス（翻訳ネットワーク）",
    "clock.intelligence.elint": "ELINT — 電子インテリジェンス（プラットフォーム配信）",
    "clock.intelligence.geoint": "GEOINT — 地理空間インテリジェンス（8言語地域のマッピング）",
    "clock.intelligence.humint": "HUMINT — ヒューマンインテリジェンス（パイオニア＋アンバサダー）",
    "clock.intelligence.masint": "MASINT — 測定・標識インテリジェンス（学習分析）",
    "clock.intelligence.osint": "OSINT — オープンソースインテリジェンス（GitHub＋公開データ）",
    "clock.intelligence.sigint": "SIGINT — シグナルインテリジェンス（DAVID AI分析）",
    "clock.intelligence.title": "IAAIインテリジェンスネットワーク（INTs）",
    "clock.milestones.first_pioneer": "最初のパイオニアの波",
    "clock.milestones.github": "GitHubオープンソース化",
    "clock.milestones.seed": "シードラウンド（50万ドル）",
    "clock.milestones.title": "マイルストーン",
    "clock.milestones.vr": "VRキャンパス（Meta）",
    "clock.notyet.ce_firms": "土木工学会社（トップ100）",
    "clock.notyet.cta": "上記の各数字は挑戦です。各ゼロは招待状です。",
    "clock.notyet.eng_students": "工学部の学生",
    "clock.notyet.govts": "各国政府",
    "clock.notyet.people": "インフラについて知らない人々",
    "clock.notyet.title": "まだ参加していない — 挑戦",
    "clock.notyet.un_bodies": "国連機関",
    "clock.notyet.universities": "世界の大学",
    "clock.partners.title": "パートナーチャレンジリーダーボード",
    "clock.platform.game_pages": "ゲームページ",
    "clock.platform.inventions": "カタログ化された発明",
    "clock.platform.languages_active": "アクティブな言語",
    "clock.platform.languages_planned": "計画中の言語",
    "clock.platform.pages": "ウェブサイトページ",
    "clock.platform.relays": "構築済みのリレー",
    "clock.platform.tests": "合格したテスト",
    "clock.platform.title": "プラットフォーム指標",
    "clock.platform.words": "執筆された単語数",
    "clock.regions.coverage": "総合的なカバレッジ：世界のゲーム市場の約85%・教育技術支出の約80%",
    "clock.regions.goal": "目標：2027年までに全8言語",
    "clock.regions.title": "8つの言語ブロック — グローバルな競争",
    "clock.scaling.phase1": "フェーズ1：創設者",
    "clock.scaling.phase2": "フェーズ2：パイオニア（各ブロック2〜3人）",
    "clock.scaling.phase3": "フェーズ3：アンバサダー（各ブロック10人）",
    "clock.scaling.phase4": "フェーズ4：GitHubオープンソース化",
    "clock.scaling.phase5": "フェーズ5：大学での採用",
    "clock.scaling.phase6": "フェーズ6：有機的成長",
    "clock.scaling.title": "スケーリングモデル",
    "clock.subtitle": "インフラリテラシーへの人類の競争 — 挑戦",
    "clock.title": "IAAIグローバル動員時計",
    "footer.ep1": "エピソード 1：地球の基盤",
    "footer.ep2": "エピソード 2：灰色の闘技場",
    "footer.ep3": "エピソード 3：宇宙のスケール",
    "footer.copyright": "&copy; 2026 インフラストラクチャー・アカデミー。全著作権所有。知識を永遠に保存します。",
    "framework.4cs.challenge": "課題 (Challenge)",
    "framework.4cs.consequence": "結果 (Consequence)",
    "framework.4cs.context": "背景 (Context)",
    "framework.4cs.continuum": "連続体 (Continuum)",
    "framework.4cs.title": "4C分析フレームワーク",
    "framework.modes.east": "東洋モード",
    "framework.modes.east.desc": "連続／建設型 — 始皇帝の原型",
    "framework.modes.outrider": "アウトライダー・モード",
    "framework.modes.outrider.desc": "半連続／一時的建設 — チンギス・ハーンの原型",
    "framework.modes.title": "三つの文明モード",
    "framework.modes.west": "西洋モード",
    "framework.modes.west.desc": "不連続／建設型 — アレキサンダー大王の原型",
    "framework.relays.title": "12の文明リレー",
    "framework.subtitle": "統合的システム思考の方法論",
    "framework.title": "完全なフレームワーク",
    "header.subtitle": "インフラストラクチャー・オデッセイ：第一巻 — カロリーから意識へ",
    "header.subtitle.v2": "インフラストラクチャー・オデッセイ：第二巻 — 実践ガイド",
    "header.subtitle.v3": "インフラストラクチャー・オデッセイ：第三巻 — リアリティ・エンジン",
    "header.title": "インフラストラクチャー・アカデミー",
    "home.archive.architects": "運命の建築家と偉大な統一者：アレキサンダー大王、チンギス・ハーン、始皇帝",
    "home.archive.p1": "インフラストラクチャー・アカデミーは、「インフラストラクチャー・オデッセイ」の完全な知識資産を保存するデジタルアーカイブです。これは、12,000年にわたる人類のインフラ開発に関する文明のマスタークラスです。このウェブサイトは、世界中の学者、技術者、学習者が知識に永遠にアクセスできるようにします。",
    "home.archive.p2": "すべてのコンテンツ、視覚化、フレームワークがここに統合されており、簡単なナビゲーションと発見が可能です。これは、カロリーから意識へと至る人類の台頭の永続的な記録であり、ペンによってデジタルの永遠に刻まれています。",
    "home.archive.title": "このアーカイブについて",
    "home.author": "著者：ナイジェル・T・デアデン技術士 (Ir. Nigel T. Dearden)",
    "home.challenge.stat1.desc": "のカリキュラムが学際的統合を欠いている",
    "home.challenge.stat1.num": "70%",
    "home.challenge.stat2.desc": "の学生が実践的応用への準備不足を感じている",
    "home.challenge.stat2.num": "65%",
    "home.challenge.stat3.desc": "がシステムレベルの思考への限定的な接触を報告",
    "home.challenge.stat3.num": "45%",
    "home.challenge.stat4.desc": "の雇用主がプロジェクト準備におけるスキルギャップを認識",
    "home.challenge.stat4.num": "80%",
    "home.challenge.stat5.desc": "のプロジェクトがコミュニティや環境への影響指標を統合",
    "home.challenge.stat5.num": "30%",
    "home.challenge.stat6.desc": "のインフラプロジェクトが実践的知識のギャップにより遅延",
    "home.challenge.stat6.num": "90%",
    "home.challenge.subtitle": "インフラ教育は断片的で抽象的であり、現実世界への影響から切り離されている。",
    "home.challenge.title": "私たちが取り組む課題",
    "home.challenge.urgent": "緊急の必要性：未来に対応できるインフラ専門家への橋渡し",
    "home.cover.front": "表紙と裏表紙 — 第一話：地球の基盤",
    "home.cover.interior": "内側見開き — 第一章：火のリレー（第一部＆第二部）",
    "home.cover.portrait": "文明のリレー — 木からトーラスまでの12章",
    "home.ep1.btn": "公開済み",
    "home.ep1.desc": "カロリーから意識へ — 火からトーラスまでの12のリレー",
    "home.ep1.subtitle": "地球の基盤",
    "home.ep1.title": "第一話",
    "home.ep2.btn": "近日公開",
    "home.ep2.desc": "サイバネティクス、AI、そして知的システム",
    "home.ep2.subtitle": "リアリティ・エンジン — 灰色の闘技場",
    "home.ep2.title": "第二話",
    "home.ep3.btn": "近日公開",
    "home.ep3.desc": "惑星、太陽系、そして銀河の管理",
    "home.ep3.subtitle": "管理と更新 — 宇宙のスケール",
    "home.ep3.title": "第三話",
    "home.framework.journey": "旅こそが仕事である。",
    "home.framework.modes.caption": "三つのモード — 12,000年にわたる西洋、東洋、そしてアウトライダー",
    "home.framework.motto": "インフラ教育：暗記ではなく、システム思考",
    "home.framework.relays.caption": "12の文明リレー — 火から意識へ",
    "home.framework.silk.caption": "シルクロードのパラドックス — アウトライダーは交易路を支配したが、インフラを建設しなかった",
    "home.framework.subtitle": "土木技術者の視点を通したインフラ教育のための統合的システム思考",
    "home.framework.title": "完全なフレームワーク",
    "home.game.cta.sub": "第三巻：リアリティ・エンジン — 誘導学習プラットフォーム",
    "home.game.cta.title": "ゲームに参加",
    "home.game.desc": "学んだことを応用する準備はできましたか？リアリティ・エンジンに足を踏み入れましょう — あなたがインフラ技術者になる没入型学習プラットフォームです。",
    "home.game.note": "シミュレーションと実践：動的な環境で概念を応用する",
    "home.game.title": "第三巻：ゲーム",
    "home.hero.caption": "カロリーから意識へ：インフラストラクチャー・オデッセイ — 文明のリレー",
    "home.kw.subtitle": "書記の包括的な歴史 — 会計トークンからデジタル時代まで。究極のインフラリレーとしてのペン。",
    "home.kw.title": "知識のウェブ：インフラとしての言葉",
    "home.media.calories": "カロリーから意識へ",
    "home.media.engine": "リアリティ・エンジン — 誘導学習プラットフォーム",
    "home.media.river": "リバープレーン・フィルム",
    "home.media.title": "メディア",
    "home.media.trailer": "スナップショット・トレーラー",
    "home.ppp.clock.sub": "インフラリテラシーへの人類の競争をリアルタイムで追跡します。挑戦は始まっています。",
    "home.ppp.clock.title": "動員時計を見る",
    "home.s1.desc": "基礎概念 — 三つのモード、元素時計、道路と船舶のタイムライン",
    "home.s1.title": "S1：特定",
    "home.s2.desc": "技術の拡散 — インフラとしてのペン、書記体系",
    "home.s2.title": "S2：理解",
    "home.s3.desc": "実装 — 各リレーの管理図",
    "home.s3.title": "S3：管理と制御",
    "home.s4.desc": "カウンターパート — 各リレーの西洋、アウトライダー、東洋の比較",
    "home.s4.title": "S4：論文とビジョン",
    "home.subtitle": "土木技術者のための視点とガイドブック — 第一話：カロリーから意識へ",
    "home.supplements.btn": "補足資料を見る",
    "home.supplements.title": "第二巻：4つの補足資料",
    "home.title": "インフラストラクチャー・オデッセイ",
    "home.trilogy.title": "三部作のビジョン",
    "home.vol1.btn": "視点を読む",
    "home.vol1.desc": "物語の基盤：12,000年にわたる人類のインフラ開発を描く12の文明リレー。火の習得から意識のトーラスまで。",
    "home.vol1.subtitle": "歴史と背景 — 物語",
    "home.vol1.title": "第一巻：視点",
    "home.vol2.btn": "ガイドブックを読む",
    "home.vol2.desc": "実践的フレームワーク：西洋／東洋／アウトライダーの比較アプローチ、4C分析、そしてインフラを文明のDNAとして理解するための戦略モデル。",
    "home.vol2.subtitle": "戦略的フレームワーク — 展開",
    "home.vol2.title": "第二巻：ガイドブック",
    "inst.coming": "近日公開 — 完全な機関データベースは構築中です",
    "inst.sdg.title": "SDGsによる分類",
    "inst.status.challenged": "挑戦済み",
    "inst.status.engaged": "関与済み",
    "inst.status.notyet": "未接触",
    "inst.status.potential": "潜在的",
    "inst.subtitle": "インテリジェンスマップ — 招集、挑戦、または協力できるすべての機関、大学、国連機関、専門家協会、NGO、技術プロバイダー、および資本機関。世界的な優先事項との整合性を示すために、国連の持続可能な開発目標（SDGs）別に整理されています。",
    "inst.title": "機関",
    "lib.supp_title": "補足ドキュメント",
    "lib.title": "ドキュメントライブラリ",
    "library.subtitle": "完全な知識資産アーカイブ",
    "library.title": "文献ライブラリ",
    "nav.author": "著者",
    "nav.charter": "憲章",
    "nav.civclock": "文明時計",
    "nav.clock": "動員時計",
    "nav.documents": "文献",
    "nav.framework": "フレームワーク",
    "nav.home": "ホーム",
    "nav.institutions": "機関",
    "nav.outriders": "アウトライダー",
    "nav.pioneers": "パイオニアプログラム",
    "nav.precis": "エグゼクティブ・サマリー",
    "nav.resources": "リソース",
    "nav.supplements": "補足資料",
    "nav.taxonomy": "分類体系",
    "nav.ep1": "EP.1：視点",
    "nav.ep2": "EP.2：ガイドブック",
    "nav.ep3": "EP.3：ゲーム",
    "or.conn.book.desc": "各章はアウトライダーの引用で始まり、終わります。彼らの革新はケーススタディです。彼らの失敗は警告です。彼らは議論の証拠基盤です。",
    "or.conn.book.title": "本の中で",
    "or.conn.game.desc": "アウトライダーは、各リレーでNPCガイド、引用元、歴史的背景の提供者として登場します。プレイヤーは12の章を進むにつれて彼らに出会います。",
    "or.conn.game.title": "ゲームの中で",
    "or.conn.movement.desc": "アウトライダーは道徳的権威を提供します。IAAIがユネスコやMITに挑戦するとき、それはこれらの人物が体現する12,000年のインフラの知恵の肩の上に立っています。",
    "or.conn.movement.title": "ムーブメントの中で",
    "or.conn.title": "アウトライダーがミッションにどのように貢献するか",
    "or.era1.title": "古代世界",
    "or.era2.title": "古典世界",
    "or.era3.title": "中世とルネサンス",
    "or.era4.title": "産業革命",
    "or.era5.title": "近代",
    "or.era6.title": "デジタルと未来",
    "or.quote": "\"賢明なる君主と善良なる将軍が、動いて敵に勝ち、その成功が衆に秀でる所以は、先知なり。\" — 孫子、第十三章",
    "or.stat.civilisations": "代表される文明",
    "or.stat.eras": "歴史的時代",
    "or.stat.relays": "カバーされたリレー",
    "or.stat.total": "アウトライダー総数",
    "or.subtitle": "各階層と並行して歩む歴史的な精神的ガイド — 6+1階層には数えられず、これらの知恵のパートナーはすべてのモード、すべてのリレー、すべての12,000年を横断します。彼らはゲームの声であり、壁の引用であり、火とトーラスをつなぐ知恵です。",
    "or.title": "アウトライダー",
    "pioneers.charter.agree": "私はIAAI憲章を読み、同意します。私は誠実な貢献、文化的な尊重、そして言語や国境を越えた知識のオープンな共有を誓います。これがボランティアプログラムであり、私の貢献はCC BY-NC-SA 4.0ライセンスの下でクレジットされることを理解しています。",
    "pioneers.charter.text": "私たちは、インフラが文明のオペレーティングシステムであると信じています。川がゆっくりと、しかし執拗に地球を彫刻して惑星規模の変化を達成するように、私たちはオープンな知識、検証済みの貢献、文化的な尊重、そして私たちが世界をどのように構築するかがより良い世界を構築するための第一歩であるという理解にコミットしています。",
    "pioneers.charter.title": "IAAI憲章",
    "pioneers.form.country": "国",
    "pioneers.form.email": "メールアドレス",
    "pioneers.form.expertise": "専門分野",
    "pioneers.form.language": "主要言語",
    "pioneers.form.motivation": "参加したい理由（任意）",
    "pioneers.form.name": "フルネーム",
    "pioneers.form.other_langs": "その他の言語",
    "pioneers.form.submit": "応募を送信 — 競争に参加",
    "pioneers.form.subtitle": "無料のベータアクセス。費用なし。義務なし。ただ好奇心とコミットメントだけ。",
    "pioneers.form.title": "パイオニアになるための応募",
    "pioneers.subtitle": "最初の貢献者の波が、各大陸でインフラリテラシーをテスト、翻訳、検証し、広めます。無料のベータアクセス。創設者の壁にあなたの場所を確保しましょう。",
    "pioneers.tier1.desc": "最初のテスター。ゲームをプレイし、バグを報告し、コンテンツを検証します。各言語ブロックに2〜3人。インテリジェンスネットワークの偵察兵。",
    "pioneers.tier1.req": "要件：好奇心、任意の言語、テストへの意欲",
    "pioneers.tier1.title": "パイオニア",
    "pioneers.tier2.desc": "言語リーダー。AI翻訳をレビューし、母語の用法に合わせて修正します。クレジット付きの貢献者になります。各言語ブロックに10人。",
    "pioneers.tier2.req": "要件：母語の流暢さ＋パイオニア経験",
    "pioneers.tier2.title": "アンバサダー",
    "pioneers.tier3.desc": "学術バリデーター。技術者、教授、研究者が技術的な正確性を検証し、コンテンツをカリキュラムにマッピングします。",
    "pioneers.tier3.req": "要件：学術資格＋専門分野",
    "pioneers.tier3.title": "スカラー",
    "pioneers.tier4.desc": "戦略的指導。業界のリーダー、政策立案者、機関とのコネクターが、扉を開き、方向性を形作ります。",
    "pioneers.tier4.req": "要件：招待または指名",
    "pioneers.tier4.title": "アドバイザー",
    "pioneers.title": "パイオニアプログラム",
    "precis.relay.epilogue": "エピローグ",
    "precis.relay.prologue": "プロローグ",
    "precis.relay.relay_10_aaa": "リレー10：AAAトライアド",
    "precis.relay.relay_10_autoair": "リレー10：自動車／航空",
    "precis.relay.relay_11_humans": "リレー11：ヒューマンノード",
    "precis.relay.relay_11_orbit": "リレー11：軌道",
    "precis.relay.relay_12_programmable": "リレー12：プログラマブル",
    "precis.relay.relay_12_torus": "リレー12：トーラス",
    "precis.relay.relay_1_fire": "リレー1：火",
    "precis.relay.relay_2_tree": "リレー2：木",
    "precis.relay.relay_3_river": "リレー3：川",
    "precis.relay.relay_4_horse": "リレー4：馬",
    "precis.relay.relay_5_road": "リレー5：道路",
    "precis.relay.relay_6_ship": "リレー6：船",
    "precis.relay.relay_7_rail": "リレー7：鉄道",
    "precis.relay.relay_8_loom": "リレー8：織機",
    "precis.relay.relay_9_engine": "リレー9：エンジン",
    "precis.relay.torus": "トーラス",
    "precis.subtitle": "インフラストラクチャー・オデッセイ — 戦略的概要",
    "precis.title": "エグゼクティブ・サマリー",
    "relay.1.name": "リレー1：火",
    "relay.1.subtitle": "原初の火花 — エネルギー掌握の始まり",
    "relay.10.name": "リレー10：AAAトライアド",
    "relay.10.subtitle": "航空、原子、自動化 — 現代の三位一体",
    "relay.11.name": "リレー11：ヒューマンノード",
    "relay.11.subtitle": "ネットワーク化された人類 — デジタル接続",
    "relay.12.name": "リレー12：意識",
    "relay.12.subtitle": "トーラス — インフラの究極形態",
    "relay.2.name": "リレー2：木",
    "relay.2.subtitle": "生きた建築 — 工学としての自然",
    "relay.3.name": "リレー3：川",
    "relay.3.subtitle": "水力文明 — 液体のインフラ",
    "relay.4.name": "リレー4：馬",
    "relay.4.subtitle": "移動革命 — 速度と帝国",
    "relay.5.name": "リレー5：道路",
    "relay.5.subtitle": "接続のネットワーク — 帝国の動脈",
    "relay.6.name": "リレー6：船",
    "relay.6.subtitle": "海洋のハイウェイ — グローバル貿易ネットワーク",
    "relay.7.name": "リレー7：鉄道",
    "relay.7.subtitle": "鋼鉄の背骨 — 産業の接続",
    "relay.8.name": "リレー8：織機",
    "relay.8.subtitle": "織りなすウェブ — 情報インフラ",
    "relay.9.name": "リレー9：エンジン",
    "relay.9.subtitle": "動力革命 — 機械化された世界",
    "relay.epilogue": "エピローグ",
    "relay.prologue": "プロローグ",
    "resources.subtitle": "参考文献、データソース、さらなる読書",
    "resources.title": "リソース",
    "section.4c_analysis": "4C分析",
    "section.active_webs": "アクティブなウェブ",
    "section.back_to_index": "目次に戻る",
    "section.challenge": "課題",
    "section.communication_web": "コミュニケーションウェブ",
    "section.comparative_analysis": "比較分析",
    "section.consciousness_web": "意識のウェブ",
    "section.consequence": "結果",
    "section.context": "背景",
    "section.continuity": "連続性",
    "section.continuum": "連続体",
    "section.counterparts_title": "カウンターパート",
    "section.digital_web": "デジタルネットワーク",
    "section.documents": "文献",
    "section.east_mode": "東洋モデル",
    "section.energy_web": "エネルギーネットワーク",
    "section.four_pillars": "四本柱",
    "section.gallery": "ギャラリー",
    "section.governance_web": "ガバナンスネットワーク",
    "section.historical_significance": "歴史的重要性",
    "section.home.title": "ホーム",
    "section.impact": "インパクト：",
    "section.information_web": "情報ネットワーク",
    "section.infrastructure": "インフラストラクチャ",
    "section.infrastructure_web": "インフラウェブ",
    "section.introduction": "はじめに",
    "section.key_insights": "重要な洞察",
    "section.knowledge_web": "知識のウェブ",
    "section.legacy": "レガシー：",
    "section.management_diagram": "管理図",
    "section.military_web": "軍事ネットワーク",
    "section.next_relay": "次のリレー",
    "section.observation": "観察",
    "section.outrider_mode": "先駆者モード",
    "section.power_web": "パワーウェブ",
    "section.previous_relay": "前のリレー",
    "section.production_web": "生産ネットワーク",
    "section.reading": "読書",
    "section.strategic_framework": "戦略フレームワーク",
    "section.summary": "概要",
    "section.supplements": "補足資料",
    "section.technical_specs": "技術仕様",
    "section.the_counterparts": "対応者：",
    "section.the_first_infrastructure": "最初のインフラストラクチャ",
    "section.threats": "脅威",
    "section.timeline": "タイムライン",
    "section.title": "タイトル",
    "section.trade_web": "貿易ウェブ",
    "section.transport_web": "交通ウェブ",
    "section.unification": "統合",
    "section.video": "ビデオ",
    "section.west_mode": "西洋モデル",
    "section.world_tree": "世界樹",
    "special.conclusion": "結論",
    "special.epilogue": "エピローグ",
    "special.from_calories_to_consciousness": "カロリーから意識へ",
    "special.prologue": "序章",
    "special.the_beginning": "始まり",
    "special.the_journey_begins": "旅の始まり",
    "special.the_journey_continues": "旅の継続",
    "supplements.s1": "補足1：特定",
    "supplements.s2": "補足2：理解",
    "supplements.s3": "補足3：管理と制御",
    "supplements.s4": "補足4：論文とビジョン",
    "supplements.subtitle": "第二巻の詳細な拡張資料",
    "supplements.title": "補足資料",
    "tax.advisors": "アドバイザー",
    "tax.advisors.desc": "戦略的指導。業界のリーダーと機関のコネクター。",
    "tax.ambassadors": "アンバサダー",
    "tax.ambassadors.desc": "言語リーダー。各言語ブロックに10人。",
    "tax.backers": "バッカー",
    "tax.backers.desc": "資金と機関の支援。パトロンとパートナー。",
    "tax.biology": "生物学の類推",
    "tax.count": "数",
    "tax.founder": "創設者",
    "tax.founder.desc": "建築家。1人。システム全体を設計しました。",
    "tax.iaai": "IAAIランク",
    "tax.outriders.note": "アウトライダー（歴史的な精神的ガイド）は6+1階層には数えられません — 彼らはすべてのモード、すべてのリレー、すべての12,000年を並行して歩みます。",
    "tax.pioneers": "パイオニア",
    "tax.pioneers.desc": "最初のテスター。各言語ブロックに2〜3人。",
    "tax.players": "プレイヤー",
    "tax.players.desc": "ゲーム参加者。目標：10億人の学習者。",
    "tax.role": "役割",
    "tax.scholars": "スカラー",
    "tax.scholars.desc": "学術バリデーター。教授、技術者、研究者。",
    "tax.subtitle": "6+1階層構造 — 生物学の分類が界から種へと進むように、IAAIの貢献者階層は創設者からバッカーまで、各層がより広く、より専門的になります。",
    "tax.title": "IAAI分類体系",
    "toc.chapter": "第",
    "toc.chapter.suffix": "章",
    "toc.epilogue": "エピローグ",
    "toc.prologue": "プロローグ",
    "toc.title": "目次",
    "toc.volume1": "第一巻：視点 — 歴史と背景",
    "toc.volume2": "第二巻：ガイドブック — 戦略的フレームワーク",
    "toc.volume3": "第三巻：ゲーム — シミュレーションと実践",
    "ui.available": "公開済み",
    "ui.back": "戻る",
    "ui.coming.soon": "近日公開",
    "ui.download": "ダウンロード",
    "ui.error": "コンテンツの読み込み中にエラーが発生しました。もう一度お試しください。",
    "ui.loading": "読み込み中...",
    "ui.next": "次へ",
    "ui.prev": "前へ",
    "ui.read.more": "続きを読む",
    "ui.view": "表示",
    "v1.index.about_title": "この巻について",
    "v1.index.relays_title": "十二のリレー",
    "v1.index.title": "第一巻：視点",
    "v1.r01.active_webs": "アクティブネットワーク",
    "v1.r01.counterparts_title": "対応者：火",
    "v1.r01.four_pillars": "4つの柱",
    "v1.r01.historical_significance": "歴史的重要性",
    "v1.r01.next_relay": "次へ →",
    "v1.r01.previous_relay": "← 前へ",
    "v1.r01.subtitle": "原始の火花 — エネルギー掌握の始まり",
    "v1.r01.title": "リレー1：火",
    "v1.r02.active_webs": "アクティブネットワーク",
    "v1.r02.counterparts_title": "対応者：樹木",
    "v1.r02.four_pillars": "4つの柱",
    "v1.r02.historical_significance": "歴史的重要性",
    "v1.r02.next_relay": "次へ →",
    "v1.r02.previous_relay": "← 前へ",
    "v1.r02.subtitle": "生きた建築 — 自然の工学",
    "v1.r02.title": "リレー2：樹木",
    "v1.r03.active_webs": "アクティブネットワーク",
    "v1.r03.counterparts_title": "対応者：河川",
    "v1.r03.four_pillars": "4つの柱",
    "v1.r03.historical_significance": "歴史的重要性",
    "v1.r03.next_relay": "次へ →",
    "v1.r03.previous_relay": "← 前へ",
    "v1.r03.subtitle": "水利文明 — 流体インフラ",
    "v1.r03.title": "リレー3：河川",
    "v1.r04.active_webs": "アクティブネットワーク",
    "v1.r04.counterparts_title": "対応者：馬",
    "v1.r04.four_pillars": "4つの柱",
    "v1.r04.historical_significance": "歴史的重要性",
    "v1.r04.next_relay": "次へ →",
    "v1.r04.previous_relay": "← 前へ",
    "v1.r04.subtitle": "移動革命 — 速度と帝国",
    "v1.r04.title": "リレー4：馬",
    "v1.r05.active_webs": "アクティブネットワーク",
    "v1.r05.counterparts_title": "対応者：道路",
    "v1.r05.four_pillars": "4つの柱",
    "v1.r05.historical_significance": "歴史的重要性",
    "v1.r05.next_relay": "次へ →",
    "v1.r05.previous_relay": "← 前へ",
    "v1.r05.subtitle": "接続されたネットワーク — 帝国の動脈",
    "v1.r05.title": "リレー5：道路",
    "v1.r06.active_webs": "アクティブネットワーク",
    "v1.r06.counterparts_title": "対応者：船舶",
    "v1.r06.four_pillars": "4つの柱",
    "v1.r06.historical_significance": "歴史的重要性",
    "v1.r06.next_relay": "次へ →",
    "v1.r06.previous_relay": "← 前へ",
    "v1.r06.subtitle": "海の高速道路 — グローバル貿易ネットワーク",
    "v1.r06.title": "リレー6：船舶",
    "v1.r07.active_webs": "アクティブネットワーク",
    "v1.r07.counterparts_title": "対応者：鉄道",
    "v1.r07.four_pillars": "4つの柱",
    "v1.r07.historical_significance": "歴史的重要性",
    "v1.r07.next_relay": "次へ →",
    "v1.r07.previous_relay": "← 前へ",
    "v1.r07.subtitle": "鉄の背骨 — 工業の連結",
    "v1.r07.title": "リレー7：鉄道",
    "v1.r08.active_webs": "アクティブネットワーク",
    "v1.r08.counterparts_title": "対応者：織機",
    "v1.r08.four_pillars": "4つの柱",
    "v1.r08.historical_significance": "歴史的重要性",
    "v1.r08.next_relay": "次へ →",
    "v1.r08.previous_relay": "← 前へ",
    "v1.r08.subtitle": "織りなすネットワーク — 情報インフラ",
    "v1.r08.title": "リレー8：織機",
    "v1.r09.active_webs": "アクティブネットワーク",
    "v1.r09.counterparts_title": "対応者：エンジン",
    "v1.r09.four_pillars": "4つの柱",
    "v1.r09.historical_significance": "歴史的重要性",
    "v1.r09.next_relay": "次へ →",
    "v1.r09.previous_relay": "← 前へ",
    "v1.r09.subtitle": "動力革命 — 機械化された世界",
    "v1.r09.title": "リレー9：エンジン",
    "v1.r10.active_webs": "アクティブネットワーク",
    "v1.r10.counterparts_title": "対応者：AAAトリニティ",
    "v1.r10.four_pillars": "4つの柱",
    "v1.r10.historical_significance": "歴史的重要性",
    "v1.r10.next_relay": "次へ →",
    "v1.r10.previous_relay": "← 前へ",
    "v1.r10.subtitle": "航空、原子力、自動化 — 現代の三位一体",
    "v1.r10.title": "リレー10：AAAトリニティ",
    "v1.r11.active_webs": "アクティブネットワーク",
    "v1.r11.counterparts_title": "対応者：人間ノード",
    "v1.r11.four_pillars": "4つの柱",
    "v1.r11.historical_significance": "歴史的重要性",
    "v1.r11.next_relay": "次へ →",
    "v1.r11.previous_relay": "← 前へ",
    "v1.r11.subtitle": "ネットワーク化された人類 — デジタル接続",
    "v1.r11.title": "リレー11：人間ノード",
    "v1.r12.active_webs": "アクティブネットワーク",
    "v1.r12.counterparts_title": "対応者：意識",
    "v1.r12.four_pillars": "4つの柱",
    "v1.r12.historical_significance": "歴史的重要性",
    "v1.r12.next_relay": "次へ →",
    "v1.r12.previous_relay": "← 前へ",
    "v1.r12.subtitle": "トーラス — インフラの究極形態",
    "v1.r12.title": "リレー12：意識",
    "v2.index.about_text": "第二巻：ガイドブックは、四本柱のフレームワーク（観察 → 教育 → 応用 → 論文）を十二の文明リレーのそれぞれに適用します。この巻は、インフラシステムがどのように機能し、どのように分析し、現代の課題にどのように適用できるかを理解するための実用的なガイダンスを提供します。",
    "v2.index.about_title": "この巻について",
    "v2.index.app": "応用",
    "v2.index.app_text": "これらの教訓をどのように応用できますか？このリレーからどのような実用的なフレームワークとツールが生まれますか？",
    "v2.index.edu": "教育",
    "v2.index.edu_text": "このリレーから何を学ぶことができますか？インフラに関するどのような原則と教訓を教えてくれますか？",
    "v2.index.framework_title": "四本柱のフレームワーク",
    "v2.index.obs": "観察",
    "v2.index.obs_text": "このリレーについて何を観察しますか？その特徴、構成要素、パターンは何ですか？",
    "v2.index.relays_caption": "十二の文明リレー — 火から意識へ",
    "v2.index.subtitle": "ガイドブック — 実用的なフレームワークと拡張分析",
    "v2.index.thesis": "論文",
    "v2.index.thesis_text": "全体的な論文は何ですか？このリレーが明らかにする根本的な洞察は何ですか？",
    "v2.index.title": "第二巻：ガイドブック",
    "v2.r01.active_webs": "アクティブネットワーク",
    "v2.r01.counterparts_title": "対応者：火",
    "v2.r01.four_pillars": "4つの柱",
    "v2.r01.historical_significance": "歴史的重要性",
    "v2.r01.next_relay": "次へ →",
    "v2.r01.previous_relay": "← 前へ",
    "v2.r01.subtitle": "原始の火花 — エネルギー掌握の始まり",
    "v2.r01.title": "リレー1：火",
    "v2.r02.active_webs": "アクティブネットワーク",
    "v2.r02.counterparts_title": "対応者：樹木",
    "v2.r02.four_pillars": "4つの柱",
    "v2.r02.historical_significance": "歴史的重要性",
    "v2.r02.next_relay": "次へ →",
    "v2.r02.previous_relay": "← 前へ",
    "v2.r02.subtitle": "生きた建築 — 自然の工学",
    "v2.r02.title": "リレー2：樹木",
    "v2.r03.active_webs": "アクティブネットワーク",
    "v2.r03.counterparts_title": "対応者：河川",
    "v2.r03.four_pillars": "4つの柱",
    "v2.r03.historical_significance": "歴史的重要性",
    "v2.r03.next_relay": "次へ →",
    "v2.r03.previous_relay": "← 前へ",
    "v2.r03.subtitle": "水利文明 — 流体インフラ",
    "v2.r03.title": "リレー3：河川",
    "v2.r04.active_webs": "アクティブネットワーク",
    "v2.r04.counterparts_title": "対応者：馬",
    "v2.r04.four_pillars": "4つの柱",
    "v2.r04.historical_significance": "歴史的重要性",
    "v2.r04.next_relay": "次へ →",
    "v2.r04.previous_relay": "← 前へ",
    "v2.r04.subtitle": "移動革命 — 速度と帝国",
    "v2.r04.title": "リレー4：馬",
    "v2.r05.active_webs": "アクティブネットワーク",
    "v2.r05.counterparts_title": "対応者：道路",
    "v2.r05.four_pillars": "4つの柱",
    "v2.r05.historical_significance": "歴史的重要性",
    "v2.r05.next_relay": "次へ →",
    "v2.r05.previous_relay": "← 前へ",
    "v2.r05.subtitle": "接続されたネットワーク — 帝国の動脈",
    "v2.r05.title": "リレー5：道路",
    "v2.r06.active_webs": "アクティブネットワーク",
    "v2.r06.counterparts_title": "対応者：船舶",
    "v2.r06.four_pillars": "4つの柱",
    "v2.r06.historical_significance": "歴史的重要性",
    "v2.r06.next_relay": "次へ →",
    "v2.r06.previous_relay": "← 前へ",
    "v2.r06.subtitle": "海の高速道路 — グローバル貿易ネットワーク",
    "v2.r06.title": "リレー6：船舶",
    "v2.r07.active_webs": "アクティブネットワーク",
    "v2.r07.counterparts_title": "対応者：鉄道",
    "v2.r07.four_pillars": "4つの柱",
    "v2.r07.historical_significance": "歴史的重要性",
    "v2.r07.next_relay": "次へ →",
    "v2.r07.previous_relay": "← 前へ",
    "v2.r07.subtitle": "鉄の背骨 — 工業の連結",
    "v2.r07.title": "リレー7：鉄道",
    "v2.r08.active_webs": "アクティブネットワーク",
    "v2.r08.counterparts_title": "対応者：織機",
    "v2.r08.four_pillars": "4つの柱",
    "v2.r08.historical_significance": "歴史的重要性",
    "v2.r08.next_relay": "次へ →",
    "v2.r08.previous_relay": "← 前へ",
    "v2.r08.subtitle": "織りなすネットワーク — 情報インフラ",
    "v2.r08.title": "リレー8：織機",
    "v2.r09.active_webs": "アクティブネットワーク",
    "v2.r09.counterparts_title": "対応者：エンジン",
    "v2.r09.four_pillars": "4つの柱",
    "v2.r09.historical_significance": "歴史的重要性",
    "v2.r09.next_relay": "次へ →",
    "v2.r09.previous_relay": "← 前へ",
    "v2.r09.subtitle": "動力革命 — 機械化された世界",
    "v2.r09.title": "リレー9：エンジン",
    "v2.r10.active_webs": "アクティブネットワーク",
    "v2.r10.counterparts_title": "対応者：AAAトリニティ",
    "v2.r10.four_pillars": "4つの柱",
    "v2.r10.historical_significance": "歴史的重要性",
    "v2.r10.next_relay": "次へ →",
    "v2.r10.previous_relay": "← 前へ",
    "v2.r10.subtitle": "航空、原子力、自動化 — 現代の三位一体",
    "v2.r10.title": "リレー10：AAAトリニティ",
    "v2.r11.active_webs": "アクティブネットワーク",
    "v2.r11.counterparts_title": "対応者：人間ノード",
    "v2.r11.four_pillars": "4つの柱",
    "v2.r11.historical_significance": "歴史的重要性",
    "v2.r11.next_relay": "次へ →",
    "v2.r11.previous_relay": "← 前へ",
    "v2.r11.subtitle": "ネットワーク化された人類 — デジタル接続",
    "v2.r11.title": "リレー11：人間ノード",
    "v2.r12.active_webs": "アクティブネットワーク",
    "v2.r12.counterparts_title": "対応者：意識",
    "v2.r12.four_pillars": "4つの柱",
    "v2.r12.historical_significance": "歴史的重要性",
    "v2.r12.next_relay": "次へ →",
    "v2.r12.previous_relay": "← 前へ",
    "v2.r12.subtitle": "トーラス — インフラの究極形態",
    "v2.r12.title": "リレー12：意識",
    "v3.index.experience_title": "リレー体験",
    "v3.index.title": "第三巻：ゲーム",
    "vol1.index.desc": "12の文明リレーを通じて12,000年にわたるインフラ開発を探求します。各リレーは人類の能力における根本的な飛躍を表しています。",
    "vol1.index.subtitle": "歴史と背景 — 物語",
    "vol1.index.title": "第一巻：視点",
    "vol2.index.desc": "各リレーの実践的なフレームワーク、比較分析、戦略モデル。西洋、東洋、アウトライダーのアプローチの詳細な比較。",
    "vol2.index.subtitle": "戦略的フレームワーク — 展開",
    "vol2.index.title": "第二巻：ガイドブック",
    "vol3.index.desc": "リアリティ・エンジン誘導学習プラットフォーム。動的なシミュレーション環境で概念を応用します。",
    "vol3.index.subtitle": "シミュレーションと実践 — 応用",
    "vol3.index.title": "第三巻：ゲーム",
    "home.charter.charter.h": "憲章",
    "home.charter.charter.p": "私たちはインフラが文明のオペレーティングシステムであると信じています。川がゆっくりと粘り強く大地を削り、惑星規模の変化をもたらすように、私たちはオープンな知識、検証された貢献、文化的尊重、そして世界をどのように建設したかを理解することがより良い世界を建設する第一歩であるという信念に尽力します。",
    "home.charter.mission.h": "ミッション",
    "home.charter.mission.p": "世界初のオープンで多言語対応のAIガイド付きインフラ教育プラットフォームを提供します — 8言語で10億人の学習者に届け、すべての大陸からの人間の貢献者によって検証されます。",
    "home.charter.title": "ミッション、ビジョン & 憲章",
    "home.charter.vision.h": "ビジョン",
    "home.charter.vision.p": "すべての人が文明を支えるインフラを理解し — 次に何を建設すべきかの知識を持つ世界。",
    "home.pop.answer": "IAAIはその数字を変えるために存在します。",
    "home.pop.question": "人がこの惑星のインフラを共有しています。何人がそれを理解しているでしょうか？",
    "home.pop.source": "出典：国連世界人口推計（リアルタイム予測）",
    "home.ppp.cta.sub": "無料ベータアクセス — テスト、翻訳、検証し、創設者の壁であなたの場所を獲得してください。オデッセイに参加しましょう。",
    "home.ppp.cta.title": "パイオニアになる",
    "home.ppp.partners.h": "パートナー",
    "home.ppp.partners.p": "大学、テクノロジープラットフォーム、インフラ企業。MIT OCW、カーンアカデミー、Meta/VR、Manus/AI、AECOM、Arup、Bechtel。技術、コンテンツ検証、市場アクセス。",
    "home.ppp.partners.status": "ステータス：チャレンジ受付中 — プレイヤーが指名",
    "home.ppp.patrons.h": "パトロン",
    "home.ppp.patrons.p": "普遍的なインフラ教育とミッションが一致する機関。UNESCO、ナショナルジオグラフィック、NASA、王立協会、ディスカバリー、スミソニアン、NOAA、世界銀行、ADB、中国科学院。",
    "home.ppp.patrons.status": "ステータス：チャレンジ受付中 — プレイヤーが指名",
    "home.ppp.players.h": "プレイヤー",
    "home.ppp.players.p": "すべての国からのパイオニア、アンバサダー、スカラー、アドバイザー。テスト、翻訳、検証、貢献、そして言葉を広める実在の人々。民主主義の力。",
    "home.ppp.players.status": "ステータス：パイオニア募集中 — 無料ベータアクセス",
    "home.ppp.reach.active": "アクティブ",
    "home.ppp.reach.active2": "アクティブ",
    "home.ppp.reach.active3": "アクティブ",
    "home.ppp.reach.active4": "アクティブ",
    "home.ppp.reach.active5": "アクティブ",
    "home.ppp.reach.active6": "アクティブ",
    "home.ppp.reach.active7": "アクティブ",
    "home.ppp.reach.active8": "アクティブ",
    "home.ppp.reach.ar": "アラビア語",
    "home.ppp.reach.cn": "中国語",
    "home.ppp.reach.coverage": "8言語で世界のゲーム市場の約85%、EdTech支出の約80%、そしてトップのインフラ投資回廊をカバーしています。",
    "home.ppp.reach.en": "英語",
    "home.ppp.reach.es": "スペイン語",
    "home.ppp.reach.h": "グローバル言語リーチ",
    "home.ppp.reach.hi": "ヒンディー語",
    "home.ppp.reach.ja": "日本語",
    "home.ppp.reach.ko": "韓国語",
    "home.ppp.reach.vi": "ベトナム語",
    "home.ppp.subtitle": "カロリーから意識へ — 止めることも制御することもできない個人レベルの行動喚起。ただ学び続けるだけです。",
    "home.ppp.title": "パトロン、パートナー & プレイヤー",
    "nav.founders": "創設者の壁",
    // ============================================
    // MISSING KEYS - ADDED BY TRANSLATION GENERATOR
    // ============================================
    "home.guide.btn": "ガイドを読む",
    "home.guide.title": "第2巻：ガイド",
    "masters.subtitle": "すべての階層に寄り添う歴史的精神ガイド — 6+1の階層には含まれず、すべてのモード、すべてのリレー、12,000年にわたる知的な仲間です。ゲーム中の声、壁の引用、火からトーラスへとつなぐ知恵です。",
    "masters.title": "マスター",
    "nav.glossary": "用語集",
    "nav.masters": "マスター",
    "nav.olympiad": "オリンピアード",
    "nav.starthere": "ここから始める",
    "precis.relay.relay_10_orbit": "リレー11：軌道",
    "precis.relay.relay_11_human_nodes": "リレー12：ヒューマンノード",
    "precis.relay.relay_1_tree": "リレー2：樹",
    "precis.relay.relay_2_river": "リレー3：川",
    "precis.relay.relay_3_horse": "リレー4：馬",
    "precis.relay.relay_4_roads": "リレー5：道路",
    "precis.relay.relay_5_ships": "リレー6：船",
    "precis.relay.relay_6_loom": "リレー7：織機",
    "precis.relay.relay_8_engine": "リレー9：エンジン",
    "precis.relay.relay_9_aaa": "リレー10：AAAトライアド",
    "tax.cta": "ツリーの中であなたの場所を見つけよう",
    "tax.cta.sub": "すべての種は一つの生物から始まる。すべての運動は一人の先駆者から始まる。",
    "tax.footer.cc": "CC BY-NC-SA 4.0",
    "tax.parallel.institutions.desc": "Organisations that can be challenged, engaged, or partnered with. Universities, UN bodies, professional societies, government agencies, NGOs, and corporations. They sit outside the contributor hierarchy but are the targets of the intelligence network and the Challenge Board.",
    "tax.parallel.institutions.title": "&#x1F3DB; Institutions &mdash; The Challenge Map",
    "tax.parallel.institutions.who": "UNESCO &bull; World Bank &bull; ASCE &bull; ICE &bull; MIT &bull; Khan Academy &bull; Meta &bull; National Geographic",
    "tax.parallel.outriders.desc": "Historical and philosophical figures who ride alongside every tier as intellectual companions. Not counted in the 6+1 &mdash; they exist across all levels, all modes, all time periods. They are the voices in the game, the quotes on the walls, the wisdom that connects 12,000 years of infrastructure.",
    "tax.parallel.outriders.title": "&#x1F3C7; Outriders &mdash; Spirit Guides",
    "tax.parallel.outriders.who": "Laozi &bull; Sun Tzu &bull; Confucius &bull; Vitruvius &bull; Leonardo da Vinci &bull; Isambard Kingdom Brunel &bull; Nikola Tesla &bull; Ada Lovelace",
    "tax.parallel.title": "パラレルトラック（階層外）",
    "tax.plus1.desc": "生物学では、種は最も具体的な分類——個体そのものです。IAAIでは、+1は10億人の学習者です",
    "tax.plus1.subtitle": "人類の12.1% — インフラリテラシーの転換点",
    "tax.plus1.target": "目標：1,000,000,000",
    "tax.plus1.title": "+1 — 種",
    "tax.quote": "\"すべての生命が共通の祖先を持つように、すべてのインフラは共通の目的を持つ——文明に奉仕すること。\"",
    "tax.rank.class": "綱",
    "tax.rank.domain": "ドメイン",
    "tax.rank.family": "科",
    "tax.rank.genus": "属",
    "tax.rank.kingdom": "界",
    "tax.rank.order": "目",
    "tax.rank.phylum": "門",
    "tax.table.biology": "生物学",
    "tax.table.count": "数",
    "tax.table.iaai": "IAAI",
    "tax.table.suntzu": "インテリジェンス (INT)",
    "tax.tier1.analogy": "Biology: Domain (Eukarya) &bull; Military: Commander-in-Chief &bull; Architecture: Master Builder",
    "tax.tier1.desc": "The singular origin point. Conceived the 12-relay framework, wrote the trilogy, designed the game, and built the platform. Like Domain in biology &mdash; the broadest, most fundamental classification from which everything else branches.",
    "tax.tier1.name": "創設者",
    "tax.tier1.title": "アーキテクト",
    "tax.tier1.who": "Ir. Nigel T. Dearden &mdash; CEng MICE MHKIE",
    "tax.tier2.analogy": "Biology: Kingdom (Animalia) &bull; Military: General Staff &bull; Sun Tzu: The Five Essentials",
    "tax.tier2.desc": "The inner circle. Industry leaders, capital strategists, and institutional connectors who shape direction, open doors, and bridge the gap between vision and execution. By invitation or nomination only.",
    "tax.tier2.name": "アドバイザー",
    "tax.tier2.title": "戦略評議会",
    "tax.tier2.who": "Michael Wu (COO) &bull; Henry Leong (CFO) &bull; Frank Sheu (CTO) &bull; Stephen Markscheid (Strategic Advisor)",
    "tax.tier3.analogy": "Biology: Phylum (Chordata) &bull; Military: Intelligence Corps &bull; Academia: Peer Review Board",
    "tax.tier3.desc": "Engineers, professors, and researchers who verify technical accuracy, map content to university curricula, and provide the academic credibility that transforms a game into an educational standard. The peer-review layer.",
    "tax.tier3.name": "スカラー",
    "tax.tier3.title": "学術検証者",
    "tax.tier3.who": "Target: Engineering faculties, infrastructure researchers, curriculum designers",
    "tax.tier4.analogy": "Biology: Class (Mammalia) &bull; Military: Field Officers &bull; Diplomacy: Cultural Attach&eacute;s",
    "tax.tier4.desc": "Native-fluency contributors who review and correct AI translations against real usage. 10 per language block across 8 languages. They ensure infrastructure literacy speaks authentically in every tongue. Credited contributors with their names on the work.",
    "tax.tier4.name": "アンバサダー",
    "tax.tier4.title": "言語リーダー",
    "tax.tier4.who": "Target: 10 per block &times; 8 blocks = 80 Ambassadors worldwide",
    "tax.tier5.analogy": "Biology: Order (Primates) &bull; Military: HUMINT (Human Intelligence) &bull; Scouts &amp; Reconnaissance",
    "tax.tier5.desc": "The first wave. 2&ndash;3 per language block who play the game, report bugs, validate content, and provide the ground-truth feedback that shapes the platform before public release. The HUMINT assets of the intelligence network — human intelligence on the ground.",
    "tax.tier5.name": "パイオニア",
    "tax.tier5.title": "ベータテスター＆スカウト",
    "tax.tier5.who": "Currently recruiting &mdash; 3 active across EN and CN blocks",
    "tax.tier6.analogy": "Biology: Family (Hominidae) &bull; Military: The Rank and File &bull; Gaming: The Player Base",
    "tax.tier6.desc": "Everyone who plays The Reality Engine. From casual explorers to completionists who master all 12 relays across all 4 modes. They generate the data, the engagement, and the democratic nominations that power the Challenge Board. The lifeblood of the platform.",
    "tax.tier6.name": "プレイヤー",
    "tax.tier6.title": "ゲームコミュニティ",
    "tax.tier6.who": "Target: 1M players by Year 2 &bull; Currently: 21 (beta)",
    "tax.tier7.analogy": "Biology: Genus (Homo) &bull; Military: ELINT (Electronic Intelligence) &bull; Logistics &amp; Supply",
    "tax.tier7.desc": "Those who fund the mission &mdash; from individual Kickstarter backers to institutional patrons (UNESCO, National Geographic, universities). They don't play or translate; they enable. Challenged by Players, engaged by Advisors. The ELINT channel of the intelligence network — converting institutional signals into engagement.",
    "tax.tier7.name": "バッカー",
    "tax.tier7.title": "財務・機関サポーター",
    "tax.tier7.who": "Target: $500K seed &bull; Challenged: UNESCO, NatGeo, NASA, Royal Society, MIT OCW, Khan Academy",
    "v1.r01.continuity": "継続性",
    "v1.r01.energy_web": "エネルギーウェブ",
    "v1.r01.infrastructure": "インフラストラクチャー",
    "v1.r01.knowledge_web": "知識ウェブ",
    "v1.r01.threats": "脅威",
    "v1.r01.unification": "統一",
    "v1.r02.continuity": "継続性",
    "v1.r02.energy_web": "エネルギーウェブ",
    "v1.r02.infrastructure": "インフラストラクチャー",
    "v1.r02.knowledge_web": "知識ウェブ",
    "v1.r02.threats": "脅威",
    "v1.r02.unification": "統一",
    "v1.r03.continuity": "継続性",
    "v1.r03.energy_web": "エネルギーウェブ",
    "v1.r03.infrastructure": "インフラストラクチャー",
    "v1.r03.knowledge_web": "知識ウェブ",
    "v1.r03.threats": "脅威",
    "v1.r03.unification": "統一",
    "v1.r04.continuity": "継続性",
    "v1.r04.energy_web": "エネルギーウェブ",
    "v1.r04.infrastructure": "インフラストラクチャー",
    "v1.r04.threats": "脅威",
    "v1.r04.unification": "統一",
    "v1.r05.consciousness_web": "意識ウェブ",
    "v1.r05.continuity": "継続性",
    "v1.r05.infrastructure": "インフラストラクチャー",
    "v1.r05.knowledge_web": "知識ウェブ",
    "v1.r05.threats": "脅威",
    "v1.r05.unification": "統一",
    "v1.r06.consciousness_web": "意識ウェブ",
    "v1.r06.continuity": "継続性",
    "v1.r06.infrastructure": "インフラストラクチャー",
    "v1.r06.knowledge_web": "知識ウェブ",
    "v1.r06.threats": "脅威",
    "v1.r06.unification": "統一",
    "v1.r07.continuity": "継続性",
    "v1.r07.energy_web": "エネルギーウェブ",
    "v1.r07.infrastructure": "インフラストラクチャー",
    "v1.r07.knowledge_web": "知識ウェブ",
    "v1.r07.threats": "脅威",
    "v1.r07.unification": "統一",
    "v1.r08.consciousness_web": "意識ウェブ",
    "v1.r08.continuity": "継続性",
    "v1.r08.energy_web": "エネルギーウェブ",
    "v1.r08.infrastructure": "インフラストラクチャー",
    "v1.r08.knowledge_web": "知識ウェブ",
    "v1.r08.threats": "脅威",
    "v1.r08.unification": "統一",
    "v1.r09.continuity": "継続性",
    "v1.r09.energy_web": "エネルギーウェブ",
    "v1.r09.infrastructure": "インフラストラクチャー",
    "v1.r09.knowledge_web": "知識ウェブ",
    "v1.r09.threats": "脅威",
    "v1.r09.unification": "統一",
    "v1.r10.consciousness_web": "意識ウェブ",
    "v1.r10.continuity": "継続性",
    "v1.r10.energy_web": "エネルギーウェブ",
    "v1.r10.infrastructure": "インフラストラクチャー",
    "v1.r10.knowledge_web": "知識ウェブ",
    "v1.r10.threats": "脅威",
    "v1.r10.unification": "統一",
    "v1.r11.consciousness_web": "意識ウェブ",
    "v1.r11.continuity": "継続性",
    "v1.r11.infrastructure": "インフラストラクチャー",
    "v1.r11.knowledge_web": "知識ウェブ",
    "v1.r11.threats": "脅威",
    "v1.r11.unification": "統一",
    "v1.r12.consciousness_web": "意識ウェブ",
    "v1.r12.continuity": "継続性",
    "v1.r12.infrastructure": "インフラストラクチャー",
    "v1.r12.knowledge_web": "知識ウェブ",
    "v1.r12.threats": "脅威",
    "v1.r12.unification": "統一",
    "oly.title": "インフラストラクチャーオリンピック",
    "oly.stat.blocks": "言語ブロック",
    "oly.stat.categories": "競技カテゴリー",
    "oly.stat.universities": "世界の大学",
    "oly.stat.xpcap": "XP上限（マスターウィーバー）",
    "oly.stat.people": "到達人口",
    "oly.stat.gap": "インフラギャップ",
    "oly.flywheel.title": "フライホイール — オリンピックの自己成長メカニズム",
    "oly.flywheel.players": "選手が競う",
    "oly.flywheel.professionals": "専門家が検証",
    "oly.flywheel.patrons": "スポンサーが支援",
    "oly.flywheel.platform": "プラットフォームが拡大",
    "oly.medal.title": "ライブメダルテーブル — 文明管理で競う国々",
    "oly.th.nation": "国",
    "oly.th.blocks": "ブロック",
    "oly.th.pop": "人口（百万）",
    "oly.th.gamers": "ゲーマー（百万）",
    "oly.th.story": "インフラストーリー",
    "oly.th.total": "合計",
    "oly.th.status": "ステータス",
    "oly.rogue.title": "ローグチーム — 非所属タレントプール",
    "oly.categories.title": "競技カテゴリー — 文明インフラの6本柱",
    "oly.pipeline.unis": "世界の大学",
    "oly.pipeline.students": "工学部学生",
    "oly.pipeline.firms": "トップ土木工学企業",
    "oly.pipeline.govts": "各国政府",
    "oly.sponsor.title": "スポンサーシップ — ナショナルチームを支援",
    "oly.sponsor.gold": "ゴールドスポンサー",
    "oly.sponsor.silver": "シルバースポンサー",
    "oly.sponsor.bronze": "ブロンズスポンサー",
    "oly.sponsor.patron": "パトロン",
    "oly.form.register.title": "大学チームを登録",
    "oly.form.sponsor.title": "スポンサーお問い合わせ",
    "nav.behind": "論文の裏側",

    // SDG Alignment Section
    "sdg.title": "持続可能な開発目標 — 整合性",
    "sdg.subtitle": "IAAIの12リレーカリキュラムが国連持続可能な開発目標にどのように対応するか",
    "sdg.iconCaption": "IAAIのコンテンツは17の持続可能な開発目標のうち11に直接対応しています。各アイコンは国連の公式目標ページにリンクしています。",
    "sdg.col.relay": "IAAIリレー",
    "sdg.col.sdgGoals": "SDG目標",
    "sdg.col.alignment": "整合性の根拠",
    "sdg.col.5p": "5Pカテゴリー",
    "sdg.r1.rationale": "道路ネットワークは経済発展の循環システムです。道路なくして市場アクセスも緊急サービスもサプライチェーンもありません。",
    "sdg.r2.rationale": "鉄道は大量輸送と貨物の基幹です。道路よりトンキロあたりの排出量が少なく、持続可能な都市化を可能にします。",
    "sdg.r3.rationale": "港は国を世界貿易に接続します。世界の物資の90%は海上輸送です。",
    "sdg.r4.rationale": "航空インフラはグローバルな接続性、貿易、観光、緊急対応を可能にします。",
    "sdg.r5.rationale": "清潔な水は最も基本的なインフラです。22億人がまだ安全に管理された飲料水を利用できていません。",
    "sdg.r6.rationale": "衛生設備は病気を予防し、水源を保護し、人間の尊厳を守ります。",
    "sdg.r7.rationale": "エネルギーインフラは、国がクリーンに工業化するか化石燃料依存を繰り返すかを決定します。",
    "sdg.r8.rationale": "通信は人々を教育、市場、ガバナンスに接続します。デジタル格差はインフラ格差です。",
    "sdg.r9.rationale": "廃棄物管理は消費の鏡です。循環型経済には収集、分別、リサイクルのインフラが必要です。",
    "sdg.r10.rationale": "医療インフラ — 病院、診療所、サプライチェーン — は人口がパンデミックを生き延びるかどうかを決定します。",
    "sdg.r11.rationale": "教育インフラ — 学校、大学、図書館 — は文明が世代を超えて知識を伝達するメカニズムです。",
    "sdg.r12.rationale": "デジタルインフラ — データセンター、光ファイバー、クラウド — は21世紀の道路と港です。",
    "sdg.5pTitle": "5P — 人間、地球、繁栄、平和、パートナーシップ",
    "sdg.5pText": "国連は5つの柱（5P）を通じて17のSDGを構成しています。インフラは文明が5つのPすべてを実現するメカニズムです。",
    "sdg.visitUN": "国連SDG公式ウェブサイトを訪問 →",
    "sdg.disclaimerTitle": "免責事項：",
    "sdg.disclaimerText": "本出版物の内容は国連によって承認されておらず、国連またはその職員もしくは加盟国の見解を反映するものではありません。",
    "home.dominion.title": "支配権の喪失 — 収束危機",
    "home.dominion.text": "第六のリセットは宇宙からは来ない。それはすでにここにある — 意思決定、設計、統治が人間のシステムから機械のシステムへ移行する中に。絶滅ではない。置換である。12,000年にわたり文明を支えたインフラが、どの世代も吸収できないほどの速さで収束している。これが収束危機である。エピソード2は人類の連続性のアーキテクチャを描く。",
    "home.fw.ele_planetary": "ELE惑星時計 — 地球：45億年。5回のリセット。ELE 6は文明的 — 2050年。今行動せよ、さもなくば支配権を失う。",
    "home.fw.continuity_grid": "完全連続性グリッド — 人類の歴史が1,200ページの本だとしたら。24行 = 24時間。グリッドが時計である。第24行 = 最後の1時間。",
    "home.fw.row24": "第24行展開 — 最後の1時間。12,000年（紀元前10,000年 → 2050年）。500世代。人類がリレーを活用する唯一の行。七人の学者。246年で6つのリレー。すべて今も稼働中。",
    "home.fw.relay_cone": "リレーコーン — 500世代の文明が12のインフラリレーに圧縮。側面図、上面図、そして七人の学者。最初の6つのリレーは11,500年に及ぶ。最後の6つは246年に圧縮される。",
    "home.ascent.title": "意識への上昇",
    "home.ascent.subtitle": "リレー12とその先 — 2050年を真夜中とする文明論",
    "home.ascent.text": "ここに文明の核心がある。カロリーから意識へ — インフラストラクチャー・オデッセイは12,000年を12のリレー、7人の学者、5つのウェブ、3つの大帝国を通じて描く。意識への上昇はリレー12とその先：生物知性が自らのインフラと出会う転換点。ホメロスから応用世代まで5つの知的系譜が一つの問いに収束する：誰がリレーを引き継ぐのか？神学的含意は深遠である。支配権の喪失が危機を枠組み、対抗力：部分、尺度、均衡がエンジニアの計算を提供する。第8の学者は開かれた探求のまま — 3,500年の基礎的叡智の連鎖における次のノード。",
    "home.ascent.source": "系譜5層 — 第8の学者に向かう3,500年の知的リレー — iAAi真理フレームワーク"
};
