window.IA_LANG_ES = {
    "archive.documents": "Documentos",
    "archive.images": "Imágenes",
    "archive.references": "Referencias",
    "archive.relays": "Relés",
    "archive.subtitle": "Preservación completa del patrimonio del conocimiento",
    "archive.supplements": "Materiales complementarios",
    "archive.title": "Archivo",
    "author.bio": "Ir. Nigel T Dearden (鄧禮祖) es Ingeniero Civil y Estructural Colegiado e Ingeniero de Agua y Medio Ambiente Colegiado, con más de 33 años de experiencia en infraestructura en Hong Kong. Fundador de 4 Elements Consulting Ltd (est. 2006, www.4ecl.com). BEng (Hon's), CEng, C.WEM, RPE (CSB), MICE, MHKIE, MCIWEM.",
    "author.credentials": "Ingeniero Colegiado (CEng), Miembro del Instituto de Ingenieros Civiles del Reino Unido (MICE), Miembro del Instituto de Ingenieros de Hong Kong (MHKIE)",
    "author.name": "Ingeniero Dearden (Ir. Nigel T. Dearden)",
    "author.title": "Acerca del Autor",
    "civ.civilisation.subtitle": "12,000 años = 24 horas",
    "civ.civilisation.title": "Reloj de civilización",
    "civ.cosmic.subtitle": "13.5 mil millones de años = 24 horas",
    "civ.cosmic.title": "Reloj cósmico",
    "civ.cta.desc": "La pluma está en nuestra mano. La infraestructura está lista. El momento es ahora. La pregunta no es si esta fusión ocurrirá — ya está ocurriendo. La pregunta es: ¿cómo responderemos?",
    "civ.cta.title": "La medianoche se acerca",
    "civ.epigraph": "\"El reloj de elementos avanza hacia la medianoche. Todo lo que hagamos en los últimos segundos resonará por milenios.\"",
    "civ.nesting.desc": "Cada reloj está anidado dentro del anterior. El reloj planetario ocupa solo el último tercio del reloj cósmico. El reloj de civilización ocupa solo el último instante del reloj planetario. Vivimos en el último momento antes de la medianoche.",
    "civ.nesting.title": "Tres relojes, una historia",
    "civ.planetary.subtitle": "4.5 mil millones de años = 24 horas",
    "civ.planetary.title": "Reloj planetario",
    "civ.relay.title": "12 relevos en el reloj de civilización",
    "civ.subtitle": "Tres relojes anidados de 24 horas — desde el Big Bang hasta el instante humano. 13.5 mil millones de años de historia cósmica, 4.5 mil millones de años de evolución planetaria, 12,000 años de civilización — cada uno mapeado a un día. La medianoche se acerca.",
    "civ.title": "Reloj de elementos",
    "clock.bar.end": "1,000,000,000 — Misión cumplida",
    "clock.bar.mid": "Pioneros → Embajadores → Académicos",
    "clock.bar.start": "0 — Inicio",
    "clock.challenge.note": "Desafiado = nominado por jugadores · Pendiente = esperando nominación",
    "clock.challenge.title": "Tabla de desafíos de patrocinadores",
    "clock.contributors.advisors": "Asesores (estratégicos)",
    "clock.contributors.ambassadors": "Embajadores (líderes lingüísticos)",
    "clock.contributors.backers": "Financiadores",
    "clock.contributors.founders": "Equipo fundador",
    "clock.contributors.patrons": "Patrocinadores (instituciones)",
    "clock.contributors.pioneers": "Pioneros (probadores)",
    "clock.contributors.players": "Jugadores (en juego)",
    "clock.contributors.scholars": "Académicos (verificadores académicos)",
    "clock.contributors.title": "Categorías de contribuyentes",
    "clock.cta": "Únete a la competencia — Sé un pionero",
    "clock.cta.sub": "El viaje de mil millones de aprendices comienza con un pionero.",
    "clock.hero.mobilised": "Actualmente movilizados",
    "clock.hero.pop": "Población mundial",
    "clock.hero.pop.sub": "Estimación en tiempo real de la ONU",
    "clock.hero.target": "Meta: 1,000 millones de aprendices",
    "clock.hero.target.sub": "12.1% de la humanidad — Punto crítico",
    "clock.intelligence.comint": "COMINT — Inteligencia de comunicaciones (red de traducción)",
    "clock.intelligence.elint": "ELINT — Inteligencia electrónica (distribución en plataforma)",
    "clock.intelligence.geoint": "GEOINT — Inteligencia geoespacial (mapa de 8 regiones lingüísticas)",
    "clock.intelligence.humint": "HUMINT — Inteligencia humana (pioneros + embajadores)",
    "clock.intelligence.masint": "MASINT — Inteligencia de medición (análisis de aprendizaje)",
    "clock.intelligence.osint": "OSINT — Inteligencia de código abierto (GitHub + datos públicos)",
    "clock.intelligence.sigint": "SIGINT — Inteligencia de señales (análisis DAVID AI)",
    "clock.intelligence.title": "Red de inteligencia IAAI (INTs)",
    "clock.milestones.first_pioneer": "Primera ola de pioneros",
    "clock.milestones.github": "Código abierto en GitHub",
    "clock.milestones.seed": "Ronda semilla ($500K)",
    "clock.milestones.title": "Hitos",
    "clock.milestones.vr": "Campus VR (Meta)",
    "clock.notyet.ce_firms": "Empresas de ingeniería civil (top 100)",
    "clock.notyet.cta": "Cada número es un desafío. Cada cero, una invitación.",
    "clock.notyet.eng_students": "Estudiantes de ingeniería",
    "clock.notyet.govts": "Gobiernos nacionales",
    "clock.notyet.people": "Personas sin conocimiento de infraestructura",
    "clock.notyet.title": "Aún no participando — Desafíos",
    "clock.notyet.un_bodies": "Agencias de la ONU",
    "clock.notyet.universities": "Universidades globales",
    "clock.partners.title": "Tabla de desafíos de socios",
    "clock.platform.game_pages": "Páginas de juego",
    "clock.platform.inventions": "Inventos catalogados",
    "clock.platform.languages_active": "Idiomas activos",
    "clock.platform.languages_planned": "Idiomas planeados",
    "clock.platform.pages": "Páginas web",
    "clock.platform.relays": "Relevos construidos",
    "clock.platform.tests": "Pruebas aprobadas",
    "clock.platform.title": "Indicadores de la plataforma",
    "clock.platform.words": "Palabras escritas",
    "clock.regions.coverage": "Cobertura integral: ~85% mercado global de juegos · ~80% gasto en edtech",
    "clock.regions.goal": "Meta: los 8 idiomas para 2027",
    "clock.regions.title": "8 bloques lingüísticos — Competencia global",
    "clock.scaling.phase1": "Fase 1: Fundadores",
    "clock.scaling.phase2": "Fase 2: Pioneros (2-3 por bloque)",
    "clock.scaling.phase3": "Fase 3: Embajadores (10 por bloque)",
    "clock.scaling.phase4": "Fase 4: Código abierto en GitHub",
    "clock.scaling.phase5": "Fase 5: Adopción universitaria",
    "clock.scaling.phase6": "Fase 6: Crecimiento orgánico",
    "clock.scaling.title": "Modelo de escalamiento",
    "clock.subtitle": "La carrera humana hacia la alfabetización en infraestructura — Desafíos",
    "clock.title": "Reloj global de movilización IAAI",
    "footer.ep1": "Episodio 1: Fundamentos de la Tierra",
    "footer.ep2": "Episodio 2: Arena Gris",
    "footer.ep3": "Episodio 3: Escala Cósmica",
    "footer.copyright": "&copy; 2026 Academia de Infraestructura. Todos los derechos reservados. Conocimiento preservado para siempre.",
    "framework.4cs.challenge": "Desafío",
    "framework.4cs.consequence": "Consecuencia",
    "framework.4cs.context": "Contexto",
    "framework.4cs.continuum": "Continuo",
    "framework.4cs.title": "Marco de Análisis 4C",
    "framework.modes.east": "Modo Oriental",
    "framework.modes.east.desc": "Continuo / Construcción — Prototipo Qin Shi Huang",
    "framework.modes.outrider": "Modo Outrider",
    "framework.modes.outrider.desc": "Semi-continuo / Temporal — Prototipo Gengis Kan",
    "framework.modes.title": "Tres Modos de Civilización",
    "framework.modes.west": "Modo Occidental",
    "framework.modes.west.desc": "Discontinuo / Construcción — Prototipo Alejandro Magno",
    "framework.relays.title": "12 Relevos de la Civilización",
    "framework.subtitle": "Metodología de Pensamiento Sistémico Integrado",
    "framework.title": "Marco Completo",
    "header.subtitle": "Odisea de Infraestructura: Volumen 1 — De Calorías a Conciencia",
    "header.subtitle.v2": "Odisea de Infraestructura: Volumen 2 — Guía práctica",
    "header.subtitle.v3": "Odisea de Infraestructura: Volumen 3 — Motor de la realidad",
    "header.title": "Academia de Infraestructura",
    "home.archive.architects": "Arquitectos del destino y grandes unificadores: Alejandro Magno, Gengis Kan, Qin Shi Huang",
    "home.archive.p1": "La Academia de Infraestructura es un archivo digital que preserva el conocimiento completo de la Odisea de Infraestructura — un curso magistral sobre 12,000 años de desarrollo de infraestructura humana. Este sitio asegura la preservación eterna del conocimiento para académicos, ingenieros y aprendices en todo el mundo.",
    "home.archive.p2": "Todo el contenido, visualizaciones y marcos están integrados aquí para facilitar la navegación y el descubrimiento. Es un registro eterno del ascenso humano de calorías a conciencia, grabado con el bolígrafo en la eternidad digital.",
    "home.archive.title": "Acerca de este Archivo",
    "home.author": "Autor: Ingeniero Dearden (Ir. Nigel T. Dearden)",
    "home.challenge.stat1.desc": "de los cursos carecen de integración interdisciplinaria",
    "home.challenge.stat1.num": "70%",
    "home.challenge.stat2.desc": "de los estudiantes se sienten poco preparados para la aplicación práctica",
    "home.challenge.stat2.num": "65%",
    "home.challenge.stat3.desc": "reportan exposición limitada al pensamiento sistémico",
    "home.challenge.stat3.num": "45%",
    "home.challenge.stat4.desc": "de los empleadores identifican brechas de habilidades en la preparación de proyectos",
    "home.challenge.stat4.num": "80%",
    "home.challenge.stat5.desc": "de los proyectos integran indicadores de impacto comunitario o ambiental",
    "home.challenge.stat5.num": "30%",
    "home.challenge.stat6.desc": "de los proyectos de infraestructura se retrasan por brechas en el conocimiento práctico",
    "home.challenge.stat6.num": "90%",
    "home.challenge.subtitle": "La educación en infraestructura está fragmentada, es abstracta y desconectada del impacto en el mundo real.",
    "home.challenge.title": "Los Desafíos que Enfrentamos",
    "home.challenge.urgent": "Necesidad urgente: construir puentes para profesionales de infraestructura preparados para el futuro",
    "home.charter.charter.h": "LA CARTA",
    "home.charter.charter.p": "Creemos que la infraestructura es el sistema operativo de la civilización. Como un río que talla la tierra lenta y persistentemente para lograr un cambio planetario, nos comprometemos con el conocimiento abierto, la contribución verificada, el respeto cultural y la creencia de que entender cómo construimos el mundo es el primer paso para construirlo mejor.",
    "home.charter.mission.h": "MISIÓN",
    "home.charter.mission.p": "Ofrecer la primera plataforma educativa de infraestructura abierta, multilingüe y guiada por IA del mundo — llegando a mil millones de estudiantes en 8 idiomas, verificada por contribuyentes humanos de todos los continentes.",
    "home.charter.title": "MISIÓN, VISIÓN Y CARTA",
    "home.charter.vision.h": "VISIÓN",
    "home.charter.vision.p": "Un mundo donde cada persona comprenda la infraestructura que sostiene la civilización — y tenga el conocimiento para construir lo que viene después.",
    "home.cover.front": "Portada y contraportada — Episodio 1: Fundamentos de la Tierra",
    "home.cover.interior": "Vista interior — Capítulo 1: Relevo del Fuego (Parte 1 y Parte 2)",
    "home.cover.portrait": "Relevos de la Civilización — 12 capítulos desde el Árbol hasta el Torus",
    "home.ep1.btn": "Publicado",
    "home.ep1.desc": "De Calorías a Conciencia — 12 relevos desde el fuego hasta el torus",
    "home.ep1.subtitle": "Fundamentos de la Tierra",
    "home.ep1.title": "Episodio 1",
    "home.ep2.btn": "Próximamente",
    "home.ep2.desc": "Cibernética, IA y sistemas inteligentes",
    "home.ep2.subtitle": "Motor de la Realidad — Arena Gris",
    "home.ep2.title": "Episodio 2",
    "home.ep3.btn": "Próximamente",
    "home.ep3.desc": "Gestión planetaria, del sistema solar y galáctica",
    "home.ep3.subtitle": "Gestión y Renovación — Escala Cósmica",
    "home.ep3.title": "Episodio 3",
    "home.framework.journey": "El viaje es el trabajo.",
    "home.framework.modes.caption": "Tres modos — A través de 12,000 años: Occidental, Oriental y Outrider",
    "home.framework.motto": "Educación en Infraestructura: Pensamiento Sistémico, no Memorización",
    "home.framework.relays.caption": "12 relevos de la civilización — Del fuego a la conciencia",
    "home.framework.silk.caption": "La paradoja de la Ruta de la Seda — Los Outriders controlaron las rutas comerciales pero no construyeron infraestructura",
    "home.framework.subtitle": "Educación en Infraestructura con Pensamiento Sistémico desde la Perspectiva del Ingeniero Civil",
    "home.framework.title": "Marco Completo",
    "home.game.cta.sub": "Volumen 3: Motor de la Realidad — Plataforma de aprendizaje guiado",
    "home.game.cta.title": "Entrar al Juego",
    "home.game.desc": "¿Listo para aplicar lo aprendido? Entra en Motor de la Realidad — Plataforma de aprendizaje inmersivo donde serás un ingeniero de infraestructura.",
    "home.game.note": "Simulación y práctica: aplica conceptos en un entorno dinámico",
    "home.game.title": "Volumen 3: Juego",
    "home.hero.caption": "De Calorías a Conciencia: Odisea de Infraestructura — Relevos de la Civilización",
    "home.kw.subtitle": "Historia completa de la escritura — Desde fichas contables hasta la era digital. El bolígrafo como el relevo definitivo de infraestructura.",
    "home.kw.title": "Red de Conocimiento: La Escritura como Infraestructura",
    "home.media.calories": "De Calorías a Conciencia",
    "home.media.engine": "Motor de la Realidad — Plataforma de aprendizaje guiado",
    "home.media.river": "Película de la Llanura Fluvial",
    "home.media.title": "Medios",
    "home.media.trailer": "Tráiler rápido",
    "home.pop.answer": "IAAI existe para cambiar ese número.",
    "home.pop.question": "personas comparten la infraestructura de este planeta. ¿Cuántas la entienden?",
    "home.pop.source": "Fuente: Estimaciones de Población Mundial de la ONU (proyección en tiempo real)",
    "home.ppp.clock.sub": "Seguimiento en tiempo real de la carrera humana hacia la alfabetización en infraestructura. El desafío ya comenzó.",
    "home.ppp.clock.title": "Ver reloj de movilización",
    "home.ppp.cta.sub": "Acceso beta gratuito — Prueba, traduce, valida y gana tu lugar en el Muro de Fundadores. Únete a la Odisea.",
    "home.ppp.cta.title": "Conviértete en Pionero",
    "home.ppp.partners.h": "SOCIOS",
    "home.ppp.partners.p": "Universidades, plataformas tecnológicas y empresas de infraestructura. MIT OCW, Khan Academy, Meta/VR, Manus/AI, AECOM, Arup, Bechtel. Tecnología, validación de contenido y acceso al mercado.",
    "home.ppp.partners.status": "Estado: Abierto al Desafío — Nominados por Jugadores",
    "home.ppp.patrons.h": "PATROCINADORES",
    "home.ppp.patrons.p": "Instituciones cuya misión se alinea con la educación universal en infraestructura. UNESCO, National Geographic, NASA, Royal Society, Discovery, Smithsonian, NOAA, Banco Mundial, BAsD, Academia China de Ciencias.",
    "home.ppp.patrons.status": "Estado: Abierto al Desafío — Nominados por Jugadores",
    "home.ppp.players.h": "JUGADORES",
    "home.ppp.players.p": "Pioneros, Embajadores, Académicos y Asesores de todos los países. Personas reales que prueban, traducen, validan, contribuyen y difunden el mensaje. La fuerza de la democracia.",
    "home.ppp.players.status": "Estado: Reclutando Pioneros — Acceso Beta Gratuito",
    "home.ppp.reach.active": "ACTIVO",
    "home.ppp.reach.active2": "ACTIVO",
    "home.ppp.reach.active3": "ACTIVO",
    "home.ppp.reach.active4": "ACTIVO",
    "home.ppp.reach.active5": "ACTIVO",
    "home.ppp.reach.active6": "ACTIVO",
    "home.ppp.reach.active7": "ACTIVO",
    "home.ppp.reach.active8": "ACTIVO",
    "home.ppp.reach.ar": "Árabe",
    "home.ppp.reach.cn": "Chino",
    "home.ppp.reach.coverage": "8 idiomas que cubren ~85% del mercado global de juegos, ~80% del gasto en EdTech y los principales corredores de inversión en infraestructura.",
    "home.ppp.reach.en": "Inglés",
    "home.ppp.reach.es": "Español",
    "home.ppp.reach.h": "ALCANCE LINGÜÍSTICO GLOBAL",
    "home.ppp.reach.hi": "Hindi",
    "home.ppp.reach.ja": "Japonés",
    "home.ppp.reach.ko": "Coreano",
    "home.ppp.reach.vi": "Vietnamita",
    "home.ppp.subtitle": "De calorías a conciencia — un llamado a la acción a nivel individual que no puede ser detenido ni controlado. Simplemente sigue aprendiendo.",
    "home.ppp.title": "PATROCINADORES, SOCIOS Y JUGADORES",
    "home.s1.desc": "Conceptos básicos — Tres modos, reloj elemental, líneas de tiempo de caminos y barcos",
    "home.s1.title": "S1: Identificación",
    "home.s2.desc": "Difusión tecnológica — El bolígrafo como infraestructura, sistemas de escritura",
    "home.s2.title": "S2: Comprensión",
    "home.s3.desc": "Implementación — Diagramas de gestión para cada relevo",
    "home.s3.title": "S3: Gestión y Control",
    "home.s4.desc": "Correspondencias — Comparación Occidental, Outrider y Oriental para cada relevo",
    "home.s4.title": "S4: Ensayos y Visiones",
    "home.subtitle": "Perspectivas y Guía para Ingenieros Civiles — Episodio 1: De Calorías a Conciencia",
    "home.supplements.btn": "Ver Materiales Complementarios",
    "home.supplements.title": "Volumen 2: 4 Materiales Complementarios",
    "home.title": "Odisea de Infraestructura",
    "home.trilogy.title": "Visión de la Trilogía",
    "home.vol1.btn": "Leer Perspectivas",
    "home.vol1.desc": "Fundamento narrativo: 12 relevos de la civilización a lo largo de 12,000 años de desarrollo de infraestructura humana. Desde el dominio del fuego hasta el torus de la conciencia.",
    "home.vol1.subtitle": "Historia y Contexto — Narrativa",
    "home.vol1.title": "Volumen 1: Perspectivas",
    "home.vol2.btn": "Leer Guía",
    "home.vol2.desc": "Marco práctico: Métodos comparativos Occidental/Oriental/Outrider, análisis 4C y modelo estratégico para entender la infraestructura como ADN de la civilización.",
    "home.vol2.subtitle": "Marco Estratégico — Expansión",
    "home.vol2.title": "Volumen 2: Guía",
    "inst.coming": "Próximamente — Base de datos completa de instituciones en desarrollo",
    "inst.sdg.title": "Clasificado por Objetivos de Desarrollo Sostenible",
    "inst.status.challenged": "Desafiado",
    "inst.status.engaged": "Comprometido",
    "inst.status.notyet": "No contactado aún",
    "inst.status.potential": "Potencial",
    "inst.subtitle": "Mapa de inteligencia — Cada institución, universidad, agencia de la ONU, sociedad profesional, ONG, proveedor tecnológico y entidad financiera que puede ser convocada, desafiada o colaborada. Organizado por Objetivos de Desarrollo Sostenible para mostrar alineación con prioridades globales.",
    "inst.title": "Instituciones",
    "lib.supp_title": "Documentos complementarios",
    "lib.title": "Biblioteca de documentos",
    "library.subtitle": "Archivo completo de activos de conocimiento",
    "library.title": "Biblioteca de Documentos",
    "nav.author": "Autor",
    "nav.charter": "Carta",
    "nav.civclock": "Reloj de civilización",
    "nav.clock": "Reloj de movilización",
    "nav.documents": "Documentos",
    "nav.founders": "MURO DE FUNDADORES",
    "nav.framework": "Marco",
    "nav.home": "Inicio",
    "nav.institutions": "Instituciones",
    "nav.outriders": "Pioneros",
    "nav.pioneers": "Programa pionero",
    "nav.precis": "Resumen Ejecutivo",
    "nav.resources": "Recursos",
    "nav.supplements": "Materiales complementarios",
    "nav.taxonomy": "Taxonomía",
    "nav.ep1": "EP.1: Perspectivas",
    "nav.ep2": "EP.2: Guía",
    "nav.ep3": "EP.3: Juego",
    "or.conn.book.desc": "Cada capítulo comienza y termina con citas de pioneros. Sus innovaciones son estudios de caso. Sus fracasos, advertencias. Son la base de evidencia de los argumentos.",
    "or.conn.book.title": "En el libro",
    "or.conn.game.desc": "Los pioneros aparecen como mentores NPC, fuentes de citas y proveedores de contexto histórico en cada relevo. Los jugadores los encuentran a lo largo de los 12 capítulos.",
    "or.conn.game.title": "En el juego",
    "or.conn.movement.desc": "Los pioneros ofrecen autoridad moral. Cuando IAAI desafía a la UNESCO o al MIT, se apoya en los hombros de 12,000 años de sabiduría en infraestructura que ellos representan.",
    "or.conn.movement.title": "En el movimiento",
    "or.conn.title": "Cómo los pioneros sirven a la misión",
    "or.era1.title": "Mundo antiguo",
    "or.era2.title": "Mundo clásico",
    "or.era3.title": "Edad Media y Renacimiento",
    "or.era4.title": "Revolución Industrial",
    "or.era5.title": "Moderno",
    "or.era6.title": "Digital y futuro",
    "or.quote": "\"Un líder sabio y un general virtuoso, por eso actúa y vence a otros; el éxito surge de la multitud, es un profeta.\" — Sun Tzu, capítulo 13",
    "or.stat.civilisations": "Civilizaciones representadas",
    "or.stat.eras": "Eras históricas",
    "or.stat.relays": "Relevos cubiertos",
    "or.stat.total": "Total de pioneros",
    "or.subtitle": "Mentores espirituales históricos que caminan junto a cada nivel — no incluidos en la jerarquía 6+1, estos sabios atraviesan todos los modos, relevos y 12,000 años. Son la voz en el juego, las citas en el muro, la sabiduría que conecta el fuego con el torus.",
    "or.title": "Pioneros",
    "pioneers.charter.agree": "He leído y acepto la Carta IAAI. Me comprometo a contribuir con honestidad, respeto cultural y compartir conocimiento abierto a través de idiomas y fronteras. Entiendo que es un programa voluntario y que mis contribuciones serán atribuidas bajo licencia CC BY-NC-SA 4.0.",
    "pioneers.charter.text": "Creemos que la infraestructura es el sistema operativo de la civilización. Así como los ríos esculpen lentamente la tierra para lograr transformaciones planetarias, nos comprometemos con el conocimiento abierto, contribuciones verificadas, respeto cultural y la comprensión de que construir el mundo es el primer paso para construir un mundo mejor.",
    "pioneers.charter.title": "Carta IAAI",
    "pioneers.form.country": "País",
    "pioneers.form.email": "Correo electrónico",
    "pioneers.form.expertise": "Área de especialización",
    "pioneers.form.language": "Idioma principal",
    "pioneers.form.motivation": "¿Por qué quieres unirte? (opcional)",
    "pioneers.form.name": "Nombre completo",
    "pioneers.form.other_langs": "Otros idiomas",
    "pioneers.form.submit": "Enviar solicitud — Únete a la competencia",
    "pioneers.form.subtitle": "Acceso beta gratuito. Sin costo. Sin compromiso. Solo curiosidad y compromiso.",
    "pioneers.form.title": "Solicita ser pionero",
    "pioneers.subtitle": "Los primeros contribuyentes probarán, traducirán, verificarán y difundirán la alfabetización en infraestructura en cada continente. Acceso a versión beta gratuita. Gana tu lugar en el muro de fundadores.",
    "pioneers.tier1.desc": "Primeros probadores. Juegan, reportan errores, verifican contenido. 2-3 por bloque lingüístico. Exploradores de la red de inteligencia.",
    "pioneers.tier1.req": "Requisitos: Curiosidad, cualquier idioma, disposición para probar",
    "pioneers.tier1.title": "Pionero",
    "pioneers.tier2.desc": "Líderes lingüísticos. Revisan y corrigen traducciones AI para uso nativo. Contribuyentes con firma. 10 por bloque lingüístico.",
    "pioneers.tier2.req": "Requisitos: Fluidez nativa + experiencia como pionero",
    "pioneers.tier2.title": "Embajador",
    "pioneers.tier3.desc": "Verificadores académicos. Ingenieros, profesores, investigadores que validan precisión técnica y mapean contenido a currículos.",
    "pioneers.tier3.req": "Requisitos: Credenciales académicas + especialización",
    "pioneers.tier3.title": "Académico",
    "pioneers.tier4.desc": "Guía estratégica. Líderes de industria, formuladores de políticas y conectores institucionales que abren puertas y moldean dirección.",
    "pioneers.tier4.req": "Requisitos: Invitación o nominación",
    "pioneers.tier4.title": "Asesor",
    "pioneers.title": "Programa pionero",
    "precis.relay.epilogue": "Epílogo",
    "precis.relay.prologue": "Prólogo",
    "precis.relay.relay_10_aaa": "Relevo 10: Tríada AAA",
    "precis.relay.relay_10_autoair": "Relevo 10: Auto/Aéreo",
    "precis.relay.relay_11_humans": "Relevo 11: Nodo humano",
    "precis.relay.relay_11_orbit": "Relevo 11: Órbita",
    "precis.relay.relay_12_programmable": "Relevo 12: Programable",
    "precis.relay.relay_12_torus": "Relevo 12: Torus",
    "precis.relay.relay_1_fire": "Relevo 1: Fuego",
    "precis.relay.relay_2_tree": "Relevo 2: Árbol",
    "precis.relay.relay_3_river": "Relevo 3: Río",
    "precis.relay.relay_4_horse": "Relevo 4: Caballo",
    "precis.relay.relay_5_road": "Relevo 5: Caminos",
    "precis.relay.relay_6_ship": "Relevo 6: Barcos",
    "precis.relay.relay_7_rail": "Relevo 7: Ferrocarril",
    "precis.relay.relay_8_loom": "Relevo 8: Telar",
    "precis.relay.relay_9_engine": "Relevo 9: Motor",
    "precis.relay.torus": "Torus",
    "precis.subtitle": "Odisea de Infraestructura — Visión Estratégica",
    "precis.title": "Resumen Ejecutivo",
    "relay.1.name": "Relevo 1: Fuego",
    "relay.1.subtitle": "Chispa Primordial — Comienzo del dominio energético",
    "relay.10.name": "Relevo 10: Tríada AAA",
    "relay.10.subtitle": "Aviación, Atómico, Automatización — Trinidad moderna",
    "relay.11.name": "Relevo 11: Humanos Programables",
    "relay.11.subtitle": "Humanos en red — Conexión digital",
    "relay.12.name": "Relevo 12: Conciencia",
    "relay.12.subtitle": "Torus — Forma definitiva de infraestructura",
    "relay.2.name": "Relevo 2: Árbol",
    "relay.2.subtitle": "Arquitectura viva — La naturaleza como ingeniería",
    "relay.3.name": "Relevo 3: Río",
    "relay.3.subtitle": "Civilización hidráulica — Infraestructura líquida",
    "relay.4.name": "Relevo 4: Caballo",
    "relay.4.subtitle": "Revolución móvil — Velocidad e imperios",
    "relay.5.name": "Relevo 5: Caminos",
    "relay.5.subtitle": "Red conectada — Arterias del imperio",
    "relay.6.name": "Relevo 6: Barcos",
    "relay.6.subtitle": "Autopistas oceánicas — Red global de comercio",
    "relay.7.name": "Relevo 7: Ferrocarril",
    "relay.7.subtitle": "Columna vertebral de acero — Conexión industrial",
    "relay.8.name": "Relevo 8: Telar",
    "relay.8.subtitle": "Red tejida — Infraestructura de información",
    "relay.9.name": "Relevo 9: Motor",
    "relay.9.subtitle": "Revolución energética — Mundo mecanizado",
    "relay.epilogue": "Epílogo",
    "relay.prologue": "Prólogo",
    "resources.subtitle": "Referencias, fuentes de datos y lecturas adicionales",
    "resources.title": "Recursos",
    "section.4c_analysis": "Análisis 4C",
    "section.active_webs": "Redes activas",
    "section.back_to_index": "Volver al índice",
    "section.challenge": "Desafío",
    "section.communication_web": "Red de comunicación",
    "section.comparative_analysis": "Análisis comparativo",
    "section.consciousness_web": "Red de conciencia",
    "section.consequence": "Consecuencia",
    "section.context": "Contexto",
    "section.continuity": "Continuidad",
    "section.continuum": "Continuo",
    "section.digital_web": "Red digital",
    "section.east_mode": "Modo oriental",
    "section.energy_web": "Red energética",
    "section.four_pillars": "Cuatro pilares",
    "section.governance_web": "Red de gobernanza",
    "section.historical_significance": "Significado histórico",
    "section.impact": "Impacto:",
    "section.information_web": "Red de información",
    "section.infrastructure": "Infraestructura",
    "section.key_insights": "Perspectivas clave",
    "section.knowledge_web": "Red de conocimiento",
    "section.legacy": "Legado:",
    "section.management_diagram": "Diagrama de gestión",
    "section.military_web": "Red militar",
    "section.next_relay": "Siguiente relé →",
    "section.outrider_mode": "Modo explorador",
    "section.previous_relay": "← Relé anterior",
    "section.production_web": "Red de producción",
    "section.strategic_framework": "Marco estratégico",
    "section.the_counterparts": "Contrapartes:",
    "section.the_first_infrastructure": "La primera infraestructura",
    "section.threats": "Amenazas",
    "section.timeline": "Cronología:",
    "section.trade_web": "Red comercial",
    "section.transport_web": "Red de transporte",
    "section.unification": "Unificación",
    "section.west_mode": "Modo occidental",
    "special.conclusion": "Conclusión",
    "special.epilogue": "Epílogo",
    "special.from_calories_to_consciousness": "De calorías a conciencia",
    "special.prologue": "Prólogo",
    "special.the_beginning": "El comienzo",
    "special.the_journey_begins": "Comienza el viaje",
    "special.the_journey_continues": "El viaje continúa",
    "supplements.s1": "Complemento 1: Identificación",
    "supplements.s2": "Complemento 2: Comprensión",
    "supplements.s3": "Complemento 3: Gestión y Control",
    "supplements.s4": "Complemento 4: Ensayos y Visiones",
    "supplements.subtitle": "Extensiones profundas del Volumen 2",
    "supplements.title": "Materiales Complementarios",
    "tax.advisors": "Asesores",
    "tax.advisors.desc": "Guía estratégica. Líderes de industria y conectores institucionales.",
    "tax.ambassadors": "Embajadores",
    "tax.ambassadors.desc": "Líderes lingüísticos. 10 por bloque lingüístico.",
    "tax.backers": "Financiadores",
    "tax.backers.desc": "Apoyo financiero e institucional. Patrocinadores y socios.",
    "tax.biology": "Analogía biológica",
    "tax.count": "Cantidad",
    "tax.founder": "Fundador",
    "tax.founder.desc": "Arquitecto. 1 persona. Diseñó todo el sistema.",
    "tax.iaai": "Niveles IAAI",
    "tax.outriders.note": "Los pioneros (mentores espirituales históricos) no cuentan en la jerarquía 6+1 — atraviesan todos los modos, relevos y 12,000 años caminando juntos.",
    "tax.pioneers": "Pioneros",
    "tax.pioneers.desc": "Primeros probadores. 2-3 por bloque lingüístico.",
    "tax.players": "Jugadores",
    "tax.players.desc": "Participantes en el juego. Meta: 1,000 millones de aprendices.",
    "tax.role": "Rol",
    "tax.scholars": "Académicos",
    "tax.scholars.desc": "Verificadores académicos. Profesores, ingenieros, investigadores.",
    "tax.subtitle": "Jerarquía 6+1 — Como la clasificación biológica de reino a especie, los contribuyentes IAAI van de fundadores a patrocinadores, cada nivel más amplio y especializado.",
    "tax.title": "Taxonomía IAAI",
    "toc.chapter": "Capítulo",
    "toc.chapter.suffix": "Capítulo",
    "toc.epilogue": "Epílogo",
    "toc.prologue": "Prólogo",
    "toc.title": "Índice",
    "toc.volume1": "Volumen 1: Perspectivas — Historia y Contexto",
    "toc.volume2": "Volumen 2: Guía — Marco Estratégico",
    "toc.volume3": "Volumen 3: Juego — Simulación y Práctica",
    "ui.available": "Publicado",
    "ui.back": "Regresar",
    "ui.coming.soon": "Próximamente",
    "ui.download": "Descargar",
    "ui.error": "Error al cargar contenido. Por favor, inténtelo de nuevo.",
    "ui.loading": "Cargando...",
    "ui.next": "Página siguiente",
    "ui.prev": "Página anterior",
    "ui.read.more": "Leer más",
    "ui.view": "Ver",
    "v1.index.about_title": "Acerca de este volumen",
    "v1.index.relays_title": "Doce relevos",
    "v1.index.title": "Volumen 1: Perspectivas",
    "v1.r01.active_webs": "Redes activas",
    "v1.r01.counterparts_title": "Contraparte: Fire",
    "v1.r01.four_pillars": "Cuatro pilares",
    "v1.r01.historical_significance": "Significado histórico",
    "v1.r01.next_relay": "Siguiente relé →",
    "v1.r01.previous_relay": "← Relé anterior",
    "v1.r01.subtitle": "Chispa primordial — El inicio del dominio energético",
    "v1.r01.title": "Relé 1: Fire",
    "v1.r02.active_webs": "Redes activas",
    "v1.r02.counterparts_title": "Contraparte: Tree",
    "v1.r02.four_pillars": "Cuatro pilares",
    "v1.r02.historical_significance": "Significado histórico",
    "v1.r02.next_relay": "Siguiente relé →",
    "v1.r02.previous_relay": "← Relé anterior",
    "v1.r02.subtitle": "Arquitectura viva — La naturaleza como ingeniería",
    "v1.r02.title": "Relé 2: Tree",
    "v1.r03.active_webs": "Redes activas",
    "v1.r03.counterparts_title": "Contraparte: River",
    "v1.r03.four_pillars": "Cuatro pilares",
    "v1.r03.historical_significance": "Significado histórico",
    "v1.r03.next_relay": "Siguiente relé →",
    "v1.r03.previous_relay": "← Relé anterior",
    "v1.r03.subtitle": "Civilización hidráulica — Infraestructura líquida",
    "v1.r03.title": "Relé 3: River",
    "v1.r04.active_webs": "Redes activas",
    "v1.r04.counterparts_title": "Contraparte: Horse",
    "v1.r04.four_pillars": "Cuatro pilares",
    "v1.r04.historical_significance": "Significado histórico",
    "v1.r04.next_relay": "Siguiente relé →",
    "v1.r04.previous_relay": "← Relé anterior",
    "v1.r04.subtitle": "Revolución móvil — Velocidad e imperio",
    "v1.r04.title": "Relé 4: Horse",
    "v1.r05.active_webs": "Redes activas",
    "v1.r05.counterparts_title": "Contraparte: Roads",
    "v1.r05.four_pillars": "Cuatro pilares",
    "v1.r05.historical_significance": "Significado histórico",
    "v1.r05.next_relay": "Siguiente relé →",
    "v1.r05.previous_relay": "← Relé anterior",
    "v1.r05.subtitle": "Red conectada — Las arterias del imperio",
    "v1.r05.title": "Relé 5: Roads",
    "v1.r06.active_webs": "Redes activas",
    "v1.r06.counterparts_title": "Contraparte: Ships",
    "v1.r06.four_pillars": "Cuatro pilares",
    "v1.r06.historical_significance": "Significado histórico",
    "v1.r06.next_relay": "Siguiente relé →",
    "v1.r06.previous_relay": "← Relé anterior",
    "v1.r06.subtitle": "Autopista oceánica — Red global de comercio",
    "v1.r06.title": "Relé 6: Ships",
    "v1.r07.active_webs": "Redes activas",
    "v1.r07.counterparts_title": "Contraparte: Rail",
    "v1.r07.four_pillars": "Cuatro pilares",
    "v1.r07.historical_significance": "Significado histórico",
    "v1.r07.next_relay": "Siguiente relé →",
    "v1.r07.previous_relay": "← Relé anterior",
    "v1.r07.subtitle": "Columna vertebral de acero — Conexión industrial",
    "v1.r07.title": "Relé 7: Rail",
    "v1.r08.active_webs": "Redes activas",
    "v1.r08.counterparts_title": "Contraparte: Loom",
    "v1.r08.four_pillars": "Cuatro pilares",
    "v1.r08.historical_significance": "Significado histórico",
    "v1.r08.next_relay": "Siguiente relé →",
    "v1.r08.previous_relay": "← Relé anterior",
    "v1.r08.subtitle": "Red tejida — Infraestructura de información",
    "v1.r08.title": "Relé 8: Loom",
    "v1.r09.active_webs": "Redes activas",
    "v1.r09.counterparts_title": "Contraparte: Engine",
    "v1.r09.four_pillars": "Cuatro pilares",
    "v1.r09.historical_significance": "Significado histórico",
    "v1.r09.next_relay": "Siguiente relé →",
    "v1.r09.previous_relay": "← Relé anterior",
    "v1.r09.subtitle": "Revolución energética — Mundo mecanizado",
    "v1.r09.title": "Relé 9: Engine",
    "v1.r10.active_webs": "Redes activas",
    "v1.r10.counterparts_title": "Contraparte: AAA",
    "v1.r10.four_pillars": "Cuatro pilares",
    "v1.r10.historical_significance": "Significado histórico",
    "v1.r10.next_relay": "Siguiente relé →",
    "v1.r10.previous_relay": "← Relé anterior",
    "v1.r10.subtitle": "Aviación, átomo, automatización — La trinidad moderna",
    "v1.r10.title": "Relé 10: AAA",
    "v1.r11.active_webs": "Redes activas",
    "v1.r11.counterparts_title": "Contraparte: Programmable Humans",
    "v1.r11.four_pillars": "Cuatro pilares",
    "v1.r11.historical_significance": "Significado histórico",
    "v1.r11.next_relay": "Siguiente relé →",
    "v1.r11.previous_relay": "← Relé anterior",
    "v1.r11.subtitle": "Humanos en red — Conexión digital",
    "v1.r11.title": "Relé 11: Programmable Humans",
    "v1.r12.active_webs": "Redes activas",
    "v1.r12.counterparts_title": "Contraparte: Consciousness",
    "v1.r12.four_pillars": "Cuatro pilares",
    "v1.r12.historical_significance": "Significado histórico",
    "v1.r12.next_relay": "Siguiente relé →",
    "v1.r12.previous_relay": "← Relé anterior",
    "v1.r12.subtitle": "Torus — La forma definitiva de infraestructura",
    "v1.r12.title": "Relé 12: Consciousness",
    "v2.index.about_text": "Volumen 2: Guía aplica el marco de cuatro pilares (Observación → Educación → Aplicación → Tesis) a cada uno de los doce relevos de civilización. Este volumen ofrece orientación práctica para entender cómo funcionan los sistemas de infraestructura, cómo analizarlos y cómo aplicarlos a desafíos contemporáneos.",
    "v2.index.about_title": "Acerca de este volumen",
    "v2.index.app": "Aplicación",
    "v2.index.app_text": "¿Cómo aplicamos estas lecciones? ¿Qué marcos y herramientas prácticas genera este relevo?",
    "v2.index.edu": "Educación",
    "v2.index.edu_text": "¿Qué podemos aprender de este relevo? ¿Qué principios y lecciones sobre infraestructura nos enseña?",
    "v2.index.framework_title": "Marco de cuatro pilares",
    "v2.index.obs": "Observación",
    "v2.index.obs_text": "¿Qué observamos en este relevo? ¿Cuáles son sus características, componentes y patrones?",
    "v2.index.relays_caption": "Doce relevos de civilización — de fuego a conciencia",
    "v2.index.subtitle": "Guía — Marco práctico y análisis ampliado",
    "v2.index.thesis": "Tesis",
    "v2.index.thesis_text": "¿Cuál es la tesis general? ¿Qué revelación fundamental ofrece este relevo?",
    "v2.index.title": "Volumen 2: Guía",
    "v2.r01.active_webs": "Redes activas",
    "v2.r01.counterparts_title": "Contraparte: Fire",
    "v2.r01.four_pillars": "Cuatro pilares",
    "v2.r01.historical_significance": "Significado histórico",
    "v2.r01.next_relay": "Siguiente relé →",
    "v2.r01.previous_relay": "← Relé anterior",
    "v2.r01.subtitle": "Chispa primordial — El inicio del dominio energético",
    "v2.r01.title": "Relé 1: Fire",
    "v2.r02.active_webs": "Redes activas",
    "v2.r02.counterparts_title": "Contraparte: Tree",
    "v2.r02.four_pillars": "Cuatro pilares",
    "v2.r02.historical_significance": "Significado histórico",
    "v2.r02.next_relay": "Siguiente relé →",
    "v2.r02.previous_relay": "← Relé anterior",
    "v2.r02.subtitle": "Arquitectura viva — La naturaleza como ingeniería",
    "v2.r02.title": "Relé 2: Tree",
    "v2.r03.active_webs": "Redes activas",
    "v2.r03.counterparts_title": "Contraparte: River",
    "v2.r03.four_pillars": "Cuatro pilares",
    "v2.r03.historical_significance": "Significado histórico",
    "v2.r03.next_relay": "Siguiente relé →",
    "v2.r03.previous_relay": "← Relé anterior",
    "v2.r03.subtitle": "Civilización hidráulica — Infraestructura líquida",
    "v2.r03.title": "Relé 3: River",
    "v2.r04.active_webs": "Redes activas",
    "v2.r04.counterparts_title": "Contraparte: Horse",
    "v2.r04.four_pillars": "Cuatro pilares",
    "v2.r04.historical_significance": "Significado histórico",
    "v2.r04.next_relay": "Siguiente relé →",
    "v2.r04.previous_relay": "← Relé anterior",
    "v2.r04.subtitle": "Revolución móvil — Velocidad e imperio",
    "v2.r04.title": "Relé 4: Horse",
    "v2.r05.active_webs": "Redes activas",
    "v2.r05.counterparts_title": "Contraparte: Roads",
    "v2.r05.four_pillars": "Cuatro pilares",
    "v2.r05.historical_significance": "Significado histórico",
    "v2.r05.next_relay": "Siguiente relé →",
    "v2.r05.previous_relay": "← Relé anterior",
    "v2.r05.subtitle": "Red conectada — Las arterias del imperio",
    "v2.r05.title": "Relé 5: Roads",
    "v2.r06.active_webs": "Redes activas",
    "v2.r06.counterparts_title": "Contraparte: Ships",
    "v2.r06.four_pillars": "Cuatro pilares",
    "v2.r06.historical_significance": "Significado histórico",
    "v2.r06.next_relay": "Siguiente relé →",
    "v2.r06.previous_relay": "← Relé anterior",
    "v2.r06.subtitle": "Autopista oceánica — Red global de comercio",
    "v2.r06.title": "Relé 6: Ships",
    "v2.r07.active_webs": "Redes activas",
    "v2.r07.counterparts_title": "Contraparte: Rail",
    "v2.r07.four_pillars": "Cuatro pilares",
    "v2.r07.historical_significance": "Significado histórico",
    "v2.r07.next_relay": "Siguiente relé →",
    "v2.r07.previous_relay": "← Relé anterior",
    "v2.r07.subtitle": "Columna vertebral de acero — Conexión industrial",
    "v2.r07.title": "Relé 7: Rail",
    "v2.r08.active_webs": "Redes activas",
    "v2.r08.counterparts_title": "Contraparte: Loom",
    "v2.r08.four_pillars": "Cuatro pilares",
    "v2.r08.historical_significance": "Significado histórico",
    "v2.r08.next_relay": "Siguiente relé →",
    "v2.r08.previous_relay": "← Relé anterior",
    "v2.r08.subtitle": "Red tejida — Infraestructura de información",
    "v2.r08.title": "Relé 8: Loom",
    "v2.r09.active_webs": "Redes activas",
    "v2.r09.counterparts_title": "Contraparte: Engine",
    "v2.r09.four_pillars": "Cuatro pilares",
    "v2.r09.historical_significance": "Significado histórico",
    "v2.r09.next_relay": "Siguiente relé →",
    "v2.r09.previous_relay": "← Relé anterior",
    "v2.r09.subtitle": "Revolución energética — Mundo mecanizado",
    "v2.r09.title": "Relé 9: Engine",
    "v2.r10.active_webs": "Redes activas",
    "v2.r10.counterparts_title": "Contraparte: AAA",
    "v2.r10.four_pillars": "Cuatro pilares",
    "v2.r10.historical_significance": "Significado histórico",
    "v2.r10.next_relay": "Siguiente relé →",
    "v2.r10.previous_relay": "← Relé anterior",
    "v2.r10.subtitle": "Aviación, átomo, automatización — La trinidad moderna",
    "v2.r10.title": "Relé 10: AAA",
    "v2.r11.active_webs": "Redes activas",
    "v2.r11.counterparts_title": "Contraparte: Programmable Humans",
    "v2.r11.four_pillars": "Cuatro pilares",
    "v2.r11.historical_significance": "Significado histórico",
    "v2.r11.next_relay": "Siguiente relevo →",
    "v2.r11.previous_relay": "← Relevo anterior",
    "v2.r11.subtitle": "Humanos en red — Conexión digital",
    "v2.r11.title": "Relevo 11: Nodo humano",
    "v2.r12.active_webs": "Redes activas",
    "v2.r12.counterparts_title": "Contrapartes: Conciencia",
    "v2.r12.four_pillars": "Cuatro pilares",
    "v2.r12.historical_significance": "Significado histórico",
    "v2.r12.next_relay": "Siguiente relevo →",
    "v2.r12.previous_relay": "← Relevo anterior",
    "v2.r12.subtitle": "Torus — La forma definitiva de infraestructura",
    "v2.r12.title": "Relevo 12: Conciencia",
    "v3.index.experience_title": "Experiencia de relevo",
    "v3.index.title": "Volumen 3: Juego",
    "vol1.index.desc": "Explora 12,000 años de desarrollo de infraestructura a través de 12 relevos de la civilización. Cada relevo representa un salto fundamental en la capacidad humana.",
    "vol1.index.subtitle": "Historia y Contexto — Narrativa",
    "vol1.index.title": "Volumen 1: Perspectivas",
    "vol2.index.desc": "Marco práctico, análisis comparativo y modelos estratégicos para cada relevo. Comparación profunda de los métodos Occidental, Oriental y Outrider.",
    "vol2.index.subtitle": "Marco Estratégico — Expansión",
    "vol2.index.title": "Volumen 2: Guía",
    "vol3.index.desc": "Plataforma de aprendizaje guiado Motor de la Realidad. Aplica conceptos en un entorno de simulación dinámica.",
    "vol3.index.subtitle": "Simulación y Práctica — Aplicación",
    "vol3.index.title": "Volumen 3: Juego",
    // ============================================
    // MISSING KEYS - ADDED BY TRANSLATION GENERATOR
    // ============================================
    "home.guide.btn": "LEER LA GUÍA",
    "home.guide.title": "VOLUMEN 2: LA GUÍA",
    "masters.subtitle": "Guías espirituales históricos que cabalgan junto a cada nivel — No se cuentan en la jerarquía 6+1, estos compañeros intelectuales abarcan todos los modos, todos los relevos, los 12.000 años. Son las voces del juego, las citas en las paredes, la sabiduría que conecta el fuego con el toro.",
    "masters.title": "MAESTROS",
    "nav.glossary": "GLOSARIO",
    "nav.masters": "MAESTROS",
    "nav.olympiad": "OLIMPIADA",
    "nav.starthere": "EMPIEZA AQUÍ",
    "precis.relay.relay_10_orbit": "RELEVO 11: ÓRBITA",
    "precis.relay.relay_11_human_nodes": "RELEVO 12: NODOS HUMANOS",
    "precis.relay.relay_1_tree": "RELEVO 2: ÁRBOL",
    "precis.relay.relay_2_river": "RELEVO 3: RÍO",
    "precis.relay.relay_3_horse": "RELEVO 4: CABALLO",
    "precis.relay.relay_4_roads": "RELEVO 5: CAMINOS",
    "precis.relay.relay_5_ships": "RELEVO 6: BARCOS",
    "precis.relay.relay_6_loom": "RELEVO 7: TELAR",
    "precis.relay.relay_8_engine": "RELEVO 9: MOTOR",
    "precis.relay.relay_9_aaa": "RELEVO 10: TRÍADA AAA",
    "tax.cta": "ENCUENTRA TU LUGAR EN EL ÁRBOL",
    "tax.cta.sub": "Cada especie comienza con un solo organismo. Cada movimiento comienza con un solo pionero.",
    "tax.footer.cc": "CC BY-NC-SA 4.0",
    "tax.parallel.institutions.desc": "Organisations that can be challenged, engaged, or partnered with. Universities, UN bodies, professional societies, government agencies, NGOs, and corporations. They sit outside the contributor hierarchy but are the targets of the intelligence network and the Challenge Board.",
    "tax.parallel.institutions.title": "&#x1F3DB; Institutions &mdash; The Challenge Map",
    "tax.parallel.institutions.who": "UNESCO &bull; World Bank &bull; ASCE &bull; ICE &bull; MIT &bull; Khan Academy &bull; Meta &bull; National Geographic",
    "tax.parallel.outriders.desc": "Historical and philosophical figures who ride alongside every tier as intellectual companions. Not counted in the 6+1 &mdash; they exist across all levels, all modes, all time periods. They are the voices in the game, the quotes on the walls, the wisdom that connects 12,000 years of infrastructure.",
    "tax.parallel.outriders.title": "&#x1F3C7; Outriders &mdash; Spirit Guides",
    "tax.parallel.outriders.who": "Laozi &bull; Sun Tzu &bull; Confucius &bull; Vitruvius &bull; Leonardo da Vinci &bull; Isambard Kingdom Brunel &bull; Nikola Tesla &bull; Ada Lovelace",
    "tax.parallel.title": "Pistas Paralelas (Fuera de la Jerarquía)",
    "tax.plus1.desc": "En biología, la Especie es la clasificación más específica — el organismo individual. En IAAI, el +1 son los mil millones de aprendices",
    "tax.plus1.subtitle": "12,1% de la Humanidad — El Punto de Inflexión para la Alfabetización en Infraestructura",
    "tax.plus1.target": "OBJETIVO: 1.000.000.000",
    "tax.plus1.title": "EL +1 — ESPECIE",
    "tax.quote": "\"De la misma manera que toda vida comparte un ancestro común, toda infraestructura comparte un propósito común — servir a la civilización.\"",
    "tax.rank.class": "Clase",
    "tax.rank.domain": "Dominio",
    "tax.rank.family": "Familia",
    "tax.rank.genus": "Género",
    "tax.rank.kingdom": "Reino",
    "tax.rank.order": "Orden",
    "tax.rank.phylum": "Filo",
    "tax.table.biology": "Biología",
    "tax.table.count": "Cantidad",
    "tax.table.iaai": "IAAI",
    "tax.table.suntzu": "Inteligencia (INT)",
    "tax.tier1.analogy": "Biology: Domain (Eukarya) &bull; Military: Commander-in-Chief &bull; Architecture: Master Builder",
    "tax.tier1.desc": "The singular origin point. Conceived the 12-relay framework, wrote the trilogy, designed the game, and built the platform. Like Domain in biology &mdash; the broadest, most fundamental classification from which everything else branches.",
    "tax.tier1.name": "FUNDADOR",
    "tax.tier1.title": "El Arquitecto",
    "tax.tier1.who": "Ir. Nigel T. Dearden &mdash; CEng MICE MHKIE",
    "tax.tier2.analogy": "Biology: Kingdom (Animalia) &bull; Military: General Staff &bull; Sun Tzu: The Five Essentials",
    "tax.tier2.desc": "The inner circle. Industry leaders, capital strategists, and institutional connectors who shape direction, open doors, and bridge the gap between vision and execution. By invitation or nomination only.",
    "tax.tier2.name": "ASESORES",
    "tax.tier2.title": "Consejo Estratégico",
    "tax.tier2.who": "Michael Wu (COO) &bull; Henry Leong (CFO) &bull; Frank Sheu (CTO) &bull; Stephen Markscheid (Strategic Advisor)",
    "tax.tier3.analogy": "Biology: Phylum (Chordata) &bull; Military: Intelligence Corps &bull; Academia: Peer Review Board",
    "tax.tier3.desc": "Engineers, professors, and researchers who verify technical accuracy, map content to university curricula, and provide the academic credibility that transforms a game into an educational standard. The peer-review layer.",
    "tax.tier3.name": "ACADÉMICOS",
    "tax.tier3.title": "Validadores Académicos",
    "tax.tier3.who": "Target: Engineering faculties, infrastructure researchers, curriculum designers",
    "tax.tier4.analogy": "Biology: Class (Mammalia) &bull; Military: Field Officers &bull; Diplomacy: Cultural Attach&eacute;s",
    "tax.tier4.desc": "Native-fluency contributors who review and correct AI translations against real usage. 10 per language block across 8 languages. They ensure infrastructure literacy speaks authentically in every tongue. Credited contributors with their names on the work.",
    "tax.tier4.name": "EMBAJADORES",
    "tax.tier4.title": "Líderes de Idiomas",
    "tax.tier4.who": "Target: 10 per block &times; 8 blocks = 80 Ambassadors worldwide",
    "tax.tier5.analogy": "Biology: Order (Primates) &bull; Military: HUMINT (Human Intelligence) &bull; Scouts &amp; Reconnaissance",
    "tax.tier5.desc": "The first wave. 2&ndash;3 per language block who play the game, report bugs, validate content, and provide the ground-truth feedback that shapes the platform before public release. The HUMINT assets of the intelligence network — human intelligence on the ground.",
    "tax.tier5.name": "PIONEROS",
    "tax.tier5.title": "Beta Testers y Exploradores",
    "tax.tier5.who": "Currently recruiting &mdash; 3 active across EN and CN blocks",
    "tax.tier6.analogy": "Biology: Family (Hominidae) &bull; Military: The Rank and File &bull; Gaming: The Player Base",
    "tax.tier6.desc": "Everyone who plays The Reality Engine. From casual explorers to completionists who master all 12 relays across all 4 modes. They generate the data, the engagement, and the democratic nominations that power the Challenge Board. The lifeblood of the platform.",
    "tax.tier6.name": "JUGADORES",
    "tax.tier6.title": "La Comunidad de Juego",
    "tax.tier6.who": "Target: 1M players by Year 2 &bull; Currently: 21 (beta)",
    "tax.tier7.analogy": "Biology: Genus (Homo) &bull; Military: ELINT (Electronic Intelligence) &bull; Logistics &amp; Supply",
    "tax.tier7.desc": "Those who fund the mission &mdash; from individual Kickstarter backers to institutional patrons (UNESCO, National Geographic, universities). They don't play or translate; they enable. Challenged by Players, engaged by Advisors. The ELINT channel of the intelligence network — converting institutional signals into engagement.",
    "tax.tier7.name": "PATROCINADORES",
    "tax.tier7.title": "Apoyo Financiero e Institucional",
    "tax.tier7.who": "Target: $500K seed &bull; Challenged: UNESCO, NatGeo, NASA, Royal Society, MIT OCW, Khan Academy",
    "v1.r01.continuity": "CONTINUIDAD",
    "v1.r01.energy_web": "RED DE ENERGÍA",
    "v1.r01.infrastructure": "INFRAESTRUCTURA",
    "v1.r01.knowledge_web": "RED DE CONOCIMIENTO",
    "v1.r01.threats": "AMENAZAS",
    "v1.r01.unification": "UNIFICACIÓN",
    "v1.r02.continuity": "CONTINUIDAD",
    "v1.r02.energy_web": "RED DE ENERGÍA",
    "v1.r02.infrastructure": "INFRAESTRUCTURA",
    "v1.r02.knowledge_web": "RED DE CONOCIMIENTO",
    "v1.r02.threats": "AMENAZAS",
    "v1.r02.unification": "UNIFICACIÓN",
    "v1.r03.continuity": "CONTINUIDAD",
    "v1.r03.energy_web": "RED DE ENERGÍA",
    "v1.r03.infrastructure": "INFRAESTRUCTURA",
    "v1.r03.knowledge_web": "RED DE CONOCIMIENTO",
    "v1.r03.threats": "AMENAZAS",
    "v1.r03.unification": "UNIFICACIÓN",
    "v1.r04.continuity": "CONTINUIDAD",
    "v1.r04.energy_web": "RED DE ENERGÍA",
    "v1.r04.infrastructure": "INFRAESTRUCTURA",
    "v1.r04.threats": "AMENAZAS",
    "v1.r04.unification": "UNIFICACIÓN",
    "v1.r05.consciousness_web": "RED DE CONCIENCIA",
    "v1.r05.continuity": "CONTINUIDAD",
    "v1.r05.infrastructure": "INFRAESTRUCTURA",
    "v1.r05.knowledge_web": "RED DE CONOCIMIENTO",
    "v1.r05.threats": "AMENAZAS",
    "v1.r05.unification": "UNIFICACIÓN",
    "v1.r06.consciousness_web": "RED DE CONCIENCIA",
    "v1.r06.continuity": "CONTINUIDAD",
    "v1.r06.infrastructure": "INFRAESTRUCTURA",
    "v1.r06.knowledge_web": "RED DE CONOCIMIENTO",
    "v1.r06.threats": "AMENAZAS",
    "v1.r06.unification": "UNIFICACIÓN",
    "v1.r07.continuity": "CONTINUIDAD",
    "v1.r07.energy_web": "RED DE ENERGÍA",
    "v1.r07.infrastructure": "INFRAESTRUCTURA",
    "v1.r07.knowledge_web": "RED DE CONOCIMIENTO",
    "v1.r07.threats": "AMENAZAS",
    "v1.r07.unification": "UNIFICACIÓN",
    "v1.r08.consciousness_web": "RED DE CONCIENCIA",
    "v1.r08.continuity": "CONTINUIDAD",
    "v1.r08.energy_web": "RED DE ENERGÍA",
    "v1.r08.infrastructure": "INFRAESTRUCTURA",
    "v1.r08.knowledge_web": "RED DE CONOCIMIENTO",
    "v1.r08.threats": "AMENAZAS",
    "v1.r08.unification": "UNIFICACIÓN",
    "v1.r09.continuity": "CONTINUIDAD",
    "v1.r09.energy_web": "RED DE ENERGÍA",
    "v1.r09.infrastructure": "INFRAESTRUCTURA",
    "v1.r09.knowledge_web": "RED DE CONOCIMIENTO",
    "v1.r09.threats": "AMENAZAS",
    "v1.r09.unification": "UNIFICACIÓN",
    "v1.r10.consciousness_web": "RED DE CONCIENCIA",
    "v1.r10.continuity": "CONTINUIDAD",
    "v1.r10.energy_web": "RED DE ENERGÍA",
    "v1.r10.infrastructure": "INFRAESTRUCTURA",
    "v1.r10.knowledge_web": "RED DE CONOCIMIENTO",
    "v1.r10.threats": "AMENAZAS",
    "v1.r10.unification": "UNIFICACIÓN",
    "v1.r11.consciousness_web": "RED DE CONCIENCIA",
    "v1.r11.continuity": "CONTINUIDAD",
    "v1.r11.infrastructure": "INFRAESTRUCTURA",
    "v1.r11.knowledge_web": "RED DE CONOCIMIENTO",
    "v1.r11.threats": "AMENAZAS",
    "v1.r11.unification": "UNIFICACIÓN",
    "v1.r12.consciousness_web": "RED DE CONCIENCIA",
    "v1.r12.continuity": "CONTINUIDAD",
    "v1.r12.infrastructure": "INFRAESTRUCTURA",
    "v1.r12.knowledge_web": "RED DE CONOCIMIENTO",
    "v1.r12.threats": "AMENAZAS",
    "v1.r12.unification": "UNIFICACIÓN",
    "oly.title": "LA OLIMPIADA DE INFRAESTRUCTURA",
    "oly.stat.blocks": "Bloques Lingüísticos",
    "oly.stat.categories": "Categorías de Competición",
    "oly.stat.universities": "Universidades en el Mundo",
    "oly.stat.xpcap": "Tope XP (Maestro Tejedor)",
    "oly.stat.people": "Personas Alcanzadas",
    "oly.stat.gap": "Brecha de Infraestructura",
    "oly.flywheel.title": "El Volante — Cómo la Olimpiada Crece Sola",
    "oly.flywheel.players": "Los Jugadores Compiten",
    "oly.flywheel.professionals": "Los Profesionales Validan",
    "oly.flywheel.patrons": "Los Patrocinadores Apoyan",
    "oly.flywheel.platform": "La Plataforma Escala",
    "oly.medal.title": "Medallero en Vivo — Naciones Compitiendo en Gestión Civilizacional",
    "oly.th.nation": "Nación",
    "oly.th.blocks": "Bloque(s)",
    "oly.th.pop": "Pob. (M)",
    "oly.th.gamers": "Jugadores (M)",
    "oly.th.story": "Historia de Infraestructura",
    "oly.th.total": "Total",
    "oly.th.status": "Estado",
    "oly.rogue.title": "EQUIPOS ROGUE — EL TALENTO NO AFILIADO",
    "oly.categories.title": "Categorías de Competición — Seis Pilares de Infraestructura Civilizacional",
    "oly.pipeline.unis": "Universidades en el Mundo",
    "oly.pipeline.students": "Estudiantes de Ingeniería",
    "oly.pipeline.firms": "Principales Firmas de IC",
    "oly.pipeline.govts": "Gobiernos Nacionales",
    "oly.sponsor.title": "Niveles de Patrocinio — Apoya un Equipo Nacional",
    "oly.sponsor.gold": "Patrocinador Oro",
    "oly.sponsor.silver": "Patrocinador Plata",
    "oly.sponsor.bronze": "Patrocinador Bronce",
    "oly.sponsor.patron": "Mecenas",
    "oly.form.register.title": "REGISTRA TU EQUIPO UNIVERSITARIO",
    "oly.form.sponsor.title": "CONSULTA DE PATROCINIO",
    "nav.behind": "DETRÁS DE LA TESIS",

    // SDG Alignment Section
    "sdg.title": "OBJETIVOS DE DESARROLLO SOSTENIBLE — ALINEACIÓN",
    "sdg.subtitle": "Cómo el currículo de 12 relevos de IAAI se alinea con los Objetivos de Desarrollo Sostenible de la ONU",
    "sdg.iconCaption": "El contenido de IAAI aborda directamente 11 de los 17 Objetivos de Desarrollo Sostenible. Cada icono enlaza a la página oficial de la ONU.",
    "sdg.col.relay": "RELEVO IAAI",
    "sdg.col.sdgGoals": "OBJETIVO(S) ODS",
    "sdg.col.alignment": "FUNDAMENTO DE ALINEACIÓN",
    "sdg.col.5p": "CATEGORÍA 5P",
    "sdg.r1.rationale": "Las redes viales son el sistema circulatorio del desarrollo económico. Sin carreteras, no hay acceso al mercado ni servicios de emergencia.",
    "sdg.r2.rationale": "El ferrocarril es la columna vertebral del transporte masivo y la carga. Menores emisiones por tonelada-km que la carretera.",
    "sdg.r3.rationale": "Los puertos conectan naciones al comercio global. El 90% de los bienes mundiales se mueven por mar.",
    "sdg.r4.rationale": "La infraestructura aeronáutica permite la conectividad global, el comercio, el turismo y la respuesta de emergencia.",
    "sdg.r5.rationale": "El agua limpia es la infraestructura más fundamental. 2.200 millones de personas aún carecen de agua potable segura.",
    "sdg.r6.rationale": "El saneamiento previene enfermedades, protege las fuentes de agua y preserva la dignidad humana.",
    "sdg.r7.rationale": "La infraestructura energética determina si las naciones se industrializan limpiamente o repiten la dependencia de combustibles fósiles.",
    "sdg.r8.rationale": "Las telecomunicaciones conectan a las personas con la educación, los mercados y la gobernanza. La brecha digital es una brecha de infraestructura.",
    "sdg.r9.rationale": "La gestión de residuos es el espejo del consumo. Las economías circulares requieren infraestructura de recolección y reciclaje.",
    "sdg.r10.rationale": "La infraestructura sanitaria — hospitales, clínicas, cadenas de suministro — determina si las poblaciones sobreviven a las pandemias.",
    "sdg.r11.rationale": "La infraestructura educativa — escuelas, universidades, bibliotecas — es el mecanismo de transmisión del conocimiento entre generaciones.",
    "sdg.r12.rationale": "La infraestructura digital — centros de datos, fibra, nube — es el equivalente del siglo XXI de carreteras y puertos.",
    "sdg.5pTitle": "LAS 5P — PERSONAS, PLANETA, PROSPERIDAD, PAZ, ALIANZAS",
    "sdg.5pText": "La ONU enmarca los 17 ODS a través de cinco pilares conocidos como las 5P. La infraestructura es el mecanismo por el cual las civilizaciones cumplen con las cinco P.",
    "sdg.visitUN": "VISITAR EL SITIO OFICIAL DE ODS DE LA ONU →",
    "sdg.disclaimerTitle": "Descargo de responsabilidad:",
    "sdg.disclaimerText": "El contenido de esta publicación no ha sido aprobado por las Naciones Unidas y no refleja las opiniones de las Naciones Unidas ni de sus funcionarios o Estados Miembros.",
    "home.dominion.title": "Perdiendo el Dominio — La Crisis de Convergencia",
    "home.dominion.text": "El sexto reinicio no vendrá del espacio. Ya está aquí — en la transferencia de la toma de decisiones, el diseño y la gobernanza de los sistemas humanos a los sistemas de máquinas. No extinción. Desplazamiento. La infraestructura que sostuvo la civilización durante 12.000 años converge ahora más rápido de lo que cualquier generación puede absorber. Esta es la crisis de convergencia. El Episodio 2 traza la arquitectura de la continuidad humana.",
    "home.fw.ele_planetary": "Reloj Planetario ELE — Tierra: 4.500 millones de años. Cinco reinicios. ELE 6 es civilizacional — 2050. Actúa ahora o pierde el dominio.",
    "home.fw.continuity_grid": "La Cuadrícula de Continuidad Completa — Si la historia humana fuera un libro de 1.200 páginas. 24 filas = 24 horas. La cuadrícula ES el reloj. Fila 24 = la última hora.",
    "home.fw.row24": "Fila 24 Expandida — La Última Hora. 12.000 años (10.000 a.C. → 2050 d.C.). 500 generaciones. La única fila donde la humanidad aprovecha los relevos. Siete Eruditos. Seis relevos en 246 años. Todos siguen funcionando.",
    "home.fw.relay_cone": "El Cono de Relevos — 500 generaciones de civilización comprimidas en 12 relevos de infraestructura. Vista lateral, vista superior y los Siete Eruditos. Los primeros seis relevos abarcan 11.500 años; los últimos seis se comprimen en 246 años.",
    "home.ascent.title": "El Ascenso a la Consciencia",
    "home.ascent.subtitle": "Relevo 12 y Más Allá — La Tesis Civilizacional Hasta 2050 como Medianoche",
    "home.ascent.text": "Aquí es donde reside la pieza civilizacional. De Calorías a Consciencia — Una Odisea de Infraestructura traza 12.000 años a través de 12 relevos, 7 eruditos, 5 redes y 3 grandes imperios. El Ascenso a la Consciencia es el Relevo 12 y más allá: el punto de transferencia donde la inteligencia biológica se encuentra con su propia infraestructura. Cinco niveles de linaje intelectual — de Homero a la generación Aplicada — convergen en una sola pregunta: ¿quién lleva el relevo adelante? Las implicaciones teológicas son profundas. Perdiendo el Dominio enmarca la crisis; Contrafuerza: Partes, Medidas y Equilibrio proporciona el cálculo del ingeniero. El 8º Erudito sigue siendo la búsqueda abierta — el siguiente nodo en una cadena de 3.500 años de sabiduría fundacional.",
    "home.ascent.source": "LINAJE 5 NIVELES — Un Relevo Intelectual de 3.500 Años Hacia el 8º Erudito — Marco de Verdad iAAi"
};
