// ============================================
// INFRASTRUCTURE ACADEMY - CHINESE TRANSLATIONS
// 基础设施学院 - 中文翻译
// ============================================
// This file is loaded by i18n.js as a translation overlay.
// English HTML content is NEVER modified. This provides CN text swaps.

window.IA_LANG_CN = {

    // ============================================
    // SHARED NAVIGATION & HEADER
    // ============================================
    "nav.home": "首页",
    "nav.precis": "执行摘要",
    "nav.framework": "框架",
    "nav.resources": "资源",
    "nav.documents": "文献",
    "nav.author": "作者",
    "nav.ep1": "集一：视角",
    "nav.ep2": "集一：指南",
    "nav.ep3": "集一：游戏",
    "nav.supplements": "补充材料",
    "header.title": "基础设施学院",
    "header.subtitle": "基础设施奥德赛：第一集 — 从卡路里到意识",

    // ============================================
    // FOOTER
    // ============================================
    "footer.copyright": "&copy; 2026 基础设施学院。版权所有。永恒保存知识。",
    "footer.ep1": "第一集：大地基础",
    "footer.ep2": "第二集：灰色竞技场",
    "footer.ep3": "第三集：宇宙尺度",

    // ============================================
    // SITE.HTML (HOME PAGE)
    // ============================================
    "home.title": "基础设施奥德赛",
    "home.subtitle": "土木工程师的视角与指南 — 第一集：从卡路里到意识",
    "home.author": "作者：迪尔登工程师 (Ir. Nigel T. Dearden)",
    "home.hero.caption": "从卡路里到意识：基础设施奥德赛 — 文明接力",
    "home.cover.front": "正面与背面封面 — 第一集：大地基础",
    "home.cover.interior": "内页展示 — 第一章：火的接力（第一部分与第二部分）",
    "home.cover.portrait": "文明接力 — 从树到环面的12章",

    // Framework section
    "home.framework.title": "完整框架",
    "home.framework.subtitle": "通过土木工程师视角的基础设施教育综合系统思维",
    "home.framework.motto": "基础设施教育：系统思维，而非死记硬背",
    "home.framework.journey": "旅程即是工作。",
    "home.framework.modes.caption": "三种模式 — 横跨12,000年的西方、东方与游骑兵",
    "home.framework.relays.caption": "12个文明接力 — 从火到意识",
    "home.framework.silk.caption": "丝绸之路悖论 — 游骑兵控制了贸易路线，却未建造任何基础设施",

    // Volumes section
    "home.vol1.title": "卷一：视角",
    "home.vol1.subtitle": "历史与背景 — 故事",
    "home.vol1.desc": "叙事基础：横跨12,000年人类基础设施发展的12个文明接力。从掌握火到意识的环面。",
    "home.vol1.btn": "阅读视角",
    "home.vol2.title": "卷二：指南",
    "home.vol2.subtitle": "战略框架 — 扩展",
    "home.vol2.desc": "实践框架：西方/东方/游骑兵比较方法、4C分析，以及理解基础设施作为文明DNA的战略模型。",
    "home.vol2.btn": "阅读指南",
    "home.supplements.title": "卷二：4个补充材料",
    "home.s1.title": "S1：识别",
    "home.s1.desc": "基础概念 — 三种模式、元素时钟、道路与船舶时间线",
    "home.s2.title": "S2：理解",
    "home.s2.desc": "技术扩散 — 笔作为基础设施、书写系统",
    "home.s3.title": "S3：管理与控制",
    "home.s3.desc": "实施 — 每个接力的管理图表",
    "home.s4.title": "S4：论文与愿景",
    "home.s4.desc": "对应方 — 每个接力的西方、游骑兵与东方比较",
    "home.supplements.btn": "查看补充材料",

    // Challenge section
    "home.challenge.title": "我们应对的挑战",
    "home.challenge.subtitle": "基础设施教育是碎片化的、抽象的，与现实世界的影响脱节。",
    "home.challenge.stat1.num": "70%",
    "home.challenge.stat1.desc": "的课程缺乏跨学科整合",
    "home.challenge.stat2.num": "65%",
    "home.challenge.stat2.desc": "的学生感到对实际应用准备不足",
    "home.challenge.stat3.num": "45%",
    "home.challenge.stat3.desc": "报告系统级思维接触有限",
    "home.challenge.stat4.num": "80%",
    "home.challenge.stat4.desc": "的雇主认为项目准备存在技能差距",
    "home.challenge.stat5.num": "30%",
    "home.challenge.stat5.desc": "的项目整合了社区或环境影响指标",
    "home.challenge.stat6.num": "90%",
    "home.challenge.stat6.desc": "的基础设施项目因实践知识差距而延误",
    "home.challenge.urgent": "紧迫需求：为未来准备就绪的基础设施专业人才搭建桥梁",

    // Trilogy section
    "home.trilogy.title": "三部曲愿景",
    "home.ep1.title": "第一集",
    "home.ep1.subtitle": "大地基础",
    "home.ep1.desc": "从卡路里到意识 — 从火到环面的12个接力",
    "home.ep1.btn": "已发布",
    "home.ep2.title": "第二集",
    "home.ep2.subtitle": "现实引擎 — 灰色竞技场",
    "home.ep2.desc": "控制论、人工智能与智能系统",
    "home.ep2.btn": "即将推出",
    "home.ep3.title": "第三集",
    "home.ep3.subtitle": "管理与更新 — 宇宙尺度",
    "home.ep3.desc": "行星、太阳系与银河系管理",
    "home.ep3.btn": "即将推出",

    // Media section
    "home.media.title": "媒体",
    "home.media.trailer": "快照预告片",
    "home.media.calories": "从卡路里到意识",
    "home.media.engine": "现实引擎 — 引导学习平台",
    "home.media.river": "河流平原电影",

    // Knowledge Web section
    "home.kw.title": "知识网络：文字作为基础设施",
    "home.kw.subtitle": "书写的全面历史 — 从会计代币到数字时代。笔作为终极基础设施接力。",

    // Game CTA section
    "home.game.title": "卷三：游戏",
    "home.game.desc": "准备好应用所学了吗？进入现实引擎 — 沉浸式学习平台，在这里你将成为基础设施工程师。",
    "home.game.cta.title": "进入游戏",
    "home.game.cta.sub": "卷三：现实引擎 — 引导学习平台",
    "home.game.note": "模拟与实践：在动态环境中应用概念",

    // About Archive section
    "home.archive.title": "关于此档案馆",
    "home.archive.p1": "基础设施学院是一个数字档案馆，保存着《基础设施奥德赛》的完整知识资产 — 一堂横跨12,000年人类基础设施发展的文明大师课。本网站确保知识永恒保存，供全球学者、工程师和学习者使用。",
    "home.archive.p2": "所有内容、可视化和框架都在此集成，便于导航和发现。这是人类从卡路里到意识崛起的永恒记录，由笔刻入数字永恒。",

    // ============================================
    // EXECUTIVE PRÉCIS
    // ============================================
    "precis.title": "执行摘要",
    "precis.subtitle": "基础设施奥德赛 — 战略概览",

    // ============================================
    // FRAMEWORK PAGE
    // ============================================
    "framework.title": "完整框架",
    "framework.subtitle": "综合系统思维方法论",
    "framework.modes.title": "三种文明模式",
    "framework.modes.west": "西方模式",
    "framework.modes.west.desc": "不连续/建造型 — 亚历山大大帝原型",
    "framework.modes.east": "东方模式",
    "framework.modes.east.desc": "连续/建造型 — 秦始皇原型",
    "framework.modes.outrider": "游骑兵模式",
    "framework.modes.outrider.desc": "半连续/临时工程 — 成吉思汗原型",
    "framework.relays.title": "12个文明接力",
    "framework.4cs.title": "4C分析框架",
    "framework.4cs.context": "背景",
    "framework.4cs.challenge": "挑战",
    "framework.4cs.consequence": "后果",
    "framework.4cs.continuum": "连续体",

    // ============================================
    // RELAY NAMES (used across all volumes)
    // ============================================
    "relay.1.name": "接力1：火",
    "relay.1.subtitle": "原始火花 — 能量掌握的开始",
    "relay.2.name": "接力2：树",
    "relay.2.subtitle": "活的建筑 — 自然作为工程",
    "relay.3.name": "接力3：河流",
    "relay.3.subtitle": "水利文明 — 液体基础设施",
    "relay.4.name": "接力4：马",
    "relay.4.subtitle": "移动革命 — 速度与帝国",
    "relay.5.name": "接力5：道路",
    "relay.5.subtitle": "连接的网络 — 帝国的动脉",
    "relay.6.name": "接力6：船舶",
    "relay.6.subtitle": "海洋高速公路 — 全球贸易网络",
    "relay.7.name": "接力7：铁路",
    "relay.7.subtitle": "钢铁脊柱 — 工业连接",
    "relay.8.name": "接力8：织机",
    "relay.8.subtitle": "编织的网络 — 信息基础设施",
    "relay.9.name": "接力9：引擎",
    "relay.9.subtitle": "动力革命 — 机械化世界",
    "relay.10.name": "接力10：AAA三元组",
    "relay.10.subtitle": "航空、原子、自动化 — 现代三位一体",
    "relay.11.name": "接力11：人类节点",
    "relay.11.subtitle": "网络化人类 — 数字连接",
    "relay.12.name": "接力12：意识",
    "relay.12.subtitle": "环面 — 基础设施的终极形态",
    "relay.prologue": "序言",
    "relay.epilogue": "尾声",

    // ============================================
    // VOLUME INDEX PAGES
    // ============================================
    "vol1.index.title": "卷一：视角",
    "vol1.index.subtitle": "历史与背景 — 故事",
    "vol1.index.desc": "通过12个文明接力探索12,000年的基础设施发展。每个接力代表人类能力的一次根本性飞跃。",
    "vol2.index.title": "卷二：指南",
    "vol2.index.subtitle": "战略框架 — 扩展",
    "vol2.index.desc": "每个接力的实践框架、比较分析和战略模型。西方、东方和游骑兵方法的深入比较。",
    "vol3.index.title": "卷三：游戏",
    "vol3.index.subtitle": "模拟与实践 — 应用",
    "vol3.index.desc": "现实引擎引导学习平台。在动态模拟环境中应用概念。",

    // ============================================
    // RESOURCES PAGE
    // ============================================
    "resources.title": "资源",
    "resources.subtitle": "参考资料、数据来源与进一步阅读",

    // ============================================
    // ABOUT AUTHOR PAGE
    // ============================================
    "author.title": "关于作者",
    "author.name": "迪尔登工程师 (Ir. Nigel T. Dearden)",
    "author.credentials": "特许工程师 (CEng)，英国土木工程师学会会员 (MICE)，香港工程师学会会员 (MHKIE)",
    "author.bio": "鄧禮祖工程師（Ir. Nigel T Dearden）是特許土木及結構工程師、特許水務及環境管理師，擁有33年以上香港基礎設施經驗。四元素顧問有限公司創辦人（2006年成立，www.4ecl.com）。BEng (Hon's), CEng, C.WEM, RPE (CSB), MICE, MHKIE, MCIWEM。",

    // ============================================
    // LIBRARY / DOCUMENTS PAGE
    // ============================================
    "library.title": "文献库",
    "library.subtitle": "完整的知识资产档案",

    // ============================================
    // SUPPLEMENTS PAGE
    // ============================================
    "supplements.title": "补充材料",
    "supplements.subtitle": "卷二的深度扩展材料",
    "supplements.s1": "补充1：识别",
    "supplements.s2": "补充2：理解",
    "supplements.s3": "补充3：管理与控制",
    "supplements.s4": "补充4：论文与愿景",

    // ============================================
    // COMMON UI ELEMENTS
    // ============================================
    "ui.read.more": "阅读更多",
    "ui.back": "返回",
    "ui.loading": "加载中...",
    "ui.error": "加载内容时出错。请重试。",
    "ui.available": "已发布",
    "ui.coming.soon": "即将推出",
    "ui.view": "查看",
    "ui.download": "下载",
    "ui.prev": "上一页",
    "ui.next": "下一页",

    // ============================================
    // TABLE OF CONTENTS
    // ============================================
    "toc.title": "目录",
    "toc.volume1": "卷一：视角 — 历史与背景",
    "toc.volume2": "卷二：指南 — 战略框架",
    "toc.volume3": "卷三：游戏 — 模拟与实践",
    "toc.prologue": "序言",
    "toc.epilogue": "尾声",
    "toc.chapter": "第",
    "toc.chapter.suffix": "章",

    // ============================================
    // ARCHIVE PAGES
    // ============================================
    "archive.title": "档案馆",
    "archive.subtitle": "完整的知识资产保存",
    "archive.documents": "文献",
    "archive.images": "图像",
    "archive.references": "参考资料",
    "archive.relays": "接力",
    "archive.supplements": "补充材料",

    // Home page extras
    "home.archive.architects": "命运的建筑师与伟大的统一者：亚历山大大帝、成吉思汗、秦始皇",

    // Additional nav items
    "nav.supplements": "补充材料",

    // Volume subtitles
    "header.subtitle.v2": "基础设施奥德赛：第一集 — 实践指南",
    "header.subtitle.v3": "基础设施奥德赛：第一集 — 现实引擎",

    // ============================================
    // RELAY CONTENT TRANSLATIONS (Auto-generated)
    // ============================================
    "section.4c_analysis": "4C分析",
    "section.active_webs": "活跃网络",
    "section.back_to_index": "返回目录",
    "section.challenge": "挑战",
    "section.communication_web": "通信网络",
    "section.comparative_analysis": "比较分析",
    "section.consciousness_web": "意识网络",
    "section.consequence": "后果",
    "section.context": "背景",
    "section.continuity": "连续性",
    "section.continuum": "连续体",
    "section.digital_web": "数字网络",
    "section.east_mode": "东方模式",
    "section.energy_web": "能量网络",
    "section.four_pillars": "四大支柱",
    "section.governance_web": "治理网络",
    "section.historical_significance": "历史意义",
    "section.impact": "影响：",
    "section.information_web": "信息网络",
    "section.infrastructure": "基础设施",
    "section.key_insights": "关键洞察",
    "section.knowledge_web": "知识网络",
    "section.legacy": "遗产：",
    "section.management_diagram": "管理图表",
    "section.military_web": "军事网络",
    "section.next_relay": "下一接力 →",
    "section.outrider_mode": "游骑兵模式",
    "section.previous_relay": "← 上一接力",
    "section.production_web": "生产网络",
    "section.strategic_framework": "战略框架",
    "section.the_counterparts": "对应方：",
    "section.the_first_infrastructure": "第一基础设施",
    "section.threats": "威胁",
    "section.timeline": "时间线：",
    "section.trade_web": "贸易网络",
    "section.transport_web": "运输网络",
    "section.unification": "统一",
    "section.west_mode": "西方模式",
    "special.conclusion": "结论",
    "special.epilogue": "尾声",
    "special.from_calories_to_consciousness": "从卡路里到意识",
    "special.prologue": "序言",
    "special.the_beginning": "开始",
    "special.the_journey_begins": "旅程开始",
    "special.the_journey_continues": "旅程继续",
    "v1.r01.active_webs": "活跃网络",
    "v1.r01.counterparts_title": "对应方：火",
    "v1.r01.four_pillars": "四大支柱",
    "v1.r01.historical_significance": "历史意义",
    "v1.r01.next_relay": "下一接力 →",
    "v1.r01.previous_relay": "← 上一接力",
    "v1.r01.subtitle": "原始火花 — 能量掌握的开始",
    "v1.r01.title": "接力1：火",
    "v1.r02.active_webs": "活跃网络",
    "v1.r02.counterparts_title": "对应方：树",
    "v1.r02.four_pillars": "四大支柱",
    "v1.r02.historical_significance": "历史意义",
    "v1.r02.next_relay": "下一接力 →",
    "v1.r02.previous_relay": "← 上一接力",
    "v1.r02.subtitle": "活的建筑 — 自然作为工程",
    "v1.r02.title": "接力2：树",
    "v1.r03.active_webs": "活跃网络",
    "v1.r03.counterparts_title": "对应方：河流",
    "v1.r03.four_pillars": "四大支柱",
    "v1.r03.historical_significance": "历史意义",
    "v1.r03.next_relay": "下一接力 →",
    "v1.r03.previous_relay": "← 上一接力",
    "v1.r03.subtitle": "水利文明 — 液体基础设施",
    "v1.r03.title": "接力3：河流",
    "v1.r04.active_webs": "活跃网络",
    "v1.r04.counterparts_title": "对应方：马",
    "v1.r04.four_pillars": "四大支柱",
    "v1.r04.historical_significance": "历史意义",
    "v1.r04.next_relay": "下一接力 →",
    "v1.r04.previous_relay": "← 上一接力",
    "v1.r04.subtitle": "移动革命 — 速度与帝国",
    "v1.r04.title": "接力4：马",
    "v1.r05.active_webs": "活跃网络",
    "v1.r05.counterparts_title": "对应方：道路",
    "v1.r05.four_pillars": "四大支柱",
    "v1.r05.historical_significance": "历史意义",
    "v1.r05.next_relay": "下一接力 →",
    "v1.r05.previous_relay": "← 上一接力",
    "v1.r05.subtitle": "连接的网络 — 帝国的动脉",
    "v1.r05.title": "接力5：道路",
    "v1.r06.active_webs": "活跃网络",
    "v1.r06.counterparts_title": "对应方：船舶",
    "v1.r06.four_pillars": "四大支柱",
    "v1.r06.historical_significance": "历史意义",
    "v1.r06.next_relay": "下一接力 →",
    "v1.r06.previous_relay": "← 上一接力",
    "v1.r06.subtitle": "海洋高速公路 — 全球贸易网络",
    "v1.r06.title": "接力6：船舶",
    "v1.r07.active_webs": "活跃网络",
    "v1.r07.counterparts_title": "对应方：铁路",
    "v1.r07.four_pillars": "四大支柱",
    "v1.r07.historical_significance": "历史意义",
    "v1.r07.next_relay": "下一接力 →",
    "v1.r07.previous_relay": "← 上一接力",
    "v1.r07.subtitle": "钢铁脊柱 — 工业连接",
    "v1.r07.title": "接力7：铁路",
    "v1.r08.active_webs": "活跃网络",
    "v1.r08.counterparts_title": "对应方：织机",
    "v1.r08.four_pillars": "四大支柱",
    "v1.r08.historical_significance": "历史意义",
    "v1.r08.next_relay": "下一接力 →",
    "v1.r08.previous_relay": "← 上一接力",
    "v1.r08.subtitle": "编织的网络 — 信息基础设施",
    "v1.r08.title": "接力8：织机",
    "v1.r09.active_webs": "活跃网络",
    "v1.r09.counterparts_title": "对应方：引擎",
    "v1.r09.four_pillars": "四大支柱",
    "v1.r09.historical_significance": "历史意义",
    "v1.r09.next_relay": "下一接力 →",
    "v1.r09.previous_relay": "← 上一接力",
    "v1.r09.subtitle": "动力革命 — 机械化世界",
    "v1.r09.title": "接力9：引擎",
    "v1.r10.active_webs": "活跃网络",
    "v1.r10.counterparts_title": "对应方：AAA三元组",
    "v1.r10.four_pillars": "四大支柱",
    "v1.r10.historical_significance": "历史意义",
    "v1.r10.next_relay": "下一接力 →",
    "v1.r10.previous_relay": "← 上一接力",
    "v1.r10.subtitle": "航空、原子、自动化 — 现代三位一体",
    "v1.r10.title": "接力10：AAA三元组",
    "v1.r11.active_webs": "活跃网络",
    "v1.r11.counterparts_title": "对应方：人类节点",
    "v1.r11.four_pillars": "四大支柱",
    "v1.r11.historical_significance": "历史意义",
    "v1.r11.next_relay": "下一接力 →",
    "v1.r11.previous_relay": "← 上一接力",
    "v1.r11.subtitle": "网络化人类 — 数字连接",
    "v1.r11.title": "接力11：人类节点",
    "v1.r12.active_webs": "活跃网络",
    "v1.r12.counterparts_title": "对应方：意识",
    "v1.r12.four_pillars": "四大支柱",
    "v1.r12.historical_significance": "历史意义",
    "v1.r12.next_relay": "下一接力 →",
    "v1.r12.previous_relay": "← 上一接力",
    "v1.r12.subtitle": "环面 — 基础设施的终极形态",
    "v1.r12.title": "接力12：意识",
    "v2.r01.active_webs": "活跃网络",
    "v2.r01.counterparts_title": "对应方：火",
    "v2.r01.four_pillars": "四大支柱",
    "v2.r01.historical_significance": "历史意义",
    "v2.r01.next_relay": "下一接力 →",
    "v2.r01.previous_relay": "← 上一接力",
    "v2.r01.subtitle": "原始火花 — 能量掌握的开始",
    "v2.r01.title": "接力1：火",
    "v2.r02.active_webs": "活跃网络",
    "v2.r02.counterparts_title": "对应方：树",
    "v2.r02.four_pillars": "四大支柱",
    "v2.r02.historical_significance": "历史意义",
    "v2.r02.next_relay": "下一接力 →",
    "v2.r02.previous_relay": "← 上一接力",
    "v2.r02.subtitle": "活的建筑 — 自然作为工程",
    "v2.r02.title": "接力2：树",
    "v2.r03.active_webs": "活跃网络",
    "v2.r03.counterparts_title": "对应方：河流",
    "v2.r03.four_pillars": "四大支柱",
    "v2.r03.historical_significance": "历史意义",
    "v2.r03.next_relay": "下一接力 →",
    "v2.r03.previous_relay": "← 上一接力",
    "v2.r03.subtitle": "水利文明 — 液体基础设施",
    "v2.r03.title": "接力3：河流",
    "v2.r04.active_webs": "活跃网络",
    "v2.r04.counterparts_title": "对应方：马",
    "v2.r04.four_pillars": "四大支柱",
    "v2.r04.historical_significance": "历史意义",
    "v2.r04.next_relay": "下一接力 →",
    "v2.r04.previous_relay": "← 上一接力",
    "v2.r04.subtitle": "移动革命 — 速度与帝国",
    "v2.r04.title": "接力4：马",
    "v2.r05.active_webs": "活跃网络",
    "v2.r05.counterparts_title": "对应方：道路",
    "v2.r05.four_pillars": "四大支柱",
    "v2.r05.historical_significance": "历史意义",
    "v2.r05.next_relay": "下一接力 →",
    "v2.r05.previous_relay": "← 上一接力",
    "v2.r05.subtitle": "连接的网络 — 帝国的动脉",
    "v2.r05.title": "接力5：道路",
    "v2.r06.active_webs": "活跃网络",
    "v2.r06.counterparts_title": "对应方：船舶",
    "v2.r06.four_pillars": "四大支柱",
    "v2.r06.historical_significance": "历史意义",
    "v2.r06.next_relay": "下一接力 →",
    "v2.r06.previous_relay": "← 上一接力",
    "v2.r06.subtitle": "海洋高速公路 — 全球贸易网络",
    "v2.r06.title": "接力6：船舶",
    "v2.r07.active_webs": "活跃网络",
    "v2.r07.counterparts_title": "对应方：铁路",
    "v2.r07.four_pillars": "四大支柱",
    "v2.r07.historical_significance": "历史意义",
    "v2.r07.next_relay": "下一接力 →",
    "v2.r07.previous_relay": "← 上一接力",
    "v2.r07.subtitle": "钢铁脊柱 — 工业连接",
    "v2.r07.title": "接力7：铁路",
    "v2.r08.active_webs": "活跃网络",
    "v2.r08.counterparts_title": "对应方：织机",
    "v2.r08.four_pillars": "四大支柱",
    "v2.r08.historical_significance": "历史意义",
    "v2.r08.next_relay": "下一接力 →",
    "v2.r08.previous_relay": "← 上一接力",
    "v2.r08.subtitle": "编织的网络 — 信息基础设施",
    "v2.r08.title": "接力8：织机",
    "v2.r09.active_webs": "活跃网络",
    "v2.r09.counterparts_title": "对应方：引擎",
    "v2.r09.four_pillars": "四大支柱",
    "v2.r09.historical_significance": "历史意义",
    "v2.r09.next_relay": "下一接力 →",
    "v2.r09.previous_relay": "← 上一接力",
    "v2.r09.subtitle": "动力革命 — 机械化世界",
    "v2.r09.title": "接力9：引擎",
    "v2.r10.active_webs": "活跃网络",
    "v2.r10.counterparts_title": "对应方：AAA三元组",
    "v2.r10.four_pillars": "四大支柱",
    "v2.r10.historical_significance": "历史意义",
    "v2.r10.next_relay": "下一接力 →",
    "v2.r10.previous_relay": "← 上一接力",
    "v2.r10.subtitle": "航空、原子、自动化 — 现代三位一体",
    "v2.r10.title": "接力10：AAA三元组",
    "v2.r11.active_webs": "活跃网络",
    "v2.r11.counterparts_title": "对应方：人类节点",
    "v2.r11.four_pillars": "四大支柱",
    "v2.r11.historical_significance": "历史意义",
    "v2.r11.next_relay": "下一接力 →",
    "v2.r11.previous_relay": "← 上一接力",
    "v2.r11.subtitle": "网络化人类 — 数字连接",
    "v2.r11.title": "接力11：人类节点",
    "v2.r12.active_webs": "活跃网络",
    "v2.r12.counterparts_title": "对应方：意识",
    "v2.r12.four_pillars": "四大支柱",
    "v2.r12.historical_significance": "历史意义",
    "v2.r12.next_relay": "下一接力 →",
    "v2.r12.previous_relay": "← 上一接力",
    "v2.r12.subtitle": "环面 — 基础设施的终极形态",
    "v2.r12.title": "接力12：意识",

    // ============================================
    // PAGE-SPECIFIC TRANSLATIONS
    // ============================================
    "precis.relay.epilogue": "尾声",
    "precis.relay.prologue": "序言",
    "precis.relay.relay_10_aaa": "接力10：AAA三元组",
    "precis.relay.relay_11_humans": "接力11：人类节点",
    "precis.relay.relay_12_torus": "接力12：环面",
    "precis.relay.relay_10_autoair": "接力10：汽车/航空",
    "precis.relay.relay_11_orbit": "接力11：轨道",
    "precis.relay.relay_12_programmable": "接力12：可编程",
    "precis.relay.torus": "环面",
    "precis.relay.relay_1_fire": "接力1：火",
    "precis.relay.relay_2_tree": "接力2：树",
    "precis.relay.relay_3_river": "接力3：河流",
    "precis.relay.relay_4_horse": "接力4：马",
    "precis.relay.relay_5_road": "接力5：道路",
    "precis.relay.relay_6_ship": "接力6：船舶",
    "precis.relay.relay_7_rail": "接力7：铁路",
    "precis.relay.relay_8_loom": "接力8：织机",
    "precis.relay.relay_9_engine": "接力9：引擎",
    // ============================================
    // NAVIGATION — NEW PAGES
    // ============================================
    "nav.clock": "动员时钟",
    "nav.pioneers": "先锋计划",
    // ============================================
    // MOBILISATION CLOCK PAGE
    // ============================================
    "clock.title": "IAAI 全球动员时钟",
    "clock.subtitle": "人类通往基础设施素养的竞赛 — 挑战",
    "clock.hero.pop": "世界人口",
    "clock.hero.pop.sub": "联合国实时估算",
    "clock.hero.target": "目标：10亿学习者",
    "clock.hero.target.sub": "人类的12.1% — 临界点",
    "clock.hero.mobilised": "当前已动员",
    "clock.bar.start": "0 — 启动",
    "clock.bar.mid": "先锋 → 大使 → 学者",
    "clock.bar.end": "1,000,000,000 — 使命完成",
    "clock.contributors.title": "贡献者类别",
    "clock.contributors.players": "玩家（游戏）",
    "clock.contributors.pioneers": "先锋（测试者）",
    "clock.contributors.ambassadors": "大使（语言领袖）",
    "clock.contributors.scholars": "学者（学术验证者）",
    "clock.contributors.advisors": "顾问（战略）",
    "clock.contributors.patrons": "赞助人（机构）",
    "clock.contributors.backers": "支持者（资金）",
    "clock.contributors.founders": "创始团队",
    "clock.platform.title": "平台指标",
    "clock.platform.languages_active": "活跃语言",
    "clock.platform.languages_planned": "计划语言",
    "clock.platform.relays": "已建接力",
    "clock.platform.pages": "网站页面",
    "clock.platform.game_pages": "游戏页面",
    "clock.platform.inventions": "已编目发明",
    "clock.platform.words": "已撰写字数",
    "clock.platform.tests": "通过测试",
    "clock.milestones.title": "里程碑",
    "clock.milestones.github": "GitHub 开源",
    "clock.milestones.first_pioneer": "第一波先锋",
    "clock.milestones.seed": "种子轮（$500K）",
    "clock.milestones.vr": "VR校园（Meta）",
    "clock.regions.title": "8个语言区块 — 全球竞赛",
    "clock.regions.coverage": "综合覆盖：~85%全球游戏市场 · ~80%教育科技支出",
    "clock.regions.goal": "目标：2027年全部8个语言",
    "clock.notyet.title": "尚未参与 — 挑战",
    "clock.notyet.universities": "全球大学",
    "clock.notyet.eng_students": "工程专业学生",
    "clock.notyet.ce_firms": "土木工程公司（前100）",
    "clock.notyet.govts": "国家政府",
    "clock.notyet.un_bodies": "联合国机构",
    "clock.notyet.people": "不了解基础设施的人",
    "clock.notyet.cta": "以上每个数字都是一个挑战。每个零都是一个邀请。",
    "clock.challenge.title": "赞助人挑战榜",
    "clock.challenge.note": "已挑战 = 由玩家提名 · 尚未 = 等待提名",
    "clock.partners.title": "合作伙伴挑战榜",
    "clock.scaling.title": "扩展模型",
    "clock.scaling.phase1": "阶段1：创始人",
    "clock.scaling.phase2": "阶段2：先锋（每区块2-3人）",
    "clock.scaling.phase3": "阶段3：大使（每区块10人）",
    "clock.scaling.phase4": "阶段4：GitHub 开源",
    "clock.scaling.phase5": "阶段5：大学采用",
    "clock.scaling.phase6": "阶段6：有机增长",
    "clock.intelligence.title": "IAAI 情报网络（INTs）",
    "clock.intelligence.humint": "HUMINT — 人力情报（先锋 + 大使）",
    "clock.intelligence.osint": "OSINT — 开源情报（GitHub + 公开数据）",
    "clock.intelligence.sigint": "SIGINT — 信号情报（DAVID AI 分析）",
    "clock.intelligence.geoint": "GEOINT — 地理空间情报（8语言区域映射）",
    "clock.intelligence.comint": "COMINT — 通信情报（翻译网络）",
    "clock.intelligence.masint": "MASINT — 测量情报（学习分析）",
    "clock.intelligence.elint": "ELINT — 电子情报（平台分发）",
    "clock.cta": "加入竞赛 — 成为先锋",
    "clock.cta.sub": "十亿学习者的旅程始于一位先锋。",
    // ============================================
    // PIONEERS PAGE
    // ============================================
    "pioneers.title": "先锋计划",
    "pioneers.subtitle": "第一波贡献者将测试、翻译、验证并在每个大陆传播基础设施素养。免费测试版访问。在创始人墙上赢得你的位置。",
    "pioneers.tier1.title": "先锋",
    "pioneers.tier1.desc": "首批测试者。玩游戏、报告错误、验证内容。每个语言区块2-3人。情报网络的侦察兵。",
    "pioneers.tier1.req": "要求：好奇心、任何语言、愿意测试",
    "pioneers.tier2.title": "大使",
    "pioneers.tier2.desc": "语言领袖。审查和纠正AI翻译以符合母语用法。成为署名贡献者。每个语言区块10人。",
    "pioneers.tier2.req": "要求：母语流利 + 先锋经验",
    "pioneers.tier3.title": "学者",
    "pioneers.tier3.desc": "学术验证者。工程师、教授、研究人员验证技术准确性并将内容映射到课程体系。",
    "pioneers.tier3.req": "要求：学术资质 + 专业领域",
    "pioneers.tier4.title": "顾问",
    "pioneers.tier4.desc": "战略指导。行业领袖、政策制定者和机构连接者，开启大门并塑造方向。",
    "pioneers.tier4.req": "要求：邀请或提名",
    "pioneers.form.title": "申请成为先锋",
    "pioneers.form.subtitle": "免费测试版访问。无费用。无义务。只需好奇心和承诺。",
    "pioneers.form.name": "全名",
    "pioneers.form.email": "电子邮箱",
    "pioneers.form.country": "国家",
    "pioneers.form.language": "主要语言",
    "pioneers.form.expertise": "专业领域",
    "pioneers.form.other_langs": "其他语言",
    "pioneers.form.motivation": "为什么想加入？（可选）",
    "pioneers.charter.title": "IAAI 宪章",
    "pioneers.charter.text": "我们相信基础设施是文明的操作系统。如同河流缓慢而持久地雕刻大地以实现行星级变革，我们致力于开放知识、经验证的贡献、文化尊重，以及理解我们如何建设世界是建设更好世界的第一步。",
    "pioneers.charter.agree": "我已阅读并同意IAAI宪章。我承诺诚实贡献、文化尊重，以及跨语言和国界的知识开放共享。我理解这是一个志愿者计划，我的贡献将在CC BY-NC-SA 4.0许可下署名。",
    "pioneers.form.submit": "提交申请 — 加入竞赛",
    // ============================================
    // HOME PAGE — NEW SECTIONS
    // ============================================
    "home.ppp.clock.title": "查看动员时钟",
    "home.ppp.clock.sub": "实时追踪人类通往基础设施素养的竞赛。挑战已经开始。",

    // ============================================
    // NAV ROW 2 — CAMPAIGN / COMMUNITY
    // ============================================
    "nav.taxonomy": "分类体系",
    "nav.outriders": "先驱者",
    "nav.institutions": "机构",
    "nav.charter": "宪章",

    // ============================================
    // TAXONOMY PAGE
    // ============================================
    "tax.title": "IAAI 分类体系",
    "tax.subtitle": "6+1 层级结构 — 如同生物分类学从界到种，IAAI 的贡献者层级从创始人到支持者，每一层都更加广泛和专业化。",
    "tax.founder": "创始人",
    "tax.founder.desc": "建筑师。1人。设计了整个系统。",
    "tax.advisors": "顾问",
    "tax.advisors.desc": "战略指导。行业领袖和机构连接者。",
    "tax.scholars": "学者",
    "tax.scholars.desc": "学术验证者。教授、工程师、研究人员。",
    "tax.ambassadors": "大使",
    "tax.ambassadors.desc": "语言领袖。每个语言区块10人。",
    "tax.pioneers": "先锋",
    "tax.pioneers.desc": "首批测试者。每个语言区块2-3人。",
    "tax.players": "玩家",
    "tax.players.desc": "游戏参与者。目标：10亿学习者。",
    "tax.backers": "支持者",
    "tax.backers.desc": "资金和机构支持。赞助人和合作伙伴。",
    "tax.biology": "生物学类比",
    "tax.iaai": "IAAI 等级",
    "tax.count": "数量",
    "tax.role": "角色",
    "tax.outriders.note": "先驱者（历史精神导师）不计入6+1层级 — 他们跨越所有模式、所有接力、所有12,000年并肩同行。",

    // ============================================
    // OUTRIDERS PAGE
    // ============================================
    "or.title": "先驱者",
    "or.subtitle": "与每个层级并肩同行的历史精神导师 — 不计入6+1层级，这些智慧伙伴跨越所有模式、所有接力、所有12,000年。他们是游戏中的声音、墙上的名言、连接火焰与环面的智慧。",
    "or.quote": "\"明君贤将，所以动而胜人，成功出于众者，先知也。\" — 孙子，第十三篇",
    "or.stat.total": "先驱者总数",
    "or.stat.eras": "历史时代",
    "or.stat.relays": "覆盖接力",
    "or.stat.civilisations": "代表文明",
    "or.era1.title": "古代世界",
    "or.era2.title": "古典世界",
    "or.era3.title": "中世纪与文艺复兴",
    "or.era4.title": "工业革命",
    "or.era5.title": "现代",
    "or.era6.title": "数字与未来",
    "or.conn.title": "先驱者如何服务使命",
    "or.conn.game.title": "在游戏中",
    "or.conn.game.desc": "先驱者作为NPC导师、引用来源和历史背景提供者出现在每个接力中。玩家在通过12个章节时会遇到他们。",
    "or.conn.book.title": "在书中",
    "or.conn.book.desc": "每章以先驱者的名言开始和结束。他们的创新是案例研究。他们的失败是警示。他们是论点的证据基础。",
    "or.conn.movement.title": "在运动中",
    "or.conn.movement.desc": "先驱者提供道德权威。当IAAI挑战联合国教科文组织或麻省理工时，它站在这些人物所体现的12,000年基础设施智慧的肩膀上。",

    // ============================================
    // INSTITUTIONS PAGE
    // ============================================
    "inst.title": "机构",
    "inst.subtitle": "情报地图 — 每一个可以被召集、挑战或合作的机构、大学、联合国机构、专业学会、非政府组织、技术提供商和资本机构。按联合国可持续发展目标组织，以显示与全球优先事项的一致性。",
    "inst.sdg.title": "按可持续发展目标分类",
    "inst.status.challenged": "已挑战",
    "inst.status.engaged": "已参与",
    "inst.status.notyet": "尚未联系",
    "inst.status.potential": "潜在",
    "inst.coming": "即将推出 — 完整机构数据库正在建设中",

    // ============================================
    // CIVILISATION CLOCK PAGE
    // ============================================
    "nav.civclock": "文明时钟",
    "civ.title": "元素时钟",
    "civ.subtitle": "三个嵌套的24小时时钟 — 从大爆炸到人类瞬间。135亿年宇宙历史、45亿年行星演化、12,000年文明 — 各映射为一天。午夜将至。",
    "civ.epigraph": "\"元素时钟滴答走向午夜。我们在最后几秒所做的一切将回响千年。\"",
    "civ.nesting.title": "三个时钟，一个故事",
    "civ.nesting.desc": "每个时钟嵌套在前一个之中。整个行星时钟只占宇宙时钟的最后三分之一。整个文明时钟只占行星时钟的最后一瞬。我们正生活在午夜前的最后时刻。",
    "civ.cosmic.title": "宇宙时钟",
    "civ.cosmic.subtitle": "135亿年 = 24小时",
    "civ.planetary.title": "行星时钟",
    "civ.planetary.subtitle": "45亿年 = 24小时",
    "civ.civilisation.title": "文明时钟",
    "civ.civilisation.subtitle": "12,000年 = 24小时",
    "civ.relay.title": "12个接力在文明时钟上",
    "civ.cta.title": "午夜将至",
    "civ.cta.desc": "笔在我们手中。基础设施已就位。此刻就是现在。问题不是这种融合是否会发生 — 它已经在发生。问题是：我们将如何应对？",
    // Volume index pages
    "v1.index.title": "卷一：视角",
    "v1.index.about_title": "关于本卷",
    "v1.index.relays_title": "十二次接力",
    
    "v2.index.title": "卷二：指南",
    "v2.index.subtitle": "指南 — 实用框架与扩展分析",
    "v2.index.relays_caption": "十二次文明接力 — 从火到意识",
    "v2.index.about_title": "关于本卷",
    "v2.index.about_text": "卷二：指南将四柱框架（观察 → 教育 → 应用 → 论题）应用于十二次文明接力的每一次。本卷提供实用指导，帮助理解基础设施系统如何运作、如何分析以及如何应用于当代挑战。",
    "v2.index.framework_title": "四柱框架",
    "v2.index.obs": "观察",
    "v2.index.obs_text": "我们对这次接力观察到了什么？它的特征、组成部分和模式是什么？",
    "v2.index.edu": "教育",
    "v2.index.edu_text": "我们能从这次接力中学到什么？它教给我们关于基础设施的什么原理和教训？",
    "v2.index.app": "应用",
    "v2.index.app_text": "我们如何应用这些教训？这次接力产生了哪些实用框架和工具？",
    "v2.index.thesis": "论题",
    "v2.index.thesis_text": "总体论题是什么？这次接力揭示的根本洞见是什么？",
    
    "v3.index.title": "卷三：游戏",
    "v3.index.experience_title": "接力体验",
    
    "lib.title": "文档库",
    "lib.supp_title": "补充文档",
    "home.charter.charter.h": "宪章",
    "home.charter.charter.p": "我们相信基础设施是文明的操作系统。就像河流缓慢而持久地雕刻大地以实现行星级变革，我们致力于开放知识、经过验证的贡献、文化尊重，以及这样的信念：理解我们如何建造这个世界是更好地建设它的第一步。这门课程将用思维和智慧做到河流用水所做的事情——重塑人类理解的格局。",
    "home.charter.mission.h": "使命",
    "home.charter.mission.p": "打造全球首个开放、多语言、AI引导的基础设施教育平台——通过8种语言覆盖10亿学习者，由来自每个大陆的人类贡献者验证。",
    "home.charter.title": "使命、愿景与宪章",
    "home.charter.vision.h": "愿景",
    "home.charter.vision.p": "一个每个人都理解支撑文明的基础设施的世界——并拥有建设未来的知识。",
    "home.pop.answer": "IAAI的存在就是为了改变这个数字。",
    "home.pop.question": "人共享这个星球的基础设施。有多少人真正理解它？",
    "home.pop.source": "来源：联合国世界人口估计（实时预测）",
    "home.ppp.cta.sub": "免费测试版访问——测试、翻译、验证，并在创始人墙上赢得你的位置。加入奥德赛。",
    "home.ppp.cta.title": "成为先驱者",
    "home.ppp.partners.h": "合作伙伴",
    "home.ppp.partners.p": "大学、技术平台和基础设施公司。MIT OCW、可汗学院、Meta/VR、Manus/AI、AECOM、Arup、Bechtel。技术、内容验证和市场准入。",
    "home.ppp.partners.status": "状态：开放挑战——由玩家提名",
    "home.ppp.patrons.h": "赞助人",
    "home.ppp.patrons.p": "使命与普及基础设施教育一致的机构。联合国教科文组织、国家地理、NASA、皇家学会、探索频道、史密森尼、NOAA、世界银行、亚洲开发银行、中国科学院。",
    "home.ppp.patrons.status": "状态：开放挑战——由玩家提名",
    "home.ppp.players.h": "玩家",
    "home.ppp.players.p": "来自每个国家的先驱者、大使、学者和顾问。真实的人——测试、翻译、验证、贡献并传播信息。民主的力量。",
    "home.ppp.players.status": "状态：招募先驱者——免费测试版访问",
    "home.ppp.reach.active": "已激活",
    "home.ppp.reach.active2": "已激活",
    "home.ppp.reach.active3": "已激活",
    "home.ppp.reach.active4": "已激活",
    "home.ppp.reach.active5": "已激活",
    "home.ppp.reach.active6": "已激活",
    "home.ppp.reach.active7": "已激活",
    "home.ppp.reach.active8": "已激活",
    "home.ppp.reach.ar": "阿拉伯语",
    "home.ppp.reach.cn": "中文",
    "home.ppp.reach.coverage": "8种语言覆盖全球约85%的游戏市场、约80%的教育科技支出，以及顶级基础设施投资走廊。",
    "home.ppp.reach.en": "英语",
    "home.ppp.reach.es": "西班牙语",
    "home.ppp.reach.h": "全球语言覆盖",
    "home.ppp.reach.hi": "印地语",
    "home.ppp.reach.ja": "日语",
    "home.ppp.reach.ko": "韩语",
    "home.ppp.reach.vi": "越南语",
    "home.ppp.subtitle": "从卡路里到意识——个人层面的行动号召，无法被阻止或控制。它只是不断学习。",
    "home.ppp.title": "赞助人、合作伙伴与玩家",
    "nav.founders": "创始人墙",
    // ============================================
    // MISSING KEYS - ADDED BY TRANSLATION GENERATOR
    // ============================================
    "home.guide.btn": "阅读指南",
    "home.guide.title": "第二卷：指南",
    "masters.subtitle": "历史精神向导，与每一层级并肩同行 — 不计入6+1层级，这些智慧伙伴跨越所有模式、所有接力、所有12,000年。他们是游戏中的声音，墙上的名言，连接火焰与环面的智慧。",
    "masters.title": "大师",
    "nav.glossary": "术语表",
    "nav.masters": "大师",
    "nav.olympiad": "奥林匹克",
    "nav.starthere": "从这里开始",
    "precis.relay.relay_10_orbit": "接力11：轨道",
    "precis.relay.relay_11_human_nodes": "接力12：人类节点",
    "precis.relay.relay_1_tree": "接力2：树",
    "precis.relay.relay_2_river": "接力3：河流",
    "precis.relay.relay_3_horse": "接力4：马",
    "precis.relay.relay_4_roads": "接力5：道路",
    "precis.relay.relay_5_ships": "接力6：船",
    "precis.relay.relay_6_loom": "接力7：织机",
    "precis.relay.relay_8_engine": "接力9：引擎",
    "precis.relay.relay_9_aaa": "接力10：AAA三位一体",
    "tax.cta": "在树中找到你的位置",
    "tax.cta.sub": "每个物种始于一个有机体。每场运动始于一位先驱。",
    "tax.footer.cc": "CC BY-NC-SA 4.0",
    "tax.parallel.institutions.desc": "Organisations that can be challenged, engaged, or partnered with. Universities, UN bodies, professional societies, government agencies, NGOs, and corporations. They sit outside the contributor hierarchy but are the targets of the intelligence network and the Challenge Board.",
    "tax.parallel.institutions.title": "&#x1F3DB; Institutions &mdash; The Challenge Map",
    "tax.parallel.institutions.who": "UNESCO &bull; World Bank &bull; ASCE &bull; ICE &bull; MIT &bull; Khan Academy &bull; Meta &bull; National Geographic",
    "tax.parallel.outriders.desc": "Historical and philosophical figures who ride alongside every tier as intellectual companions. Not counted in the 6+1 &mdash; they exist across all levels, all modes, all time periods. They are the voices in the game, the quotes on the walls, the wisdom that connects 12,000 years of infrastructure.",
    "tax.parallel.outriders.title": "&#x1F3C7; Outriders &mdash; Spirit Guides",
    "tax.parallel.outriders.who": "Laozi &bull; Sun Tzu &bull; Confucius &bull; Vitruvius &bull; Leonardo da Vinci &bull; Isambard Kingdom Brunel &bull; Nikola Tesla &bull; Ada Lovelace",
    "tax.parallel.title": "平行轨道（层级之外）",
    "tax.plus1.desc": "在生物学中，物种是最具体的分类——个体生物本身。在IAAI中，+1是十亿学习者",
    "tax.plus1.subtitle": "人类的12.1% — 基础设施素养的临界点",
    "tax.plus1.target": "目标：1,000,000,000",
    "tax.plus1.title": "+1 — 物种",
    "tax.quote": "\"正如所有生命共享一个共同祖先，所有基础设施共享一个共同目的——服务文明。\"",
    "tax.rank.class": "纲",
    "tax.rank.domain": "域",
    "tax.rank.family": "科",
    "tax.rank.genus": "属",
    "tax.rank.kingdom": "界",
    "tax.rank.order": "目",
    "tax.rank.phylum": "门",
    "tax.table.biology": "生物学",
    "tax.table.count": "数量",
    "tax.table.iaai": "IAAI",
    "tax.table.suntzu": "情报 (INT)",
    "tax.tier1.analogy": "Biology: Domain (Eukarya) &bull; Military: Commander-in-Chief &bull; Architecture: Master Builder",
    "tax.tier1.desc": "The singular origin point. Conceived the 12-relay framework, wrote the trilogy, designed the game, and built the platform. Like Domain in biology &mdash; the broadest, most fundamental classification from which everything else branches.",
    "tax.tier1.name": "创始人",
    "tax.tier1.title": "建筑师",
    "tax.tier1.who": "Ir. Nigel T. Dearden &mdash; CEng MICE MHKIE",
    "tax.tier2.analogy": "Biology: Kingdom (Animalia) &bull; Military: General Staff &bull; Sun Tzu: The Five Essentials",
    "tax.tier2.desc": "The inner circle. Industry leaders, capital strategists, and institutional connectors who shape direction, open doors, and bridge the gap between vision and execution. By invitation or nomination only.",
    "tax.tier2.name": "顾问",
    "tax.tier2.title": "战略委员会",
    "tax.tier2.who": "Michael Wu (COO) &bull; Henry Leong (CFO) &bull; Frank Sheu (CTO) &bull; Stephen Markscheid (Strategic Advisor)",
    "tax.tier3.analogy": "Biology: Phylum (Chordata) &bull; Military: Intelligence Corps &bull; Academia: Peer Review Board",
    "tax.tier3.desc": "Engineers, professors, and researchers who verify technical accuracy, map content to university curricula, and provide the academic credibility that transforms a game into an educational standard. The peer-review layer.",
    "tax.tier3.name": "学者",
    "tax.tier3.title": "学术验证者",
    "tax.tier3.who": "Target: Engineering faculties, infrastructure researchers, curriculum designers",
    "tax.tier4.analogy": "Biology: Class (Mammalia) &bull; Military: Field Officers &bull; Diplomacy: Cultural Attach&eacute;s",
    "tax.tier4.desc": "Native-fluency contributors who review and correct AI translations against real usage. 10 per language block across 8 languages. They ensure infrastructure literacy speaks authentically in every tongue. Credited contributors with their names on the work.",
    "tax.tier4.name": "大使",
    "tax.tier4.title": "语言领袖",
    "tax.tier4.who": "Target: 10 per block &times; 8 blocks = 80 Ambassadors worldwide",
    "tax.tier5.analogy": "Biology: Order (Primates) &bull; Military: HUMINT (Human Intelligence) &bull; Scouts &amp; Reconnaissance",
    "tax.tier5.desc": "The first wave. 2&ndash;3 per language block who play the game, report bugs, validate content, and provide the ground-truth feedback that shapes the platform before public release. The HUMINT assets of the intelligence network — human intelligence on the ground.",
    "tax.tier5.name": "先驱",
    "tax.tier5.title": "测试员与侦察兵",
    "tax.tier5.who": "Currently recruiting &mdash; 3 active across EN and CN blocks",
    "tax.tier6.analogy": "Biology: Family (Hominidae) &bull; Military: The Rank and File &bull; Gaming: The Player Base",
    "tax.tier6.desc": "Everyone who plays The Reality Engine. From casual explorers to completionists who master all 12 relays across all 4 modes. They generate the data, the engagement, and the democratic nominations that power the Challenge Board. The lifeblood of the platform.",
    "tax.tier6.name": "玩家",
    "tax.tier6.title": "游戏社区",
    "tax.tier6.who": "Target: 1M players by Year 2 &bull; Currently: 21 (beta)",
    "tax.tier7.analogy": "Biology: Genus (Homo) &bull; Military: ELINT (Electronic Intelligence) &bull; Logistics &amp; Supply",
    "tax.tier7.desc": "Those who fund the mission &mdash; from individual Kickstarter backers to institutional patrons (UNESCO, National Geographic, universities). They don't play or translate; they enable. Challenged by Players, engaged by Advisors. The ELINT channel of the intelligence network — converting institutional signals into engagement.",
    "tax.tier7.name": "支持者",
    "tax.tier7.title": "财务与机构支持者",
    "tax.tier7.who": "Target: $500K seed &bull; Challenged: UNESCO, NatGeo, NASA, Royal Society, MIT OCW, Khan Academy",
    "v1.r01.continuity": "连续性",
    "v1.r01.energy_web": "能量之网",
    "v1.r01.infrastructure": "基础设施",
    "v1.r01.knowledge_web": "知识之网",
    "v1.r01.threats": "威胁",
    "v1.r01.unification": "统一",
    "v1.r02.continuity": "连续性",
    "v1.r02.energy_web": "能量之网",
    "v1.r02.infrastructure": "基础设施",
    "v1.r02.knowledge_web": "知识之网",
    "v1.r02.threats": "威胁",
    "v1.r02.unification": "统一",
    "v1.r03.continuity": "连续性",
    "v1.r03.energy_web": "能量之网",
    "v1.r03.infrastructure": "基础设施",
    "v1.r03.knowledge_web": "知识之网",
    "v1.r03.threats": "威胁",
    "v1.r03.unification": "统一",
    "v1.r04.continuity": "连续性",
    "v1.r04.energy_web": "能量之网",
    "v1.r04.infrastructure": "基础设施",
    "v1.r04.threats": "威胁",
    "v1.r04.unification": "统一",
    "v1.r05.consciousness_web": "意识之网",
    "v1.r05.continuity": "连续性",
    "v1.r05.infrastructure": "基础设施",
    "v1.r05.knowledge_web": "知识之网",
    "v1.r05.threats": "威胁",
    "v1.r05.unification": "统一",
    "v1.r06.consciousness_web": "意识之网",
    "v1.r06.continuity": "连续性",
    "v1.r06.infrastructure": "基础设施",
    "v1.r06.knowledge_web": "知识之网",
    "v1.r06.threats": "威胁",
    "v1.r06.unification": "统一",
    "v1.r07.continuity": "连续性",
    "v1.r07.energy_web": "能量之网",
    "v1.r07.infrastructure": "基础设施",
    "v1.r07.knowledge_web": "知识之网",
    "v1.r07.threats": "威胁",
    "v1.r07.unification": "统一",
    "v1.r08.consciousness_web": "意识之网",
    "v1.r08.continuity": "连续性",
    "v1.r08.energy_web": "能量之网",
    "v1.r08.infrastructure": "基础设施",
    "v1.r08.knowledge_web": "知识之网",
    "v1.r08.threats": "威胁",
    "v1.r08.unification": "统一",
    "v1.r09.continuity": "连续性",
    "v1.r09.energy_web": "能量之网",
    "v1.r09.infrastructure": "基础设施",
    "v1.r09.knowledge_web": "知识之网",
    "v1.r09.threats": "威胁",
    "v1.r09.unification": "统一",
    "v1.r10.consciousness_web": "意识之网",
    "v1.r10.continuity": "连续性",
    "v1.r10.energy_web": "能量之网",
    "v1.r10.infrastructure": "基础设施",
    "v1.r10.knowledge_web": "知识之网",
    "v1.r10.threats": "威胁",
    "v1.r10.unification": "统一",
    "v1.r11.consciousness_web": "意识之网",
    "v1.r11.continuity": "连续性",
    "v1.r11.infrastructure": "基础设施",
    "v1.r11.knowledge_web": "知识之网",
    "v1.r11.threats": "威胁",
    "v1.r11.unification": "统一",
    "v1.r12.consciousness_web": "意识之网",
    "v1.r12.continuity": "连续性",
    "v1.r12.infrastructure": "基础设施",
    "v1.r12.knowledge_web": "知识之网",
    "v1.r12.threats": "威胁",
    "v1.r12.unification": "统一",
    "oly.title": "基础设施奥林匹克",
    "oly.stat.blocks": "语言区块",
    "oly.stat.categories": "竞赛类别",
    "oly.stat.universities": "全球大学",
    "oly.stat.xpcap": "经验值上限（大师级）",
    "oly.stat.people": "覆盖人口",
    "oly.stat.gap": "基础设施缺口",
    "oly.flywheel.title": "飞轮效应 — 奥林匹克如何自我增长",
    "oly.flywheel.players": "玩家竞争",
    "oly.flywheel.professionals": "专业人士验证",
    "oly.flywheel.patrons": "赞助商支持",
    "oly.flywheel.platform": "平台扩展",
    "oly.medal.title": "实时奖牌榜 — 各国文明管理竞赛",
    "oly.th.nation": "国家",
    "oly.th.blocks": "区块",
    "oly.th.pop": "人口（百万）",
    "oly.th.gamers": "玩家（百万）",
    "oly.th.story": "基础设施故事",
    "oly.th.total": "总分",
    "oly.th.status": "状态",
    "oly.rogue.title": "游侠团队 — 非隶属人才库",
    "oly.categories.title": "竞赛类别 — 文明基础设施六大支柱",
    "oly.pipeline.unis": "全球大学",
    "oly.pipeline.students": "工程专业学生",
    "oly.pipeline.firms": "顶级土木工程公司",
    "oly.pipeline.govts": "国家政府",
    "oly.sponsor.title": "赞助层级 — 支持国家队",
    "oly.sponsor.gold": "金牌赞助商",
    "oly.sponsor.silver": "银牌赞助商",
    "oly.sponsor.bronze": "铜牌赞助商",
    "oly.sponsor.patron": "荣誉赞助",
    "oly.form.register.title": "注册您的大学团队",
    "oly.form.sponsor.title": "赞助咨询",
    "nav.behind": "论文背后",

    // SDG Alignment Section
    "sdg.title": "可持续发展目标 — 对标",
    "sdg.subtitle": "IAAI 12站接力课程如何对标联合国可持续发展目标",
    "sdg.iconCaption": "IAAI 内容直接涉及17个可持续发展目标中的11个。每个图标链接至联合国官方目标页面。",
    "sdg.col.relay": "IAAI 接力站",
    "sdg.col.sdgGoals": "SDG 目标",
    "sdg.col.alignment": "对标理由",
    "sdg.col.5p": "5P 类别",
    "sdg.r1.rationale": "道路网络是经济发展的循环系统。没有道路，就没有市场准入、应急服务和供应链。",
    "sdg.r2.rationale": "铁路是大众运输和货运的骨干。每吨公里排放低于公路，促进可持续城市化。",
    "sdg.r3.rationale": "港口将国家与全球贸易连接。90%的世界货物通过海运。港口基础设施直接影响海洋生态系统。",
    "sdg.r4.rationale": "航空基础设施实现全球互联互通、贸易、旅游和应急响应。经济参与的门户。",
    "sdg.r5.rationale": "清洁水是最基本的基础设施。22亿人仍然缺乏安全管理的饮用水。每个文明的兴衰都取决于水。",
    "sdg.r6.rationale": "卫生设施预防疾病、保护水源、维护人类尊严。36亿人缺乏安全管理的卫生设施。",
    "sdg.r7.rationale": "能源基础设施决定国家是清洁工业化还是重复化石燃料依赖。转型接力站。",
    "sdg.r8.rationale": "电信将人们与教育、市场和治理连接。数字鸿沟就是基础设施鸿沟。",
    "sdg.r9.rationale": "废物管理是消费的镜子。循环经济需要收集、分类、回收和回收的基础设施。",
    "sdg.r10.rationale": "健康基础设施——医院、诊所、供应链——决定人口能否在大流行中幸存并有尊严地老去。",
    "sdg.r11.rationale": "教育基础设施——学校、大学、图书馆——是文明跨代传递知识的机制。",
    "sdg.r12.rationale": "数字基础设施——数据中心、光纤、云——是21世纪的道路和港口。新的公共资源。",
    "sdg.5pTitle": "5P — 人民、地球、繁荣、和平、伙伴关系",
    "sdg.5pText": "联合国通过五大支柱（5P）构建17个可持续发展目标。基础设施是文明实现所有五个P的机制。IAAI课程中的每个接力站至少涉及一个P——大多数涉及两到三个。这不是巧合；这是基础设施作为文明管理的本质。",
    "sdg.visitUN": "访问联合国SDG官方网站 →",
    "sdg.disclaimerTitle": "免责声明：",
    "sdg.disclaimerText": "本出版物的内容未经联合国批准，不反映联合国或其官员或会员国的观点。可持续发展目标图标和个别目标图像根据联合国SDG传播指南用于信息和教育目的。基础设施学院（IAAI）是一个独立的教育平台；上述对标映射代表IAAI对其课程与SDG关系的自身解读。",

    // ============================================
    // NETWORK BAR
    // ============================================
    "net.academy": "学院",
    "net.quest": "探索",
    "net.xchange": "交易所",
    "net.memorial": "纪念",
    "net.news": "新闻",

    // ============================================
    // STATS ROW
    // ============================================
    "home.stats.blocks": "区块",
    "home.stats.icards": "知识卡",
    "home.stats.observers": "观察员",
    "home.stats.pages": "页面",
    "home.stats.sdgs": "SDG对标",

    // ============================================
    // CTA SECTION
    // ============================================
    "home.cta.title": "第一次来？",
    "home.cta.btn": "从这里开始 →",
    "home.cta.desc": "了解使命、结构和从何开始",

    // ============================================
    // ELE PARAGRAPH
    // ============================================
    "home.ele.paragraph": "地球上的生命已被五次灭绝级事件重置。每一次都抹去了当时的主导系统。每一次都为下一阶段清除了旧迹。人类是第一个能够感知这一模式的物种——也是第一个有能力打断它的物种。",

    // ============================================
    // HERO PANELS
    // ============================================
    "home.hero.book": "📖 书籍",
    "home.hero.movie": "🎬 电影",
    "home.hero.game": "🎮 游戏",
    "home.hero.tapSound": "点击开启声音",
    "home.hero.allMovies": "🎬 全部电影",

    // ============================================
    // MOBILE QUICKNAV
    // ============================================
    "home.qnav.home": "🏠 首页",
    "home.qnav.start": "📚 开始",
    "home.qnav.read": "📖 阅读",
    "home.qnav.framework": "🔧 框架",
    "home.qnav.play": "🎮 游戏",
    "home.qnav.movies": "🎬 电影",
    "home.qnav.resources": "📂 资源",
    "home.qnav.press": "📰 媒体",

    // ============================================
    // MISC
    // ============================================
    "home.follow": "关注",
    "home.popular.title": "最受欢迎页面",
    // ============================================
    // NAV PILL MENU (nav-optimise.js)
    // ============================================
    "nav.read": "阅读",
    "nav.explore": "探索",
    "nav.people": "人物",
    "nav.resources_group": "资源",
    "nav.press": "新闻资料包",
    "nav.search": "搜索",
    "nav.videos": "视频放映室",
    "nav.movies": "电影",
    "nav.relays": "12个接力",
    "nav.webs": "5大网络",
    "nav.scholars": "7位学者",
    "nav.modes": "3种模式",
    "nav.threats": "4C威胁",
    "nav.sdgs": "可持续发展目标",
    "nav.pillars": "4大支柱",
    "nav.mastery": "精通",
    "nav.narration": "叙事",
    "nav.divide": "文明鸿沟",
    "nav.quotes": "名言",
    "nav.nodes": "节点注册",
    "nav.schema": "站点架构",
    "nav.deck": "卡牌组",
    "nav.equations": "方程式",
    "nav.vault": "保险库",
    "nav.bibliography": "参考文献",
    "nav.milestones": "里程碑",
    "nav.assessmentresults": "评估结果",
    "nav.beforewriting": "写作前",
    "nav.thesisrecord": "论文记录",
    "nav.turingpaper": "图灵论文",
    "nav.icard_gallery": "知识卡画廊",
    "nav.icard_register": "知识卡注册",
    "nav.icard_4ecl": "知识卡：4ECL BR",
    "nav.icard_booksales": "知识卡：图书销售",
    "nav.icard_htetra": "知识卡：H-四面体",
    "nav.icard_khanh": "知识卡：Khanh",
    "nav.icut_gallery": "ICUT画廊",
    "nav.link_register": "链接注册",
    "nav.chip_evolution": "芯片演化",
    "nav.dcsn": "DCSN仪表盘",
    "nav.hblock": "H区块仪表盘",
    "nav.finance": "财务管理",
    "nav.4cs_decision": "4C决策",
    "nav.cashflow": "现金流Y1",
    "nav.video_playroom": "视频放映室",
    // ============================================
    // ADDITIONAL NAV (site.html nav-row2)
    // ============================================
    "nav.lamenara": "拉梅纳拉",
    "nav.analytics": "分析",
    "nav.blocks": "区块摘要",
    "nav.bridge": "桥梁",
    "nav.gallery": "ICUT画廊",
    "nav.governance": "治理",
    "nav.icards": "知识卡注册",
    "nav.igo": "iGO",
    "nav.marketplace": "市场",
    "nav.nexus": "FEW关联",
    "nav.observers": "观察员注册",
    "nav.race": "竞赛追踪",
    "nav.relaytracker": "接力追踪",
    "nav.roster": "花名册仪表盘",
    "nav.sdgmatrix": "SDG矩阵",
    // ============================================
    // BADGE
    // ============================================
    "badge.beta": "PoC 测试版 · 试用站点 | 寻求赞助资金培育世界未来建设者",
    // ============================================
    // SITE.HTML SECTIONS (EDUTAINMENT, REALITY ENGINE, ODYSSEY, etc)
    // ============================================
    "home.edutainment.title": "寓教于乐",
    "home.edutainment.subtitle": "通过娱乐进行教育",
    "home.realityengine.title": "🎮 现实引擎",
    "home.realityengine.subtitle": "12个接力 · 91+项发明 · 5大网络 · 适合8-65+岁",
    "home.realityengine.btn": "进入游戏 →",
    "home.odyssey.title": "奥德赛",
    "home.odyssey.day": "天",
    "home.playigo": "▶ 播放 iGO",
    "home.search": "🔍 搜索",
    "home.share.title": "分享奥德赛",
    "home.network.title": "基础设施奥德赛网络",
    // ============================================
    // SDG PAGE
    // ============================================
    "sdg.5pTitle": "5P框架",
    "sdg.5pText": "人类、地球、繁荣、和平、伙伴关系",
    "sdg.col.sdgGoals": "SDG目标",
    "sdg.disclaimerTitle": "免责声明",
    "sdg.disclaimerText": "本内容仅供教育参考，不代表联合国官方立场。",
    "sdg.iconCaption": "联合国可持续发展目标",
    "sdg.visitUN": "访问联合国SDG网站",
    // ============================================
    // EDUTAINMENT DETAIL
    // ============================================
    "home.edutainment.facts": "<strong>渊源：</strong> 1933年广播 → 1954年迪士尼电视 → 1973年国家地理 → 2025年基础设施学院<br><strong>三部曲：</strong> 书籍 · 电影 · 游戏 — 三种格式，一个文明课程<br><strong>道德中立。</strong> 桥梁承载军队和救护车。工具服务于所有人。<br><strong>4 × 13 = 52</strong> Tecton Trump — 恐惧 × 恐惧 = 游戏",
    "home.edutainment.foot": "当你将世界所恐惧的事物相乘，你就得到了拯救它的工具",
    // ============================================
    // MEDIA SECTION
    // ============================================
    "media.lamenara.subtitle": "基础设施奥德赛 — 从卡路里到意识",
    "media.lamenara.stats": "12,000年 | 12个接力 | 120,000小时 | 3幕 | 7位学者 | 10分钟（第153天 — 2026年4月5日）",
    "media.katana.desc": "武士刀13折纪录片 — 日本刀制工艺如何照亮基础设施治理（4:04）",
    "media.principia.desc": "完整的基础设施奥德赛10分钟版 — 12个文明接力、德尔登场、生物光环套装和飞行甲板（10:33）",
    "media.dearden.desc": "飞行甲板揭秘 — 德尔登场矩阵、神经诊断、生物计量面板和文明导航驾驶舱（2:40）",
    "media.igo.desc": "完整的iGO框架 — 12个接力、5大网络、60节点德尔登场、12种游戏格式、DAVID AI和知识卡系统。适合8-65+岁（1:40）",
    "home.game.viewall": "查看全部 →",
    // ============================================
    // ELE DECLARATION
    // ============================================
    "home.ele.declaration": "地球上的生命已被灭绝级事件重置五次。每一次都抹去了那个时代的主导系统。每一次都为下一个时代清除了障碍。人类是第一个能够感知这一模式的物种 — 也是第一个能够打断它的物种。",
    // ============================================
    // SECTION NAVIGATION
    // ============================================
    "sec.top": "顶部",
    "sec.book": "书籍",
    "sec.framework": "框架",
    "sec.volumes": "卷册",
    "sec.challenge": "挑战",
    "sec.trilogy": "三部曲",
    "sec.media": "媒体",
    "sec.knowledge": "知识",
    "sec.game": "游戏",
    "sec.counter": "计数器",
    "sec.charter": "宪章",
    "sec.patrons": "赞助人",
    "sec.archive": "档案",
    "sec.share": "分享",
    // ============================================
    // FOOTER
    // ============================================
    "footer.ep1": "第一集：地球基础",
    "footer.ep2": "第二集：灰色竞技场",
    "footer.ep3": "第三集：宇宙尺度",
    "footer.copyright": "© 2026 基础设施学院。版权所有。为永恒保存知识。",
    // ============================================
    // REMEDIATION: P2 — Additional translations (GP-001)
    // ============================================
    "home.relays.title": "第一集 — 12个文明接力 + 分形连接器",
    "home.media.premiere": "全球首映：拉梅纳拉纪录片",
    "home.media.lamenara.trailer": "拉梅纳拉 — 预告片",
    "home.media.lamenara.desc": "第一幕电影预览，配有旁白和原创艺术作品 (2:11)",
    "home.media.blade": "精选：刀锋与桥梁",
    "home.media.principia": "构造原理",
    "home.media.dearden": "迪尔登动力学",
    "home.media.igo": "iGO 建筑电影",
    "home.media.social": "社交媒体片段",
    "home.media.social.desc": "分享奥德赛 — 为 X、LinkedIn 和 WhatsApp 优化",
    "home.media.author": "迪尔登工程师 特许工程师 CWEM — 4ECL | Per Arya Ad Astra",
    "home.media.label.reality": "现实引擎",
    "home.media.label.igo": "iGO 预告片",
    "home.whatsnew": "最新动态",
    "home.changelog": "查看完整更新日志",
    "home.game.topplayers": "顶尖玩家",
    "home.equations.title": "知识产权与方程式注册 — BETA 卡组",
    "home.recent.title": "最近更新",
    "home.whatsapp.title": "通过 WHATSAPP 联系",
    "home.fw.infill": "填充地图 — 填补主接力链中间隙的不连续分支",
    "home.fw.elemental": "元素时钟 — 四个嵌套视图：从大爆炸到领土扩张的终结",
    "home.fw.territorial": "领土扩张的终结 — 从威斯特伐利亚到人类节点",
    "home.fw.timeline": "领土扩张终结时间线 — 在我们12,000年时钟的午夜前11分钟展望2050年。但前沿不是陆地或轨道，而是心智、身体和认知的人类前沿。",
    "home.fw.reading": "解读文明时钟 — 最后43分钟的四个关键时刻：威斯特伐利亚、地图完成、联合国宪章和现在（2026）",
    "home.dominion.title": "失去主权 — 融合危机",
    "home.dominion.text": "第六次重置不会来自太空。它已经在这里 — 在决策、设计和治理从人类系统向机器系统的转移中。不是灭绝，而是取代。承载文明12,000年的基础设施正在以任何一代人都无法消化的速度融合。这就是融合危机。第二集绘制了人类延续的架构。",
    "home.fw.ele_planetary": "ELE行星时钟 — 地球：45亿年。五次重置。ELE 6是文明性的 — 2050年。立即行动，否则失去主导地位。",
    "home.fw.continuity_grid": "完整延续网格 — 如果人类历史是一本1,200页的书。24行 = 24小时。网格就是时钟。第24行 = 最后一小时。",
    "home.fw.row24": "第24行展开 — 最后一小时。12,000年（公元前10,000年 → 2050年）。500代人。唯一一行人类掌握接力的行。七位学者。246年内六次接力。全部仍在运行。",
    "home.fw.relay_cone": "接力锥 — 500代文明压缩为12个基础设施接力。侧视图、俯视图和七位学者。前六次接力跨越11,500年；后六次压缩为246年。",
    "home.ascent.title": "意识的攀升",
    "home.ascent.subtitle": "接力12及更远 — 以2050年为午夜的文明论题",
    "home.ascent.text": "这就是文明论题所在。从卡路里到意识 — 基础设施奥德赛跨越12,000年，涵盖12个接力、7位学者、5个网络和3大帝国。意识的攀升是接力12及更远：生物智能与其自身基础设施相遇的转折点。五个层次的知识谱系 — 从荷马到应用世代 — 汇聚于一个问题：谁来传递接力？其神学意涵深远。失去主权框定了危机；对抗力：部分、度量与平衡提供了工程师的演算。第八位学者仍是开放的探索 — 3,500年基础智慧链中的下一个节点。",
    "home.ascent.source": "谱系五层 — 通往第八位学者的3,500年知识接力 — iAAi真理框架"
};
