// INFRASTRUCTURE ACADEMY - VI TRANSLATIONS
window.IA_LANG_VI = {
    "archive.documents": "Tài liệu",
    "archive.images": "Hình ảnh",
    "archive.references": "Tài liệu tham khảo",
    "archive.relays": "Các cuộc tiếp sức",
    "archive.subtitle": "Bảo tồn tài sản tri thức hoàn chỉnh",
    "archive.supplements": "Tài liệu bổ sung",
    "archive.title": "Kho lưu trữ",
    "author.bio": "Ir. Nigel T Dearden (鄧禮祖) là Kỹ sư Xây dựng và Kết cấu Công nhận và Quản lý Nước và Môi trường Công nhận, với hơn 33 năm kinh nghiệm cơ sở hạ tầng tại Hồng Kông. Nhà sáng lập 4 Elements Consulting Ltd (thành lập 2006, www.4ecl.com). BEng (Hon's), CEng, C.WEM, RPE (CSB), MICE, MHKIE, MCIWEM.",
    "author.credentials": "Kỹ sư được công nhận (CEng), Thành viên Viện Kỹ sư Xây dựng (MICE), Thành viên Viện Kỹ sư Hồng Kông (MHKIE)",
    "author.name": "Ir. Nigel T. Dearden",
    "author.title": "Về tác giả",
    "civ.civilisation.subtitle": "12.000 năm = 24 giờ",
    "civ.civilisation.title": "Đồng hồ văn minh",
    "civ.cosmic.subtitle": "13,5 tỷ năm = 24 giờ",
    "civ.cosmic.title": "Đồng hồ vũ trụ",
    "civ.cta.desc": "Bút nằm trong tay chúng ta. Cơ sở hạ tầng đã được thiết lập. Khoảnh khắc chính là hiện tại. Vấn đề không phải là sự hội nhập này có xảy ra hay không — nó đã đang diễn ra. Vấn đề là: chúng ta sẽ đối mặt như thế nào?",
    "civ.cta.title": "Nửa đêm sắp đến",
    "civ.epigraph": "",
    "civ.nesting.desc": "Mỗi chiếc đồng hồ được lồng vào trong chiếc đồng hồ trước đó. Toàn bộ đồng hồ hành tinh chỉ chiếm phần ba cuối cùng của đồng hồ vũ trụ. Toàn bộ đồng hồ nền văn minh chỉ chiếm khoảnh khắc cuối cùng của đồng hồ hành tinh. Chúng ta đang sống trong những giây phút cuối cùng trước nửa đêm.",
    "civ.nesting.title": "Ba chiếc đồng hồ, một câu chuyện",
    "civ.planetary.subtitle": "4,5 tỷ năm = 24 giờ",
    "civ.planetary.title": "Đồng hồ hành tinh",
    "civ.relay.title": "12 tiếp sức trên đồng hồ văn minh",
    "civ.subtitle": "Ba đồng hồ 24 giờ lồng nhau — từ Vụ Nổ Lớn đến khoảnh khắc con người. 13,5 tỷ năm lịch sử vũ trụ, 4,5 tỷ năm tiến hóa hành tinh, 12.000 năm văn minh — mỗi khoảng thời gian tương ứng với một ngày. Nửa đêm đang đến gần.",
    "civ.title": "Đồng hồ nguyên tố",
    "clock.bar.end": "1.000.000.000 — Nhiệm vụ hoàn thành",
    "clock.bar.mid": "Tiên phong → Đại sứ → Học giả",
    "clock.bar.start": "0 — Khởi động",
    "clock.challenge.note": "Đã thách đấu = Do người chơi đề cử · Chưa = Đang chờ đề cử",
    "clock.challenge.title": "Bảng xếp hạng thách thức của nhà tài trợ",
    "clock.contributors.advisors": "Cố vấn (Chiến lược)",
    "clock.contributors.ambassadors": "Đại sứ (Lãnh đạo ngôn ngữ)",
    "clock.contributors.backers": "Người ủng hộ (vốn)",
    "clock.contributors.founders": "Đội ngũ sáng lập",
    "clock.contributors.patrons": "Nhà tài trợ (tổ chức)",
    "clock.contributors.pioneers": "Tiên phong (Người kiểm thử)",
    "clock.contributors.players": "Người chơi (trò chơi)",
    "clock.contributors.scholars": "Học giả (Người xác thực học thuật)",
    "clock.contributors.title": "Loại người đóng góp",
    "clock.cta": "Tham gia cuộc thi — Trở thành người tiên phong",
    "clock.cta.sub": "Hành trình của một tỷ người học bắt đầu từ một người tiên phong.",
    "clock.hero.mobilised": "Đã huy động hiện tại",
    "clock.hero.pop": "Dân số thế giới",
    "clock.hero.pop.sub": "Ước tính thời gian thực của Liên Hợp Quốc",
    "clock.hero.target": "Mục tiêu: 1 tỷ người học",
    "clock.hero.target.sub": "12,1% của nhân loại — Điểm tới hạn",
    "clock.intelligence.comint": "COMINT — Tình báo truyền thông (Dịch mạng)",
    "clock.intelligence.elint": "ELINT — Tình báo điện tử (Phân phối nền tảng)",
    "clock.intelligence.geoint": "GEOINT — Tình báo không gian địa lý (Bản đồ khu vực 8 ngôn ngữ)",
    "clock.intelligence.humint": "HUMINT — Tình báo nhân lực (Tiên phong + Đại sứ)",
    "clock.intelligence.masint": "MASINT — Tình báo đo lường (học phân tích)",
    "clock.intelligence.osint": "OSINT — Tình báo mã nguồn mở (GitHub + Dữ liệu công khai)",
    "clock.intelligence.sigint": "SIGINT — Tín hiệu tình báo (Phân tích DAVID AI)",
    "clock.intelligence.title": "Mạng lưới Tình báo IAAI (INTs)",
    "clock.milestones.first_pioneer": "Làn sóng tiên phong đầu tiên",
    "clock.milestones.github": "GitHub mã nguồn mở",
    "clock.milestones.seed": "Vòng hạt giống (500 nghìn đô la)",
    "clock.milestones.title": "Cột mốc",
    "clock.milestones.vr": "VR Campus (Meta)",
    "clock.notyet.ce_firms": "Công ty kỹ thuật xây dựng dân dụng (Top 100)",
    "clock.notyet.cta": "Mỗi con số trên đều là một thử thách. Mỗi con số không là một lời mời gọi.",
    "clock.notyet.eng_students": "Sinh viên chuyên ngành kỹ thuật công trình",
    "clock.notyet.govts": "Chính phủ quốc gia",
    "clock.notyet.people": "Người không hiểu biết về cơ sở hạ tầng",
    "clock.notyet.title": "Chưa tham gia — Thử thách",
    "clock.notyet.un_bodies": "Các cơ quan Liên Hợp Quốc",
    "clock.notyet.universities": "Các trường đại học toàn cầu",
    "clock.partners.title": "Bảng xếp hạng thách thức đối tác",
    "clock.platform.game_pages": "Trang trò chơi",
    "clock.platform.inventions": "Phát minh đã được lập mục lục",
    "clock.platform.languages_active": "Ngôn ngữ hoạt động",
    "clock.platform.languages_planned": "Ngôn ngữ lập trình",
    "clock.platform.pages": "Trang web",
    "clock.platform.relays": "Đã xây dựng tiếp sức",
    "clock.platform.tests": "Thông qua kiểm tra",
    "clock.platform.title": "Chỉ số nền tảng",
    "clock.platform.words": "Số từ đã viết",
    "clock.regions.coverage": "Phủ sóng toàn diện: ~85% thị trường game toàn cầu · ~80% chi tiêu công nghệ giáo dục",
    "clock.regions.goal": "Mục tiêu: Đến năm 2027 hoàn thành tất cả 8 ngôn ngữ",
    "clock.regions.title": "8 khối ngôn ngữ — Cuộc thi toàn cầu",
    "clock.scaling.phase1": "Giai đoạn 1: Người sáng lập",
    "clock.scaling.phase2": "Giai đoạn 2: Tiên phong (mỗi khối 2-3 người)",
    "clock.scaling.phase3": "Giai đoạn 3: Đại sứ (10 người mỗi khối)",
    "clock.scaling.phase4": "Giai đoạn 4: Mã nguồn mở trên GitHub",
    "clock.scaling.phase5": "Giai đoạn 5: Đại học áp dụng",
    "clock.scaling.phase6": "Giai đoạn 6: Tăng trưởng hữu cơ",
    "clock.scaling.title": "Mô hình mở rộng",
    "clock.subtitle": "Cuộc đua của nhân loại hướng tới năng lực cơ sở hạ tầng — Thách thức",
    "clock.title": "Đồng hồ động viên toàn cầu IAAI",
    "footer.ep1": "Tập 1: Nền tảng Trái đất",
    "footer.ep2": "Tập 2: Đấu trường Xám",
    "footer.ep3": "Tập 3: Quy mô Vũ trụ",
    "footer.copyright": "&copy; 2026 Học viện Cơ sở hạ tầng. Bảo lưu mọi quyền. Kiến thức được lưu trữ vĩnh viễn.",
    "framework.4cs.challenge": "Thách thức",
    "framework.4cs.consequence": "Hậu quả",
    "framework.4cs.context": "Bối cảnh",
    "framework.4cs.continuum": "Chuỗi liên tục",
    "framework.4cs.title": "Khung phân tích 4C",
    "framework.modes.east": "Chế độ Phương Đông",
    "framework.modes.east.desc": "Liên tục / Xây dựng — Nguyên mẫu Tần Thủy Hoàng",
    "framework.modes.outrider": "Chế độ Outrider",
    "framework.modes.outrider.desc": "Bán liên tục / Công trình tạm thời — Nguyên mẫu Thành Cát Tư Hãn",
    "framework.modes.title": "Ba Chế độ Văn minh",
    "framework.modes.west": "Chế độ Phương Tây",
    "framework.modes.west.desc": "Không liên tục / Xây dựng — Nguyên mẫu Alexander Đại đế",
    "framework.relays.title": "12 Cuộc tiếp sức của các nền văn minh",
    "framework.subtitle": "Một phương pháp tư duy hệ thống tích hợp",
    "framework.title": "Khung chương trình hoàn chỉnh",
    "header.subtitle": "Hành trình Cơ sở hạ tầng: Tập 1 — Từ Calo đến Ý thức",
    "header.subtitle.v2": "Hành trình Cơ sở hạ tầng: Tập 2 — Hướng dẫn thực tế",
    "header.subtitle.v3": "Hành trình Cơ sở hạ tầng: Tập 3 — Cỗ máy thực tại",
    "header.title": "Học viện Cơ sở hạ tầng",
    "home.archive.architects": "Những kiến trúc sư của số phận và những người thống nhất vĩ đại: Alexander Đại đế, Thành Cát Tư Hãn, Tần Thủy Hoàng",
    "home.archive.p1": "Học viện Cơ sở hạ tầng là một kho lưu trữ kỹ thuật số bảo tồn toàn bộ tài sản tri thức của Hành trình Cơ sở hạ tầng — một lớp học tổng thể về văn minh kéo dài 12.000 năm phát triển cơ sở hạ tầng của loài người. Trang web này đảm bảo kiến thức được lưu trữ vĩnh viễn, có thể truy cập được cho các học giả, kỹ sư và người học trên toàn thế giới.",
    "home.archive.p2": "Tất cả nội dung, hình ảnh và khung chương trình được tích hợp ở đây để dễ dàng điều hướng và khám phá. Đó là một bản ghi vĩnh viễn về sự trỗi dậy của loài người từ calo đến ý thức, được khắc vào cõi vĩnh hằng kỹ thuật số bằng cây bút.",
    "home.archive.title": "Về Kho lưu trữ này",
    "home.author": "Tác giả: Ir. Nigel T. Dearden",
    "home.challenge.stat1.desc": "các chương trình giảng dạy thiếu sự tích hợp liên ngành",
    "home.challenge.stat1.num": "70%",
    "home.challenge.stat2.desc": "sinh viên cảm thấy chưa được chuẩn bị cho các ứng dụng thực tế",
    "home.challenge.stat2.num": "65%",
    "home.challenge.stat3.desc": "báo cáo về việc tiếp xúc hạn chế với tư duy cấp hệ thống",
    "home.challenge.stat3.num": "45%",
    "home.challenge.stat4.desc": "nhà tuyển dụng nhận thấy khoảng cách kỹ năng trong việc chuẩn bị dự án",
    "home.challenge.stat4.num": "80%",
    "home.challenge.stat5.desc": "dự án tích hợp các chỉ số tác động cộng đồng hoặc môi trường",
    "home.challenge.stat5.num": "30%",
    "home.challenge.stat6.desc": "dự án cơ sở hạ tầng bị trì hoãn do khoảng cách kiến thức thực tế",
    "home.challenge.stat6.num": "90%",
    "home.challenge.subtitle": "Giáo dục về cơ sở hạ tầng bị phân mảnh, trừu tượng và tách rời khỏi tác động trong thế giới thực.",
    "home.challenge.title": "Thách thức chúng ta giải quyết",
    "home.challenge.urgent": "Nhu cầu cấp thiết: Thu hẹp khoảng cách cho các chuyên gia cơ sở hạ tầng sẵn sàng cho tương lai",
    "home.cover.front": "Bìa trước và sau — Tập 1: Nền tảng Trái đất",
    "home.cover.interior": "Trang trong — Chương 1: Cuộc tiếp sức của Lửa (Phần 1 & 2)",
    "home.cover.portrait": "Cuộc đua tiếp sức của các nền văn minh — 12 chương từ Cây đến Torus",
    "home.ep1.btn": "Đã phát hành",
    "home.ep1.desc": "Từ Calo đến Ý thức — 12 cuộc tiếp sức từ Lửa đến Torus",
    "home.ep1.subtitle": "Nền tảng Trái đất",
    "home.ep1.title": "Tập 1",
    "home.ep2.btn": "Sắp ra mắt",
    "home.ep2.desc": "Điều khiển học, AI & Hệ thống thông minh",
    "home.ep2.subtitle": "Cỗ máy thực tại — Đấu trường Xám",
    "home.ep2.title": "Tập 2",
    "home.ep3.btn": "Sắp ra mắt",
    "home.ep3.desc": "Quản trị hành tinh, hệ mặt trời & thiên hà",
    "home.ep3.subtitle": "Quản lý & Đổi mới — Quy mô Vũ trụ",
    "home.ep3.title": "Tập 3",
    "home.framework.journey": "Hành trình là Công việc.",
    "home.framework.modes.caption": "Ba Chế độ — Phương Tây, Phương Đông & Outrider qua 12.000 năm",
    "home.framework.motto": "Giáo dục Cơ sở hạ tầng: Tư duy Hệ thống, không phải Ghi nhớ",
    "home.framework.relays.caption": "12 Cuộc tiếp sức của các nền văn minh — Từ Lửa đến Ý thức",
    "home.framework.silk.caption": "Nghịch lý Con đường Tơ lụa — Outriders kiểm soát các tuyến đường thương mại mà không xây dựng cơ sở hạ tầng nào",
    "home.framework.subtitle": "Tư duy hệ thống tích hợp cho giáo dục cơ sở hạ tầng qua lăng kính của Kỹ sư Xây dựng",
    "home.framework.title": "Khung chương trình hoàn chỉnh",
    "home.game.cta.sub": "Tập 3: Cỗ máy thực tại — Nền tảng học tập có hướng dẫn",
    "home.game.cta.title": "Vào trò chơi",
    "home.game.desc": "Sẵn sàng áp dụng những gì bạn đã học? Hãy bước vào Cỗ máy thực tại — nền tảng học tập nhập vai nơi bạn trở thành một kỹ sư cơ sở hạ tầng.",
    "home.game.note": "Mô phỏng & Thực hành: Áp dụng các khái niệm trong một môi trường năng động",
    "home.game.title": "Tập 3: Trò chơi",
    "home.hero.caption": "Từ Calo đến Ý thức: Hành trình Cơ sở hạ tầng — Cuộc đua tiếp sức của các nền văn minh",
    "home.kw.subtitle": "Lịch sử toàn diện của chữ viết — từ thẻ kế toán đến thời đại kỹ thuật số. Cây bút như một cuộc tiếp sức cơ sở hạ tầng tối thượng.",
    "home.kw.title": "Mạng lưới tri thức: Chữ viết như một cơ sở hạ tầng",
    "home.media.calories": "Từ Calo đến Ý thức",
    "home.media.engine": "Cỗ máy thực tại — Nền tảng học tập có hướng dẫn",
    "home.media.river": "Phim về Đồng bằng sông",
    "home.media.title": "Truyền thông",
    "home.media.trailer": "Trailer tổng quan",
    "home.ppp.clock.sub": "Theo dõi trực tiếp cuộc đua của con người hướng tới kiến thức cơ bản về cơ sở hạ tầng. Thử thách đã bắt đầu.",
    "home.ppp.clock.title": "Xem đồng hồ động viên",
    "home.s1.desc": "Các khái niệm cơ bản — Ba Chế độ, Đồng hồ Nguyên tố, Dòng thời gian của Đường bộ & Tàu thủy",
    "home.s1.title": "S1: Nhận dạng",
    "home.s2.desc": "Phổ biến công nghệ — Cây bút như một cơ sở hạ tầng, Hệ thống chữ viết",
    "home.s2.title": "S2: Hiểu biết",
    "home.s3.desc": "Thực thi — Sơ đồ quản lý cho mỗi cuộc tiếp sức",
    "home.s3.title": "S3: Quản lý & Kiểm soát",
    "home.s4.desc": "Các đối tác — So sánh Phương Tây, Outrider & Phương Đông cho mỗi cuộc tiếp sức",
    "home.s4.title": "S4: Luận án & Tầm nhìn",
    "home.subtitle": "Quan điểm và Hướng dẫn cho Kỹ sư Xây dựng — Tập 1: Từ Calo đến Ý thức",
    "home.supplements.btn": "Xem tài liệu bổ sung",
    "home.supplements.title": "Tập 2: 4 Tài liệu bổ sung",
    "home.title": "Hành trình Cơ sở hạ tầng",
    "home.trilogy.title": "Tầm nhìn bộ ba",
    "home.vol1.btn": "Đọc Quan điểm",
    "home.vol1.desc": "Nền tảng tường thuật: 12 cuộc tiếp sức của các nền văn minh qua 12.000 năm phát triển cơ sở hạ tầng của loài người. Từ việc làm chủ Lửa đến Torus của Ý thức.",
    "home.vol1.subtitle": "Lịch sử & Bối cảnh — Câu chuyện",
    "home.vol1.title": "Tập 1: Quan điểm",
    "home.vol2.btn": "Đọc Hướng dẫn",
    "home.vol2.desc": "Khung thực tế: Phương pháp so sánh Tây/Đông/Outrider, Phân tích 4C, và các mô hình chiến lược để hiểu cơ sở hạ tầng như là DNA của nền văn minh.",
    "home.vol2.subtitle": "Khung chiến lược — Mở rộng",
    "home.vol2.title": "Tập 2: Hướng dẫn",
    "inst.coming": "Sắp ra mắt — Cơ sở dữ liệu tổ chức đầy đủ đang được xây dựng",
    "inst.sdg.title": "Phân loại theo Mục tiêu Phát triển Bền vững",
    "inst.status.challenged": "Đã thử thách",
    "inst.status.engaged": "Đã tham gia",
    "inst.status.notyet": "Chưa liên hệ",
    "inst.status.potential": "Tiềm năng",
    "inst.subtitle": "Bản đồ Thông tin — Mỗi tổ chức, trường đại học, cơ quan Liên Hợp Quốc, hội chuyên môn, tổ chức phi chính phủ, nhà cung cấp công nghệ và tổ chức vốn có thể được triệu tập, thách thức hoặc hợp tác. Được tổ chức theo Mục tiêu Phát triển Bền vững của Liên Hợp Quốc, nhằm thể hiện sự nhất quán với các ưu tiên toàn cầu.",
    "inst.title": "Cơ quan",
    "lib.supp_title": "Tài liệu bổ sung",
    "lib.title": "Thư viện tài liệu",
    "library.subtitle": "Kho lưu trữ tài sản tri thức hoàn chỉnh",
    "library.title": "Thư viện tài liệu",
    "nav.author": "Tác giả",
    "nav.charter": "Hiến chương",
    "nav.civclock": "Đồng hồ văn minh",
    "nav.clock": "Đồng hồ động viên",
    "nav.documents": "Tài liệu",
    "nav.framework": "Khung chương trình",
    "nav.home": "Trang chủ",
    "nav.institutions": "cơ quan",
    "nav.outriders": "Tiên phong",
    "nav.pioneers": "Kế hoạch Tiên Phong",
    "nav.precis": "Tóm tắt điều hành",
    "nav.resources": "Tài nguyên",
    "nav.supplements": "Tài liệu bổ sung",
    "nav.taxonomy": "Hệ thống phân loại",
    "nav.ep1": "EP.1: Quan điểm",
    "nav.ep2": "EP.2: Hướng dẫn",
    "nav.ep3": "EP.3: Trò chơi",
    "or.conn.book.desc": "Mỗi chương bắt đầu và kết thúc bằng câu nói của những người tiên phong. Sự đổi mới của họ là các nghiên cứu điển hình. Sự thất bại của họ là lời cảnh báo. Họ là cơ sở bằng chứng cho các luận điểm.",
    "or.conn.book.title": "trong sách",
    "or.conn.game.desc": "Những Người Tiên Phong xuất hiện trong mỗi phần tiếp sức với vai trò là NPC hướng dẫn, cung cấp nguồn tham khảo và bối cảnh lịch sử. Người chơi sẽ gặp họ khi trải qua 12 chương.",
    "or.conn.game.title": "Trong trò chơi",
    "or.conn.movement.desc": "Những người tiên phong cung cấp thẩm quyền đạo đức. Khi IAAI thách thức UNESCO hoặc MIT, nó đứng trên vai của 12.000 năm trí tuệ hạ tầng mà những nhân vật này đại diện.",
    "or.conn.movement.title": "Trong vận động",
    "or.conn.title": "Tiên phong phục vụ sứ mệnh như thế nào",
    "or.era1.title": "Thế giới cổ đại",
    "or.era2.title": "Thế giới cổ điển",
    "or.era3.title": "Trung cổ và Phục hưng",
    "or.era4.title": "Cách mạng công nghiệp",
    "or.era5.title": "hiện đại",
    "or.era6.title": "Số hóa và Tương lai",
    "or.quote": "",
    "or.stat.civilisations": "Đại diện văn minh",
    "or.stat.eras": "Thời đại lịch sử",
    "or.stat.relays": "Chuyển tiếp phủ sóng",
    "or.stat.total": "Tổng số người tiên phong",
    "or.subtitle": "Những người thầy tinh thần lịch sử đồng hành cùng từng cấp bậc — không tính vào 6+1 cấp bậc, những người bạn trí tuệ này vượt qua mọi mô hình, mọi chặng tiếp sức, mọi 12.000 năm. Họ là tiếng nói trong trò chơi, câu danh ngôn trên tường, sự kết nối giữa ngọn lửa và mặt vòng của trí tuệ.",
    "or.title": "Tiên phong",
    "pioneers.charter.agree": "Tôi đã đọc và đồng ý với Hiến chương IAAI. Tôi cam kết đóng góp một cách trung thực, tôn trọng văn hóa, cũng như chia sẻ kiến thức một cách mở rộng qua các ngôn ngữ và biên giới. Tôi hiểu đây là một chương trình tình nguyện, và các đóng góp của tôi sẽ được ghi nhận dưới giấy phép CC BY-NC-SA 4.0.",
    "pioneers.charter.text": "Chúng tôi tin rằng cơ sở hạ tầng là hệ điều hành của nền văn minh. Giống như các con sông chảy chậm nhưng bền bỉ khắc họa địa hình để tạo ra sự thay đổi cấp hành tinh, chúng tôi cam kết mở rộng kiến thức, đóng góp dựa trên kinh nghiệm, tôn trọng văn hóa, và hiểu rằng cách chúng ta xây dựng thế giới chính là bước đầu tiên để xây dựng một thế giới tốt đẹp hơn.",
    "pioneers.charter.title": "Hiến chương IAAI",
    "pioneers.form.country": "Quốc gia",
    "pioneers.form.email": "Hộp thư điện tử",
    "pioneers.form.expertise": "Lĩnh vực chuyên ngành",
    "pioneers.form.language": "Ngôn ngữ chính",
    "pioneers.form.motivation": "Tại sao bạn muốn tham gia? (Tùy chọn)",
    "pioneers.form.name": "Họ và tên đầy đủ",
    "pioneers.form.other_langs": "Ngôn ngữ khác",
    "pioneers.form.submit": "Nộp đơn — Tham gia cuộc thi",
    "pioneers.form.subtitle": "Truy cập phiên bản thử nghiệm miễn phí. Không mất phí. Không ràng buộc. Chỉ cần sự tò mò và cam kết.",
    "pioneers.form.title": "Đăng ký trở thành Tiên phong",
    "pioneers.subtitle": "Làn sóng đóng góp đầu tiên sẽ thử nghiệm, dịch thuật, xác minh và lan tỏa kiến thức cơ sở hạ tầng trên mỗi châu lục. Truy cập phiên bản thử nghiệm miễn phí. Giành vị trí của bạn trên Bảng Vinh Danh Người Sáng Lập.",
    "pioneers.tier1.desc": "Những người thử nghiệm đầu tiên. Chơi game, báo lỗi, xác minh nội dung. Mỗi khối ngôn ngữ từ 2-3 người. Trinh sát của mạng lưới tình báo.",
    "pioneers.tier1.req": "Yêu cầu: Tính tò mò, bất kỳ ngôn ngữ nào, sẵn sàng thử nghiệm",
    "pioneers.tier1.title": "Tiên phong",
    "pioneers.tier2.desc": "Người lãnh đạo ngôn ngữ. Xem xét và chỉnh sửa bản dịch AI để phù hợp với cách dùng ngôn ngữ bản địa. Trở thành người đóng góp có ghi danh. Mỗi khối ngôn ngữ gồm 10 người.",
    "pioneers.tier2.req": "Yêu cầu: Thông thạo ngôn ngữ bản địa + Kinh nghiệm tiên phong",
    "pioneers.tier2.title": "Đại sứ",
    "pioneers.tier3.desc": "Người xác thực học thuật. Kỹ sư, giáo sư, nhà nghiên cứu xác minh độ chính xác kỹ thuật và ánh xạ nội dung vào hệ thống khóa học.",
    "pioneers.tier3.req": "Yêu cầu: Trình độ học thuật + Lĩnh vực chuyên môn",
    "pioneers.tier3.title": "học giả",
    "pioneers.tier4.desc": "Hướng dẫn chiến lược. Các nhà lãnh đạo ngành, nhà hoạch định chính sách và những người kết nối tổ chức, mở cánh cửa và định hình hướng đi.",
    "pioneers.tier4.req": "Yêu cầu: Mời hoặc đề cử",
    "pioneers.tier4.title": "Cố vấn",
    "pioneers.title": "Kế hoạch Tiên Phong",
    "precis.relay.epilogue": "Kết luận",
    "precis.relay.prologue": "Lời nói đầu",
    "precis.relay.relay_10_aaa": "Tiếp sức 10: Bộ ba AAA",
    "precis.relay.relay_10_autoair": "Tiếp sức 10: Ô tô/Hàng không",
    "precis.relay.relay_11_humans": "Tiếp sức 11: Nút con người",
    "precis.relay.relay_11_orbit": "Tiếp sức 11: Đường ray",
    "precis.relay.relay_12_programmable": "Tiếp sức 12: Có thể lập trình được",
    "precis.relay.relay_12_torus": "Tiếp sức 12: Vành mặt",
    "precis.relay.relay_1_fire": "Tiếp sức 1: Lửa",
    "precis.relay.relay_2_tree": "Tiếp sức 2: Cây",
    "precis.relay.relay_3_river": "Tiếp sức 3: Dòng sông",
    "precis.relay.relay_4_horse": "Tiếp sức 4: Ngựa",
    "precis.relay.relay_5_road": "Tiếp sức 5: Đường bộ",
    "precis.relay.relay_6_ship": "Tiếp sức 6: Tàu thủy",
    "precis.relay.relay_7_rail": "Tiếp sức 7: Đường sắt",
    "precis.relay.relay_8_loom": "Tiếp sức 8: Máy dệt",
    "precis.relay.relay_9_engine": "Tiếp sức 9: Động cơ",
    "precis.relay.torus": "Mặt vòng",
    "precis.subtitle": "Hành trình Cơ sở hạ tầng — Tổng quan chiến lược",
    "precis.title": "Tóm tắt điều hành",
    "relay.1.name": "Cuộc tiếp sức 1: Lửa",
    "relay.1.subtitle": "Tia lửa ban đầu — Sự khởi đầu của việc làm chủ năng lượng",
    "relay.10.name": "Cuộc tiếp sức 10: Bộ ba AAA",
    "relay.10.subtitle": "Hàng không, Nguyên tử, Tự động hóa — Ba ngôi hiện đại",
    "relay.11.name": "Cuộc tiếp sức 11: Nút người",
    "relay.11.subtitle": "Con người được kết nối mạng — Kết nối kỹ thuật số",
    "relay.12.name": "Cuộc tiếp sức 12: Ý thức",
    "relay.12.subtitle": "Torus — Dạng thức cuối cùng của cơ sở hạ tầng",
    "relay.2.name": "Cuộc tiếp sức 2: Cây",
    "relay.2.subtitle": "Kiến trúc sống — Thiên nhiên như một công trình kỹ thuật",
    "relay.3.name": "Cuộc tiếp sức 3: Sông",
    "relay.3.subtitle": "Văn minh thủy lợi — Cơ sở hạ tầng lỏng",
    "relay.4.name": "Cuộc tiếp sức 4: Ngựa",
    "relay.4.subtitle": "Cách mạng di động — Tốc độ và Đế chế",
    "relay.5.name": "Cuộc tiếp sức 5: Đường bộ",
    "relay.5.subtitle": "Mạng lưới kết nối — Huyết mạch của Đế chế",
    "relay.6.name": "Cuộc tiếp sức 6: Tàu thủy",
    "relay.6.subtitle": "Đại lộ trên đại dương — Mạng lưới thương mại toàn cầu",
    "relay.7.name": "Cuộc tiếp sức 7: Đường sắt",
    "relay.7.subtitle": "Xương sống bằng thép — Kết nối công nghiệp",
    "relay.8.name": "Cuộc tiếp sức 8: Khung cửi",
    "relay.8.subtitle": "Mạng lưới dệt — Cơ sở hạ tầng thông tin",
    "relay.9.name": "Cuộc tiếp sức 9: Động cơ",
    "relay.9.subtitle": "Cách mạng năng lượng — Một thế giới cơ giới hóa",
    "relay.epilogue": "Lời kết",
    "relay.prologue": "Lời mở đầu",
    "resources.subtitle": "Tài liệu tham khảo, Nguồn dữ liệu & Đọc thêm",
    "resources.title": "Tài nguyên",
    "section.4c_analysis": "Phân tích 4C",
    "section.active_webs": "Các mạng lưới hoạt động",
    "section.back_to_index": "Quay lại mục lục",
    "section.challenge": "Thách thức",
    "section.communication_web": "Mạng lưới truyền thông",
    "section.comparative_analysis": "Phân tích so sánh",
    "section.consciousness_web": "Mạng lưới ý thức",
    "section.consequence": "Hậu quả",
    "section.context": "Bối cảnh",
    "section.continuity": "Tính liên tục",
    "section.continuum": "Liên tục thể",
    "section.digital_web": "Mạng kỹ thuật số",
    "section.east_mode": "Chế độ Phương Đông",
    "section.energy_web": "Mạng lưới năng lượng",
    "section.four_pillars": "Bốn trụ cột",
    "section.governance_web": "Mạng lưới quản trị",
    "section.historical_significance": "Ý nghĩa lịch sử",
    "section.impact": "Tác động:",
    "section.information_web": "Mạng lưới thông tin",
    "section.infrastructure": "Cơ sở hạ tầng",
    "section.key_insights": "Những hiểu biết chính",
    "section.knowledge_web": "Mạng lưới tri thức",
    "section.legacy": "Di sản:",
    "section.management_diagram": "Sơ đồ quản lý",
    "section.military_web": "Mạng lưới quân sự",
    "section.next_relay": "Cuộc tiếp sức tiếp theo →",
    "section.outrider_mode": "Chế độ Outrider",
    "section.previous_relay": "← Cuộc tiếp sức trước",
    "section.production_web": "Mạng lưới sản xuất",
    "section.strategic_framework": "Khung chiến lược",
    "section.the_counterparts": "Các đối tác:",
    "section.the_first_infrastructure": "Cơ sở hạ tầng đầu tiên",
    "section.threats": "Các mối đe dọa",
    "section.timeline": "Dòng thời gian:",
    "section.trade_web": "Mạng lưới thương mại",
    "section.transport_web": "Mạng lưới giao thông",
    "section.unification": "Sự thống nhất",
    "section.west_mode": "Chế độ Phương Tây",
    "special.conclusion": "Kết luận",
    "special.epilogue": "Lời kết",
    "special.from_calories_to_consciousness": "Từ Calo đến Ý thức",
    "special.prologue": "Lời mở đầu",
    "special.the_beginning": "Sự khởi đầu",
    "special.the_journey_begins": "Hành trình bắt đầu",
    "special.the_journey_continues": "Hành trình tiếp tục",
    "supplements.s1": "Bổ sung 1: Nhận dạng",
    "supplements.s2": "Bổ sung 2: Hiểu biết",
    "supplements.s3": "Bổ sung 3: Quản lý & Kiểm soát",
    "supplements.s4": "Bổ sung 4: Luận án & Tầm nhìn",
    "supplements.subtitle": "Tài liệu mở rộng chuyên sâu cho Tập 2",
    "supplements.title": "Tài liệu bổ sung",
    "tax.advisors": "Cố vấn",
    "tax.advisors.desc": "Hướng dẫn chiến lược. Nhà lãnh đạo ngành và người kết nối các tổ chức.",
    "tax.ambassadors": "Đại sứ",
    "tax.ambassadors.desc": "Lãnh đạo ngôn ngữ. Mỗi khối ngôn ngữ gồm 10 người.",
    "tax.backers": "Người ủng hộ",
    "tax.backers.desc": "Hỗ trợ về vốn và tổ chức. Nhà tài trợ và đối tác hợp tác.",
    "tax.biology": "Phép ẩn dụ sinh học",
    "tax.count": "Số lượng",
    "tax.founder": "Người sáng lập",
    "tax.founder.desc": "Kiến trúc sư. 1 người. Thiết kế toàn bộ hệ thống.",
    "tax.iaai": "Cấp độ IAAI",
    "tax.outriders.note": "Tiên phong (Người hướng dẫn tinh thần lịch sử) không được tính vào cấp độ 6+1 — Họ vượt qua tất cả các mô hình, tất cả các giai đoạn chuyển tiếp, đồng hành cùng nhau suốt 12.000 năm.",
    "tax.pioneers": "Tiên phong",
    "tax.pioneers.desc": "Những người thử nghiệm đầu tiên. Mỗi khu vực ngôn ngữ có 2-3 người.",
    "tax.players": "Người chơi",
    "tax.players.desc": "Người tham gia trò chơi. Mục tiêu: 1 tỷ người học.",
    "tax.role": "Vai trò",
    "tax.scholars": "học giả",
    "tax.scholars.desc": "Người xác thực học thuật. Giáo sư, kỹ sư, nhà nghiên cứu.",
    "tax.subtitle": "Cấu trúc 6+1 cấp — Tương tự như phân loại sinh học từ giới đến loài, các cấp độ đóng góp của IAAI từ người sáng lập đến người ủng hộ, mỗi cấp đều ngày càng rộng hơn và chuyên môn hơn.",
    "tax.title": "Hệ thống phân loại IAAI",
    "toc.chapter": "Chương",
    "toc.chapter.suffix": "",
    "toc.epilogue": "Lời kết",
    "toc.prologue": "Lời mở đầu",
    "toc.title": "Mục lục",
    "toc.volume1": "Tập 1: Quan điểm — Lịch sử & Bối cảnh",
    "toc.volume2": "Tập 2: Hướng dẫn — Khung chiến lược",
    "toc.volume3": "Tập 3: Trò chơi — Mô phỏng & Thực hành",
    "ui.available": "Đã phát hành",
    "ui.back": "Quay lại",
    "ui.coming.soon": "Sắp ra mắt",
    "ui.download": "Tải xuống",
    "ui.error": "Lỗi khi tải nội dung. Vui lòng thử lại.",
    "ui.loading": "Đang tải...",
    "ui.next": "Tiếp theo",
    "ui.prev": "Trước",
    "ui.read.more": "Đọc thêm",
    "ui.view": "Xem",
    "v1.index.about_title": "Về tập này",
    "v1.index.relays_title": "Mười hai lần tiếp sức",
    "v1.index.title": "Quyển Một: Góc Nhìn",
    "v1.r01.active_webs": "Các mạng lưới hoạt động",
    "v1.r01.counterparts_title": "Các đối tác: Lửa",
    "v1.r01.four_pillars": "Bốn trụ cột",
    "v1.r01.historical_significance": "Ý nghĩa lịch sử",
    "v1.r01.next_relay": "Cuộc tiếp sức tiếp theo →",
    "v1.r01.previous_relay": "← Cuộc tiếp sức trước",
    "v1.r01.subtitle": "Tia lửa ban đầu — Sự khởi đầu của việc làm chủ năng lượng",
    "v1.r01.title": "Cuộc tiếp sức 1: Lửa",
    "v1.r02.active_webs": "Các mạng lưới hoạt động",
    "v1.r02.counterparts_title": "Các đối tác: Cây",
    "v1.r02.four_pillars": "Bốn trụ cột",
    "v1.r02.historical_significance": "Ý nghĩa lịch sử",
    "v1.r02.next_relay": "Cuộc tiếp sức tiếp theo →",
    "v1.r02.previous_relay": "← Cuộc tiếp sức trước",
    "v1.r02.subtitle": "Kiến trúc sống — Thiên nhiên như một công trình kỹ thuật",
    "v1.r02.title": "Cuộc tiếp sức 2: Cây",
    "v1.r03.active_webs": "Các mạng lưới hoạt động",
    "v1.r03.counterparts_title": "Các đối tác: Sông",
    "v1.r03.four_pillars": "Bốn trụ cột",
    "v1.r03.historical_significance": "Ý nghĩa lịch sử",
    "v1.r03.next_relay": "Cuộc tiếp sức tiếp theo →",
    "v1.r03.previous_relay": "← Cuộc tiếp sức trước",
    "v1.r03.subtitle": "Văn minh thủy lợi — Cơ sở hạ tầng lỏng",
    "v1.r03.title": "Cuộc tiếp sức 3: Sông",
    "v1.r04.active_webs": "Các mạng lưới hoạt động",
    "v1.r04.counterparts_title": "Các đối tác: Ngựa",
    "v1.r04.four_pillars": "Bốn trụ cột",
    "v1.r04.historical_significance": "Ý nghĩa lịch sử",
    "v1.r04.next_relay": "Cuộc tiếp sức tiếp theo →",
    "v1.r04.previous_relay": "← Cuộc tiếp sức trước",
    "v1.r04.subtitle": "Cách mạng di động — Tốc độ và Đế chế",
    "v1.r04.title": "Cuộc tiếp sức 4: Ngựa",
    "v1.r05.active_webs": "Các mạng lưới hoạt động",
    "v1.r05.counterparts_title": "Các đối tác: Đường bộ",
    "v1.r05.four_pillars": "Bốn trụ cột",
    "v1.r05.historical_significance": "Ý nghĩa lịch sử",
    "v1.r05.next_relay": "Cuộc tiếp sức tiếp theo →",
    "v1.r05.previous_relay": "← Cuộc tiếp sức trước",
    "v1.r05.subtitle": "Mạng lưới kết nối — Huyết mạch của Đế chế",
    "v1.r05.title": "Cuộc tiếp sức 5: Đường bộ",
    "v1.r06.active_webs": "Các mạng lưới hoạt động",
    "v1.r06.counterparts_title": "Các đối tác: Tàu thủy",
    "v1.r06.four_pillars": "Bốn trụ cột",
    "v1.r06.historical_significance": "Ý nghĩa lịch sử",
    "v1.r06.next_relay": "Cuộc tiếp sức tiếp theo →",
    "v1.r06.previous_relay": "← Cuộc tiếp sức trước",
    "v1.r06.subtitle": "Đại lộ trên đại dương — Mạng lưới thương mại toàn cầu",
    "v1.r06.title": "Cuộc tiếp sức 6: Tàu thủy",
    "v1.r07.active_webs": "Các mạng lưới hoạt động",
    "v1.r07.counterparts_title": "Các đối tác: Đường sắt",
    "v1.r07.four_pillars": "Bốn trụ cột",
    "v1.r07.historical_significance": "Ý nghĩa lịch sử",
    "v1.r07.next_relay": "Cuộc tiếp sức tiếp theo →",
    "v1.r07.previous_relay": "← Cuộc tiếp sức trước",
    "v1.r07.subtitle": "Xương sống bằng thép — Kết nối công nghiệp",
    "v1.r07.title": "Cuộc tiếp sức 7: Đường sắt",
    "v1.r08.active_webs": "Các mạng lưới hoạt động",
    "v1.r08.counterparts_title": "Các đối tác: Khung cửi",
    "v1.r08.four_pillars": "Bốn trụ cột",
    "v1.r08.historical_significance": "Ý nghĩa lịch sử",
    "v1.r08.next_relay": "Cuộc tiếp sức tiếp theo →",
    "v1.r08.previous_relay": "← Cuộc tiếp sức trước",
    "v1.r08.subtitle": "Mạng lưới dệt — Cơ sở hạ tầng thông tin",
    "v1.r08.title": "Cuộc tiếp sức 8: Khung cửi",
    "v1.r09.active_webs": "Các mạng lưới hoạt động",
    "v1.r09.counterparts_title": "Các đối tác: Động cơ",
    "v1.r09.four_pillars": "Bốn trụ cột",
    "v1.r09.historical_significance": "Ý nghĩa lịch sử",
    "v1.r09.next_relay": "Cuộc tiếp sức tiếp theo →",
    "v1.r09.previous_relay": "← Cuộc tiếp sức trước",
    "v1.r09.subtitle": "Cách mạng năng lượng — Một thế giới cơ giới hóa",
    "v1.r09.title": "Cuộc tiếp sức 9: Động cơ",
    "v1.r10.active_webs": "Các mạng lưới hoạt động",
    "v1.r10.counterparts_title": "Các đối tác: Bộ ba AAA",
    "v1.r10.four_pillars": "Bốn trụ cột",
    "v1.r10.historical_significance": "Ý nghĩa lịch sử",
    "v1.r10.next_relay": "Cuộc tiếp sức tiếp theo →",
    "v1.r10.previous_relay": "← Cuộc tiếp sức trước",
    "v1.r10.subtitle": "Hàng không, Nguyên tử, Tự động hóa — Ba ngôi hiện đại",
    "v1.r10.title": "Cuộc tiếp sức 10: Bộ ba AAA",
    "v1.r11.active_webs": "Các mạng lưới hoạt động",
    "v1.r11.counterparts_title": "Các đối tác: Nút người",
    "v1.r11.four_pillars": "Bốn trụ cột",
    "v1.r11.historical_significance": "Ý nghĩa lịch sử",
    "v1.r11.next_relay": "Cuộc tiếp sức tiếp theo →",
    "v1.r11.previous_relay": "← Cuộc tiếp sức trước",
    "v1.r11.subtitle": "Con người được kết nối mạng — Kết nối kỹ thuật số",
    "v1.r11.title": "Cuộc tiếp sức 11: Nút người",
    "v1.r12.active_webs": "Các mạng lưới hoạt động",
    "v1.r12.counterparts_title": "Các đối tác: Ý thức",
    "v1.r12.four_pillars": "Bốn trụ cột",
    "v1.r12.historical_significance": "Ý nghĩa lịch sử",
    "v1.r12.next_relay": "Cuộc tiếp sức tiếp theo →",
    "v1.r12.previous_relay": "← Cuộc tiếp sức trước",
    "v1.r12.subtitle": "Torus — Dạng thức cuối cùng của cơ sở hạ tầng",
    "v1.r12.title": "Cuộc tiếp sức 12: Ý thức",
    "v2.index.about_text": "Tập hai: Hướng dẫn áp dụng khung bốn trụ (Quan sát → Giáo dục → Ứng dụng → Chủ đề) vào từng lần trong mười hai lần tiếp sức văn minh. Tập này cung cấp hướng dẫn thực tiễn, giúp hiểu cách hệ thống cơ sở hạ tầng vận hành, cách phân tích và cách áp dụng vào các thách thức đương đại.",
    "v2.index.about_title": "Về tập tài liệu này",
    "v2.index.app": "Ứng dụng",
    "v2.index.app_text": "Chúng ta áp dụng những bài học này như thế nào? Cuộc tiếp sức lần này đã tạo ra những khung công tác và công cụ thực tiễn nào?",
    "v2.index.edu": "Giáo dục",
    "v2.index.edu_text": "Chúng ta có thể học được gì từ cuộc tiếp sức lần này? Nó dạy cho chúng ta những nguyên lý và bài học gì về cơ sở hạ tầng?",
    "v2.index.framework_title": "Khung bốn trụ",
    "v2.index.obs": "Quan sát",
    "v2.index.obs_text": "Chúng ta đã quan sát được gì về cuộc tiếp sức lần này? Đặc điểm, các thành phần và mô hình của nó là gì?",
    "v2.index.relays_caption": "Mười hai lần tiếp sức văn minh — Từ lửa đến ý thức",
    "v2.index.subtitle": "Hướng dẫn — Khung thực tiễn và Phân tích mở rộng",
    "v2.index.thesis": "Luận đề",
    "v2.index.thesis_text": "Chủ đề tổng thể là gì? Những hiểu biết cơ bản mà lần tiếp sức này tiết lộ là gì?",
    "v2.index.title": "Quyển Hai: Hướng Dẫn",
    "v2.r01.active_webs": "Các mạng lưới hoạt động",
    "v2.r01.counterparts_title": "Các đối tác: Lửa",
    "v2.r01.four_pillars": "Bốn trụ cột",
    "v2.r01.historical_significance": "Ý nghĩa lịch sử",
    "v2.r01.next_relay": "Cuộc tiếp sức tiếp theo →",
    "v2.r01.previous_relay": "← Cuộc tiếp sức trước",
    "v2.r01.subtitle": "Tia lửa ban đầu — Sự khởi đầu của việc làm chủ năng lượng",
    "v2.r01.title": "Cuộc tiếp sức 1: Lửa",
    "v2.r02.active_webs": "Các mạng lưới hoạt động",
    "v2.r02.counterparts_title": "Các đối tác: Cây",
    "v2.r02.four_pillars": "Bốn trụ cột",
    "v2.r02.historical_significance": "Ý nghĩa lịch sử",
    "v2.r02.next_relay": "Cuộc tiếp sức tiếp theo →",
    "v2.r02.previous_relay": "← Cuộc tiếp sức trước",
    "v2.r02.subtitle": "Kiến trúc sống — Thiên nhiên như một công trình kỹ thuật",
    "v2.r02.title": "Cuộc tiếp sức 2: Cây",
    "v2.r03.active_webs": "Các mạng lưới hoạt động",
    "v2.r03.counterparts_title": "Các đối tác: Sông",
    "v2.r03.four_pillars": "Bốn trụ cột",
    "v2.r03.historical_significance": "Ý nghĩa lịch sử",
    "v2.r03.next_relay": "Cuộc tiếp sức tiếp theo →",
    "v2.r03.previous_relay": "← Cuộc tiếp sức trước",
    "v2.r03.subtitle": "Văn minh thủy lợi — Cơ sở hạ tầng lỏng",
    "v2.r03.title": "Cuộc tiếp sức 3: Sông",
    "v2.r04.active_webs": "Các mạng lưới hoạt động",
    "v2.r04.counterparts_title": "Các đối tác: Ngựa",
    "v2.r04.four_pillars": "Bốn trụ cột",
    "v2.r04.historical_significance": "Ý nghĩa lịch sử",
    "v2.r04.next_relay": "Cuộc tiếp sức tiếp theo →",
    "v2.r04.previous_relay": "← Cuộc tiếp sức trước",
    "v2.r04.subtitle": "Cách mạng di động — Tốc độ và Đế chế",
    "v2.r04.title": "Cuộc tiếp sức 4: Ngựa",
    "v2.r05.active_webs": "Các mạng lưới hoạt động",
    "v2.r05.counterparts_title": "Các đối tác: Đường bộ",
    "v2.r05.four_pillars": "Bốn trụ cột",
    "v2.r05.historical_significance": "Ý nghĩa lịch sử",
    "v2.r05.next_relay": "Cuộc tiếp sức tiếp theo →",
    "v2.r05.previous_relay": "← Cuộc tiếp sức trước",
    "v2.r05.subtitle": "Mạng lưới kết nối — Huyết mạch của Đế chế",
    "v2.r05.title": "Cuộc tiếp sức 5: Đường bộ",
    "v2.r06.active_webs": "Các mạng lưới hoạt động",
    "v2.r06.counterparts_title": "Các đối tác: Tàu thủy",
    "v2.r06.four_pillars": "Bốn trụ cột",
    "v2.r06.historical_significance": "Ý nghĩa lịch sử",
    "v2.r06.next_relay": "Cuộc tiếp sức tiếp theo →",
    "v2.r06.previous_relay": "← Cuộc tiếp sức trước",
    "v2.r06.subtitle": "Đại lộ trên đại dương — Mạng lưới thương mại toàn cầu",
    "v2.r06.title": "Cuộc tiếp sức 6: Tàu thủy",
    "v2.r07.active_webs": "Các mạng lưới hoạt động",
    "v2.r07.counterparts_title": "Các đối tác: Đường sắt",
    "v2.r07.four_pillars": "Bốn trụ cột",
    "v2.r07.historical_significance": "Ý nghĩa lịch sử",
    "v2.r07.next_relay": "Cuộc tiếp sức tiếp theo →",
    "v2.r07.previous_relay": "← Cuộc tiếp sức trước",
    "v2.r07.subtitle": "Xương sống bằng thép — Kết nối công nghiệp",
    "v2.r07.title": "Cuộc tiếp sức 7: Đường sắt",
    "v2.r08.active_webs": "Các mạng lưới hoạt động",
    "v2.r08.counterparts_title": "Các đối tác: Khung cửi",
    "v2.r08.four_pillars": "Bốn trụ cột",
    "v2.r08.historical_significance": "Ý nghĩa lịch sử",
    "v2.r08.next_relay": "Cuộc tiếp sức tiếp theo →",
    "v2.r08.previous_relay": "← Cuộc tiếp sức trước",
    "v2.r08.subtitle": "Mạng lưới dệt — Cơ sở hạ tầng thông tin",
    "v2.r08.title": "Cuộc tiếp sức 8: Khung cửi",
    "v2.r09.active_webs": "Các mạng lưới hoạt động",
    "v2.r09.counterparts_title": "Các đối tác: Động cơ",
    "v2.r09.four_pillars": "Bốn trụ cột",
    "v2.r09.historical_significance": "Ý nghĩa lịch sử",
    "v2.r09.next_relay": "Cuộc tiếp sức tiếp theo →",
    "v2.r09.previous_relay": "← Cuộc tiếp sức trước",
    "v2.r09.subtitle": "Cách mạng năng lượng — Một thế giới cơ giới hóa",
    "v2.r09.title": "Cuộc tiếp sức 9: Động cơ",
    "v2.r10.active_webs": "Các mạng lưới hoạt động",
    "v2.r10.counterparts_title": "Các đối tác: Bộ ba AAA",
    "v2.r10.four_pillars": "Bốn trụ cột",
    "v2.r10.historical_significance": "Ý nghĩa lịch sử",
    "v2.r10.next_relay": "Cuộc tiếp sức tiếp theo →",
    "v2.r10.previous_relay": "← Cuộc tiếp sức trước",
    "v2.r10.subtitle": "Hàng không, Nguyên tử, Tự động hóa — Ba ngôi hiện đại",
    "v2.r10.title": "Cuộc tiếp sức 10: Bộ ba AAA",
    "v2.r11.active_webs": "Các mạng lưới hoạt động",
    "v2.r11.counterparts_title": "Các đối tác: Nút người",
    "v2.r11.four_pillars": "Bốn trụ cột",
    "v2.r11.historical_significance": "Ý nghĩa lịch sử",
    "v2.r11.next_relay": "Cuộc tiếp sức tiếp theo →",
    "v2.r11.previous_relay": "← Cuộc tiếp sức trước",
    "v2.r11.subtitle": "Con người được kết nối mạng — Kết nối kỹ thuật số",
    "v2.r11.title": "Cuộc tiếp sức 11: Nút người",
    "v2.r12.active_webs": "Các mạng lưới hoạt động",
    "v2.r12.counterparts_title": "Các đối tác: Ý thức",
    "v2.r12.four_pillars": "Bốn trụ cột",
    "v2.r12.historical_significance": "Ý nghĩa lịch sử",
    "v2.r12.next_relay": "Cuộc tiếp sức tiếp theo →",
    "v2.r12.previous_relay": "← Cuộc tiếp sức trước",
    "v2.r12.subtitle": "Torus — Dạng thức cuối cùng của cơ sở hạ tầng",
    "v2.r12.title": "Cuộc tiếp sức 12: Ý thức",
    "v3.index.experience_title": "Trải nghiệm tiếp sức",
    "v3.index.title": "Quyển Ba: Trò Chơi",
    "vol1.index.desc": "Khám phá 12.000 năm phát triển cơ sở hạ tầng qua 12 cuộc tiếp sức của các nền văn minh. Mỗi cuộc tiếp sức đại diện cho một bước nhảy vọt cơ bản trong năng lực của con người.",
    "vol1.index.subtitle": "Lịch sử & Bối cảnh — Câu chuyện",
    "vol1.index.title": "Tập 1: Quan điểm",
    "vol2.index.desc": "Các khung thực tế, phân tích so sánh và mô hình chiến lược cho mỗi cuộc tiếp sức. So sánh sâu sắc các phương pháp của Phương Tây, Phương Đông và Outrider.",
    "vol2.index.subtitle": "Khung chiến lược — Mở rộng",
    "vol2.index.title": "Tập 2: Hướng dẫn",
    "vol3.index.desc": "Nền tảng học tập có hướng dẫn của Cỗ máy thực tại. Áp dụng các khái niệm trong một môi trường mô phỏng năng động.",
    "vol3.index.subtitle": "Mô phỏng & Thực hành — Ứng dụng",
    "vol3.index.title": "Tập 3: Trò chơi",
    "home.charter.charter.h": "HIẾN CHƯƠNG",
    "home.charter.charter.p": "Chúng tôi tin rằng cơ sở hạ tầng là hệ điều hành của nền văn minh. Giống như dòng sông chậm rãi và bền bỉ bào mòn mặt đất để tạo ra thay đổi ở quy mô hành tinh, chúng tôi cam kết với kiến thức mở, đóng góp được xác minh, tôn trọng văn hóa và niềm tin rằng hiểu cách chúng ta xây dựng thế giới là bước đầu tiên để xây dựng nó tốt hơn.",
    "home.charter.mission.h": "SỨ MỆNH",
    "home.charter.mission.p": "Cung cấp nền tảng giáo dục cơ sở hạ tầng mở, đa ngôn ngữ, được AI hướng dẫn đầu tiên trên thế giới — tiếp cận 1 tỷ người học qua 8 ngôn ngữ, được xác minh bởi những người đóng góp từ mọi châu lục.",
    "home.charter.title": "SỨ MỆNH, TẦM NHÌN & HIẾN CHƯƠNG",
    "home.charter.vision.h": "TẦM NHÌN",
    "home.charter.vision.p": "Một thế giới nơi mọi người hiểu được cơ sở hạ tầng duy trì nền văn minh — và có kiến thức để xây dựng những gì tiếp theo.",
    "home.pop.answer": "IAAI tồn tại để thay đổi con số đó.",
    "home.pop.question": "người chia sẻ cơ sở hạ tầng của hành tinh này. Bao nhiêu người hiểu nó?",
    "home.pop.source": "Nguồn: Ước tính Dân số Thế giới của LHQ (dự báo thời gian thực)",
    "home.ppp.cta.sub": "Truy cập beta miễn phí — Kiểm tra, dịch thuật, xác nhận và giành vị trí của bạn trên Bức tường Sáng lập. Tham gia Odyssey.",
    "home.ppp.cta.title": "Trở thành Người tiên phong",
    "home.ppp.partners.h": "ĐỐI TÁC",
    "home.ppp.partners.p": "Các trường đại học, nền tảng công nghệ và công ty cơ sở hạ tầng. MIT OCW, Khan Academy, Meta/VR, Manus/AI, AECOM, Arup, Bechtel. Công nghệ, xác nhận nội dung và tiếp cận thị trường.",
    "home.ppp.partners.status": "Trạng thái: Mở thách thức — Được đề cử bởi Người chơi",
    "home.ppp.patrons.h": "NHÀ BẢO TRỢ",
    "home.ppp.patrons.p": "Các tổ chức có sứ mệnh phù hợp với giáo dục cơ sở hạ tầng toàn cầu. UNESCO, National Geographic, NASA, Hội Hoàng gia, Discovery, Smithsonian, NOAA, Ngân hàng Thế giới, ADB, Viện Hàn lâm Khoa học Trung Quốc.",
    "home.ppp.patrons.status": "Trạng thái: Mở thách thức — Được đề cử bởi Người chơi",
    "home.ppp.players.h": "NGƯỜI CHƠI",
    "home.ppp.players.p": "Người tiên phong, Đại sứ, Học giả và Cố vấn từ mọi quốc gia. Những người thực sự kiểm tra, dịch thuật, xác nhận, đóng góp và lan truyền thông điệp. Sức mạnh của dân chủ.",
    "home.ppp.players.status": "Trạng thái: Tuyển dụng Người tiên phong — Truy cập Beta Miễn phí",
    "home.ppp.reach.active": "HOẠT ĐỘNG",
    "home.ppp.reach.active2": "HOẠT ĐỘNG",
    "home.ppp.reach.active3": "HOẠT ĐỘNG",
    "home.ppp.reach.active4": "HOẠT ĐỘNG",
    "home.ppp.reach.active5": "HOẠT ĐỘNG",
    "home.ppp.reach.active6": "HOẠT ĐỘNG",
    "home.ppp.reach.active7": "HOẠT ĐỘNG",
    "home.ppp.reach.active8": "HOẠT ĐỘNG",
    "home.ppp.reach.ar": "Tiếng Ả Rập",
    "home.ppp.reach.cn": "Tiếng Trung",
    "home.ppp.reach.coverage": "8 ngôn ngữ bao phủ ~85% thị trường game toàn cầu, ~80% chi tiêu EdTech và các hành lang đầu tư cơ sở hạ tầng hàng đầu.",
    "home.ppp.reach.en": "Tiếng Anh",
    "home.ppp.reach.es": "Tiếng Tây Ban Nha",
    "home.ppp.reach.h": "PHẠM VI NGÔN NGỮ TOÀN CẦU",
    "home.ppp.reach.hi": "Tiếng Hindi",
    "home.ppp.reach.ja": "Tiếng Nhật",
    "home.ppp.reach.ko": "Tiếng Hàn",
    "home.ppp.reach.vi": "Tiếng Việt",
    "home.ppp.subtitle": "Từ calo đến ý thức — lời kêu gọi hành động ở cấp độ cá nhân không thể bị ngăn chặn hay kiểm soát. Nó chỉ tiếp tục học hỏi.",
    "home.ppp.title": "NHÀ BẢO TRỢ, ĐỐI TÁC & NGƯỜI CHƠI",
    "nav.founders": "TƯỜNG SÁNG LẬP",
    // ============================================
    // MISSING KEYS - ADDED BY TRANSLATION GENERATOR
    // ============================================
    "home.guide.btn": "ĐỌC HƯỚNG DẪN",
    "home.guide.title": "TẬP 2: HƯỚNG DẪN",
    "masters.subtitle": "Những hướng dẫn viên tâm linh lịch sử đồng hành cùng mọi cấp bậc — Không tính trong hệ thống phân cấp 6+1, những người bạn trí tuệ này trải dài qua mọi chế độ, mọi cuộc tiếp sức, suốt 12.000 năm. Họ là giọng nói trong trò chơi, câu trích dẫn trên tường, trí tuệ kết nối lửa với hình xuyến.",
    "masters.title": "BẬC THẦY",
    "nav.glossary": "THUẬT NGỮ",
    "nav.masters": "BẬC THẦY",
    "nav.olympiad": "OLYMPIAD",
    "nav.starthere": "BẮT ĐẦU TỪ ĐÂY",
    "precis.relay.relay_10_orbit": "TIẾP SỨC 11: QUỸ ĐẠO",
    "precis.relay.relay_11_human_nodes": "TIẾP SỨC 12: NÚT NHÂN LOẠI",
    "precis.relay.relay_1_tree": "TIẾP SỨC 2: CÂY",
    "precis.relay.relay_2_river": "TIẾP SỨC 3: SÔNG",
    "precis.relay.relay_3_horse": "TIẾP SỨC 4: NGỰA",
    "precis.relay.relay_4_roads": "TIẾP SỨC 5: ĐƯỜNG",
    "precis.relay.relay_5_ships": "TIẾP SỨC 6: TÀU",
    "precis.relay.relay_6_loom": "TIẾP SỨC 7: KHUNG CỬI",
    "precis.relay.relay_8_engine": "TIẾP SỨC 9: ĐỘNG CƠ",
    "precis.relay.relay_9_aaa": "TIẾP SỨC 10: BỘ BA AAA",
    "tax.cta": "TÌM VỊ TRÍ CỦA BẠN TRONG CÂY",
    "tax.cta.sub": "Mỗi loài bắt đầu từ một sinh vật. Mỗi phong trào bắt đầu từ một người tiên phong.",
    "tax.footer.cc": "CC BY-NC-SA 4.0",
    "tax.parallel.institutions.desc": "Organisations that can be challenged, engaged, or partnered with. Universities, UN bodies, professional societies, government agencies, NGOs, and corporations. They sit outside the contributor hierarchy but are the targets of the intelligence network and the Challenge Board.",
    "tax.parallel.institutions.title": "&#x1F3DB; Institutions &mdash; The Challenge Map",
    "tax.parallel.institutions.who": "UNESCO &bull; World Bank &bull; ASCE &bull; ICE &bull; MIT &bull; Khan Academy &bull; Meta &bull; National Geographic",
    "tax.parallel.outriders.desc": "Historical and philosophical figures who ride alongside every tier as intellectual companions. Not counted in the 6+1 &mdash; they exist across all levels, all modes, all time periods. They are the voices in the game, the quotes on the walls, the wisdom that connects 12,000 years of infrastructure.",
    "tax.parallel.outriders.title": "&#x1F3C7; Outriders &mdash; Spirit Guides",
    "tax.parallel.outriders.who": "Laozi &bull; Sun Tzu &bull; Confucius &bull; Vitruvius &bull; Leonardo da Vinci &bull; Isambard Kingdom Brunel &bull; Nikola Tesla &bull; Ada Lovelace",
    "tax.parallel.title": "Đường Song Song (Ngoài Hệ Thống Phân Cấp)",
    "tax.plus1.desc": "Trong sinh học, Loài là phân loại cụ thể nhất — sinh vật cá thể. Trong IAAI, +1 là một tỷ người học",
    "tax.plus1.subtitle": "12,1% Nhân Loại — Điểm Bùng Phát cho Hiểu Biết Hạ Tầng",
    "tax.plus1.target": "MỤC TIÊU: 1.000.000.000",
    "tax.plus1.title": "+1 — LOÀI",
    "tax.quote": "\"Cũng như mọi sự sống chia sẻ một tổ tiên chung, mọi cơ sở hạ tầng chia sẻ một mục đích chung — phục vụ nền văn minh.\"",
    "tax.rank.class": "Lớp",
    "tax.rank.domain": "Vực",
    "tax.rank.family": "Họ",
    "tax.rank.genus": "Chi",
    "tax.rank.kingdom": "Giới",
    "tax.rank.order": "Bộ",
    "tax.rank.phylum": "Ngành",
    "tax.table.biology": "Sinh học",
    "tax.table.count": "Số lượng",
    "tax.table.iaai": "IAAI",
    "tax.table.suntzu": "Tình báo (INT)",
    "tax.tier1.analogy": "Biology: Domain (Eukarya) &bull; Military: Commander-in-Chief &bull; Architecture: Master Builder",
    "tax.tier1.desc": "The singular origin point. Conceived the 12-relay framework, wrote the trilogy, designed the game, and built the platform. Like Domain in biology &mdash; the broadest, most fundamental classification from which everything else branches.",
    "tax.tier1.name": "NGƯỜI SÁNG LẬP",
    "tax.tier1.title": "Kiến Trúc Sư",
    "tax.tier1.who": "Ir. Nigel T. Dearden &mdash; CEng MICE MHKIE",
    "tax.tier2.analogy": "Biology: Kingdom (Animalia) &bull; Military: General Staff &bull; Sun Tzu: The Five Essentials",
    "tax.tier2.desc": "The inner circle. Industry leaders, capital strategists, and institutional connectors who shape direction, open doors, and bridge the gap between vision and execution. By invitation or nomination only.",
    "tax.tier2.name": "CỐ VẤN",
    "tax.tier2.title": "Hội Đồng Chiến Lược",
    "tax.tier2.who": "Michael Wu (COO) &bull; Henry Leong (CFO) &bull; Frank Sheu (CTO) &bull; Stephen Markscheid (Strategic Advisor)",
    "tax.tier3.analogy": "Biology: Phylum (Chordata) &bull; Military: Intelligence Corps &bull; Academia: Peer Review Board",
    "tax.tier3.desc": "Engineers, professors, and researchers who verify technical accuracy, map content to university curricula, and provide the academic credibility that transforms a game into an educational standard. The peer-review layer.",
    "tax.tier3.name": "HỌC GIẢ",
    "tax.tier3.title": "Người Xác Nhận Học Thuật",
    "tax.tier3.who": "Target: Engineering faculties, infrastructure researchers, curriculum designers",
    "tax.tier4.analogy": "Biology: Class (Mammalia) &bull; Military: Field Officers &bull; Diplomacy: Cultural Attach&eacute;s",
    "tax.tier4.desc": "Native-fluency contributors who review and correct AI translations against real usage. 10 per language block across 8 languages. They ensure infrastructure literacy speaks authentically in every tongue. Credited contributors with their names on the work.",
    "tax.tier4.name": "ĐẠI SỨ",
    "tax.tier4.title": "Trưởng Nhóm Ngôn Ngữ",
    "tax.tier4.who": "Target: 10 per block &times; 8 blocks = 80 Ambassadors worldwide",
    "tax.tier5.analogy": "Biology: Order (Primates) &bull; Military: HUMINT (Human Intelligence) &bull; Scouts &amp; Reconnaissance",
    "tax.tier5.desc": "The first wave. 2&ndash;3 per language block who play the game, report bugs, validate content, and provide the ground-truth feedback that shapes the platform before public release. The HUMINT assets of the intelligence network — human intelligence on the ground.",
    "tax.tier5.name": "TIÊN PHONG",
    "tax.tier5.title": "Người Thử Nghiệm & Trinh Sát",
    "tax.tier5.who": "Currently recruiting &mdash; 3 active across EN and CN blocks",
    "tax.tier6.analogy": "Biology: Family (Hominidae) &bull; Military: The Rank and File &bull; Gaming: The Player Base",
    "tax.tier6.desc": "Everyone who plays The Reality Engine. From casual explorers to completionists who master all 12 relays across all 4 modes. They generate the data, the engagement, and the democratic nominations that power the Challenge Board. The lifeblood of the platform.",
    "tax.tier6.name": "NGƯỜI CHƠI",
    "tax.tier6.title": "Cộng Đồng Game",
    "tax.tier6.who": "Target: 1M players by Year 2 &bull; Currently: 21 (beta)",
    "tax.tier7.analogy": "Biology: Genus (Homo) &bull; Military: ELINT (Electronic Intelligence) &bull; Logistics &amp; Supply",
    "tax.tier7.desc": "Those who fund the mission &mdash; from individual Kickstarter backers to institutional patrons (UNESCO, National Geographic, universities). They don't play or translate; they enable. Challenged by Players, engaged by Advisors. The ELINT channel of the intelligence network — converting institutional signals into engagement.",
    "tax.tier7.name": "NHÀ TÀI TRỢ",
    "tax.tier7.title": "Hỗ Trợ Tài Chính & Tổ Chức",
    "tax.tier7.who": "Target: $500K seed &bull; Challenged: UNESCO, NatGeo, NASA, Royal Society, MIT OCW, Khan Academy",
    "v1.r01.continuity": "TÍNH LIÊN TỤC",
    "v1.r01.energy_web": "MẠNG NĂNG LƯỢNG",
    "v1.r01.infrastructure": "CƠ SỞ HẠ TẦNG",
    "v1.r01.knowledge_web": "MẠNG TRI THỨC",
    "v1.r01.threats": "MỐI ĐE DỌA",
    "v1.r01.unification": "THỐNG NHẤT",
    "v1.r02.continuity": "TÍNH LIÊN TỤC",
    "v1.r02.energy_web": "MẠNG NĂNG LƯỢNG",
    "v1.r02.infrastructure": "CƠ SỞ HẠ TẦNG",
    "v1.r02.knowledge_web": "MẠNG TRI THỨC",
    "v1.r02.threats": "MỐI ĐE DỌA",
    "v1.r02.unification": "THỐNG NHẤT",
    "v1.r03.continuity": "TÍNH LIÊN TỤC",
    "v1.r03.energy_web": "MẠNG NĂNG LƯỢNG",
    "v1.r03.infrastructure": "CƠ SỞ HẠ TẦNG",
    "v1.r03.knowledge_web": "MẠNG TRI THỨC",
    "v1.r03.threats": "MỐI ĐE DỌA",
    "v1.r03.unification": "THỐNG NHẤT",
    "v1.r04.continuity": "TÍNH LIÊN TỤC",
    "v1.r04.energy_web": "MẠNG NĂNG LƯỢNG",
    "v1.r04.infrastructure": "CƠ SỞ HẠ TẦNG",
    "v1.r04.threats": "MỐI ĐE DỌA",
    "v1.r04.unification": "THỐNG NHẤT",
    "v1.r05.consciousness_web": "MẠNG Ý THỨC",
    "v1.r05.continuity": "TÍNH LIÊN TỤC",
    "v1.r05.infrastructure": "CƠ SỞ HẠ TẦNG",
    "v1.r05.knowledge_web": "MẠNG TRI THỨC",
    "v1.r05.threats": "MỐI ĐE DỌA",
    "v1.r05.unification": "THỐNG NHẤT",
    "v1.r06.consciousness_web": "MẠNG Ý THỨC",
    "v1.r06.continuity": "TÍNH LIÊN TỤC",
    "v1.r06.infrastructure": "CƠ SỞ HẠ TẦNG",
    "v1.r06.knowledge_web": "MẠNG TRI THỨC",
    "v1.r06.threats": "MỐI ĐE DỌA",
    "v1.r06.unification": "THỐNG NHẤT",
    "v1.r07.continuity": "TÍNH LIÊN TỤC",
    "v1.r07.energy_web": "MẠNG NĂNG LƯỢNG",
    "v1.r07.infrastructure": "CƠ SỞ HẠ TẦNG",
    "v1.r07.knowledge_web": "MẠNG TRI THỨC",
    "v1.r07.threats": "MỐI ĐE DỌA",
    "v1.r07.unification": "THỐNG NHẤT",
    "v1.r08.consciousness_web": "MẠNG Ý THỨC",
    "v1.r08.continuity": "TÍNH LIÊN TỤC",
    "v1.r08.energy_web": "MẠNG NĂNG LƯỢNG",
    "v1.r08.infrastructure": "CƠ SỞ HẠ TẦNG",
    "v1.r08.knowledge_web": "MẠNG TRI THỨC",
    "v1.r08.threats": "MỐI ĐE DỌA",
    "v1.r08.unification": "THỐNG NHẤT",
    "v1.r09.continuity": "TÍNH LIÊN TỤC",
    "v1.r09.energy_web": "MẠNG NĂNG LƯỢNG",
    "v1.r09.infrastructure": "CƠ SỞ HẠ TẦNG",
    "v1.r09.knowledge_web": "MẠNG TRI THỨC",
    "v1.r09.threats": "MỐI ĐE DỌA",
    "v1.r09.unification": "THỐNG NHẤT",
    "v1.r10.consciousness_web": "MẠNG Ý THỨC",
    "v1.r10.continuity": "TÍNH LIÊN TỤC",
    "v1.r10.energy_web": "MẠNG NĂNG LƯỢNG",
    "v1.r10.infrastructure": "CƠ SỞ HẠ TẦNG",
    "v1.r10.knowledge_web": "MẠNG TRI THỨC",
    "v1.r10.threats": "MỐI ĐE DỌA",
    "v1.r10.unification": "THỐNG NHẤT",
    "v1.r11.consciousness_web": "MẠNG Ý THỨC",
    "v1.r11.continuity": "TÍNH LIÊN TỤC",
    "v1.r11.infrastructure": "CƠ SỞ HẠ TẦNG",
    "v1.r11.knowledge_web": "MẠNG TRI THỨC",
    "v1.r11.threats": "MỐI ĐE DỌA",
    "v1.r11.unification": "THỐNG NHẤT",
    "v1.r12.consciousness_web": "MẠNG Ý THỨC",
    "v1.r12.continuity": "TÍNH LIÊN TỤC",
    "v1.r12.infrastructure": "CƠ SỞ HẠ TẦNG",
    "v1.r12.knowledge_web": "MẠNG TRI THỨC",
    "v1.r12.threats": "MỐI ĐE DỌA",
    "v1.r12.unification": "THỐNG NHẤT",
    "oly.title": "OLYMPIC CƠ SỞ HẠ TẦNG",
    "oly.stat.blocks": "Khối Ngôn ngữ",
    "oly.stat.categories": "Hạng mục Thi đấu",
    "oly.stat.universities": "Đại học Toàn cầu",
    "oly.stat.xpcap": "Giới hạn XP (Bậc Thầy)",
    "oly.stat.people": "Người Tiếp cận",
    "oly.stat.gap": "Khoảng cách Hạ tầng",
    "oly.flywheel.title": "Bánh đà — Olympic Tự phát triển Như thế nào",
    "oly.flywheel.players": "Người chơi Thi đấu",
    "oly.flywheel.professionals": "Chuyên gia Xác nhận",
    "oly.flywheel.patrons": "Nhà tài trợ Hỗ trợ",
    "oly.flywheel.platform": "Nền tảng Mở rộng",
    "oly.medal.title": "Bảng Huy chương Trực tiếp — Các Quốc gia Thi đấu về Quản lý Văn minh",
    "oly.th.nation": "Quốc gia",
    "oly.th.blocks": "Khối",
    "oly.th.pop": "Dân số (Tr)",
    "oly.th.gamers": "Game thủ (Tr)",
    "oly.th.story": "Câu chuyện Hạ tầng",
    "oly.th.total": "Tổng",
    "oly.th.status": "Trạng thái",
    "oly.rogue.title": "ĐỘI ROGUE — NHÂN TÀI KHÔNG LIÊN KẾT",
    "oly.categories.title": "Hạng mục Thi đấu — Sáu Trụ cột Hạ tầng Văn minh",
    "oly.pipeline.unis": "Đại học Toàn cầu",
    "oly.pipeline.students": "Sinh viên Kỹ thuật",
    "oly.pipeline.firms": "Công ty Xây dựng Hàng đầu",
    "oly.pipeline.govts": "Chính phủ Quốc gia",
    "oly.sponsor.title": "Cấp Tài trợ — Hỗ trợ Đội Quốc gia",
    "oly.sponsor.gold": "Nhà tài trợ Vàng",
    "oly.sponsor.silver": "Nhà tài trợ Bạc",
    "oly.sponsor.bronze": "Nhà tài trợ Đồng",
    "oly.sponsor.patron": "Người Bảo trợ",
    "oly.form.register.title": "ĐĂNG KÝ ĐỘI ĐẠI HỌC",
    "oly.form.sponsor.title": "YÊU CẦU TÀI TRỢ",
    "nav.behind": "ĐẰNG SAU LUẬN VĂN",

    // SDG Alignment Section
    "sdg.title": "MỤC TIÊU PHÁT TRIỂN BỀN VỮNG — LIÊN KẾT",
    "sdg.subtitle": "Chương trình 12 chặng tiếp sức của IAAI liên kết với Mục tiêu Phát triển Bền vững của Liên Hợp Quốc như thế nào",
    "sdg.iconCaption": "Nội dung IAAI trực tiếp đề cập đến 11 trong 17 Mục tiêu Phát triển Bền vững. Mỗi biểu tượng liên kết đến trang mục tiêu chính thức của LHQ.",
    "sdg.col.relay": "CHẶNG IAAI",
    "sdg.col.sdgGoals": "MỤC TIÊU SDG",
    "sdg.col.alignment": "CƠ SỞ LIÊN KẾT",
    "sdg.col.5p": "PHÂN LOẠI 5P",
    "sdg.r1.rationale": "Mạng lưới đường bộ là hệ tuần hoàn của phát triển kinh tế. Không có đường, không có tiếp cận thị trường, dịch vụ khẩn cấp hay chuỗi cung ứng.",
    "sdg.r2.rationale": "Đường sắt là xương sống của vận tải hành khách và hàng hóa. Phát thải thấp hơn đường bộ trên mỗi tấn-km.",
    "sdg.r3.rationale": "Cảng kết nối các quốc gia với thương mại toàn cầu. 90% hàng hóa thế giới di chuyển bằng đường biển.",
    "sdg.r4.rationale": "Hạ tầng hàng không cho phép kết nối toàn cầu, thương mại, du lịch và ứng phó khẩn cấp.",
    "sdg.r5.rationale": "Nước sạch là hạ tầng cơ bản nhất. 2,2 tỷ người vẫn thiếu nước uống an toàn.",
    "sdg.r6.rationale": "Vệ sinh ngăn ngừa bệnh tật, bảo vệ nguồn nước và giữ gìn phẩm giá con người.",
    "sdg.r7.rationale": "Hạ tầng năng lượng quyết định liệu các quốc gia công nghiệp hóa sạch hay lặp lại sự phụ thuộc nhiên liệu hóa thạch.",
    "sdg.r8.rationale": "Viễn thông kết nối con người với giáo dục, thị trường và quản trị. Khoảng cách số là khoảng cách hạ tầng.",
    "sdg.r9.rationale": "Quản lý chất thải là tấm gương của tiêu dùng. Kinh tế tuần hoàn cần hạ tầng thu gom, phân loại và tái chế.",
    "sdg.r10.rationale": "Hạ tầng y tế — bệnh viện, phòng khám, chuỗi cung ứng — quyết định liệu dân số có sống sót qua đại dịch hay không.",
    "sdg.r11.rationale": "Hạ tầng giáo dục — trường học, đại học, thư viện — là cơ chế truyền tải kiến thức qua các thế hệ.",
    "sdg.r12.rationale": "Hạ tầng số — trung tâm dữ liệu, cáp quang, đám mây — là đường bộ và cảng biển của thế kỷ 21.",
    "sdg.5pTitle": "5P — CON NGƯỜI, HÀNH TINH, THỊNH VƯỢNG, HÒA BÌNH, ĐỐI TÁC",
    "sdg.5pText": "LHQ xây dựng 17 SDG qua năm trụ cột (5P). Hạ tầng là cơ chế mà các nền văn minh thực hiện cả năm P.",
    "sdg.visitUN": "TRUY CẬP TRANG WEB CHÍNH THỨC SDG CỦA LHQ →",
    "sdg.disclaimerTitle": "Tuyên bố miễn trừ:",
    "sdg.disclaimerText": "Nội dung của ấn phẩm này chưa được Liên Hợp Quốc phê duyệt và không phản ánh quan điểm của Liên Hợp Quốc hoặc các quan chức hay Quốc gia Thành viên.",
    "home.dominion.title": "Mất Quyền Thống Trị — Khủng Hoảng Hội Tụ",
    "home.dominion.text": "Lần đặt lại thứ sáu sẽ không đến từ không gian. Nó đã ở đây — trong việc chuyển giao quyền ra quyết định, thiết kế và quản trị từ hệ thống con người sang hệ thống máy móc. Không phải tuyệt chủng. Thay thế. Cơ sở hạ tầng đã mang nền văn minh suốt 12.000 năm đang hội tụ nhanh hơn bất kỳ thế hệ nào có thể hấp thụ. Đây là khủng hoảng hội tụ. Tập 2 vẽ nên kiến trúc của sự liên tục nhân loại.",
    "home.fw.ele_planetary": "Đồng Hồ Hành Tinh ELE — Trái Đất: 4,5 tỷ năm. Năm lần đặt lại. ELE 6 mang tính văn minh — 2050. Hành động ngay hoặc mất quyền thống trị.",
    "home.fw.continuity_grid": "Lưới Liên Tục Đầy Đủ — Nếu lịch sử nhân loại là cuốn sách 1.200 trang. 24 hàng = 24 giờ. Lưới chính LÀ đồng hồ. Hàng 24 = giờ cuối cùng.",
    "home.fw.row24": "Hàng 24 Mở Rộng — Giờ Cuối Cùng. 12.000 năm (10.000 TCN → 2050 CN). 500 thế hệ. Hàng duy nhất nơi nhân loại khai thác các cuộc tiếp sức. Bảy Học Giả. Sáu cuộc tiếp sức trong 246 năm. Tất cả vẫn đang vận hành.",
    "home.fw.relay_cone": "Hình Nón Tiếp Sức — 500 thế hệ văn minh nén thành 12 cuộc tiếp sức hạ tầng. Góc nhìn bên, góc nhìn trên, và Bảy Học Giả. Sáu cuộc tiếp sức đầu tiên trải dài 11.500 năm; sáu cuộc cuối nén trong 246 năm.",
    "home.ascent.title": "Sự Thăng Tiến Đến Ý Thức",
    "home.ascent.subtitle": "Tiếp Sức 12 và Xa Hơn — Luận Đề Văn Minh Đến 2050 Như Nửa Đêm",
    "home.ascent.text": "Đây là nơi mảnh ghép văn minh cư trú. Từ Calo đến Ý Thức — Hành Trình Hạ Tầng vẽ nên 12.000 năm qua 12 cuộc tiếp sức, 7 học giả, 5 mạng lưới và 3 đế chế vĩ đại. Sự Thăng Tiến Đến Ý Thức là Tiếp Sức 12 và xa hơn: điểm chuyển giao nơi trí tuệ sinh học gặp chính hạ tầng của mình. Năm tầng dòng dõi trí tuệ — từ Homer đến thế hệ Ứng Dụng — hội tụ vào một câu hỏi duy nhất: ai mang cuộc tiếp sức tiến về phía trước? Hàm ý thần học sâu sắc. Mất Quyền Thống Trị đóng khung cuộc khủng hoảng; Phản Lực: Phần, Thước Đo và Cân Bằng cung cấp phép tính của kỹ sư. Học Giả Thứ 8 vẫn là cuộc tìm kiếm mở — nút tiếp theo trong chuỗi trí tuệ nền tảng 3.500 năm.",
    "home.ascent.source": "DÒNG DÕI 5 TẦNG — Cuộc Tiếp Sức Trí Tuệ 3.500 Năm Hướng Tới Học Giả Thứ 8 — Khung Chân Lý iAAi"
};
