// INFRASTRUCTURE ACADEMY - KO TRANSLATIONS
window.IA_LANG_KO = {
    "archive.documents": "문서",
    "archive.images": "이미지",
    "archive.references": "참고 자료",
    "archive.relays": "릴레이",
    "archive.subtitle": "완전한 지식 자산 보존",
    "archive.supplements": "보충 자료",
    "archive.title": "아카이브",
    "author.bio": "Ir. Nigel T Dearden (鄧禮祖)은 공인 토목 및 구조 기사이자 공인 수자원 및 환경 관리사로, 홍콩 인프라 분야에서 33년 이상의 경력을 보유하고 있습니다. 4 Elements Consulting Ltd 설립자 (2006년, www.4ecl.com). BEng (Hon's), CEng, C.WEM, RPE (CSB), MICE, MHKIE, MCIWEM.",
    "author.credentials": "공인 엔지니어(CEng), 영국 토목 학회 회원(MICE), 홍콩 엔지니어 학회 회원(MHKIE)",
    "author.name": "니어든 엔지니어 (Ir. Nigel T. Dearden)",
    "author.title": "저자 소개",
    "civ.civilisation.subtitle": "12,000년 = 24시간",
    "civ.civilisation.title": "문명 시계",
    "civ.cosmic.subtitle": "138억 년 = 24시간",
    "civ.cosmic.title": "우주 시계",
    "civ.cta.desc": "펜은 우리 손에 있습니다. 인프라는 제자리에 있습니다. 지금이 바로 그 순간입니다. 문제는 이 융합이 일어날 것인가가 아닙니다 — 이미 일어나고 있습니다. 문제는 우리가 어떻게 대응할 것인가입니다.",
    "civ.cta.title": "자정이 다가온다",
    "civ.epigraph": "\"원소 시계는 자정을 향해 똑딱거린다. 우리가 마지막 몇 초 동안 하는 일은 천 년 동안 울려 퍼질 것이다.\"",
    "civ.nesting.desc": "각 시계는 이전 시계 안에 중첩되어 있습니다. 전체 행성 시계는 우주 시계의 마지막 3분의 1에 불과합니다. 전체 문명 시계는 행성 시계의 마지막 순간에 불과합니다. 우리는 자정 직전의 마지막 순간에 살고 있습니다.",
    "civ.nesting.title": "세 개의 시계, 하나의 이야기",
    "civ.planetary.subtitle": "45억 년 = 24시간",
    "civ.planetary.title": "행성 시계",
    "civ.relay.title": "문명 시계의 12개 계주",
    "civ.subtitle": "세 개의 중첩된 24시간 시계 — 빅뱅에서 인간의 순간까지. 138억 년의 우주 역사, 45억 년의 행성 진화, 12,000년의 문명 — 각각 하루로 매핑됩니다. 자정이 다가오고 있습니다.",
    "civ.title": "원소 시계",
    "clock.bar.end": "1,000,000,000 — 임무 완수",
    "clock.bar.mid": "선구자 → 대사 → 학자",
    "clock.bar.start": "0 — 시작",
    "clock.challenge.note": "도전 받음 = 플레이어가 지명함 · 아직 아님 = 지명 대기 중",
    "clock.challenge.title": "후원자 챌린지 보드",
    "clock.contributors.advisors": "고문 (전략)",
    "clock.contributors.ambassadors": "대사 (언어 리더)",
    "clock.contributors.backers": "후원자 (자금)",
    "clock.contributors.founders": "창립 팀",
    "clock.contributors.patrons": "후원자 (기관)",
    "clock.contributors.pioneers": "선구자 (테스터)",
    "clock.contributors.players": "플레이어 (게임)",
    "clock.contributors.scholars": "학자 (학술 검증자)",
    "clock.contributors.title": "기여자 클래스",
    "clock.cta": "경주에 참여하세요 — 선구자가 되세요",
    "clock.cta.sub": "10억 학습자의 여정은 한 명의 선구자로부터 시작됩니다.",
    "clock.hero.mobilised": "현재 동원됨",
    "clock.hero.pop": "세계 인구",
    "clock.hero.pop.sub": "UN 실시간 추정치",
    "clock.hero.target": "목표: 10억 명의 학습자",
    "clock.hero.target.sub": "인류의 12.1% — 티핑 포인트",
    "clock.intelligence.comint": "COMINT — 통신 정보 (번역 네트워크)",
    "clock.intelligence.elint": "ELINT — 전자 정보 (플랫폼 배포)",
    "clock.intelligence.geoint": "GEOINT — 지리 공간 정보 (8개 언어 지역 매핑)",
    "clock.intelligence.humint": "HUMINT — 인간 정보 (선구자 + 대사)",
    "clock.intelligence.masint": "MASINT — 측정 및 서명 정보 (학습 분석)",
    "clock.intelligence.osint": "OSINT — 공개 출처 정보 (GitHub + 공개 데이터)",
    "clock.intelligence.sigint": "SIGINT — 신호 정보 (DAVID AI 분석)",
    "clock.intelligence.title": "IAAI 정보 네트워크 (INTs)",
    "clock.milestones.first_pioneer": "첫 선구자 물결",
    "clock.milestones.github": "GitHub 오픈 소스",
    "clock.milestones.seed": "시드 라운드 ($500K)",
    "clock.milestones.title": "마일스톤",
    "clock.milestones.vr": "VR 캠퍼스 (Meta)",
    "clock.notyet.ce_firms": "토목 공학 회사 (상위 100개)",
    "clock.notyet.cta": "위의 모든 숫자는 도전입니다. 모든 0은 초대입니다.",
    "clock.notyet.eng_students": "공학 학생",
    "clock.notyet.govts": "국가 정부",
    "clock.notyet.people": "인프라에 대해 모르는 사람들",
    "clock.notyet.title": "아직 아님 — 도전",
    "clock.notyet.un_bodies": "UN 기구",
    "clock.notyet.universities": "글로벌 대학",
    "clock.partners.title": "파트너 챌린지 보드",
    "clock.platform.game_pages": "게임 페이지",
    "clock.platform.inventions": "목록화된 발명품",
    "clock.platform.languages_active": "활성 언어",
    "clock.platform.languages_planned": "계획된 언어",
    "clock.platform.pages": "웹사이트 페이지",
    "clock.platform.relays": "구축된 계주",
    "clock.platform.tests": "통과된 테스트",
    "clock.platform.title": "플랫폼 지표",
    "clock.platform.words": "작성된 단어 수",
    "clock.regions.coverage": "결합된 범위: ~85% 글로벌 게임 시장 · ~80% 교육 기술 지출",
    "clock.regions.goal": "목표: 2027년까지 8개 언어 모두",
    "clock.regions.title": "8개 언어 블록 — 글로벌 레이스",
    "clock.scaling.phase1": "1단계: 창립자",
    "clock.scaling.phase2": "2단계: 선구자 (블록당 2-3명)",
    "clock.scaling.phase3": "3단계: 대사 (블록당 10명)",
    "clock.scaling.phase4": "4단계: GitHub 오픈 소스",
    "clock.scaling.phase5": "5단계: 대학 채택",
    "clock.scaling.phase6": "6단계: 유기적 성장",
    "clock.scaling.title": "확장 모델",
    "clock.subtitle": "인프라 리터러시를 향한 인류의 경주 — 도전",
    "clock.title": "IAAI 글로벌 동원 시계",
    "footer.ep1": "에피소드 1: 대지의 기반",
    "footer.ep2": "에피소드 2: 회색 경기장",
    "footer.ep3": "에피소드 3: 우주적 규모",
    "footer.copyright": "&copy; 2026 인프라스트럭처 아카데미. 판권 소유. 지식의 영원한 보존.",
    "framework.4cs.challenge": "도전",
    "framework.4cs.consequence": "결과",
    "framework.4cs.context": "배경",
    "framework.4cs.continuum": "연속체",
    "framework.4cs.title": "4C 분석 프레임워크",
    "framework.modes.east": "동양 모델",
    "framework.modes.east.desc": "연속적/건설적 — 진시황 원형",
    "framework.modes.outrider": "아웃라이더 모델",
    "framework.modes.outrider.desc": "반연속적/임시 공학 — 징기스칸 원형",
    "framework.modes.title": "세 가지 문명 모델",
    "framework.modes.west": "서양 모델",
    "framework.modes.west.desc": "불연속적/건설적 — 알렉산더 대왕 원형",
    "framework.relays.title": "12개의 문명 릴레이",
    "framework.subtitle": "종합 시스템 사고 방법론",
    "framework.title": "전체 프레임워크",
    "header.subtitle": "인프라 오디세이: 제1권 — 칼로리에서 의식까지",
    "header.subtitle.v2": "인프라 오디세이: 제2권 — 실용 가이드",
    "header.subtitle.v3": "인프라 오디세이: 제3권 — 현실 엔진",
    "header.title": "인프라스트럭처 아카데미",
    "home.archive.architects": "운명의 건축가와 위대한 통일자: 알렉산더 대왕, 징기스칸, 진시황",
    "home.archive.p1": "인프라스트럭처 아카데미는 12,000년에 걸친 인류 인프라 발전의 문명 마스터클래스인 '인프라 오디세이'의 완전한 지식 자산을 보존하는 디지털 아카이브입니다. 이 웹사이트는 전 세계 학자, 엔지니어, 학습자들이 지식을 영원히 보존하여 사용할 수 있도록 보장합니다.",
    "home.archive.p2": "모든 콘텐츠, 시각화 및 프레임워크가 여기에 통합되어 있어 탐색과 발견이 용이합니다. 이것은 칼로리에서 의식으로의 인류의 부상을 영원히 기록한 것으로, 펜으로 디지털 영원에 새겨졌습니다.",
    "home.archive.title": "이 아카이브에 대하여",
    "home.author": "저자: 니어든 엔지니어 (Ir. Nigel T. Dearden)",
    "home.challenge.stat1.desc": "의 과정이 학제 간 통합이 부족합니다",
    "home.challenge.stat1.num": "70%",
    "home.challenge.stat2.desc": "의 학생들이 실제 적용에 대한 준비가 부족하다고 느낍니다",
    "home.challenge.stat2.num": "65%",
    "home.challenge.stat3.desc": "가 시스템 수준 사고에 대한 접촉이 제한적이라고 보고합니다",
    "home.challenge.stat3.num": "45%",
    "home.challenge.stat4.desc": "의 고용주가 프로젝트 준비에 있어 기술 격차가 있다고 생각합니다",
    "home.challenge.stat4.num": "80%",
    "home.challenge.stat5.desc": "의 프로젝트가 지역 사회 또는 환경 영향 지표를 통합합니다",
    "home.challenge.stat5.num": "30%",
    "home.challenge.stat6.desc": "의 인프라 프로젝트가 실용적인 지식 격차로 인해 지연됩니다",
    "home.challenge.stat6.num": "90%",
    "home.challenge.subtitle": "인프라 교육은 파편화되고 추상적이며 현실 세계의 영향과 단절되어 있습니다.",
    "home.challenge.title": "우리가 해결해야 할 과제",
    "home.challenge.urgent": "긴급한 요구: 미래에 대비한 인프라 전문가를 위한 다리 놓기",
    "home.cover.front": "앞면과 뒷면 표지 — 제1부: 대지의 기반",
    "home.cover.interior": "내지 펼침 — 제1장: 불의 릴레이 (제1부 및 제2부)",
    "home.cover.portrait": "문명 릴레이 — 나무에서 토러스까지 12장",
    "home.ep1.btn": "출판됨",
    "home.ep1.desc": "칼로리에서 의식으로 — 불에서 토러스까지 12개의 릴레이",
    "home.ep1.subtitle": "대지의 기반",
    "home.ep1.title": "제1부",
    "home.ep2.btn": "출시 예정",
    "home.ep2.desc": "사이버네틱스, 인공지능 및 지능형 시스템",
    "home.ep2.subtitle": "현실 엔진 — 회색 경기장",
    "home.ep2.title": "제2부",
    "home.ep3.btn": "출시 예정",
    "home.ep3.desc": "행성, 태양계 및 은하계 관리",
    "home.ep3.subtitle": "관리 및 업데이트 — 우주적 규모",
    "home.ep3.title": "제3부",
    "home.framework.journey": "여정이 곧 작업이다.",
    "home.framework.modes.caption": "세 가지 모델 — 12,000년에 걸친 서양, 동양 및 아웃라이더",
    "home.framework.motto": "인프라 교육: 암기보다는 시스템 사고",
    "home.framework.relays.caption": "12개의 문명 릴레이 — 불에서 의식까지",
    "home.framework.silk.caption": "실크로드의 역설 — 아웃라이더는 무역로를 통제했지만 인프라를 건설하지 않았습니다",
    "home.framework.subtitle": "토목 기사의 관점을 통한 인프라 교육의 종합 시스템 사고",
    "home.framework.title": "전체 프레임워크",
    "home.game.cta.sub": "제3권: 현실 엔진 — 안내 학습 플랫폼",
    "home.game.cta.title": "게임 시작",
    "home.game.desc": "배운 것을 적용할 준비가 되셨습니까? 현실 엔진으로 들어가십시오 — 인프라 엔지니어가 되는 몰입형 학습 플랫폼입니다.",
    "home.game.note": "시뮬레이션 및 실습: 동적 환경에서 개념 적용",
    "home.game.title": "제3권: 게임",
    "home.hero.caption": "칼로리에서 의식으로: 인프라 오디세이 — 문명 릴레이",
    "home.kw.subtitle": "회계 토큰에서 디지털 시대까지의 포괄적인 문자 역사. 최종 인프라 릴레이로서의 펜.",
    "home.kw.title": "지식 웹: 인프라로서의 문자",
    "home.media.calories": "칼로리에서 의식으로",
    "home.media.engine": "현실 엔진 — 안내 학습 플랫폼",
    "home.media.river": "강 평원 영화",
    "home.media.title": "미디어",
    "home.media.trailer": "스냅샷 예고편",
    "home.ppp.clock.sub": "인프라 리터러시를 향한 인류의 경주를 실시간으로 추적하세요. 도전이 시작되었습니다.",
    "home.ppp.clock.title": "동원 시계 보기",
    "home.s1.desc": "기본 개념 — 세 가지 모델, 원소 시계, 도로 및 선박 타임라인",
    "home.s1.title": "S1: 식별",
    "home.s2.desc": "기술 확산 — 인프라로서의 펜, 문자 체계",
    "home.s2.title": "S2: 이해",
    "home.s3.desc": "구현 — 각 릴레이의 관리 다이어그램",
    "home.s3.title": "S3: 관리 및 통제",
    "home.s4.desc": "상대방 — 각 릴레이의 서양, 아웃라이더 및 동양 비교",
    "home.s4.title": "S4: 논문 및 비전",
    "home.subtitle": "토목 기사의 관점과 가이드 — 제1부: 칼로리에서 의식까지",
    "home.supplements.btn": "보충 자료 보기",
    "home.supplements.title": "제2권: 4개의 보충 자료",
    "home.title": "인프라 오디세이",
    "home.trilogy.title": "3부작 비전",
    "home.vol1.btn": "관점 읽기",
    "home.vol1.desc": "서사적 기반: 12,000년에 걸친 인류 인프라 발전의 12개 문명 릴레이. 불의 숙달에서 의식의 토러스까지.",
    "home.vol1.subtitle": "역사와 배경 — 이야기",
    "home.vol1.title": "제1권: 관점",
    "home.vol2.btn": "가이드 읽기",
    "home.vol2.desc": "실용적인 프레임워크: 서양/동양/아웃라이더 비교 방법론, 4C 분석 및 문명 DNA로서의 인프라를 이해하기 위한 전략적 모델.",
    "home.vol2.subtitle": "전략적 프레임워크 — 확장",
    "home.vol2.title": "제2권: 가이드",
    "inst.coming": "출시 예정 — 전체 기관 데이터베이스 구축 중",
    "inst.sdg.title": "SDG별 분류",
    "inst.status.challenged": "도전 받음",
    "inst.status.engaged": "참여 중",
    "inst.status.notyet": "아직 연락 안 됨",
    "inst.status.potential": "잠재적",
    "inst.subtitle": "정보 지도 — 동원, 도전 또는 협력할 수 있는 모든 기관, 대학, UN 기구, 전문 학회, NGO, 기술 제공업체 및 자본 기관. 글로벌 우선 순위와의 일치를 보여주기 위해 UN 지속가능발전목표(SDG)별로 구성되었습니다.",
    "inst.title": "기관",
    "lib.supp_title": "보충 문서",
    "lib.title": "문서 라이브러리",
    "library.subtitle": "완전한 지식 자산 아카이브",
    "library.title": "문헌 라이브러리",
    "nav.author": "저자",
    "nav.charter": "헌장",
    "nav.civclock": "문명 시계",
    "nav.clock": "동원 시계",
    "nav.documents": "문서",
    "nav.framework": "프레임워크",
    "nav.home": "홈",
    "nav.institutions": "기관",
    "nav.outriders": "선구자들",
    "nav.pioneers": "선구자 프로그램",
    "nav.precis": "요약",
    "nav.resources": "자료",
    "nav.supplements": "보충 자료",
    "nav.taxonomy": "분류 체계",
    "nav.ep1": "에피소드 1: 관점",
    "nav.ep2": "에피소드 1: 가이드",
    "nav.ep3": "에피소드 1: 게임",
    "or.conn.book.desc": "각 장은 선구자의 인용문으로 시작하고 끝납니다. 그들의 혁신은 사례 연구입니다. 그들의 실패는 경고의 이야기입니다. 그들은 주장의 증거 기반입니다.",
    "or.conn.book.title": "책에서",
    "or.conn.game.desc": "선구자들은 각 계주에서 NPC 멘토, 인용 출처 및 역사적 맥락 제공자로 나타납니다. 플레이어는 12개 챕터를 진행하면서 그들을 만납니다.",
    "or.conn.game.title": "게임에서",
    "or.conn.movement.desc": "선구자들은 도덕적 권위를 제공합니다. IAAI가 유네스코나 MIT에 도전할 때, 그것은 이 인물들이 구현한 12,000년의 인프라 지혜의 어깨 위에 서 있습니다.",
    "or.conn.movement.title": "운동에서",
    "or.conn.title": "선구자들이 임무에 봉사하는 방법",
    "or.era1.title": "고대 세계",
    "or.era2.title": "고전 세계",
    "or.era3.title": "중세 및 르네상스",
    "or.era4.title": "산업 혁명",
    "or.era5.title": "현대",
    "or.era6.title": "디지털 및 미래",
    "or.quote": "\"현명한 군주와 훌륭한 장수가 움직여서 남을 이기고, 성공이 보통 사람을 뛰어넘는 까닭은 먼저 알기 때문이다.\" — 손자, 제13편",
    "or.stat.civilisations": "대표되는 문명",
    "or.stat.eras": "역사적 시대",
    "or.stat.relays": "다루는 계주",
    "or.stat.total": "총 선구자 수",
    "or.subtitle": "모든 계층과 함께 걷는 역사적 정신 가이드 — 6+1 계층에 포함되지 않는 이 지혜의 동반자들은 모든 모드, 모든 계주, 12,000년 전체에 걸쳐 있습니다. 그들은 게임의 목소리, 벽의 인용문, 불과 토러스를 잇는 지혜입니다.",
    "or.title": "선구자들",
    "pioneers.charter.agree": "IAAI 헌장을 읽고 동의합니다. 저는 정직한 기여, 문화적 존중, 언어와 국경을 넘어 지식을 개방적으로 공유할 것을 약속합니다. 이것이 자원 봉사 프로그램이며 제 기여는 CC BY-NC-SA 4.0에 따라 크레딧이 부여됨을 이해합니다.",
    "pioneers.charter.text": "우리는 인프라가 문명의 운영 체제라고 믿습니다. 강이 행성 규모의 변화를 위해 느리고 꾸준하게 땅을 조각하는 것처럼, 우리는 개방된 지식, 검증된 기여, 문화적 존중, 그리고 우리가 세상을 건설하는 방법이 더 나은 세상을 건설하는 첫 걸음임을 이해하는 데 전념합니다.",
    "pioneers.charter.title": "IAAI 헌장",
    "pioneers.form.country": "국가",
    "pioneers.form.email": "이메일 주소",
    "pioneers.form.expertise": "전문 분야",
    "pioneers.form.language": "주요 언어",
    "pioneers.form.motivation": "참여하고 싶은 이유 (선택 사항)",
    "pioneers.form.name": "전체 이름",
    "pioneers.form.other_langs": "기타 언어",
    "pioneers.form.submit": "신청서 제출 — 경주에 참여",
    "pioneers.form.subtitle": "무료 베타 액세스. 비용 없음. 의무 없음. 오직 호기심과 헌신만.",
    "pioneers.form.title": "선구자 신청",
    "pioneers.subtitle": "각 대륙에서 인프라 리터러시를 테스트, 번역, 검증 및 전파할 첫 번째 기여자 물결. 무료 베타 액세스. 창립자 벽에 당신의 자리를 차지하세요.",
    "pioneers.tier1.desc": "최초의 테스터. 게임을 플레이하고, 버그를 보고하고, 콘텐츠를 검증합니다. 언어 블록당 2-3명. 정보 네트워크의 정찰병.",
    "pioneers.tier1.req": "요구 사항: 호기심, 모든 언어, 테스트 의지",
    "pioneers.tier1.title": "선구자",
    "pioneers.tier2.desc": "언어 리더. 원어민 사용법에 맞게 AI 번역을 검토하고 수정합니다. 크레딧을 받은 기여자가 되십시오. 언어 블록당 10명.",
    "pioneers.tier2.req": "요구 사항: 원어민 유창성 + 선구자 경험",
    "pioneers.tier2.title": "대사",
    "pioneers.tier3.desc": "학술 검증자. 기술적 정확성을 검증하고 콘텐츠를 커리큘럼에 매핑하는 엔지니어, 교수, 연구원.",
    "pioneers.tier3.req": "요구 사항: 학술 자격 + 전문 분야",
    "pioneers.tier3.title": "학자",
    "pioneers.tier4.desc": "전략적 안내. 문을 열고 방향을 설정하는 업계 리더, 정책 입안자 및 기관 연결자.",
    "pioneers.tier4.req": "요구 사항: 초대 또는 지명",
    "pioneers.tier4.title": "고문",
    "pioneers.title": "선구자 프로그램",
    "precis.relay.epilogue": "에필로그",
    "precis.relay.prologue": "프롤로그",
    "precis.relay.relay_10_aaa": "계주 10: AAA 트리펙타",
    "precis.relay.relay_10_autoair": "계주 10: 자동차/항공",
    "precis.relay.relay_11_humans": "계주 11: 인간 노드",
    "precis.relay.relay_11_orbit": "계주 11: 궤도",
    "precis.relay.relay_12_programmable": "계주 12: 프로그래밍 가능",
    "precis.relay.relay_12_torus": "계주 12: 토러스",
    "precis.relay.relay_1_fire": "계주 1: 불",
    "precis.relay.relay_2_tree": "계주 2: 나무",
    "precis.relay.relay_3_river": "계주 3: 강",
    "precis.relay.relay_4_horse": "계주 4: 말",
    "precis.relay.relay_5_road": "계주 5: 도로",
    "precis.relay.relay_6_ship": "계주 6: 배",
    "precis.relay.relay_7_rail": "계주 7: 철도",
    "precis.relay.relay_8_loom": "계주 8: 직조기",
    "precis.relay.relay_9_engine": "계주 9: 엔진",
    "precis.relay.torus": "토러스",
    "precis.subtitle": "인프라 오디세이 — 전략적 개요",
    "precis.title": "요약",
    "relay.1.name": "릴레이 1: 불",
    "relay.1.subtitle": "원시의 불꽃 — 에너지 숙달의 시작",
    "relay.10.name": "릴레이 10: AAA 트리오",
    "relay.10.subtitle": "항공, 원자, 자동화 — 현대의 삼위일체",
    "relay.11.name": "릴레이 11: 인간 노드",
    "relay.11.subtitle": "네트워크화된 인류 — 디지털 연결",
    "relay.12.name": "릴레이 12: 의식",
    "relay.12.subtitle": "토러스 — 인프라의 궁극적인 형태",
    "relay.2.name": "릴레이 2: 나무",
    "relay.2.subtitle": "살아있는 건축 — 공학으로서의 자연",
    "relay.3.name": "릴레이 3: 강",
    "relay.3.subtitle": "수력 문명 — 액체 인프라",
    "relay.4.name": "릴레이 4: 말",
    "relay.4.subtitle": "이동 혁명 — 속도와 제국",
    "relay.5.name": "릴레이 5: 도로",
    "relay.5.subtitle": "연결된 네트워크 — 제국의 동맥",
    "relay.6.name": "릴레이 6: 배",
    "relay.6.subtitle": "해양 고속도로 — 글로벌 무역 네트워크",
    "relay.7.name": "릴레이 7: 철도",
    "relay.7.subtitle": "강철 척추 — 산업 연결",
    "relay.8.name": "릴레이 8: 직조기",
    "relay.8.subtitle": "짜여진 웹 — 정보 인프라",
    "relay.9.name": "릴레이 9: 엔진",
    "relay.9.subtitle": "동력 혁명 — 기계화된 세계",
    "relay.epilogue": "에필로그",
    "relay.prologue": "프롤로그",
    "resources.subtitle": "참고 자료, 데이터 출처 및 추가 읽기 자료",
    "resources.title": "자료",
    "section.4c_analysis": "4C 분석",
    "section.active_webs": "활성 웹",
    "section.back_to_index": "목차로 돌아가기",
    "section.challenge": "도전",
    "section.chapter_1": "1장",
    "section.chapter_10": "10장",
    "section.chapter_11": "11장",
    "section.chapter_12": "12장",
    "section.chapter_2": "2장",
    "section.chapter_3": "3장",
    "section.chapter_4": "4장",
    "section.chapter_5": "5장",
    "section.chapter_6": "6장",
    "section.chapter_7": "7장",
    "section.chapter_8": "8장",
    "section.chapter_9": "9장",
    "section.communication_web": "통신 웹",
    "section.comparative_analysis": "비교 분석",
    "section.consciousness_web": "의식 웹",
    "section.consequence": "결과",
    "section.context": "배경",
    "section.continuity": "연속성",
    "section.continuum": "연속체",
    "section.control_web": "제어 웹",
    "section.counterparts": "상대방",
    "section.digital_web": "디지털 웹",
    "section.documents": "문서",
    "section.east_mode": "동양 모델",
    "section.energy_web": "에너지 웹",
    "section.epilogue": "에필로그",
    "section.four_cs": "4C",
    "section.four_pillars": "네 가지 기둥",
    "section.gallery": "갤러리",
    "section.governance_web": "거버넌스 웹",
    "section.historical_significance": "역사적 중요성",
    "section.impact": "영향:",
    "section.information_web": "정보 웹",
    "section.infrastructure": "인프라",
    "section.infrastructure_web": "인프라 웹",
    "section.intelligence_web": "정보 웹",
    "section.introduction": "소개",
    "section.key_insights": "핵심 통찰력",
    "section.knowledge_web": "지식 웹",
    "section.legacy": "유산:",
    "section.logistics_web": "물류 웹",
    "section.management_charts": "관리 차트",
    "section.management_diagram": "관리 다이어그램",
    "section.military_web": "군사 웹",
    "section.next_relay": "다음 계주",
    "section.notes": "노트",
    "section.outrider_mode": "아웃라이더 모델",
    "section.preface": "서문",
    "section.previous_relay": "이전 계주",
    "section.production_web": "생산 웹",
    "section.prologue": "프롤로그",
    "section.references": "참고 문헌",
    "section.strategic_framework": "전략적 프레임워크",
    "section.the_counterparts": "상대방:",
    "section.the_first_infrastructure": "최초의 인프라",
    "section.threats": "위협",
    "section.timeline": "타임라인:",
    "section.trade_web": "무역 웹",
    "section.transport_web": "운송 웹",
    "section.unification": "통일",
    "section.volume_1_perspective": "제1권: 관점",
    "section.volume_2_playbook": "제2권: 플레이북",
    "section.west_mode": "서양 모델",
    "special.conclusion": "결론",
    "special.epilogue": "에필로그",
    "special.from_calories_to_consciousness": "칼로리에서 의식으로",
    "special.prologue": "프롤로그",
    "special.the_beginning": "시작",
    "special.the_journey_begins": "여정의 시작",
    "special.the_journey_continues": "여정은 계속된다",
    "supplements.s1": "보충 1: 식별",
    "supplements.s2": "보충 2: 이해",
    "supplements.s3": "보충 3: 관리 및 통제",
    "supplements.s4": "보충 4: 논문 및 비전",
    "supplements.subtitle": "제2권의 심층 확장 자료",
    "supplements.title": "보충 자료",
    "tax.advisors": "고문",
    "tax.advisors.desc": "전략적 안내. 업계 리더 및 기관 연결자.",
    "tax.ambassadors": "대사",
    "tax.ambassadors.desc": "언어 리더. 언어 블록당 10명.",
    "tax.backers": "후원자",
    "tax.backers.desc": "자금 및 기관 지원. 후원자 및 파트너.",
    "tax.biology": "생물학적 비유",
    "tax.count": "수량",
    "tax.founder": "창립자",
    "tax.founder.desc": "설계자. 1명. 전체 시스템을 설계했습니다.",
    "tax.iaai": "IAAI 등급",
    "tax.outriders.note": "선구자들(역사적 정신 가이드)은 6+1 계층에 포함되지 않습니다 — 그들은 모든 모드, 모든 계주, 12,000년 전체에 걸쳐 함께 걷습니다.",
    "tax.pioneers": "선구자",
    "tax.pioneers.desc": "최초의 테스터. 언어 블록당 2-3명.",
    "tax.players": "플레이어",
    "tax.players.desc": "게임 참여자. 목표: 10억 명의 학습자.",
    "tax.role": "역할",
    "tax.scholars": "학자",
    "tax.scholars.desc": "학술 검증자. 교수, 엔지니어, 연구원.",
    "tax.subtitle": "6+1 계층 구조 — 생물학적 분류가 왕국에서 종으로 이동하는 것처럼, IAAI의 기여자 계층은 창립자에서 후원자까지, 각 계층이 더 광범위하고 전문화됩니다.",
    "tax.title": "IAAI 분류 체계",
    "toc.chapter": "제",
    "toc.chapter.suffix": "장",
    "toc.epilogue": "에필로그",
    "toc.prologue": "프롤로그",
    "toc.title": "목차",
    "toc.volume1": "제1권: 관점 — 역사와 배경",
    "toc.volume2": "제2권: 가이드 — 전략적 프레임워크",
    "toc.volume3": "제3권: 게임 — 시뮬레이션 및 실습",
    "ui.available": "사용 가능",
    "ui.back": "뒤로",
    "ui.coming.soon": "출시 예정",
    "ui.download": "다운로드",
    "ui.error": "콘텐츠를 로드하는 중에 오류가 발생했습니다. 다시 시도하십시오.",
    "ui.loading": "로드 중...",
    "ui.next": "다음",
    "ui.prev": "이전",
    "ui.read.more": "더 읽기",
    "ui.view": "보기",
    "v1.index.about_title": "이 책에 대하여",
    "v1.index.relays_title": "열두 계주",
    "v1.index.title": "제1권: 관점",
    "v1.r01.active_webs": "활성 웹",
    "v1.r01.counterparts_title": "상대방: 불",
    "v1.r01.four_pillars": "네 가지 기둥",
    "v1.r01.historical_significance": "역사적 중요성",
    "v1.r01.next_relay": "다음 릴레이 →",
    "v1.r01.previous_relay": "← 이전 릴레이",
    "v1.r01.subtitle": "원시의 불꽃 — 에너지 숙달의 시작",
    "v1.r01.title": "릴레이 1: 불",
    "v1.r02.active_webs": "활성 웹",
    "v1.r02.counterparts_title": "상대방: 나무",
    "v1.r02.four_pillars": "네 가지 기둥",
    "v1.r02.historical_significance": "역사적 중요성",
    "v1.r02.next_relay": "다음 릴레이 →",
    "v1.r02.previous_relay": "← 이전 릴레이",
    "v1.r02.subtitle": "살아있는 건축 — 공학으로서의 자연",
    "v1.r02.title": "릴레이 2: 나무",
    "v1.r03.active_webs": "활성 웹",
    "v1.r03.counterparts_title": "상대방: 강",
    "v1.r03.four_pillars": "네 가지 기둥",
    "v1.r03.historical_significance": "역사적 중요성",
    "v1.r03.next_relay": "다음 릴레이 →",
    "v1.r03.previous_relay": "← 이전 릴레이",
    "v1.r03.subtitle": "수력 문명 — 액체 인프라",
    "v1.r03.title": "릴레이 3: 강",
    "v1.r04.active_webs": "활성 웹",
    "v1.r04.counterparts_title": "상대방: 말",
    "v1.r04.four_pillars": "네 가지 기둥",
    "v1.r04.historical_significance": "역사적 중요성",
    "v1.r04.next_relay": "다음 릴레이 →",
    "v1.r04.previous_relay": "← 이전 릴레이",
    "v1.r04.subtitle": "이동 혁명 — 속도와 제국",
    "v1.r04.title": "릴레이 4: 말",
    "v1.r05.active_webs": "활성 웹",
    "v1.r05.counterparts_title": "상대방: 도로",
    "v1.r05.four_pillars": "네 가지 기둥",
    "v1.r05.historical_significance": "역사적 중요성",
    "v1.r05.next_relay": "다음 릴레이 →",
    "v1.r05.previous_relay": "← 이전 릴레이",
    "v1.r05.subtitle": "연결된 네트워크 — 제국의 동맥",
    "v1.r05.title": "릴레이 5: 도로",
    "v1.r06.active_webs": "활성 웹",
    "v1.r06.counterparts_title": "상대방: 배",
    "v1.r06.four_pillars": "네 가지 기둥",
    "v1.r06.historical_significance": "역사적 중요성",
    "v1.r06.next_relay": "다음 릴레이 →",
    "v1.r06.previous_relay": "← 이전 릴레이",
    "v1.r06.subtitle": "해양 고속도로 — 글로벌 무역 네트워크",
    "v1.r06.title": "릴레이 6: 배",
    "v1.r07.active_webs": "활성 웹",
    "v1.r07.counterparts_title": "상대방: 철도",
    "v1.r07.four_pillars": "네 가지 기둥",
    "v1.r07.historical_significance": "역사적 중요성",
    "v1.r07.next_relay": "다음 릴레이 →",
    "v1.r07.previous_relay": "← 이전 릴레이",
    "v1.r07.subtitle": "강철 척추 — 산업 연결",
    "v1.r07.title": "릴레이 7: 철도",
    "v1.r08.active_webs": "활성 웹",
    "v1.r08.counterparts_title": "상대방: 직조기",
    "v1.r08.four_pillars": "네 가지 기둥",
    "v1.r08.historical_significance": "역사적 중요성",
    "v1.r08.next_relay": "다음 릴레이 →",
    "v1.r08.previous_relay": "← 이전 릴레이",
    "v1.r08.subtitle": "짜여진 웹 — 정보 인프라",
    "v1.r08.title": "릴레이 8: 직조기",
    "v1.r09.active_webs": "활성 웹",
    "v1.r09.counterparts_title": "상대방: 엔진",
    "v1.r09.four_pillars": "네 가지 기둥",
    "v1.r09.historical_significance": "역사적 중요성",
    "v1.r09.next_relay": "다음 릴레이 →",
    "v1.r09.previous_relay": "← 이전 릴레이",
    "v1.r09.subtitle": "동력 혁명 — 기계화된 세계",
    "v1.r09.title": "릴레이 9: 엔진",
    "v1.r10.active_webs": "활성 웹",
    "v1.r10.counterparts_title": "상대방: AAA 트리오",
    "v1.r10.four_pillars": "네 가지 기둥",
    "v1.r10.historical_significance": "역사적 중요성",
    "v1.r10.next_relay": "다음 릴레이 →",
    "v1.r10.previous_relay": "← 이전 릴레이",
    "v1.r10.subtitle": "항공, 원자, 자동화 — 현대의 삼위일체",
    "v1.r10.title": "릴레이 10: AAA 트리오",
    "v1.r11.active_webs": "활성 웹",
    "v1.r11.counterparts_title": "상대방: 인간 노드",
    "v1.r11.four_pillars": "네 가지 기둥",
    "v1.r11.historical_significance": "역사적 중요성",
    "v1.r11.next_relay": "다음 릴레이 →",
    "v1.r11.previous_relay": "← 이전 릴레이",
    "v1.r11.subtitle": "네트워크화된 인류 — 디지털 연결",
    "v1.r11.title": "릴레이 11: 인간 노드",
    "v1.r12.active_webs": "활성 웹",
    "v1.r12.counterparts_title": "상대방: 의식",
    "v1.r12.four_pillars": "네 가지 기둥",
    "v1.r12.historical_significance": "역사적 중요성",
    "v1.r12.next_relay": "다음 릴레이 →",
    "v1.r12.previous_relay": "← 이전 릴레이",
    "v1.r12.subtitle": "토러스 — 인프라의 궁극적인 형태",
    "v1.r12.title": "릴레이 12: 의식",
    "v2.index.about_text": "제2권: 플레이북은 네 가지 기둥 프레임워크(관찰 → 교육 → 적용 → 논제)를 열두 문명 계주 각각에 적용합니다. 이 책은 인프라 시스템이 어떻게 작동하는지, 어떻게 분석하는지, 그리고 현대적 과제에 어떻게 적용하는지에 대한 실용적인 지침을 제공합니다.",
    "v2.index.about_title": "이 책에 대하여",
    "v2.index.app": "적용",
    "v2.index.app_text": "이 교훈을 어떻게 적용할 수 있습니까? 이 계주에서 어떤 실용적인 프레임워크와 도구가 나옵니까?",
    "v2.index.edu": "교육",
    "v2.index.edu_text": "이 계주에서 무엇을 배울 수 있습니까? 인프라에 대한 어떤 원칙과 교훈을 가르쳐 줍니까?",
    "v2.index.framework_title": "네 가지 기둥 프레임워크",
    "v2.index.obs": "관찰",
    "v2.index.obs_text": "이 계주에 대해 무엇을 관찰합니까? 그 특징, 구성 요소 및 패턴은 무엇입니까?",
    "v2.index.relays_caption": "열두 문명 계주 — 불에서 의식까지",
    "v2.index.subtitle": "플레이북 — 실용적인 프레임워크 및 확장된 분석",
    "v2.index.thesis": "논제",
    "v2.index.thesis_text": "전체적인 논제는 무엇입니까? 이 계주가 드러내는 근본적인 통찰력은 무엇입니까?",
    "v2.index.title": "제2권: 플레이북",
    "v2.r01.active_webs": "활성 웹",
    "v2.r01.counterparts_title": "상대방: 불",
    "v2.r01.four_pillars": "네 가지 기둥",
    "v2.r01.historical_significance": "역사적 중요성",
    "v2.r01.next_relay": "다음 릴레이 →",
    "v2.r01.previous_relay": "← 이전 릴레이",
    "v2.r01.subtitle": "원시의 불꽃 — 에너지 숙달의 시작",
    "v2.r01.title": "릴레이 1: 불",
    "v2.r02.active_webs": "활성 웹",
    "v2.r02.counterparts_title": "상대방: 나무",
    "v2.r02.four_pillars": "네 가지 기둥",
    "v2.r02.historical_significance": "역사적 중요성",
    "v2.r02.next_relay": "다음 릴레이 →",
    "v2.r02.previous_relay": "← 이전 릴레이",
    "v2.r02.subtitle": "살아있는 건축 — 공학으로서의 자연",
    "v2.r02.title": "릴레이 2: 나무",
    "v2.r03.active_webs": "활성 웹",
    "v2.r03.counterparts_title": "상대방: 강",
    "v2.r03.four_pillars": "네 가지 기둥",
    "v2.r03.historical_significance": "역사적 중요성",
    "v2.r03.next_relay": "다음 릴레이 →",
    "v2.r03.previous_relay": "← 이전 릴레이",
    "v2.r03.subtitle": "수력 문명 — 액체 인프라",
    "v2.r03.title": "릴레이 3: 강",
    "v2.r04.active_webs": "활성 웹",
    "v2.r04.counterparts_title": "상대방: 말",
    "v2.r04.four_pillars": "네 가지 기둥",
    "v2.r04.historical_significance": "역사적 중요성",
    "v2.r04.next_relay": "다음 릴레이 →",
    "v2.r04.previous_relay": "← 이전 릴레이",
    "v2.r04.subtitle": "이동 혁명 — 속도와 제국",
    "v2.r04.title": "릴레이 4: 말",
    "v2.r05.active_webs": "활성 웹",
    "v2.r05.counterparts_title": "상대방: 도로",
    "v2.r05.four_pillars": "네 가지 기둥",
    "v2.r05.historical_significance": "역사적 중요성",
    "v2.r05.next_relay": "다음 릴레이 →",
    "v2.r05.previous_relay": "← 이전 릴레이",
    "v2.r05.subtitle": "연결된 네트워크 — 제국의 동맥",
    "v2.r05.title": "릴레이 5: 도로",
    "v2.r06.active_webs": "활성 웹",
    "v2.r06.counterparts_title": "상대방: 배",
    "v2.r06.four_pillars": "네 가지 기둥",
    "v2.r06.historical_significance": "역사적 중요성",
    "v2.r06.next_relay": "다음 릴레이 →",
    "v2.r06.previous_relay": "← 이전 릴레이",
    "v2.r06.subtitle": "해양 고속도로 — 글로벌 무역 네트워크",
    "v2.r06.title": "릴레이 6: 배",
    "v2.r07.active_webs": "활성 웹",
    "v2.r07.counterparts_title": "상대방: 철도",
    "v2.r07.four_pillars": "네 가지 기둥",
    "v2.r07.historical_significance": "역사적 중요성",
    "v2.r07.next_relay": "다음 릴레이 →",
    "v2.r07.previous_relay": "← 이전 릴레이",
    "v2.r07.subtitle": "강철 척추 — 산업 연결",
    "v2.r07.title": "릴레이 7: 철도",
    "v2.r08.active_webs": "활성 웹",
    "v2.r08.counterparts_title": "상대방: 직조기",
    "v2.r08.four_pillars": "네 가지 기둥",
    "v2.r08.historical_significance": "역사적 중요성",
    "v2.r08.next_relay": "다음 릴레이 →",
    "v2.r08.previous_relay": "← 이전 릴레이",
    "v2.r08.subtitle": "짜여진 웹 — 정보 인프라",
    "v2.r08.title": "릴레이 8: 직조기",
    "v2.r09.active_webs": "활성 웹",
    "v2.r09.counterparts_title": "상대방: 엔진",
    "v2.r09.four_pillars": "네 가지 기둥",
    "v2.r09.historical_significance": "역사적 중요성",
    "v2.r09.next_relay": "다음 릴레이 →",
    "v2.r09.previous_relay": "← 이전 릴레이",
    "v2.r09.subtitle": "동력 혁명 — 기계화된 세계",
    "v2.r09.title": "릴레이 9: 엔진",
    "v2.r1.next_relay": "다음 계주 →",
    "v2.r1.previous_relay": "← 이전 계주",
    "v2.r1.subtitle": "원시의 불꽃 — 에너지 숙달의 시작",
    "v2.r1.title": "계주 1: 불",
    "v2.r10.active_webs": "활성 웹",
    "v2.r10.counterparts_title": "상대방: AAA 트리오",
    "v2.r10.four_pillars": "네 가지 기둥",
    "v2.r10.historical_significance": "역사적 중요성",
    "v2.r10.next_relay": "다음 계주 →",
    "v2.r10.previous_relay": "← 이전 계주",
    "v2.r10.subtitle": "항공, 원자, 자동화 — 현대의 삼위일체",
    "v2.r10.title": "계주 10: AAA 트리펙타",
    "v2.r11.active_webs": "활성 웹",
    "v2.r11.counterparts_title": "상대방: 인간 노드",
    "v2.r11.four_pillars": "네 가지 기둥",
    "v2.r11.historical_significance": "역사적 중요성",
    "v2.r11.next_relay": "다음 계주 →",
    "v2.r11.previous_relay": "← 이전 계주",
    "v2.r11.subtitle": "네트워크화된 인류 — 디지털 연결",
    "v2.r11.title": "계주 11: 인간 노드",
    "v2.r12.active_webs": "활성 웹",
    "v2.r12.counterparts_title": "상대방: 의식",
    "v2.r12.four_pillars": "네 가지 기둥",
    "v2.r12.historical_significance": "역사적 중요성",
    "v2.r12.next_relay": "다음 계주 →",
    "v2.r12.previous_relay": "← 이전 계주",
    "v2.r12.subtitle": "토러스 — 인프라의 궁극적 형태",
    "v2.r12.title": "계주 12: 의식",
    "v2.r2.next_relay": "다음 계주 →",
    "v2.r2.previous_relay": "← 이전 계주",
    "v2.r2.subtitle": "살아있는 건축 — 자연으로서의 공학",
    "v2.r2.title": "계주 2: 나무",
    "v2.r3.next_relay": "다음 계주 →",
    "v2.r3.previous_relay": "← 이전 계주",
    "v2.r3.subtitle": "수력 문명 — 액체 인프라",
    "v2.r3.title": "계주 3: 강",
    "v2.r4.next_relay": "다음 계주 →",
    "v2.r4.previous_relay": "← 이전 계주",
    "v2.r4.subtitle": "이동성 혁명 — 속도와 제국",
    "v2.r4.title": "계주 4: 말",
    "v2.r5.next_relay": "다음 계주 →",
    "v2.r5.previous_relay": "← 이전 계주",
    "v2.r5.subtitle": "연결된 네트워크 — 제국의 동맥",
    "v2.r5.title": "계주 5: 도로",
    "v2.r6.next_relay": "다음 계주 →",
    "v2.r6.previous_relay": "← 이전 계주",
    "v2.r6.subtitle": "해양 고속도로 — 글로벌 무역망",
    "v2.r6.title": "계주 6: 배",
    "v2.r7.next_relay": "다음 계주 →",
    "v2.r7.previous_relay": "← 이전 계주",
    "v2.r7.subtitle": "강철 척추 — 산업적 연결",
    "v2.r7.title": "계주 7: 철도",
    "v2.r8.next_relay": "다음 계주 →",
    "v2.r8.previous_relay": "← 이전 계주",
    "v2.r8.subtitle": "짜여진 웹 — 정보 인프라",
    "v2.r8.title": "계주 8: 직조기",
    "v2.r9.next_relay": "다음 계주 →",
    "v2.r9.previous_relay": "← 이전 계주",
    "v2.r9.subtitle": "동력 혁명 — 기계화된 세계",
    "v2.r9.title": "계주 9: 엔진",
    "v3.index.experience_title": "계주 경험",
    "v3.index.title": "제3권: 게임",
    "vol1.index.desc": "12개의 문명 릴레이를 통해 12,000년의 인프라 발전을 탐험하세요. 각 릴레이는 인류 능력의 근본적인 도약을 나타냅니다.",
    "vol1.index.subtitle": "역사와 배경 — 이야기",
    "vol1.index.title": "제1권: 관점",
    "vol2.index.desc": "각 릴레이의 실용적인 프레임워크, 비교 분석 및 전략적 모델. 서양, 동양 및 아웃라이더 방법론의 심층 비교.",
    "vol2.index.subtitle": "전략적 프레임워크 — 확장",
    "vol2.index.title": "제2권: 가이드",
    "vol3.index.desc": "현실 엔진 안내 학습 플랫폼. 동적 시뮬레이션 환경에서 개념을 적용합니다.",
    "vol3.index.subtitle": "시뮬레이션 및 실습 — 적용",
    "vol3.index.title": "제3권: 게임",
    "home.charter.charter.h": "헌장",
    "home.charter.charter.p": "우리는 인프라가 문명의 운영 체제라고 믿습니다. 강이 천천히 그리고 끈질기게 대지를 깎아 행성적 변화를 만들어내듯이, 우리는 개방된 지식, 검증된 기여, 문화적 존중, 그리고 우리가 세상을 어떻게 건설했는지 이해하는 것이 더 나은 세상을 건설하는 첫걸음이라는 신념에 전념합니다.",
    "home.charter.mission.h": "사명",
    "home.charter.mission.p": "세계 최초의 개방형, 다국어, AI 가이드 인프라 교육 플랫폼을 제공합니다 — 8개 언어로 10억 학습자에게 도달하며, 모든 대륙의 인간 기여자들이 검증합니다.",
    "home.charter.title": "사명, 비전 & 헌장",
    "home.charter.vision.h": "비전",
    "home.charter.vision.p": "모든 사람이 문명을 지탱하는 인프라를 이해하고 — 다음을 건설할 지식을 갖춘 세상.",
    "home.pop.answer": "IAAI는 그 숫자를 바꾸기 위해 존재합니다.",
    "home.pop.question": "명이 이 행성의 인프라를 공유합니다. 얼마나 많은 사람이 이해하고 있을까요?",
    "home.pop.source": "출처: UN 세계 인구 추정치 (실시간 예측)",
    "home.ppp.cta.sub": "무료 베타 접근 — 테스트, 번역, 검증하고 창립자 벽에서 당신의 자리를 차지하세요. 오디세이에 참여하세요.",
    "home.ppp.cta.title": "파이오니어가 되세요",
    "home.ppp.partners.h": "파트너",
    "home.ppp.partners.p": "대학, 기술 플랫폼, 인프라 기업. MIT OCW, Khan Academy, Meta/VR, Manus/AI, AECOM, Arup, Bechtel. 기술, 콘텐츠 검증, 시장 접근.",
    "home.ppp.partners.status": "상태: 도전 개방 — 플레이어가 지명",
    "home.ppp.patrons.h": "후원자",
    "home.ppp.patrons.p": "보편적 인프라 교육과 사명이 일치하는 기관. UNESCO, 내셔널 지오그래픽, NASA, 왕립학회, 디스커버리, 스미소니언, NOAA, 세계은행, ADB, 중국과학원.",
    "home.ppp.patrons.status": "상태: 도전 개방 — 플레이어가 지명",
    "home.ppp.players.h": "플레이어",
    "home.ppp.players.p": "모든 나라의 파이오니어, 앰배서더, 스칼라, 어드바이저. 테스트하고, 번역하고, 검증하고, 기여하고, 전파하는 실제 사람들. 민주주의의 힘.",
    "home.ppp.players.status": "상태: 파이오니어 모집 중 — 무료 베타 접근",
    "home.ppp.reach.active": "활성",
    "home.ppp.reach.active2": "활성",
    "home.ppp.reach.active3": "활성",
    "home.ppp.reach.active4": "활성",
    "home.ppp.reach.active5": "활성",
    "home.ppp.reach.active6": "활성",
    "home.ppp.reach.active7": "활성",
    "home.ppp.reach.active8": "활성",
    "home.ppp.reach.ar": "아랍어",
    "home.ppp.reach.cn": "중국어",
    "home.ppp.reach.coverage": "8개 언어로 전 세계 게임 시장의 약 85%, 에듀테크 지출의 약 80%, 그리고 최고의 인프라 투자 회랑을 커버합니다.",
    "home.ppp.reach.en": "영어",
    "home.ppp.reach.es": "스페인어",
    "home.ppp.reach.h": "글로벌 언어 도달 범위",
    "home.ppp.reach.hi": "힌디어",
    "home.ppp.reach.ja": "일본어",
    "home.ppp.reach.ko": "한국어",
    "home.ppp.reach.vi": "베트남어",
    "home.ppp.subtitle": "칼로리에서 의식까지 — 멈출 수도 통제할 수도 없는 개인 수준의 행동 촉구. 그저 계속 배울 뿐입니다.",
    "home.ppp.title": "후원자, 파트너 & 플레이어",
    "nav.founders": "창립자 벽",
    // ============================================
    // MISSING KEYS - ADDED BY TRANSLATION GENERATOR
    // ============================================
    "home.guide.btn": "가이드 읽기",
    "home.guide.title": "제2권: 가이드",
    "masters.subtitle": "모든 계층과 함께하는 역사적 정신 가이드 — 6+1 계층에 포함되지 않으며, 모든 모드, 모든 릴레이, 12,000년에 걸친 지적 동반자입니다. 게임 속 목소리, 벽의 인용문, 불에서 토러스로 이어지는 지혜입니다.",
    "masters.title": "마스터",
    "nav.glossary": "용어집",
    "nav.masters": "마스터",
    "nav.olympiad": "올림피아드",
    "nav.starthere": "여기서 시작",
    "precis.relay.relay_10_orbit": "릴레이 11: 궤도",
    "precis.relay.relay_11_human_nodes": "릴레이 12: 인간 노드",
    "precis.relay.relay_1_tree": "릴레이 2: 나무",
    "precis.relay.relay_2_river": "릴레이 3: 강",
    "precis.relay.relay_3_horse": "릴레이 4: 말",
    "precis.relay.relay_4_roads": "릴레이 5: 도로",
    "precis.relay.relay_5_ships": "릴레이 6: 배",
    "precis.relay.relay_6_loom": "릴레이 7: 직기",
    "precis.relay.relay_8_engine": "릴레이 9: 엔진",
    "precis.relay.relay_9_aaa": "릴레이 10: AAA 트라이어드",
    "tax.cta": "나무에서 당신의 자리를 찾으세요",
    "tax.cta.sub": "모든 종은 하나의 유기체에서 시작됩니다. 모든 운동은 한 명의 개척자에서 시작됩니다.",
    "tax.footer.cc": "CC BY-NC-SA 4.0",
    "tax.parallel.institutions.desc": "Organisations that can be challenged, engaged, or partnered with. Universities, UN bodies, professional societies, government agencies, NGOs, and corporations. They sit outside the contributor hierarchy but are the targets of the intelligence network and the Challenge Board.",
    "tax.parallel.institutions.title": "&#x1F3DB; Institutions &mdash; The Challenge Map",
    "tax.parallel.institutions.who": "UNESCO &bull; World Bank &bull; ASCE &bull; ICE &bull; MIT &bull; Khan Academy &bull; Meta &bull; National Geographic",
    "tax.parallel.outriders.desc": "Historical and philosophical figures who ride alongside every tier as intellectual companions. Not counted in the 6+1 &mdash; they exist across all levels, all modes, all time periods. They are the voices in the game, the quotes on the walls, the wisdom that connects 12,000 years of infrastructure.",
    "tax.parallel.outriders.title": "&#x1F3C7; Outriders &mdash; Spirit Guides",
    "tax.parallel.outriders.who": "Laozi &bull; Sun Tzu &bull; Confucius &bull; Vitruvius &bull; Leonardo da Vinci &bull; Isambard Kingdom Brunel &bull; Nikola Tesla &bull; Ada Lovelace",
    "tax.parallel.title": "병렬 트랙 (계층 구조 외부)",
    "tax.plus1.desc": "생물학에서 종은 가장 구체적인 분류 — 개별 유기체 자체입니다. IAAI에서 +1은 10억 학습자입니다",
    "tax.plus1.subtitle": "인류의 12.1% — 인프라 리터러시의 전환점",
    "tax.plus1.target": "목표: 1,000,000,000",
    "tax.plus1.title": "+1 — 종",
    "tax.quote": "\"모든 생명이 공통 조상을 공유하듯, 모든 인프라는 공통 목적을 공유합니다 — 문명에 봉사하는 것.\"",
    "tax.rank.class": "강",
    "tax.rank.domain": "역",
    "tax.rank.family": "과",
    "tax.rank.genus": "속",
    "tax.rank.kingdom": "계",
    "tax.rank.order": "목",
    "tax.rank.phylum": "문",
    "tax.table.biology": "생물학",
    "tax.table.count": "수",
    "tax.table.iaai": "IAAI",
    "tax.table.suntzu": "정보 (INT)",
    "tax.tier1.analogy": "Biology: Domain (Eukarya) &bull; Military: Commander-in-Chief &bull; Architecture: Master Builder",
    "tax.tier1.desc": "The singular origin point. Conceived the 12-relay framework, wrote the trilogy, designed the game, and built the platform. Like Domain in biology &mdash; the broadest, most fundamental classification from which everything else branches.",
    "tax.tier1.name": "창립자",
    "tax.tier1.title": "건축가",
    "tax.tier1.who": "Ir. Nigel T. Dearden &mdash; CEng MICE MHKIE",
    "tax.tier2.analogy": "Biology: Kingdom (Animalia) &bull; Military: General Staff &bull; Sun Tzu: The Five Essentials",
    "tax.tier2.desc": "The inner circle. Industry leaders, capital strategists, and institutional connectors who shape direction, open doors, and bridge the gap between vision and execution. By invitation or nomination only.",
    "tax.tier2.name": "고문단",
    "tax.tier2.title": "전략 위원회",
    "tax.tier2.who": "Michael Wu (COO) &bull; Henry Leong (CFO) &bull; Frank Sheu (CTO) &bull; Stephen Markscheid (Strategic Advisor)",
    "tax.tier3.analogy": "Biology: Phylum (Chordata) &bull; Military: Intelligence Corps &bull; Academia: Peer Review Board",
    "tax.tier3.desc": "Engineers, professors, and researchers who verify technical accuracy, map content to university curricula, and provide the academic credibility that transforms a game into an educational standard. The peer-review layer.",
    "tax.tier3.name": "학자",
    "tax.tier3.title": "학술 검증자",
    "tax.tier3.who": "Target: Engineering faculties, infrastructure researchers, curriculum designers",
    "tax.tier4.analogy": "Biology: Class (Mammalia) &bull; Military: Field Officers &bull; Diplomacy: Cultural Attach&eacute;s",
    "tax.tier4.desc": "Native-fluency contributors who review and correct AI translations against real usage. 10 per language block across 8 languages. They ensure infrastructure literacy speaks authentically in every tongue. Credited contributors with their names on the work.",
    "tax.tier4.name": "대사",
    "tax.tier4.title": "언어 리더",
    "tax.tier4.who": "Target: 10 per block &times; 8 blocks = 80 Ambassadors worldwide",
    "tax.tier5.analogy": "Biology: Order (Primates) &bull; Military: HUMINT (Human Intelligence) &bull; Scouts &amp; Reconnaissance",
    "tax.tier5.desc": "The first wave. 2&ndash;3 per language block who play the game, report bugs, validate content, and provide the ground-truth feedback that shapes the platform before public release. The HUMINT assets of the intelligence network — human intelligence on the ground.",
    "tax.tier5.name": "개척자",
    "tax.tier5.title": "베타 테스터 & 정찰대",
    "tax.tier5.who": "Currently recruiting &mdash; 3 active across EN and CN blocks",
    "tax.tier6.analogy": "Biology: Family (Hominidae) &bull; Military: The Rank and File &bull; Gaming: The Player Base",
    "tax.tier6.desc": "Everyone who plays The Reality Engine. From casual explorers to completionists who master all 12 relays across all 4 modes. They generate the data, the engagement, and the democratic nominations that power the Challenge Board. The lifeblood of the platform.",
    "tax.tier6.name": "플레이어",
    "tax.tier6.title": "게임 커뮤니티",
    "tax.tier6.who": "Target: 1M players by Year 2 &bull; Currently: 21 (beta)",
    "tax.tier7.analogy": "Biology: Genus (Homo) &bull; Military: ELINT (Electronic Intelligence) &bull; Logistics &amp; Supply",
    "tax.tier7.desc": "Those who fund the mission &mdash; from individual Kickstarter backers to institutional patrons (UNESCO, National Geographic, universities). They don't play or translate; they enable. Challenged by Players, engaged by Advisors. The ELINT channel of the intelligence network — converting institutional signals into engagement.",
    "tax.tier7.name": "후원자",
    "tax.tier7.title": "재정 & 기관 후원자",
    "tax.tier7.who": "Target: $500K seed &bull; Challenged: UNESCO, NatGeo, NASA, Royal Society, MIT OCW, Khan Academy",
    "v1.r01.continuity": "연속성",
    "v1.r01.energy_web": "에너지 웹",
    "v1.r01.infrastructure": "인프라",
    "v1.r01.knowledge_web": "지식 웹",
    "v1.r01.threats": "위협",
    "v1.r01.unification": "통합",
    "v1.r02.continuity": "연속성",
    "v1.r02.energy_web": "에너지 웹",
    "v1.r02.infrastructure": "인프라",
    "v1.r02.knowledge_web": "지식 웹",
    "v1.r02.threats": "위협",
    "v1.r02.unification": "통합",
    "v1.r03.continuity": "연속성",
    "v1.r03.energy_web": "에너지 웹",
    "v1.r03.infrastructure": "인프라",
    "v1.r03.knowledge_web": "지식 웹",
    "v1.r03.threats": "위협",
    "v1.r03.unification": "통합",
    "v1.r04.continuity": "연속성",
    "v1.r04.energy_web": "에너지 웹",
    "v1.r04.infrastructure": "인프라",
    "v1.r04.threats": "위협",
    "v1.r04.unification": "통합",
    "v1.r05.consciousness_web": "의식 웹",
    "v1.r05.continuity": "연속성",
    "v1.r05.infrastructure": "인프라",
    "v1.r05.knowledge_web": "지식 웹",
    "v1.r05.threats": "위협",
    "v1.r05.unification": "통합",
    "v1.r06.consciousness_web": "의식 웹",
    "v1.r06.continuity": "연속성",
    "v1.r06.infrastructure": "인프라",
    "v1.r06.knowledge_web": "지식 웹",
    "v1.r06.threats": "위협",
    "v1.r06.unification": "통합",
    "v1.r07.continuity": "연속성",
    "v1.r07.energy_web": "에너지 웹",
    "v1.r07.infrastructure": "인프라",
    "v1.r07.knowledge_web": "지식 웹",
    "v1.r07.threats": "위협",
    "v1.r07.unification": "통합",
    "v1.r08.consciousness_web": "의식 웹",
    "v1.r08.continuity": "연속성",
    "v1.r08.energy_web": "에너지 웹",
    "v1.r08.infrastructure": "인프라",
    "v1.r08.knowledge_web": "지식 웹",
    "v1.r08.threats": "위협",
    "v1.r08.unification": "통합",
    "v1.r09.continuity": "연속성",
    "v1.r09.energy_web": "에너지 웹",
    "v1.r09.infrastructure": "인프라",
    "v1.r09.knowledge_web": "지식 웹",
    "v1.r09.threats": "위협",
    "v1.r09.unification": "통합",
    "v1.r10.consciousness_web": "의식 웹",
    "v1.r10.continuity": "연속성",
    "v1.r10.energy_web": "에너지 웹",
    "v1.r10.infrastructure": "인프라",
    "v1.r10.knowledge_web": "지식 웹",
    "v1.r10.threats": "위협",
    "v1.r10.unification": "통합",
    "v1.r11.consciousness_web": "의식 웹",
    "v1.r11.continuity": "연속성",
    "v1.r11.infrastructure": "인프라",
    "v1.r11.knowledge_web": "지식 웹",
    "v1.r11.threats": "위협",
    "v1.r11.unification": "통합",
    "v1.r12.consciousness_web": "의식 웹",
    "v1.r12.continuity": "연속성",
    "v1.r12.infrastructure": "인프라",
    "v1.r12.knowledge_web": "지식 웹",
    "v1.r12.threats": "위협",
    "v1.r12.unification": "통합",
    "oly.title": "인프라스트럭처 올림피아드",
    "oly.stat.blocks": "언어 블록",
    "oly.stat.categories": "경쟁 카테고리",
    "oly.stat.universities": "전 세계 대학",
    "oly.stat.xpcap": "XP 상한 (마스터 위버)",
    "oly.stat.people": "도달 인구",
    "oly.stat.gap": "인프라 격차",
    "oly.flywheel.title": "플라이휠 — 올림피아드의 자체 성장 메커니즘",
    "oly.flywheel.players": "선수들이 경쟁",
    "oly.flywheel.professionals": "전문가들이 검증",
    "oly.flywheel.patrons": "후원자들이 지원",
    "oly.flywheel.platform": "플랫폼이 확장",
    "oly.medal.title": "실시간 메달 테이블 — 문명 관리에서 경쟁하는 국가들",
    "oly.th.nation": "국가",
    "oly.th.blocks": "블록",
    "oly.th.pop": "인구 (M)",
    "oly.th.gamers": "게이머 (M)",
    "oly.th.story": "인프라 스토리",
    "oly.th.total": "합계",
    "oly.th.status": "상태",
    "oly.rogue.title": "로그 팀 — 비소속 인재 풀",
    "oly.categories.title": "경쟁 카테고리 — 문명 인프라의 6대 기둥",
    "oly.pipeline.unis": "전 세계 대학",
    "oly.pipeline.students": "공학부 학생",
    "oly.pipeline.firms": "상위 토목공학 기업",
    "oly.pipeline.govts": "국가 정부",
    "oly.sponsor.title": "후원 등급 — 국가대표팀을 후원하세요",
    "oly.sponsor.gold": "골드 스폰서",
    "oly.sponsor.silver": "실버 스폰서",
    "oly.sponsor.bronze": "브론즈 스폰서",
    "oly.sponsor.patron": "후원자",
    "oly.form.register.title": "대학 팀 등록",
    "oly.form.sponsor.title": "후원 문의",
    "nav.behind": "논문 뒤에서",

    // SDG Alignment Section
    "sdg.title": "지속가능발전목표 — 정렬",
    "sdg.subtitle": "IAAI의 12릴레이 커리큘럼이 유엔 지속가능발전목표와 어떻게 연결되는가",
    "sdg.iconCaption": "IAAI 콘텐츠는 17개 지속가능발전목표 중 11개를 직접 다룹니다. 각 아이콘은 유엔 공식 목표 페이지로 연결됩니다.",
    "sdg.col.relay": "IAAI 릴레이",
    "sdg.col.sdgGoals": "SDG 목표",
    "sdg.col.alignment": "정렬 근거",
    "sdg.col.5p": "5P 범주",
    "sdg.r1.rationale": "도로 네트워크는 경제 발전의 순환 시스템입니다. 도로 없이는 시장 접근도, 응급 서비스도, 공급망도 없습니다.",
    "sdg.r2.rationale": "철도는 대중교통과 화물의 근간입니다. 도로보다 톤-km당 배출량이 적어 지속 가능한 도시화를 가능하게 합니다.",
    "sdg.r3.rationale": "항구는 국가를 세계 무역에 연결합니다. 세계 물품의 90%가 해상으로 이동합니다.",
    "sdg.r4.rationale": "항공 인프라는 글로벌 연결성, 무역, 관광 및 긴급 대응을 가능하게 합니다.",
    "sdg.r5.rationale": "깨끗한 물은 가장 근본적인 인프라입니다. 22억 명이 여전히 안전한 식수를 이용하지 못하고 있습니다.",
    "sdg.r6.rationale": "위생 시설은 질병을 예방하고 수원을 보호하며 인간의 존엄성을 지킵니다.",
    "sdg.r7.rationale": "에너지 인프라는 국가가 청정하게 산업화할지 화석연료 의존을 반복할지를 결정합니다.",
    "sdg.r8.rationale": "통신은 사람들을 교육, 시장, 거버넌스에 연결합니다. 디지털 격차는 인프라 격차입니다.",
    "sdg.r9.rationale": "폐기물 관리는 소비의 거울입니다. 순환 경제에는 수거, 분류, 재활용 인프라가 필요합니다.",
    "sdg.r10.rationale": "건강 인프라 — 병원, 클리닉, 공급망 — 는 인구가 팬데믹에서 살아남을 수 있는지를 결정합니다.",
    "sdg.r11.rationale": "교육 인프라 — 학교, 대학, 도서관 — 는 문명이 세대를 넘어 지식을 전달하는 메커니즘입니다.",
    "sdg.r12.rationale": "디지털 인프라 — 데이터 센터, 광섬유, 클라우드 — 는 21세기의 도로와 항구입니다.",
    "sdg.5pTitle": "5P — 사람, 지구, 번영, 평화, 파트너십",
    "sdg.5pText": "유엔은 5개 기둥(5P)을 통해 17개 SDG를 구성합니다. 인프라는 문명이 5개 P 모두를 실현하는 메커니즘입니다.",
    "sdg.visitUN": "유엔 SDG 공식 웹사이트 방문 →",
    "sdg.disclaimerTitle": "면책 조항:",
    "sdg.disclaimerText": "이 출판물의 내용은 유엔의 승인을 받지 않았으며 유엔 또는 그 관리 또는 회원국의 견해를 반영하지 않습니다.",
    "home.dominion.title": "지배권 상실 — 수렴 위기",
    "home.dominion.text": "여섯 번째 리셋은 우주에서 오지 않는다. 이미 여기에 있다 — 의사결정, 설계, 거버넌스가 인간 시스템에서 기계 시스템으로 이전되는 과정에서. 멸종이 아니다. 대체다. 12,000년간 문명을 지탱한 인프라가 어떤 세대도 흡수할 수 없는 속도로 수렴하고 있다. 이것이 수렴 위기다. 에피소드 2는 인류 연속성의 아키텍처를 그린다.",
    "home.fw.ele_planetary": "ELE 행성 시계 — 지구: 45억 년. 다섯 번의 리셋. ELE 6은 문명적 — 2050년. 지금 행동하라, 아니면 지배권을 잃는다.",
    "home.fw.continuity_grid": "완전 연속성 그리드 — 인류 역사가 1,200페이지 책이라면. 24행 = 24시간. 그리드가 시계다. 24행 = 마지막 한 시간.",
    "home.fw.row24": "24행 확장 — 마지막 한 시간. 12,000년 (기원전 10,000년 → 2050년). 500세대. 인류가 릴레이를 활용하는 유일한 행. 일곱 학자. 246년 내 여섯 릴레이. 모두 여전히 가동 중.",
    "home.fw.relay_cone": "릴레이 콘 — 500세대의 문명이 12개 인프라 릴레이로 압축. 측면도, 상면도, 그리고 일곱 학자. 처음 여섯 릴레이는 11,500년에 걸친다; 마지막 여섯은 246년으로 압축된다.",
    "home.ascent.title": "의식으로의 상승",
    "home.ascent.subtitle": "릴레이 12와 그 너머 — 2050년을 자정으로 하는 문명 논제",
    "home.ascent.text": "여기에 문명의 핵심이 있다. 칼로리에서 의식으로 — 인프라 오디세이는 12,000년을 12개 릴레이, 7명의 학자, 5개 웹, 3대 제국을 통해 그린다. 의식으로의 상승은 릴레이 12와 그 너머: 생물학적 지능이 자신의 인프라와 만나는 전환점이다. 호메로스에서 응용 세대까지 5개 층의 지적 계보가 하나의 질문으로 수렴한다: 누가 릴레이를 이어갈 것인가? 신학적 함의는 심오하다. 지배권 상실이 위기를 틀짓고, 대항력: 부분, 척도, 균형이 엔지니어의 계산을 제공한다. 제8학자는 여전히 열린 탐색 — 3,500년 기초 지혜 사슬의 다음 노드.",
    "home.ascent.source": "계보 5층 — 제8학자를 향한 3,500년 지적 릴레이 — iAAi 진리 프레임워크"
};
