// INFRASTRUCTURE ACADEMY - AR TRANSLATIONS
window.IA_LANG_AR = {
    "archive.documents": "الوثائق",
    "archive.images": "الصور",
    "archive.references": "المراجع",
    "archive.relays": "السباقات",
    "archive.subtitle": "الحفاظ الكامل على الأصول المعرفية",
    "archive.supplements": "الملحقات",
    "archive.title": "الأرشيف",
    "author.bio": "المهندس نايجل تي ديردن (鄧禮祖) مهندس مدني وإنشائي قانوني ومدير مياه وبيئة قانوني، يتمتع بخبرة تزيد عن 33 عامًا في البنية التحتية في هونغ كونغ. مؤسس شركة 4 Elements Consulting Ltd (تأسست 2006، www.4ecl.com). BEng (Hon's), CEng, C.WEM, RPE (CSB), MICE, MHKIE, MCIWEM.",
    "author.credentials": "مهندس معتمد (CEng)، عضو في معهد المهندسين المدنيين (MICE)، عضو في معهد هونغ كونغ للمهندسين (MHKIE)",
    "author.name": "المهندس نايجل تي. ديردن",
    "author.title": "عن المؤلف",
    "civ.civilisation.subtitle": "12,000 سنة = 24 ساعة",
    "civ.civilisation.title": "ساعة الحضارة",
    "civ.cosmic.subtitle": "13.5 مليار سنة = 24 ساعة",
    "civ.cosmic.title": "ساعة الكون",
    "civ.cta.desc": "القلم في أيدينا. البنية التحتية في مكانها. اللحظة هي الآن. السؤال ليس ما إذا كان هذا التقارب سيحدث — إنه يحدث بالفعل. السؤال هو: كيف سنستجيب؟",
    "civ.cta.title": "منتصف الليل يقترب",
    "civ.epigraph": "\"ساعة العناصر تدق نحو منتصف الليل. ما نفعله في هذه الثواني الأخيرة سيتردد صداه لآلاف السنين.\"",
    "civ.nesting.desc": "كل ساعة متداخلة داخل الأخرى. تشغل ساعة الكوكب بأكملها الثلث الأخير فقط من ساعة الكون. تشغل ساعة الحضارة بأكملها لحظة واحدة فقط من ساعة الكوكب. نحن نعيش في اللحظات الأخيرة قبل منتصف الليل.",
    "civ.nesting.title": "ثلاث ساعات، قصة واحدة",
    "civ.planetary.subtitle": "4.5 مليار سنة = 24 ساعة",
    "civ.planetary.title": "ساعة الكوكب",
    "civ.relay.title": "12 سباقًا على ساعة الحضارة",
    "civ.subtitle": "ثلاث ساعات متداخلة مدتها 24 ساعة — من الانفجار العظيم إلى اللحظة البشرية. 13.5 مليار سنة من التاريخ الكوني، 4.5 مليار سنة من التطور الكوكبي، 12,000 سنة من الحضارة — كل منها مرسومة على يوم واحد. منتصف الليل يقترب.",
    "civ.title": "ساعة العناصر",
    "clock.bar.end": "1,000,000,000 — المهمة مكتملة",
    "clock.bar.mid": "الرواد ← السفراء ← العلماء",
    "clock.bar.start": "0 — إطلاق",
    "clock.challenge.note": "تم التحدي = تم ترشيحه من قبل اللاعبين · لم يتم بعد = في انتظار الترشيح",
    "clock.challenge.title": "لوحة تحدي الرعاة",
    "clock.contributors.advisors": "المستشارون (الاستراتيجية)",
    "clock.contributors.ambassadors": "السفراء (قادة اللغة)",
    "clock.contributors.backers": "الداعمون (التمويل)",
    "clock.contributors.founders": "الفريق المؤسس",
    "clock.contributors.patrons": "الرعاة (المؤسسات)",
    "clock.contributors.pioneers": "الرواد (المختبرون)",
    "clock.contributors.players": "اللاعبون (اللعبة)",
    "clock.contributors.scholars": "العلماء (المدققون الأكاديميون)",
    "clock.contributors.title": "فئات المساهمين",
    "clock.cta": "انضم إلى السباق — كن رائدًا",
    "clock.cta.sub": "رحلة المليار متعلم تبدأ برائد واحد.",
    "clock.hero.mobilised": "تم تعبئتهم حاليًا",
    "clock.hero.pop": "سكان العالم",
    "clock.hero.pop.sub": "تقدير مباشر من الأمم المتحدة",
    "clock.hero.target": "الهدف: مليار متعلم",
    "clock.hero.target.sub": "12.1% من البشرية — نقطة التحول",
    "clock.intelligence.comint": "COMINT — استخبارات الاتصالات (شبكة الترجمة)",
    "clock.intelligence.elint": "ELINT — الاستخبارات الإلكترونية (توزيع المنصة)",
    "clock.intelligence.geoint": "GEOINT — الاستخبارات الجغرافية المكانية (رسم خرائط المناطق اللغوية الثماني)",
    "clock.intelligence.humint": "HUMINT — الاستخبارات البشرية (الرواد + السفراء)",
    "clock.intelligence.masint": "MASINT — استخبارات القياس (تحليلات التعلم)",
    "clock.intelligence.osint": "OSINT — استخبارات المصادر المفتوحة (GitHub + البيانات العامة)",
    "clock.intelligence.sigint": "SIGINT — استخبارات الإشارات (تحليل الذكاء الاصطناعي DAVID)",
    "clock.intelligence.title": "شبكة استخبارات IAAI (INTs)",
    "clock.milestones.first_pioneer": "الموجة الأولى من الرواد",
    "clock.milestones.github": "GitHub مفتوح المصدر",
    "clock.milestones.seed": "الجولة الأولية (500 ألف دولار)",
    "clock.milestones.title": "المعالم",
    "clock.milestones.vr": "الحرم الجامعي للواقع الافتراضي (Meta)",
    "clock.notyet.ce_firms": "شركات الهندسة المدنية (أفضل 100)",
    "clock.notyet.cta": "كل رقم أعلاه هو تحدٍ. كل صفر هو دعوة.",
    "clock.notyet.eng_students": "طلاب الهندسة",
    "clock.notyet.govts": "الحكومات الوطنية",
    "clock.notyet.people": "الأشخاص الذين لا يعرفون عن البنية التحتية",
    "clock.notyet.title": "لم يشارك بعد — التحدي",
    "clock.notyet.un_bodies": "هيئات الأمم المتحدة",
    "clock.notyet.universities": "جامعات العالم",
    "clock.partners.title": "لوحة تحدي الشركاء",
    "clock.platform.game_pages": "صفحات اللعبة",
    "clock.platform.inventions": "الاختراعات المفهرسة",
    "clock.platform.languages_active": "اللغات النشطة",
    "clock.platform.languages_planned": "اللغات المخطط لها",
    "clock.platform.pages": "صفحات الموقع",
    "clock.platform.relays": "السباقات المكتملة",
    "clock.platform.tests": "الاختبارات التي تم اجتيازها",
    "clock.platform.title": "مقاييس المنصة",
    "clock.platform.words": "الكلمات المكتوبة",
    "clock.regions.coverage": "تغطية مجمعة: ~85% من سوق الألعاب العالمي · ~80% من الإنفاق على تكنولوجيا التعليم",
    "clock.regions.goal": "الهدف: جميع اللغات الثماني بحلول عام 2027",
    "clock.regions.title": "8 تكتلات لغوية — السباق العالمي",
    "clock.scaling.phase1": "المرحلة 1: المؤسسون",
    "clock.scaling.phase2": "المرحلة 2: الرواد (2-3 لكل تكتل لغوي)",
    "clock.scaling.phase3": "المرحلة 3: السفراء (10 لكل تكتل لغوي)",
    "clock.scaling.phase4": "المرحلة 4: GitHub مفتوح المصدر",
    "clock.scaling.phase5": "المرحلة 5: تبني الجامعات",
    "clock.scaling.phase6": "المرحلة 6: النمو العضوي",
    "clock.scaling.title": "نموذج التوسع",
    "clock.subtitle": "سباق البشرية نحو محو الأمية في البنية التحتية — التحدي",
    "clock.title": "ساعة التعبئة العالمية IAAI",
    "footer.ep1": "الحلقة 1: الأساس الأرضي",
    "footer.ep2": "الحلقة 2: الساحة الرمادية",
    "footer.ep3": "الحلقة 3: المقياس الكوني",
    "footer.copyright": "&copy; 2026 أكاديمية البنية التحتية. جميع الحقوق محفوظة. المعرفة محفوظة إلى الأبد.",
    "framework.4cs.challenge": "التحدي",
    "framework.4cs.consequence": "العواقب",
    "framework.4cs.context": "السياق",
    "framework.4cs.continuum": "الاستمرارية",
    "framework.4cs.title": "إطار تحليل 4C",
    "framework.modes.east": "النمط الشرقي",
    "framework.modes.east.desc": "مستمر / بناء — نموذج تشين شي هوانغ",
    "framework.modes.outrider": "نمط الفارس",
    "framework.modes.outrider.desc": "شبه مستمر / أعمال مؤقتة — نموذج جنكيز خان",
    "framework.modes.title": "الأنماط الحضارية الثلاثة",
    "framework.modes.west": "النمط الغربي",
    "framework.modes.west.desc": "غير مستمر / بناء — نموذج الإسكندر الأكبر",
    "framework.relays.title": "12 سباقًا حضاريًا",
    "framework.subtitle": "منهجية تفكير نظامي شاملة",
    "framework.title": "الإطار الكامل",
    "header.subtitle": "أوديسة البنية التحتية: الكتاب الأول — من السعرات الحرارية إلى الوعي",
    "header.subtitle.v2": "أوديسة البنية التحتية: الكتاب الثاني — الدليل العملي",
    "header.subtitle.v3": "أوديسة البنية التحتية: الكتاب الثالث — محرك الواقع",
    "header.title": "أكاديمية البنية التحتية",
    "home.archive.architects": "مهندسو القدر والموحدون العظماء: الإسكندر الأكبر، جنكيز خان، تشين شي هوانغ",
    "home.archive.p1": "أكاديمية البنية التحتية هي أرشيف رقمي يحافظ على الأصول المعرفية الكاملة لأوديسة البنية التحتية — دورة متقدمة حضارية في 12,000 عام من تطور البنية التحتية البشرية. يضمن هذا الموقع الحفاظ الأبدي للمعرفة للعلماء والمهندسين والمتعلمين في جميع أنحاء العالم.",
    "home.archive.p2": "يتم دمج جميع المحتويات والتصورات والأطر هنا لسهولة التنقل والاكتشاف. إنه سجل دائم لصعود البشرية من السعرات الحرارية إلى الوعي، محفور في الخلود الرقمي بواسطة القلم.",
    "home.archive.title": "حول هذا الأرشيف",
    "home.author": "بقلم المهندس نايجل تي. ديردن",
    "home.challenge.stat1.desc": "من المناهج تفتقر إلى التكامل متعدد التخصصات",
    "home.challenge.stat1.num": "70%",
    "home.challenge.stat2.desc": "من الطلاب يشعرون بعدم الاستعداد للتطبيق العملي",
    "home.challenge.stat2.num": "65%",
    "home.challenge.stat3.desc": "يبلغون عن تعرض محدود للتفكير على مستوى الأنظمة",
    "home.challenge.stat3.num": "45%",
    "home.challenge.stat4.desc": "من أصحاب العمل يرون فجوات في المهارات في الاستعداد للمشاريع",
    "home.challenge.stat4.num": "80%",
    "home.challenge.stat5.desc": "من المشاريع تدمج مقاييس التأثير المجتمعي أو البيئي",
    "home.challenge.stat5.num": "30%",
    "home.challenge.stat6.desc": "من مشاريع البنية التحتية تتأخر بسبب فجوات المعرفة العملية",
    "home.challenge.stat6.num": "90%",
    "home.challenge.subtitle": "تعليم البنية التحتية مجزأ ومجرد ومنفصل عن التأثير في العالم الحقيقي.",
    "home.challenge.title": "التحدي الذي نعالجه",
    "home.challenge.urgent": "الحاجة الملحة: سد الفجوة لمحترفي البنية التحتية الجاهزين للمستقبل",
    "home.cover.front": "الغلاف الأمامي والخلفي — الحلقة الأولى: الأساس الأرضي",
    "home.cover.interior": "انتشار داخلي — الفصل الأول: سباق النار (الجزء الأول والثاني)",
    "home.cover.portrait": "سباق الحضارة — 12 فصلاً من الشجرة إلى الطارة",
    "home.ep1.btn": "صدرت",
    "home.ep1.desc": "من السعرات الحرارية إلى الوعي — 12 سباقًا من النار إلى الطارة",
    "home.ep1.subtitle": "الأساس الأرضي",
    "home.ep1.title": "الحلقة الأولى",
    "home.ep2.btn": "قريباً",
    "home.ep2.desc": "السيبرانية والذكاء الاصطناعي والأنظمة الذكية",
    "home.ep2.subtitle": "محرك الواقع — الساحة الرمادية",
    "home.ep2.title": "الحلقة الثانية",
    "home.ep3.btn": "قريباً",
    "home.ep3.desc": "الإشراف على الكواكب والنظام الشمسي والمجرة",
    "home.ep3.subtitle": "الإشراف والتجديد — المقياس الكوني",
    "home.ep3.title": "الحلقة الثالثة",
    "home.framework.journey": "الرحلة هي العمل.",
    "home.framework.modes.caption": "الأنماط الثلاثة — الغربي والشرقي والفارس عبر 12,000 عام",
    "home.framework.motto": "تعليم البنية التحتية: تفكير نظامي، وليس حفظًا عن ظهر قلب",
    "home.framework.relays.caption": "12 سباقًا حضاريًا — من النار إلى الوعي",
    "home.framework.silk.caption": "مفارقة طريق الحرير — سيطر الفرسان على طرق التجارة دون بناء أي بنية تحتية",
    "home.framework.subtitle": "تفكير نظامي شامل لتعليم البنية التحتية من منظور مهندس مدني",
    "home.framework.title": "الإطار الكامل",
    "home.game.cta.sub": "المجلد الثالث: محرك الواقع — منصة التعلم الموجهة",
    "home.game.cta.title": "ادخل اللعبة",
    "home.game.desc": "هل أنت مستعد لتطبيق ما تعلمته؟ ادخل محرك الواقع — منصة التعلم الغامرة حيث تصبح مهندس البنية التحتية.",
    "home.game.note": "المحاكاة والممارسة: طبق المفاهيم في بيئة ديناميكية",
    "home.game.title": "المجلد الثالث: اللعبة",
    "home.hero.caption": "من السعرات الحرارية إلى الوعي: أوديسة البنية التحتية — سباق الحضارة",
    "home.kw.subtitle": "تاريخ شامل للكتابة — من رموز المحاسبة إلى العصر الرقمي. القلم كسباق البنية التحتية النهائي.",
    "home.kw.title": "شبكة المعرفة: الكلمة كبنية تحتية",
    "home.media.calories": "من السعرات الحرارية إلى الوعي",
    "home.media.engine": "محرك الواقع — منصة التعلم الموجهة",
    "home.media.river": "فيلم سهل النهر",
    "home.media.title": "الوسائط",
    "home.media.trailer": "مقطع دعائي سريع",
    "home.ppp.clock.sub": "تتبع سباق البشرية نحو محو الأمية في البنية التحتية في الوقت الفعلي. لقد بدأ التحدي.",
    "home.ppp.clock.title": "عرض ساعة التعبئة",
    "home.s1.desc": "المفاهيم الأساسية — الأنماط الثلاثة، ساعة العناصر، الجدول الزمني للطرق والسفن",
    "home.s1.title": "S1: تحديد",
    "home.s2.desc": "انتشار التكنولوجيا — القلم كبنية تحتية، أنظمة الكتابة",
    "home.s2.title": "S2: فهم",
    "home.s3.desc": "التنفيذ — مخططات الإدارة لكل سباق",
    "home.s3.title": "S3: إدارة وتحكم",
    "home.s4.desc": "النظراء — مقارنة بين الغرب والفارس والشرق لكل سباق",
    "home.s4.title": "S4: أطروحة ورؤية",
    "home.subtitle": "منظور ودليل لمهندس مدني — الحلقة الأولى: من السعرات الحرارية إلى الوعي",
    "home.supplements.btn": "عرض الملحقات",
    "home.supplements.title": "المجلد الثاني: 4 ملاحق",
    "home.title": "أوديسة البنية التحتية",
    "home.trilogy.title": "رؤية الثلاثية",
    "home.vol1.btn": "اقرأ المنظور",
    "home.vol1.desc": "الأساس السردي: 12 سباقًا حضاريًا عبر 12,000 عام من تطور البنية التحتية البشرية. من إتقان النار إلى طارة الوعي.",
    "home.vol1.subtitle": "التاريخ والسياق — القصة",
    "home.vol1.title": "المجلد الأول: المنظور",
    "home.vol2.btn": "اقرأ الدليل",
    "home.vol2.desc": "الإطار العملي: نهج مقارن بين الغرب/الشرق/الفارس، تحليل 4C، ونماذج استراتيجية لفهم البنية التحتية كحمض نووي للحضارة.",
    "home.vol2.subtitle": "الإطار الاستراتيجي — التوسع",
    "home.vol2.title": "المجلد الثاني: الدليل",
    "inst.coming": "قريباً — قاعدة بيانات المؤسسات الكاملة قيد الإنشاء",
    "inst.sdg.title": "مصنفة حسب أهداف التنمية المستدامة",
    "inst.status.challenged": "تم التحدي",
    "inst.status.engaged": "تم المشاركة",
    "inst.status.notyet": "لم يتم الاتصال بعد",
    "inst.status.potential": "محتمل",
    "inst.subtitle": "خريطة الاستخبارات — كل مؤسسة، جامعة، هيئة تابعة للأمم المتحدة، جمعية مهنية، منظمة غير حكومية، مزود تكنولوجيا، ومؤسسة رأسمالية يمكن حشدها أو تحديها أو الشراكة معها. منظمة حسب أهداف التنمية المستدامة للأمم المتحدة لإظهار التوافق مع الأولويات العالمية.",
    "inst.title": "المؤسسات",
    "lib.supp_title": "الوثائق التكميلية",
    "lib.title": "مكتبة الوثائق",
    "library.subtitle": "الأرشيف الكامل للأصول المعرفية",
    "library.title": "مكتبة الوثائق",
    "nav.author": "المؤلف",
    "nav.charter": "الميثاق",
    "nav.civclock": "ساعة الحضارة",
    "nav.clock": "ساعة التعبئة",
    "nav.documents": "الوثائق",
    "nav.framework": "الإطار",
    "nav.home": "الرئيسية",
    "nav.institutions": "المؤسسات",
    "nav.outriders": "الرواد",
    "nav.pioneers": "برنامج الرواد",
    "nav.precis": "الموجز التنفيذي",
    "nav.resources": "الموارد",
    "nav.supplements": "الملحقات",
    "nav.taxonomy": "التصنيف",
    "nav.ep1": "الحلقة 1: المنظور",
    "nav.ep2": "الحلقة 2: الدليل",
    "nav.ep3": "الحلقة 3: اللعبة",
    "or.conn.book.desc": "يبدأ كل فصل وينتهي باقتباس من أحد الرواد. ابتكاراتهم هي دراسات حالة. إخفاقاتهم هي حكايات تحذيرية. هم الأساس الإثباتي للحجة.",
    "or.conn.book.title": "في الكتاب",
    "or.conn.game.desc": "يظهر الرواد كمرشدين غير لاعبين، ومصادر اقتباس، ومقدمي سياق تاريخي في كل سباق. يواجههم اللاعبون أثناء تقدمهم عبر الفصول الـ 12.",
    "or.conn.game.title": "في اللعبة",
    "or.conn.movement.desc": "يقدم الرواد السلطة الأخلاقية. عندما تتحدى IAAI اليونسكو أو معهد ماساتشوستس للتكنولوجيا، فإنها تقف على أكتاف 12,000 عام من حكمة البنية التحتية التي يجسدها هؤلاء الشخصيات.",
    "or.conn.movement.title": "في الحركة",
    "or.conn.title": "كيف يخدم الرواد المهمة",
    "or.era1.title": "العالم القديم",
    "or.era2.title": "العالم الكلاسيكي",
    "or.era3.title": "العصور الوسطى وعصر النهضة",
    "or.era4.title": "الثورة الصناعية",
    "or.era5.title": "العصر الحديث",
    "or.era6.title": "العصر الرقمي والمستقبل",
    "or.quote": "\"إن سبب انتصار الملك المستنير والجنرال الجيد في كل مرة يتحركون فيها، وتجاوز إنجازاتهم إنجازات الرجال العاديين، هو المعرفة المسبقة.\" — سون تزو، الفصل 13",
    "or.stat.civilisations": "الحضارات الممثلة",
    "or.stat.eras": "العصور التاريخية",
    "or.stat.relays": "السباقات المغطاة",
    "or.stat.total": "إجمالي الرواد",
    "or.subtitle": "الموجهون الروحيون التاريخيون الذين يركبون جنبًا إلى جنب مع كل طبقة — ليسوا جزءًا من هيكل 6+1، هؤلاء الشركاء الحكماء يمتدون عبر جميع الأنماط، وجميع السباقات، وكل 12,000 عام. هم الأصوات في اللعبة، والاقتباسات على الجدران، والحكمة التي تربط النار بالطارة.",
    "or.title": "الرواد",
    "pioneers.charter.agree": "لقد قرأت ووافقت على ميثاق IAAI. أتعهد بالمساهمة الصادقة والاحترام الثقافي والمشاركة المفتوحة للمعرفة عبر اللغات والحدود. أفهم أن هذا برنامج تطوعي وأن مساهماتي سيتم الاعتراف بها بموجب ترخيص CC BY-NC-SA 4.0.",
    "pioneers.charter.text": "نحن نؤمن بأن البنية التحتية هي نظام تشغيل الحضارة. مثلما ينحت النهر الأرض ببطء ولكن بثبات لتحقيق تغيير على مستوى الكوكب، نحن ملتزمون بالمعرفة المفتوحة، والمساهمات التي تم التحقق منها، والاحترام الثقافي، وفهم أن كيفية بناء عالمنا هي الخطوة الأولى لبناء عالم أفضل.",
    "pioneers.charter.title": "ميثاق IAAI",
    "pioneers.form.country": "البلد",
    "pioneers.form.email": "البريد الإلكتروني",
    "pioneers.form.expertise": "مجال الخبرة",
    "pioneers.form.language": "اللغة الأساسية",
    "pioneers.form.motivation": "لماذا تريد الانضمام؟ (اختياري)",
    "pioneers.form.name": "الاسم الكامل",
    "pioneers.form.other_langs": "لغات أخرى",
    "pioneers.form.submit": "إرسال الطلب — انضم إلى السباق",
    "pioneers.form.subtitle": "وصول تجريبي مجاني. لا رسوم. لا التزامات. فقط الفضول والالتزام.",
    "pioneers.form.title": "تقدم بطلب لتكون رائدًا",
    "pioneers.subtitle": "الموجة الأولى من المساهمين لاختبار وترجمة والتحقق من ونشر محو الأمية في البنية التحتية في كل قارة. وصول تجريبي مجاني. اكسب مكانك على جدار المؤسسين.",
    "pioneers.tier1.desc": "المختبرون الأوائل. العب اللعبة، أبلغ عن الأخطاء، تحقق من المحتوى. 2-3 لكل تكتل لغوي. كشافة شبكة الاستخبارات.",
    "pioneers.tier1.req": "المتطلبات: الفضول، أي لغة، الرغبة في الاختبار",
    "pioneers.tier1.title": "الرواد",
    "pioneers.tier2.desc": "قادة اللغة. مراجعة وتصحيح ترجمات الذكاء الاصطناعي للاستخدام الأصلي. كن مساهمًا معتمدًا. 10 لكل تكتل لغوي.",
    "pioneers.tier2.req": "المتطلبات: إتقان اللغة الأم + خبرة رائد",
    "pioneers.tier2.title": "السفراء",
    "pioneers.tier3.desc": "المدققون الأكاديميون. مهندسون وأساتذة وباحثون يتحققون من الدقة الفنية ويربطون المحتوى بالمناهج الدراسية.",
    "pioneers.tier3.req": "المتطلبات: مؤهلات أكاديمية + خبرة في المجال",
    "pioneers.tier3.title": "العلماء",
    "pioneers.tier4.desc": "التوجيه الاستراتيجي. قادة الصناعة وواضعو السياسات والموصلون المؤسسيون الذين يفتحون الأبواب ويشكلون الاتجاه.",
    "pioneers.tier4.req": "المتطلبات: دعوة أو ترشيح",
    "pioneers.tier4.title": "المستشارون",
    "pioneers.title": "برنامج الرواد",
    "precis.relay.epilogue": "الخاتمة",
    "precis.relay.prologue": "المقدمة",
    "precis.relay.relay_10_aaa": "السباق 10: ثلاثية AAA",
    "precis.relay.relay_10_autoair": "السباق 10: السيارات/الطيران",
    "precis.relay.relay_11_humans": "السباق 11: العقد البشرية",
    "precis.relay.relay_11_orbit": "السباق 11: المدار",
    "precis.relay.relay_12_programmable": "السباق 12: قابل للبرمجة",
    "precis.relay.relay_12_torus": "السباق 12: الطارة",
    "precis.relay.relay_1_fire": "السباق 1: النار",
    "precis.relay.relay_2_tree": "السباق 2: الشجرة",
    "precis.relay.relay_3_river": "السباق 3: النهر",
    "precis.relay.relay_4_horse": "السباق 4: الحصان",
    "precis.relay.relay_5_road": "السباق 5: الطرق",
    "precis.relay.relay_6_ship": "السباق 6: السفن",
    "precis.relay.relay_7_rail": "السباق 7: السكك الحديدية",
    "precis.relay.relay_8_loom": "السباق 8: النول",
    "precis.relay.relay_9_engine": "السباق 9: المحرك",
    "precis.relay.torus": "الطارة",
    "precis.subtitle": "أوديسة البنية التحتية — نظرة عامة استراتيجية",
    "precis.title": "الموجز التنفيذي",
    "relay.1.name": "السباق 1: النار",
    "relay.1.subtitle": "الشرارة البدائية — بداية إتقان الطاقة",
    "relay.10.name": "السباق 10: ثلاثية AAA",
    "relay.10.subtitle": "الطيران، الذرة، الأتمتة — الثالوث الحديث",
    "relay.11.name": "السباق 11: العقد البشرية",
    "relay.11.subtitle": "البشر المتصلون بالشبكة — الاتصال الرقمي",
    "relay.12.name": "السباق 12: الوعي",
    "relay.12.subtitle": "الطارة — الشكل النهائي للبنية التحتية",
    "relay.2.name": "السباق 2: الشجرة",
    "relay.2.subtitle": "العمارة الحية — الطبيعة كهندسة",
    "relay.3.name": "السباق 3: النهر",
    "relay.3.subtitle": "الحضارات الهيدروليكية — البنية التحتية السائلة",
    "relay.4.name": "السباق 4: الحصان",
    "relay.4.subtitle": "ثورة التنقل — السرعة والإمبراطوريات",
    "relay.5.name": "السباق 5: الطرق",
    "relay.5.subtitle": "الشبكات المتصلة — شرايين الإمبراطورية",
    "relay.6.name": "السباق 6: السفن",
    "relay.6.subtitle": "طرق المحيط السريعة — شبكات التجارة العالمية",
    "relay.7.name": "السباق 7: السكك الحديدية",
    "relay.7.subtitle": "العمود الفقري الفولاذي — الاتصال الصناعي",
    "relay.8.name": "السباق 8: النول",
    "relay.8.subtitle": "الشبكة المنسوجة — بنية تحتية للمعلومات",
    "relay.9.name": "السباق 9: المحرك",
    "relay.9.subtitle": "ثورة القوة — عالم ميكانيكي",
    "relay.epilogue": "الخاتمة",
    "relay.prologue": "المقدمة",
    "resources.subtitle": "المراجع ومصادر البيانات والقراءات الإضافية",
    "resources.title": "الموارد",
    "section.4c_analysis": "تحليل 4C",
    "section.active_webs": "الشبكات النشطة",
    "section.back_to_index": "العودة إلى الفهرس",
    "section.challenge": "التحدي",
    "section.communication_web": "شبكة الاتصالات",
    "section.comparative_analysis": "تحليل مقارن",
    "section.consciousness_web": "شبكة الوعي",
    "section.consequence": "العواقب",
    "section.context": "السياق",
    "section.continuity": "الاستمرارية",
    "section.continuum": "المستمر",
    "section.digital_web": "الشبكة الرقمية",
    "section.east_mode": "النموذج الشرقي",
    "section.energy_web": "شبكة الطاقة",
    "section.four_pillars": "الأركان الأربعة الرئيسية",
    "section.governance_web": "شبكة الحوكمة",
    "section.historical_significance": "الأهمية التاريخية",
    "section.impact": "التأثير:",
    "section.information_web": "شبكة المعلومات",
    "section.infrastructure": "البنية التحتية",
    "section.key_insights": "رؤى رئيسية",
    "section.knowledge_web": "شبكة المعرفة",
    "section.legacy": "الإرث:",
    "section.management_diagram": "إدارة المخططات",
    "section.military_web": "الشبكات العسكرية",
    "section.next_relay": "التسليم التالي →",
    "section.outrider_mode": "وضع الرينجر",
    "section.previous_relay": "← السابقة التتابع",
    "section.production_web": "شبكة الإنتاج",
    "section.strategic_framework": "الإطار الاستراتيجي",
    "section.the_counterparts": "الطرف المقابل:",
    "section.the_first_infrastructure": "البنية التحتية الأولى",
    "section.threats": "تهديد",
    "section.timeline": "الجدول الزمني:",
    "section.trade_web": "شبكة التجارة",
    "section.transport_web": "شبكة النقل",
    "section.unification": "موحد",
    "section.west_mode": "النموذج الغربي",
    "special.conclusion": "الاستنتاج",
    "special.epilogue": "الخاتمة",
    "special.from_calories_to_consciousness": "من السعرات الحرارية إلى الوعي",
    "special.prologue": "المقدمة",
    "special.the_beginning": "ابدأ",
    "special.the_journey_begins": "بداية الرحلة",
    "special.the_journey_continues": "تستمر الرحلة",
    "supplements.s1": "الملحق 1: تحديد",
    "supplements.s2": "الملحق 2: فهم",
    "supplements.s3": "الملحق 3: إدارة وتحكم",
    "supplements.s4": "الملحق 4: أطروحة ورؤية",
    "supplements.subtitle": "مواد توسعية متعمقة للمجلد الثاني",
    "supplements.title": "الملحقات",
    "tax.advisors": "المستشارون",
    "tax.advisors.desc": "التوجيه الاستراتيجي. قادة الصناعة والموصلون المؤسسيون.",
    "tax.ambassadors": "السفراء",
    "tax.ambassadors.desc": "قادة اللغة. 10 لكل تكتل لغوي.",
    "tax.backers": "الداعمون",
    "tax.backers.desc": "التمويل والدعم المؤسسي. الرعاة والشركاء.",
    "tax.biology": "التناظر البيولوجي",
    "tax.count": "العدد",
    "tax.founder": "المؤسس",
    "tax.founder.desc": "المهندس المعماري. شخص واحد. صمم النظام بأكمله.",
    "tax.iaai": "رتبة IAAI",
    "tax.outriders.note": "الرواد (الموجهون الروحيون التاريخيون) ليسوا جزءًا من هيكل 6+1 — فهم يركبون جنبًا إلى جنب مع جميع الأنماط، وجميع السباقات، وكل 12,000 عام.",
    "tax.pioneers": "الرواد",
    "tax.pioneers.desc": "المختبرون الأوائل. 2-3 لكل تكتل لغوي.",
    "tax.players": "اللاعبون",
    "tax.players.desc": "المشاركون في اللعبة. الهدف: مليار متعلم.",
    "tax.role": "الدور",
    "tax.scholars": "العلماء",
    "tax.scholars.desc": "المدققون الأكاديميون. أساتذة ومهندسون وباحثون.",
    "tax.subtitle": "هيكل من 6+1 طبقات — مثلما ينتقل التصنيف البيولوجي من المملكة إلى النوع، تنتقل طبقات مساهمي IAAI من المؤسس إلى الداعمين، كل طبقة أوسع وأكثر تخصصًا.",
    "tax.title": "تصنيف IAAI",
    "toc.chapter": "الفصل",
    "toc.chapter.suffix": "",
    "toc.epilogue": "الخاتمة",
    "toc.prologue": "المقدمة",
    "toc.title": "جدول المحتويات",
    "toc.volume1": "المجلد الأول: المنظور — التاريخ والسياق",
    "toc.volume2": "المجلد الثاني: الدليل — الإطار الاستراتيجي",
    "toc.volume3": "المجلد الثالث: اللعبة — المحاكاة والممارسة",
    "ui.available": "صدرت",
    "ui.back": "رجوع",
    "ui.coming.soon": "قريباً",
    "ui.download": "تنزيل",
    "ui.error": "حدث خطأ أثناء تحميل المحتوى. يرجى المحاولة مرة أخرى.",
    "ui.loading": "جار التحميل...",
    "ui.next": "التالي",
    "ui.prev": "السابق",
    "ui.read.more": "اقرأ المزيد",
    "ui.view": "عرض",
    "v1.index.about_title": "عن هذا المجلد",
    "v1.index.relays_title": "السباقات الاثني عشر",
    "v1.index.title": "المجلد الأول: المنظور",
    "v1.r01.active_webs": "شبكة نشطة",
    "v1.r01.counterparts_title": "الطرف المقابل: النار",
    "v1.r01.four_pillars": "الأعمدة الأربعة الرئيسية",
    "v1.r01.historical_significance": "الأهمية التاريخية",
    "v1.r01.next_relay": "التتابع التالي →",
    "v1.r01.previous_relay": "← التسليم السابق",
    "v1.r01.subtitle": "الشرارة الأولى — بداية السيطرة على الطاقة",
    "v1.r01.title": "تتابع 1: النار",
    "v1.r02.active_webs": "الشبكة النشطة",
    "v1.r02.counterparts_title": "الطرف المقابل: شجرة",
    "v1.r02.four_pillars": "الأعمدة الأربعة الرئيسية",
    "v1.r02.historical_significance": "الأهمية التاريخية",
    "v1.r02.next_relay": "التسليم التالي →",
    "v1.r02.previous_relay": "← التتابع السابق",
    "v1.r02.subtitle": "الهياكل الحية — الطبيعة كالهندسة",
    "v1.r02.title": "التتابع 2: الشجرة",
    "v1.r03.active_webs": "الشبكة النشطة",
    "v1.r03.counterparts_title": "الجهة المقابلة: النهر",
    "v1.r03.four_pillars": "الأركان الأربعة الرئيسية",
    "v1.r03.historical_significance": "الأهمية التاريخية",
    "v1.r03.next_relay": "التسليم التالي →",
    "v1.r03.previous_relay": "← السابق التتابع",
    "v1.r03.subtitle": "حضارة الموارد المائية — البنية التحتية للسائل",
    "v1.r03.title": "تتابع 3: الأنهار",
    "v1.r04.active_webs": "الشبكة النشطة",
    "v1.r04.counterparts_title": "الطرف المقابل: فرس",
    "v1.r04.four_pillars": "الأركان الأربعة الأساسية",
    "v1.r04.historical_significance": "الأهمية التاريخية",
    "v1.r04.next_relay": "التتابع التالي →",
    "v1.r04.previous_relay": "← السابق التتابع",
    "v1.r04.subtitle": "ثورة التنقل — السرعة والإمبراطورية",
    "v1.r04.title": "تتابع 4: حصان",
    "v1.r05.active_webs": "الشبكة النشطة",
    "v1.r05.counterparts_title": "الجهة المقابلة: الطريق",
    "v1.r05.four_pillars": "الأعمدة الأربعة الرئيسية",
    "v1.r05.historical_significance": "الأهمية التاريخية",
    "v1.r05.next_relay": "التتابع التالي →",
    "v1.r05.previous_relay": "← العَصْر السابق",
    "v1.r05.subtitle": "الشبكات المتصلة — شرايين الإمبراطورية",
    "v1.r05.title": "تتابع 5: الطرق",
    "v1.r06.active_webs": "الشبكة النشطة",
    "v1.r06.counterparts_title": "الطرف المقابل: السفن",
    "v1.r06.four_pillars": "الأركان الأربعة الرئيسية",
    "v1.r06.historical_significance": "الأهمية التاريخية",
    "v1.r06.next_relay": "التتابع التالي →",
    "v1.r06.previous_relay": "← السباق السابق",
    "v1.r06.subtitle": "الطريق السريع البحري — شبكة التجارة العالمية",
    "v1.r06.title": "التتابع 6: السفن",
    "v1.r07.active_webs": "الشبكة النشطة",
    "v1.r07.counterparts_title": "الطرف المقابل: السكك الحديدية",
    "v1.r07.four_pillars": "الأركان الأربعة الرئيسية",
    "v1.r07.historical_significance": "الأهمية التاريخية",
    "v1.r07.next_relay": "التتابع التالي →",
    "v1.r07.previous_relay": "← التتابع السابق",
    "v1.r07.subtitle": "العمود الفقري الفولاذي — الاتصال الصناعي",
    "v1.r07.title": "التتابع 7: السكك الحديدية",
    "v1.r08.active_webs": "الشبكة النشطة",
    "v1.r08.counterparts_title": "الطرف المقابل: النول",
    "v1.r08.four_pillars": "الأركان الأربعة الأساسية",
    "v1.r08.historical_significance": "الأهمية التاريخية",
    "v1.r08.next_relay": "التسليم التالي →",
    "v1.r08.previous_relay": "← السباق السابق",
    "v1.r08.subtitle": "شبكة منسوجة — البنية التحتية للمعلومات",
    "v1.r08.title": "تتابع 8: نول النسيج",
    "v1.r09.active_webs": "الشبكة النشطة",
    "v1.r09.counterparts_title": "الطرف المقابل: المحرك",
    "v1.r09.four_pillars": "الأركان الأربعة الكبرى",
    "v1.r09.historical_significance": "الأهمية التاريخية",
    "v1.r09.next_relay": "التتابع التالي →",
    "v1.r09.previous_relay": "← التتابع السابق",
    "v1.r09.subtitle": "ثورة الطاقة — العالم الميكانيكي",
    "v1.r09.title": "التتابع 9: المحرك",
    "v1.r10.active_webs": "الشبكة النشطة",
    "v1.r10.counterparts_title": "الطرف المقابل: ثلاثية AAA",
    "v1.r10.four_pillars": "الأركان الأربعة الرئيسية",
    "v1.r10.historical_significance": "الأهمية التاريخية",
    "v1.r10.next_relay": "التتابع التالي →",
    "v1.r10.previous_relay": "← السابق في التتابع",
    "v1.r10.subtitle": "الطيران، الذرة، الأتمتة — الثالوث الحديث",
    "v1.r10.title": "تتابع 10: ثلاثي AAA",
    "v1.r11.active_webs": "الشبكة النشطة",
    "v1.r11.counterparts_title": "الجهة المقابلة: العقدة البشرية",
    "v1.r11.four_pillars": "الأركان الأربعة الرئيسية",
    "v1.r11.historical_significance": "الأهمية التاريخية",
    "v1.r11.next_relay": "التتابع التالي →",
    "v1.r11.previous_relay": "← السابقة التتابع",
    "v1.r11.subtitle": "الإنسان المُتَّصل بالشبكة — الاتصال الرقمي",
    "v1.r11.title": "تتابع 11: عقدة الإنسان",
    "v1.r12.active_webs": "الشبكة النشطة",
    "v1.r12.counterparts_title": "الطرف المقابل: الوعي",
    "v1.r12.four_pillars": "الأعمدة الأربعة الرئيسية",
    "v1.r12.historical_significance": "الأهمية التاريخية",
    "v1.r12.next_relay": "التتابع التالي →",
    "v1.r12.previous_relay": "← السابق تتابع",
    "v1.r12.subtitle": "حلقة توروس — الشكل النهائي للبنية التحتية",
    "v1.r12.title": "تتابع 12: الوعي",
    "v2.index.about_text": "المجلد الثاني: يطبق الدليل إطار الأركان الأربعة (الملاحظة ← التعليم ← التطبيق ← الأطروحة) على كل من السباقات الحضارية الاثني عشر. يقدم هذا المجلد إرشادات عملية لفهم كيفية عمل أنظمة البنية التحتية، وكيفية تحليلها، وكيفية تطبيقها على التحديات المعاصرة.",
    "v2.index.about_title": "عن هذا المجلد",
    "v2.index.app": "التطبيق",
    "v2.index.app_text": "كيف يمكننا تطبيق هذه الدروس؟ ما هي الأطر والأدوات العملية التي تنشأ من هذا السباق؟",
    "v2.index.edu": "التعليم",
    "v2.index.edu_text": "ماذا يمكننا أن نتعلم من هذا السباق؟ ما هي المبادئ والدروس التي يعلمنا إياها عن البنية التحتية؟",
    "v2.index.framework_title": "إطار الأركان الأربعة",
    "v2.index.obs": "الملاحظة",
    "v2.index.obs_text": "ماذا نلاحظ في هذا السباق؟ ما هي خصائصه ومكوناته وأنماطه؟",
    "v2.index.relays_caption": "اثنا عشر سباقًا حضاريًا — من النار إلى الوعي",
    "v2.index.subtitle": "الدليل — إطار عملي وتحليل موسع",
    "v2.index.thesis": "الأطروحة",
    "v2.index.thesis_text": "ما هي الأطروحة الشاملة؟ ما هي البصيرة الأساسية التي يكشفها هذا السباق؟",
    "v2.index.title": "المجلد الثاني: الدليل",
    "v2.r01.active_webs": "شبكة نشطة",
    "v2.r01.counterparts_title": "الطرف المقابل: النار",
    "v2.r01.four_pillars": "الأركان الأربعة الرئيسية",
    "v2.r01.historical_significance": "الأهمية التاريخية",
    "v2.r01.next_relay": "التتابع التالي →",
    "v2.r01.previous_relay": "← السباق التتابعي السابق",
    "v2.r01.subtitle": "الشرارة الأصلية — بداية السيطرة على الطاقة",
    "v2.r01.title": "تناوب 1: نار",
    "v2.r02.active_webs": "الشبكة النشطة",
    "v2.r02.counterparts_title": "الطرف المقابل: الشجرة",
    "v2.r02.four_pillars": "الأركان الأربعة الأساسية",
    "v2.r02.historical_significance": "الأهمية التاريخية",
    "v2.r02.next_relay": "التتابع التالي →",
    "v2.r02.previous_relay": "← التتابع السابق",
    "v2.r02.subtitle": "البناء الحي — الطبيعة كالهندسة",
    "v2.r02.title": "التتابع 2: الشجرة",
    "v2.r03.active_webs": "الشبكة النشطة",
    "v2.r03.counterparts_title": "الجهة المقابلة: النهر",
    "v2.r03.four_pillars": "الأركان الأربعة الرئيسية",
    "v2.r03.historical_significance": "الأهمية التاريخية",
    "v2.r03.next_relay": "التسليم التالي →",
    "v2.r03.previous_relay": "← التتابع السابق",
    "v2.r03.subtitle": "حضارة الموارد المائية — البنية التحتية السائلة",
    "v2.r03.title": "التتابع 3: الأنهار",
    "v2.r04.active_webs": "الشبكة النشطة",
    "v2.r04.counterparts_title": "الطرف المقابل: الحصان",
    "v2.r04.four_pillars": "الأركان الأربعة الكبرى",
    "v2.r04.historical_significance": "الأهمية التاريخية",
    "v2.r04.next_relay": "التتابع التالي →",
    "v2.r04.previous_relay": "← السباق التتابعي السابق",
    "v2.r04.subtitle": "ثورة التنقل — السرعة والإمبراطورية",
    "v2.r04.title": "تتابع 4: حصان",
    "v2.r05.active_webs": "الشبكة النشطة",
    "v2.r05.counterparts_title": "الطرف المقابل: الطرق",
    "v2.r05.four_pillars": "الأركان الأربعة الرئيسية",
    "v2.r05.historical_significance": "الأهمية التاريخية",
    "v2.r05.next_relay": "التتابع التالي →",
    "v2.r05.previous_relay": "← السابق التتابع",
    "v2.r05.subtitle": "الشبكات المتصلة — شرايين الإمبراطورية",
    "v2.r05.title": "التتابع 5: الطرق",
    "v2.r06.active_webs": "الشبكة النشطة",
    "v2.r06.counterparts_title": "الطرف المقابل: السفن",
    "v2.r06.four_pillars": "الأركان الأربعة الكبرى",
    "v2.r06.historical_significance": "الأهمية التاريخية",
    "v2.r06.next_relay": "التتابع التالي →",
    "v2.r06.previous_relay": "← الإرسال السابق",
    "v2.r06.subtitle": "الطريق السريع البحري — شبكة التجارة العالمية",
    "v2.r06.title": "التتابع 6: السفن",
    "v2.r07.active_webs": "الشبكة النشطة",
    "v2.r07.counterparts_title": "الطرف المعني: السكك الحديدية",
    "v2.r07.four_pillars": "الأركان الأربعة الكبرى",
    "v2.r07.historical_significance": "الأهمية التاريخية",
    "v2.r07.next_relay": "التتابع التالي →",
    "v2.r07.previous_relay": "← التتابع السابق",
    "v2.r07.subtitle": "العمود الفقري الفولاذي — الاتصال الصناعي",
    "v2.r07.title": "التتابع 7: السكك الحديدية",
    "v2.r08.active_webs": "الشبكة النشطة",
    "v2.r08.counterparts_title": "الطرف المقابل: النول",
    "v2.r08.four_pillars": "الأعمدة الأربعة الرئيسية",
    "v2.r08.historical_significance": "الأهمية التاريخية",
    "v2.r08.next_relay": "التتابع التالي →",
    "v2.r08.previous_relay": "← العَدْوَة السابقة",
    "v2.r08.subtitle": "الشبكة المنسوجة — البنية التحتية للمعلومات",
    "v2.r08.title": "تتابع 8: نول النسيج",
    "v2.r09.active_webs": "الشبكة النشطة",
    "v2.r09.counterparts_title": "الجهة المقابلة: المحرك",
    "v2.r09.four_pillars": "الأركان الأربعة الرئيسية",
    "v2.r09.historical_significance": "الأهمية التاريخية",
    "v2.r09.next_relay": "التتابع التالي →",
    "v2.r09.previous_relay": "← السابق في التسلسل",
    "v2.r09.subtitle": "ثورة الطاقة — العالم الميكانيكي",
    "v2.r09.title": "تتابع 9: المحرك",
    "v2.r10.active_webs": "الشبكة النشطة",
    "v2.r10.counterparts_title": "الطرف المقابل: ثلاثي AAA",
    "v2.r10.four_pillars": "الأركان الأربعة الرئيسية",
    "v2.r10.historical_significance": "الأهمية التاريخية",
    "v2.r10.next_relay": "التتابع التالي →",
    "v2.r10.previous_relay": "← التسليم السابق",
    "v2.r10.subtitle": "الطيران، الذرة، الأتمتة — الثالوث الحديث",
    "v2.r10.title": "تتابع 10: ثلاثي AAA",
    "v2.r11.active_webs": "الشبكة النشطة",
    "v2.r11.counterparts_title": "الطرف المقابل: عقدة بشرية",
    "v2.r11.four_pillars": "الأركان الأربعة الرئيسية",
    "v2.r11.historical_significance": "الأهمية التاريخية",
    "v2.r11.next_relay": "السباق التالي →",
    "v2.r11.previous_relay": "← السباق السابق",
    "v2.r11.subtitle": "البشر المتصلون بالشبكة — الاتصال الرقمي",
    "v2.r11.title": "السباق 11: العقد البشرية",
    "v2.r12.active_webs": "الشبكات النشطة",
    "v2.r12.counterparts_title": "النظراء: الوعي",
    "v2.r12.four_pillars": "الأركان الأربعة",
    "v2.r12.historical_significance": "الأهمية التاريخية",
    "v2.r12.next_relay": "السباق التالي →",
    "v2.r12.previous_relay": "← السباق السابق",
    "v2.r12.subtitle": "الطارة — الشكل النهائي للبنية التحتية",
    "v2.r12.title": "السباق 12: الوعي",
    "v3.index.experience_title": "تجربة السباق",
    "v3.index.title": "المجلد الثالث: اللعبة",
    "vol1.index.desc": "استكشف 12,000 عام من تطور البنية التحتية من خلال 12 سباقًا حضاريًا. يمثل كل سباق قفزة أساسية في القدرة البشرية.",
    "vol1.index.subtitle": "التاريخ والسياق — القصة",
    "vol1.index.title": "المجلد الأول: المنظور",
    "vol2.index.desc": "إطار عملي وتحليل مقارن ونماذج استراتيجية لكل سباق. مقارنة متعمقة بين مناهج الغرب والشرق والفارس.",
    "vol2.index.subtitle": "الإطار الاستراتيجي — التوسع",
    "vol2.index.title": "المجلد الثاني: الدليل",
    "vol3.index.desc": "منصة التعلم الموجهة بمحرك الواقع. طبق المفاهيم في بيئة محاكاة ديناميكية.",
    "vol3.index.subtitle": "المحاكاة والممارسة — التطبيق",
    "vol3.index.title": "المجلد الثالث: اللعبة",
    "home.charter.charter.h": "الميثاق",
    "home.charter.charter.p": "نؤمن بأن البنية التحتية هي نظام تشغيل الحضارة. مثل النهر الذي ينحت الأرض ببطء وإصرار لإحداث تغيير كوكبي، نلتزم بالمعرفة المفتوحة والمساهمة الموثقة والاحترام الثقافي والإيمان بأن فهم كيف بنينا العالم هو الخطوة الأولى لبنائه بشكل أفضل.",
    "home.charter.mission.h": "المهمة",
    "home.charter.mission.p": "تقديم أول منصة تعليمية مفتوحة ومتعددة اللغات وموجهة بالذكاء الاصطناعي للبنية التحتية في العالم — للوصول إلى مليار متعلم عبر 8 لغات، تم التحقق منها بواسطة مساهمين بشريين من كل قارة.",
    "home.charter.title": "المهمة والرؤية والميثاق",
    "home.charter.vision.h": "الرؤية",
    "home.charter.vision.p": "عالم يفهم فيه كل شخص البنية التحتية التي تدعم الحضارة — ويمتلك المعرفة لبناء ما يأتي بعد ذلك.",
    "home.pop.answer": "IAAI موجود لتغيير هذا الرقم.",
    "home.pop.question": "شخص يتشاركون البنية التحتية لهذا الكوكب. كم منهم يفهمها؟",
    "home.pop.source": "المصدر: تقديرات الأمم المتحدة لسكان العالم (إسقاط في الوقت الفعلي)",
    "home.ppp.cta.sub": "وصول مجاني للنسخة التجريبية — اختبر وترجم وتحقق واكسب مكانك في جدار المؤسسين. انضم إلى الأوديسة.",
    "home.ppp.cta.title": "كن رائداً",
    "home.ppp.partners.h": "الشركاء",
    "home.ppp.partners.p": "الجامعات ومنصات التكنولوجيا وشركات البنية التحتية. MIT OCW، أكاديمية خان، Meta/VR، Manus/AI، AECOM، Arup، Bechtel. التكنولوجيا والتحقق من المحتوى والوصول إلى السوق.",
    "home.ppp.partners.status": "الحالة: مفتوح للتحدي — يرشحهم اللاعبون",
    "home.ppp.patrons.h": "الرعاة",
    "home.ppp.patrons.p": "مؤسسات تتوافق مهمتها مع تعليم البنية التحتية الشامل. اليونسكو، ناشيونال جيوغرافيك، ناسا، الجمعية الملكية، ديسكفري، سميثسونيان، NOAA، البنك الدولي، بنك التنمية الآسيوي، الأكاديمية الصينية للعلوم.",
    "home.ppp.patrons.status": "الحالة: مفتوح للتحدي — يرشحهم اللاعبون",
    "home.ppp.players.h": "اللاعبون",
    "home.ppp.players.p": "رواد وسفراء وعلماء ومستشارون من كل بلد. أشخاص حقيقيون يختبرون ويترجمون ويتحققون ويساهمون وينشرون الكلمة. قوة الديمقراطية.",
    "home.ppp.players.status": "الحالة: توظيف الرواد — وصول مجاني للنسخة التجريبية",
    "home.ppp.reach.active": "نشط",
    "home.ppp.reach.active2": "نشط",
    "home.ppp.reach.active3": "نشط",
    "home.ppp.reach.active4": "نشط",
    "home.ppp.reach.active5": "نشط",
    "home.ppp.reach.active6": "نشط",
    "home.ppp.reach.active7": "نشط",
    "home.ppp.reach.active8": "نشط",
    "home.ppp.reach.ar": "العربية",
    "home.ppp.reach.cn": "الصينية",
    "home.ppp.reach.coverage": "8 لغات تغطي ~85% من سوق الألعاب العالمي، ~80% من إنفاق تكنولوجيا التعليم، وأهم ممرات الاستثمار في البنية التحتية.",
    "home.ppp.reach.en": "الإنجليزية",
    "home.ppp.reach.es": "الإسبانية",
    "home.ppp.reach.h": "الانتشار اللغوي العالمي",
    "home.ppp.reach.hi": "الهندية",
    "home.ppp.reach.ja": "اليابانية",
    "home.ppp.reach.ko": "الكورية",
    "home.ppp.reach.vi": "الفيتنامية",
    "home.ppp.subtitle": "من السعرات الحرارية إلى الوعي — دعوة للعمل على المستوى الفردي لا يمكن إيقافها أو التحكم فيها. إنها تستمر في التعلم فحسب.",
    "home.ppp.title": "الرعاة والشركاء واللاعبون",
    "nav.founders": "جدار المؤسسين",
    // ============================================
    // MISSING KEYS - ADDED BY TRANSLATION GENERATOR
    // ============================================
    "home.guide.btn": "اقرأ الدليل",
    "home.guide.title": "المجلد 2: الدليل",
    "masters.subtitle": "مرشدون روحيون تاريخيون يسيرون جنبًا إلى جنب مع كل مستوى — لا يُحسبون في التسلسل الهرمي 6+1، هؤلاء الرفاق الفكريون يمتدون عبر جميع الأنماط وجميع التتابعات و12,000 عام. هم الأصوات في اللعبة والاقتباسات على الجدران والحكمة التي تربط النار بالطوق.",
    "masters.title": "الأساتذة",
    "nav.glossary": "المصطلحات",
    "nav.masters": "الأساتذة",
    "nav.olympiad": "الأولمبياد",
    "nav.starthere": "ابدأ هنا",
    "precis.relay.relay_10_orbit": "التتابع 11: المدار",
    "precis.relay.relay_11_human_nodes": "التتابع 12: العقد البشرية",
    "precis.relay.relay_1_tree": "التتابع 2: الشجرة",
    "precis.relay.relay_2_river": "التتابع 3: النهر",
    "precis.relay.relay_3_horse": "التتابع 4: الحصان",
    "precis.relay.relay_4_roads": "التتابع 5: الطرق",
    "precis.relay.relay_5_ships": "التتابع 6: السفن",
    "precis.relay.relay_6_loom": "التتابع 7: النول",
    "precis.relay.relay_8_engine": "التتابع 9: المحرك",
    "precis.relay.relay_9_aaa": "التتابع 10: ثالوث AAA",
    "tax.cta": "اعثر على مكانك في الشجرة",
    "tax.cta.sub": "كل نوع يبدأ بكائن واحد. كل حركة تبدأ برائد واحد.",
    "tax.footer.cc": "CC BY-NC-SA 4.0",
    "tax.parallel.institutions.desc": "Organisations that can be challenged, engaged, or partnered with. Universities, UN bodies, professional societies, government agencies, NGOs, and corporations. They sit outside the contributor hierarchy but are the targets of the intelligence network and the Challenge Board.",
    "tax.parallel.institutions.title": "&#x1F3DB; Institutions &mdash; The Challenge Map",
    "tax.parallel.institutions.who": "UNESCO &bull; World Bank &bull; ASCE &bull; ICE &bull; MIT &bull; Khan Academy &bull; Meta &bull; National Geographic",
    "tax.parallel.outriders.desc": "Historical and philosophical figures who ride alongside every tier as intellectual companions. Not counted in the 6+1 &mdash; they exist across all levels, all modes, all time periods. They are the voices in the game, the quotes on the walls, the wisdom that connects 12,000 years of infrastructure.",
    "tax.parallel.outriders.title": "&#x1F3C7; Outriders &mdash; Spirit Guides",
    "tax.parallel.outriders.who": "Laozi &bull; Sun Tzu &bull; Confucius &bull; Vitruvius &bull; Leonardo da Vinci &bull; Isambard Kingdom Brunel &bull; Nikola Tesla &bull; Ada Lovelace",
    "tax.parallel.title": "مسارات موازية (خارج التسلسل الهرمي)",
    "tax.plus1.desc": "في علم الأحياء، النوع هو التصنيف الأكثر تحديدًا — الكائن الحي الفردي. في IAAI، +1 هو مليار متعلم",
    "tax.plus1.subtitle": "12.1% من البشرية — نقطة التحول لمحو الأمية في البنية التحتية",
    "tax.plus1.target": "الهدف: 1,000,000,000",
    "tax.plus1.title": "+1 — النوع",
    "tax.quote": "\"كما تتشارك جميع أشكال الحياة سلفًا مشتركًا، تتشارك جميع البنى التحتية هدفًا مشتركًا — خدمة الحضارة.\"",
    "tax.rank.class": "صنف",
    "tax.rank.domain": "نطاق",
    "tax.rank.family": "عائلة",
    "tax.rank.genus": "جنس",
    "tax.rank.kingdom": "مملكة",
    "tax.rank.order": "رتبة",
    "tax.rank.phylum": "شعبة",
    "tax.table.biology": "علم الأحياء",
    "tax.table.count": "العدد",
    "tax.table.iaai": "IAAI",
    "tax.table.suntzu": "الاستخبارات (INT)",
    "tax.tier1.analogy": "Biology: Domain (Eukarya) &bull; Military: Commander-in-Chief &bull; Architecture: Master Builder",
    "tax.tier1.desc": "The singular origin point. Conceived the 12-relay framework, wrote the trilogy, designed the game, and built the platform. Like Domain in biology &mdash; the broadest, most fundamental classification from which everything else branches.",
    "tax.tier1.name": "المؤسس",
    "tax.tier1.title": "المهندس المعماري",
    "tax.tier1.who": "Ir. Nigel T. Dearden &mdash; CEng MICE MHKIE",
    "tax.tier2.analogy": "Biology: Kingdom (Animalia) &bull; Military: General Staff &bull; Sun Tzu: The Five Essentials",
    "tax.tier2.desc": "The inner circle. Industry leaders, capital strategists, and institutional connectors who shape direction, open doors, and bridge the gap between vision and execution. By invitation or nomination only.",
    "tax.tier2.name": "المستشارون",
    "tax.tier2.title": "المجلس الاستراتيجي",
    "tax.tier2.who": "Michael Wu (COO) &bull; Henry Leong (CFO) &bull; Frank Sheu (CTO) &bull; Stephen Markscheid (Strategic Advisor)",
    "tax.tier3.analogy": "Biology: Phylum (Chordata) &bull; Military: Intelligence Corps &bull; Academia: Peer Review Board",
    "tax.tier3.desc": "Engineers, professors, and researchers who verify technical accuracy, map content to university curricula, and provide the academic credibility that transforms a game into an educational standard. The peer-review layer.",
    "tax.tier3.name": "العلماء",
    "tax.tier3.title": "المحققون الأكاديميون",
    "tax.tier3.who": "Target: Engineering faculties, infrastructure researchers, curriculum designers",
    "tax.tier4.analogy": "Biology: Class (Mammalia) &bull; Military: Field Officers &bull; Diplomacy: Cultural Attach&eacute;s",
    "tax.tier4.desc": "Native-fluency contributors who review and correct AI translations against real usage. 10 per language block across 8 languages. They ensure infrastructure literacy speaks authentically in every tongue. Credited contributors with their names on the work.",
    "tax.tier4.name": "السفراء",
    "tax.tier4.title": "قادة اللغات",
    "tax.tier4.who": "Target: 10 per block &times; 8 blocks = 80 Ambassadors worldwide",
    "tax.tier5.analogy": "Biology: Order (Primates) &bull; Military: HUMINT (Human Intelligence) &bull; Scouts &amp; Reconnaissance",
    "tax.tier5.desc": "The first wave. 2&ndash;3 per language block who play the game, report bugs, validate content, and provide the ground-truth feedback that shapes the platform before public release. The HUMINT assets of the intelligence network — human intelligence on the ground.",
    "tax.tier5.name": "الرواد",
    "tax.tier5.title": "مختبرو بيتا والكشافة",
    "tax.tier5.who": "Currently recruiting &mdash; 3 active across EN and CN blocks",
    "tax.tier6.analogy": "Biology: Family (Hominidae) &bull; Military: The Rank and File &bull; Gaming: The Player Base",
    "tax.tier6.desc": "Everyone who plays The Reality Engine. From casual explorers to completionists who master all 12 relays across all 4 modes. They generate the data, the engagement, and the democratic nominations that power the Challenge Board. The lifeblood of the platform.",
    "tax.tier6.name": "اللاعبون",
    "tax.tier6.title": "مجتمع اللعبة",
    "tax.tier6.who": "Target: 1M players by Year 2 &bull; Currently: 21 (beta)",
    "tax.tier7.analogy": "Biology: Genus (Homo) &bull; Military: ELINT (Electronic Intelligence) &bull; Logistics &amp; Supply",
    "tax.tier7.desc": "Those who fund the mission &mdash; from individual Kickstarter backers to institutional patrons (UNESCO, National Geographic, universities). They don't play or translate; they enable. Challenged by Players, engaged by Advisors. The ELINT channel of the intelligence network — converting institutional signals into engagement.",
    "tax.tier7.name": "الداعمون",
    "tax.tier7.title": "الداعمون الماليون والمؤسسيون",
    "tax.tier7.who": "Target: $500K seed &bull; Challenged: UNESCO, NatGeo, NASA, Royal Society, MIT OCW, Khan Academy",
    "v1.r01.continuity": "الاستمرارية",
    "v1.r01.energy_web": "شبكة الطاقة",
    "v1.r01.infrastructure": "البنية التحتية",
    "v1.r01.knowledge_web": "شبكة المعرفة",
    "v1.r01.threats": "التهديدات",
    "v1.r01.unification": "التوحيد",
    "v1.r02.continuity": "الاستمرارية",
    "v1.r02.energy_web": "شبكة الطاقة",
    "v1.r02.infrastructure": "البنية التحتية",
    "v1.r02.knowledge_web": "شبكة المعرفة",
    "v1.r02.threats": "التهديدات",
    "v1.r02.unification": "التوحيد",
    "v1.r03.continuity": "الاستمرارية",
    "v1.r03.energy_web": "شبكة الطاقة",
    "v1.r03.infrastructure": "البنية التحتية",
    "v1.r03.knowledge_web": "شبكة المعرفة",
    "v1.r03.threats": "التهديدات",
    "v1.r03.unification": "التوحيد",
    "v1.r04.continuity": "الاستمرارية",
    "v1.r04.energy_web": "شبكة الطاقة",
    "v1.r04.infrastructure": "البنية التحتية",
    "v1.r04.threats": "التهديدات",
    "v1.r04.unification": "التوحيد",
    "v1.r05.consciousness_web": "شبكة الوعي",
    "v1.r05.continuity": "الاستمرارية",
    "v1.r05.infrastructure": "البنية التحتية",
    "v1.r05.knowledge_web": "شبكة المعرفة",
    "v1.r05.threats": "التهديدات",
    "v1.r05.unification": "التوحيد",
    "v1.r06.consciousness_web": "شبكة الوعي",
    "v1.r06.continuity": "الاستمرارية",
    "v1.r06.infrastructure": "البنية التحتية",
    "v1.r06.knowledge_web": "شبكة المعرفة",
    "v1.r06.threats": "التهديدات",
    "v1.r06.unification": "التوحيد",
    "v1.r07.continuity": "الاستمرارية",
    "v1.r07.energy_web": "شبكة الطاقة",
    "v1.r07.infrastructure": "البنية التحتية",
    "v1.r07.knowledge_web": "شبكة المعرفة",
    "v1.r07.threats": "التهديدات",
    "v1.r07.unification": "التوحيد",
    "v1.r08.consciousness_web": "شبكة الوعي",
    "v1.r08.continuity": "الاستمرارية",
    "v1.r08.energy_web": "شبكة الطاقة",
    "v1.r08.infrastructure": "البنية التحتية",
    "v1.r08.knowledge_web": "شبكة المعرفة",
    "v1.r08.threats": "التهديدات",
    "v1.r08.unification": "التوحيد",
    "v1.r09.continuity": "الاستمرارية",
    "v1.r09.energy_web": "شبكة الطاقة",
    "v1.r09.infrastructure": "البنية التحتية",
    "v1.r09.knowledge_web": "شبكة المعرفة",
    "v1.r09.threats": "التهديدات",
    "v1.r09.unification": "التوحيد",
    "v1.r10.consciousness_web": "شبكة الوعي",
    "v1.r10.continuity": "الاستمرارية",
    "v1.r10.energy_web": "شبكة الطاقة",
    "v1.r10.infrastructure": "البنية التحتية",
    "v1.r10.knowledge_web": "شبكة المعرفة",
    "v1.r10.threats": "التهديدات",
    "v1.r10.unification": "التوحيد",
    "v1.r11.consciousness_web": "شبكة الوعي",
    "v1.r11.continuity": "الاستمرارية",
    "v1.r11.infrastructure": "البنية التحتية",
    "v1.r11.knowledge_web": "شبكة المعرفة",
    "v1.r11.threats": "التهديدات",
    "v1.r11.unification": "التوحيد",
    "v1.r12.consciousness_web": "شبكة الوعي",
    "v1.r12.continuity": "الاستمرارية",
    "v1.r12.infrastructure": "البنية التحتية",
    "v1.r12.knowledge_web": "شبكة المعرفة",
    "v1.r12.threats": "التهديدات",
    "v1.r12.unification": "التوحيد",
    "oly.title": "أولمبياد البنية التحتية",
    "oly.stat.blocks": "كتل لغوية",
    "oly.stat.categories": "فئات المنافسة",
    "oly.stat.universities": "جامعات حول العالم",
    "oly.stat.xpcap": "سقف XP (نسّاج ماهر)",
    "oly.stat.people": "الأشخاص المُستهدفون",
    "oly.stat.gap": "فجوة البنية التحتية",
    "oly.flywheel.title": "دولاب الموازنة — كيف ينمو الأولمبياد ذاتياً",
    "oly.flywheel.players": "اللاعبون يتنافسون",
    "oly.flywheel.professionals": "المحترفون يصادقون",
    "oly.flywheel.patrons": "الرعاة يدعمون",
    "oly.flywheel.platform": "المنصة تتوسع",
    "oly.medal.title": "جدول الميداليات المباشر — الأمم تتنافس على إدارة الحضارة",
    "oly.th.nation": "الدولة",
    "oly.th.blocks": "الكتلة",
    "oly.th.pop": "السكان (م)",
    "oly.th.gamers": "اللاعبون (م)",
    "oly.th.story": "قصة البنية التحتية",
    "oly.th.total": "المجموع",
    "oly.th.status": "الحالة",
    "oly.rogue.title": "الفرق المارقة — مجمع المواهب غير المنتسبة",
    "oly.categories.title": "فئات المنافسة — ستة أعمدة للبنية التحتية الحضارية",
    "oly.pipeline.unis": "جامعات حول العالم",
    "oly.pipeline.students": "طلاب الهندسة",
    "oly.pipeline.firms": "أبرز شركات الهندسة المدنية",
    "oly.pipeline.govts": "الحكومات الوطنية",
    "oly.sponsor.title": "مستويات الرعاية — ادعم فريقاً وطنياً",
    "oly.sponsor.gold": "الراعي الذهبي",
    "oly.sponsor.silver": "الراعي الفضي",
    "oly.sponsor.bronze": "الراعي البرونزي",
    "oly.sponsor.patron": "الراعي الشرفي",
    "oly.form.register.title": "سجّل فريقك الجامعي",
    "oly.form.sponsor.title": "استفسار الرعاية",
    "nav.behind": "وراء الأطروحة",

    // SDG Alignment Section
    "sdg.title": "أهداف التنمية المستدامة — المواءمة",
    "sdg.subtitle": "كيف يتوافق منهج IAAI المكون من 12 تتابعاً مع أهداف التنمية المستدامة للأمم المتحدة",
    "sdg.iconCaption": "يتناول محتوى IAAI مباشرة 11 من أصل 17 هدفاً من أهداف التنمية المستدامة. كل أيقونة ترتبط بصفحة الهدف الرسمية للأمم المتحدة.",
    "sdg.col.relay": "تتابع IAAI",
    "sdg.col.sdgGoals": "أهداف التنمية المستدامة",
    "sdg.col.alignment": "مبررات المواءمة",
    "sdg.col.5p": "فئة 5P",
    "sdg.r1.rationale": "شبكات الطرق هي الجهاز الدوري للتنمية الاقتصادية. بدون طرق، لا وصول للأسواق ولا خدمات طوارئ.",
    "sdg.r2.rationale": "السكك الحديدية هي العمود الفقري للنقل الجماعي والشحن. انبعاثات أقل لكل طن-كم من الطرق.",
    "sdg.r3.rationale": "الموانئ تربط الدول بالتجارة العالمية. 90% من البضائع العالمية تنتقل بحراً.",
    "sdg.r4.rationale": "البنية التحتية للطيران تمكّن الاتصال العالمي والتجارة والسياحة والاستجابة للطوارئ.",
    "sdg.r5.rationale": "المياه النظيفة هي البنية التحتية الأكثر أساسية. 2.2 مليار شخص لا يزالون يفتقرون لمياه شرب آمنة.",
    "sdg.r6.rationale": "الصرف الصحي يمنع الأمراض ويحمي مصادر المياه ويحافظ على كرامة الإنسان.",
    "sdg.r7.rationale": "البنية التحتية للطاقة تحدد ما إذا كانت الدول تتصنع بشكل نظيف أم تكرر الاعتماد على الوقود الأحفوري.",
    "sdg.r8.rationale": "الاتصالات تربط الناس بالتعليم والأسواق والحوكمة. الفجوة الرقمية هي فجوة في البنية التحتية.",
    "sdg.r9.rationale": "إدارة النفايات هي مرآة الاستهلاك. الاقتصادات الدائرية تتطلب بنية تحتية للجمع والفرز وإعادة التدوير.",
    "sdg.r10.rationale": "البنية التحتية الصحية — المستشفيات والعيادات وسلاسل الإمداد — تحدد ما إذا كانت السكان ينجون من الأوبئة.",
    "sdg.r11.rationale": "البنية التحتية التعليمية — المدارس والجامعات والمكتبات — هي الآلية التي تنقل بها الحضارات المعرفة عبر الأجيال.",
    "sdg.r12.rationale": "البنية التحتية الرقمية — مراكز البيانات والألياف والسحابة — هي مكافئ القرن الحادي والعشرين للطرق والموانئ.",
    "sdg.5pTitle": "الـ 5P — الناس، الكوكب، الازدهار، السلام، الشراكة",
    "sdg.5pText": "تؤطر الأمم المتحدة أهداف التنمية المستدامة الـ17 من خلال خمسة ركائز تُعرف بالـ 5P. البنية التحتية هي الآلية التي تحقق بها الحضارات جميع الركائز الخمس.",
    "sdg.visitUN": "زيارة الموقع الرسمي لأهداف التنمية المستدامة ←",
    "sdg.disclaimerTitle": "إخلاء مسؤولية:",
    "sdg.disclaimerText": "لم تتم الموافقة على محتوى هذا المنشور من قبل الأمم المتحدة ولا يعكس آراء الأمم المتحدة أو مسؤوليها أو الدول الأعضاء.",
    "home.dominion.title": "فقدان السيادة — أزمة التقارب",
    "home.dominion.text": "إعادة الضبط السادسة لن تأتي من الفضاء. إنها هنا بالفعل — في نقل صنع القرار والتصميم والحوكمة من الأنظمة البشرية إلى أنظمة الآلات. ليس انقراضاً. إزاحة. البنية التحتية التي حملت الحضارة لمدة 12,000 عام تتقارب الآن بسرعة أكبر مما يمكن لأي جيل استيعابه. هذه هي أزمة التقارب. الحلقة الثانية ترسم هندسة الاستمرارية البشرية.",
    "home.fw.ele_planetary": "ساعة ELE الكوكبية — الأرض: 4.5 مليار سنة. خمس عمليات إعادة ضبط. ELE 6 حضارية — 2050. تصرف الآن أو اخسر الهيمنة.",
    "home.fw.continuity_grid": "شبكة الاستمرارية الكاملة — لو كان تاريخ البشرية كتاباً من 1,200 صفحة. 24 صفاً = 24 ساعة. الشبكة هي الساعة. الصف 24 = الساعة الأخيرة.",
    "home.fw.row24": "الصف 24 موسع — الساعة الأخيرة. 12,000 سنة (10,000 ق.م → 2050 م). 500 جيل. الصف الوحيد الذي يسخّر فيه البشر التتابعات. سبعة علماء. ست تتابعات في 246 سنة. جميعها لا تزال تعمل.",
    "home.fw.relay_cone": "مخروط التتابع — 500 جيل من الحضارة مضغوطة في 12 تتابع بنية تحتية. منظر جانبي، منظر علوي، والعلماء السبعة. التتابعات الستة الأولى تمتد 11,500 سنة؛ الستة الأخيرة مضغوطة في 246 سنة.",
    "home.ascent.title": "الصعود إلى الوعي",
    "home.ascent.subtitle": "التتابع 12 وما بعده — الأطروحة الحضارية حتى 2050 كمنتصف الليل",
    "home.ascent.text": "هنا تكمن القطعة الحضارية. من السعرات الحرارية إلى الوعي — أوديسة البنية التحتية ترسم 12,000 سنة عبر 12 تتابعاً و7 علماء و5 شبكات و3 إمبراطوريات عظمى. الصعود إلى الوعي هو التتابع 12 وما بعده: نقطة التحول حيث يلتقي الذكاء البيولوجي ببنيته التحتية الخاصة. خمسة مستويات من النسب الفكري — من هوميروس إلى الجيل التطبيقي — تتقارب على سؤال واحد: من يحمل التتابع إلى الأمام؟ الآثار اللاهوتية عميقة. فقدان السيادة يؤطر الأزمة؛ القوة المضادة: الأجزاء والمقاييس والتوازن توفر حساب المهندس. العالم الثامن يبقى البحث المفتوح — العقدة التالية في سلسلة حكمة أساسية عمرها 3,500 سنة.",
    "home.ascent.source": "النسب ذو الخمسة مستويات — تتابع فكري عمره 3,500 سنة نحو العالم الثامن — إطار حقيقة iAAi"
};
